### PR TITLE
Fix S3 client retry and timeout config

### LINKED ISSUE #6085: Flaky stateproof monitor check
### Description

We get periodic false alerts for our monitor API state proof check. The issues occurs because of a race condition between clusters and cloud bucket delay.

### Steps to reproduce

Run monitor API against mainnet

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.80.0

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the v3 aws s3 client config bug

- Properly config v3 s3 client maxAttempts, connectionTimeout and requestTimeout

**Related issue(s)**:

Fixes #6085 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by steven-sheehy — APPROVED** [review]
LGTM

File: hedera-mirror-rest/__tests__/integration/template.js [hunk 1]
```diff
@@ -102,7 +102,7 @@ describe(`API specification tests - ${groupSpecPath}`, () => {
   let s3Ops;
 
   const configS3ForStateProof = (endpoint) => {
-    config.stateproof = {
```
Comment (xin-hedera) [inline hedera-mirror-rest/__tests__/integration/template.js:105]: deep merge to correctly override stateproof config for integration tests, otherwise since the new config doesn't `httpOptions`, stateproof integration tests would fail

**Review by jascks — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good
