### PR TITLE
Fix incorrect token balance values returned in rest api

### LINKED ISSUE #3612: Incorrect token balance values returned in REST API
### Description

The maximum supply a token can have is 9223372036854775807. However, two API endpoints return a greater value (9223372036854776000) for token balances.

The tokens endpoint shows the correct value for max_supply and total_supply but both the accounts and balances endpoints show the incorrect value for the account's token balance.

Upon further investigation, it looks like Javascript is rounding up the number as it's returned as a number in those endpoints and as a string in the tokens endpoint. The correct value is given in the account balance protobuf files and stored in the database.

### Steps to reproduce

1. Check the max_supply and total_supply values for token id 0.0.287935 using the tokens endpoint 
https://mainnet-public.mirrornode.hedera.com/api/v1/tokens/0.0.287935

```
"max_supply":"9223372036854775807"
"total_supply":"9223372036854775807"
```

2. Check the balance of that token for the account holding it using the balances and accounts endpoints
https://mainnet-public.mirrornode.hedera.com/api/v1/accounts?account.id=0.0.278981
https://mainnet-public.mirrornode.hedera.com/api/v1/balances?account.id=0.0.278981

```
"token_id":"0.0.287935","balance":9223372036854776000
```

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.54.0

### Operating system

Linux

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the incorrect token balance issue.

- Use json-bigint to stringify bigint
- Config node pg driver to parse pg bigint to js BigInt
- Remove `Number` conversions where it's now either a `Number` within js MAX_SAFE_INTEGER or a `BigInt`

**Related issue(s)**:

Fixes #3612

**Notes for reviewer**:

This is a ~13% performance penalty, tested using `/api/v1/accounts?limit=100`.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/utils.js [hunk 1]
```diff
@@ -464,23 +458,6 @@ const parseBalanceQueryParam = (parsedQueryParams, columnName) => {
...
-  return parseParams(
-    parsedQueryParams[constants.filterKeys.ACCOUNT_PUBLICKEY],
-    (value) => {
-      return parsePublicKey(value);
-    },
-    (op, value) => [`${columnName}${op}?`, [value]],
-    false
-  );
-};
-
```
Comment (xin-hedera) [inline hedera-mirror-rest/utils.js:483]: these functions are just reordered

File: hedera-mirror-rest/utils.js [hunk 2]
```diff
@@ -540,6 +510,50 @@ const parseLimitAndOrderParams = (req, defaultOrder = constants.orderFilterValue
...
+
+const parseTimestampQueryParam = (parsedQueryParams, columnName, opOverride = {}) => {
+  return parseParams(
+    parsedQueryParams[constants.filterKeys.TIMESTAMP],
+    (value) => parseTimestampParam(value),
+    (op, value) => [`${columnName}${op in opOverride ? opOverride[op] : op}?`, [value]],
+    false
+  );
+};
+
```
Comment (xin-hedera) [inline hedera-mirror-rest/utils.js:556]: reordered

File: hedera-mirror-rest/__tests__/__snapshots__/utilsFilters.test.js.snap [hunk 3]
```diff
@@ -1,364 +1,16 @@
...
-`;
-
-exports[`utils validateAndParseFilters crypto key tests Verify validateAndParseFilters for invalid {"key":"account.publickey","operator":"eq","value":"key"} 1`] = `
-Array [
-  "Invalid parameter: account.publickey",
-]
-`;
-
-exports[`utils validateAndParseFilters crypto key tests Verify validateAndParseFilters for invalid {"key":"publickey","operator":"eq","value":"3c3d546321ff6f63d701d2ec5c2"} 1`] = `
+exports[`utils buildAndValidateFilters test exceeded max number of repeated parameters 1`] = `
```
Comment (xin-hedera) [inline hedera-mirror-rest/__tests__/__snapshots__/utilsFilters.test.js.snap:3]: most tests no longer expect exception since the exception is now thrown only in `buildAndValidateFilters`. previously it's thrown in `validateAndParseFilters`.

File: hedera-mirror-rest/entityId.js [hunk 4]
```diff
@@ -67,14 +70,21 @@ class EntityId {
...
     if (this.encodedId === undefined) {
-      this.encodedId =
-        this.num === null
-          ? null
-          : ((BigInt(this.shard) << shardOffset) | (BigInt(this.realm) << numBits) | BigInt(this.num)).toString();
+      if (this.num === null) {
+        this.encodedId = null;
+      } else {
+        this.encodedId =
+          this.shard <= maxSafeShard
```
Comment (steven-sheehy) [inline hedera-mirror-rest/entityId.js:84]: Shard will always be less than maxSafeShard, so we will effectively always this code path. I understand that BigInt is slower than Number, but is the multiplication/addition faster than the bit shifting? Seems weird to have two code paths with different implementations, not just different types.

**Review by steven-sheehy — APPROVED** [review]
LGTM

File: hedera-mirror-rest/entityId.js (hunk 4 above)
Comment (xin-hedera) [reply hedera-mirror-rest/entityId.js:84]: `maxSafeShard` is 31, not 2**15 - 1. It's checked against to make sure with the 16-bit realm + 32-bit num, we support encoding into a number of at most (16 + 32 + 5) = 53 bits, that's js Number.MAX_SAFE_INTEGER (2^53 - 1). 

it's way faster than using BigInt with bit shift, micro benchmark:

10:31 $ node benchmark.js
BigInt x 4,016,012 ops/sec ±0.94% (89 runs sampled)
Number x 892,189,740 ops/sec ±0.81% (90 runs sampled)
Fastest is Number

Comment (xin-hedera) [reply hedera-mirror-rest/entityId.js:84]: more on the multiplication, the problem is bit shift with js Number doesn't work as we expected. It seems nodejs limits the number of bits to 32 for Number bit shift operations:

```
> 1<< 30
1073741824
> 1<< 31
-2147483648
> 1<< 32
1
> 1<< 33
2
```

So I have to use multiplication to get the correct value.

**Review by Nana-EC — APPROVED** [review]
LGTM
This was a good one 👍🏾
