### PR TITLE
Fix acceptance test cleanup

### LINKED ISSUE #6959: Logs show multiple stacktraces in passing acceptance test
### Description

`TOKEN_NOT_ASSOCIATED_TO_ACCOUNT` and `TOKEN_WAS_DELETED` errors occur during acceptance tests runs despite the overall tests passing.

### Steps to reproduce

`./gradlew :test:acceptance --info -Dcucumber.filter.tags=@acceptance`

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.89

### Operating system

None

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Add an `AccountNameEnum.OPERATOR`
* Add cleanup of contracts, files, schedules and topic entities
* Add more info to contract call tracer logs
* Add support for `AccountNameEnum` and `TokenNameEnum` method parameters
* Add well known account name to account creation log statement
* Combine create/update/delete topic flows to reduce costs
* Fix `GrpcErrors` log level alert by suppressing max connections `NettyServerHandler` warnings
* Fix not cleaning up contract token associations
* Reduce Loki log retention period from 90 to 60 days
* Remove ad-hoc account creation in token feature in favor of `AccountNameEnum`
* Remove extra token creation in custom fee scenario to reduce costs
* Rename `@tokenbase` to `@token`
* Rename `@topicmessagebase` tag to `@topic`

**Related issue(s)**:

Fixes #6959

**Notes for reviewer**:

Cleanup after changes:
```
2023-09-25T16:03:01.917Z  INFO ForkJoinPool-1-worker-1 c.h.m.t.e.a.c.TokenClient Deleting 9 tokens and dissociating 29 token relationships 
2023-09-25T16:04:18.609Z  INFO ForkJoinPool-1-worker-1 c.h.m.t.e.a.c.ContractClient Deleting 7 contracts 
2023-09-25T16:04:33.172Z  INFO ForkJoinPool-1-worker-1 c.h.m.t.e.a.c.FileClient Deleting 8 files 
2023-09-25T16:04:49.520Z  INFO ForkJoinPool-1-worker-1 c.h.m.t.e.a.c.ScheduleClient Deleting 1 schedules 
2023-09-25T16:04:51.588Z  INFO ForkJoinPool-1-worker-1 c.h.m.t.e.a.c.TopicClient Deleting 3 topics 
2023-09-25T16:04:57.711Z  INFO ForkJoinPool-1-worker-1 c.h.m.t.e.a.c.AccountClient Deleting 5 accounts 
2023-09-25T16:05:07.963Z  WARN ForkJoinPool-1-worker-1 c.h.m.t.e.a.c.AccountClient Tests cost 697.85130818 ℏ to run 
```

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java [hunk 1]
```diff
@@ -75,100 +76,83 @@
...
         }
     }
 
-    @Given("I associate account {string} with token {string}")
-    public void associateToken(String accountName, String tokenName) {
-        var accountId = accountClient.getAccount(AccountClient.AccountNameEnum.valueOf(accountName));
-        var tokenId = tokenClient
-                .getToken(TokenClient.TokenNameEnum.valueOf(tokenName))
-                .tokenId();
+    @Given("I associate account {account} with token {token}")
```
Comment (jascks) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java:105]: So, you can specify `{account}` and `{token}` because of those method names in `AcceptanceTest.java`? Pretty cool.

File: hedera-mirror-test/src/test/resources/features/topic/topic.feature [hunk 2]
```diff
@@ -1,46 +1,23 @@
...
+    When I successfully update an existing topic
+    Then the mirror node should successfully observe the transaction
     When I provide a number of messages <numMessages> I want to receive
     And I subscribe with a filter to retrieve messages
     Then the network should successfully observe these messages
-    Examples:
-      | numMessages |
-      | 10          |
-
-  @release @acceptance @updatetopic
```
Comment (jascks) [inline hedera-mirror-test/src/test/resources/features/topic/topic.feature:16]: This is some of the HAPI specific testing you mentioned earlier?

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java [hunk 3]
```diff
@@ -220,7 +227,13 @@ private ExpandedAccountId createCryptoAccount(
                     "Receipt for %s returned no accountId, receipt: %s", response.getTransactionId(), receipt));
         }
 
-        log.info("Created new account {} with {} via {}", newAccountId, initialBalance, response.getTransactionId());
+        var accountName = AccountNameEnum.of(memo).map(a -> a + " ").orElse("");
+        log.info(
+                "Created new account {}{} with {} via {}",
```
Comment (xin-hedera) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java:232]: nit
```suggestion
                "Created new account {} {} with {} tℏ via {}",
```

**Review by jascks — APPROVED** [review]
This is quite an improvement to the test infrastructure and understandability!  Looks good!

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java (hunk 3 above)
Comment (steven-sheehy) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java:232]: The lack of space is intentional so we don't add an extra space if we're not creating an enum account. See `.map(a -> a + " ").orElse("")`.

Comment (steven-sheehy) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java:232]: And the `th` is unnecessary since we're printing a `Hbar` object which formats the units internally.

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java:105]: Correct. As such we should prefer cucumber expressions over regular expressions when writing a scenario since `{}` variables only work in the former.

File: hedera-mirror-test/src/test/resources/features/topic/topic.feature (hunk 2 above)
Comment (steven-sheehy) [reply hedera-mirror-test/src/test/resources/features/topic/topic.feature:16]: This is to merge create/update/delete flow into one to not create unnecessary topics.

**Review by xin-hedera — APPROVED** [review]
LGTM
