### PR TITLE
Fix rest java specs failing when they're changed

### LINKED ISSUE #9975: RestJava RestSpecTest will likely fail when the selected specs are changed
### Description

RestJava `RestSpecTest` runs a selected subset of spec tests against `hedera-mirror-rest:latest` image running in a container. Problem arises when any PR changes the spec due to either enhancement or bug fix, `RestSpecTest` would then fail since the response from the latest production image will cause mismatch.

### Steps to reproduce

Check CI workflow run log [here](https://github.com/hashgraph/hedera-mirror-node/actions/runs/12377057368/job/34546066347?pr=9973)

### Additional context

_No response_

### Hedera network

other

### Version

v0.121.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Fix REST java specs failing due to out of date container by always pulling latest

**Related issue(s)**:

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by edwin-greene — APPROVED** [review]
Looks good

File: hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/config/SpecTestConfig.java [hunk 1]
```diff
@@ -81,8 +82,9 @@ GenericContainer<?> jsRestApi(PostgreSQLContainer<?> postgresql, Network prostgr
 
         return new GenericContainer<>(DockerImageName.parse("gcr.io/mirrornode/hedera-mirror-rest:latest"))
                 .dependsOn(postgresql)
-                .withNetwork(prostgresqlNetwork)
                 .withExposedPorts(5551)
-                .withEnv(envBuilder.build());
+                .withEnv(envBuilder.build())
+                .withImagePullPolicy(PullPolicy.alwaysPull())
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/config/SpecTestConfig.java:87]: since the `latest` image tag points to the image tagged and pushed by release-production github workflow jobs, the spec tests can still fail when fixes in the js rest module are only in SNAPSHOT.

We should instead use the `main` image when it's a SNAPSHOT build and use the `latest` image otherwise.

It can still fail when we tag in release branches as the `latest` image will again not match what the test class expects. That is transient failure and should work once the images of the new tag are published.

Comment (xin-hedera) [reply hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/config/SpecTestConfig.java:87]: umm. actually I'm wrong. anytime we make changes to js REST API module that the spec tests need the matching changes to pass, the spec tests in rest java will still fail.

Comment (steven-sheehy) [reply hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/config/SpecTestConfig.java:87]: So this PR fixes a real issue I experienced locally and also that Edwin has seen in his PR. We definitely need this change, but maybe it doesn't fully fix the ticket. I can find a way to feed the gradle `version` property to the test config and use that version to pull. Will that not fix most of the problems except during the period where that image is being replaced which should auto resolve on retry after publishing?

Comment (xin-hedera) [reply hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/config/SpecTestConfig.java:87]: nope, using SNAPSHOT images won't fully fix the issue. think we can leave it as is. what we really need is a js rest image built right from the PR branch or a way to programmatically run the js rest api service from source.

**Review by xin-hedera — APPROVED** [review]
LGTM
