### PR TITLE
Fix flaky Rest test

### LINKED ISSUE #7974: Rest Test Setup Is Flaky
### Description

When running the gradle test task for the rest module, there are random failures that occur. The failures seem to indicate that the database schema has not been initialized on the target container. These failures were observed in CI.

Note: it was also observed when running the task locally that the test containers were not cleaned up correctly and the docker containers stuck around long after test run. 

### Steps to reproduce

1. Observer failed github actions for the gradle rest task

1. Run gradle test task locally and monitor the cleanup of docker containers. 

### Additional context

_No response_

### Hedera network

other

### Version

v0.101.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by edwin-greene**
**Description**:

Updates the rest test container creation, configuration and reuse: 

* Remove testcontainers `Reuse` and replaces it with custom container reuse, which allows Ryuk to clean up containers at the end of builds and when builds are cancelled mid-run.
* Update container connection configuration which fixes intermittent test failures with Github Actions CI.

**Related issue(s)**:

Fixes #7974

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/__tests__/integrationDbOps.js [hunk 1]
```diff
@@ -87,27 +78,46 @@ const createDbContainer = async () => {
...
+};
+
+/**
+ * Gets the port of the container in use by the Jest worker. If the container does not exist, a new container is created
+ *
+ * @returns {Promise<number|string>}
+ */
+const getContainerPort = async () => {
+  const client = await getContainerRuntimeClient();
+  const container = await client.container.fetchByLabel('workerId', workerId);
```
Comment (xin-hedera) [inline hedera-mirror-rest/__tests__/integrationDbOps.js:99]: we should not need `getContainerRuntimeClient` and the custom workerId label anymore. Just need to have module level variable `let dockerDb` instead of the local one to keep track of it.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
