### PR TITLE
Set correct sender account in `TransferPrecompile`

### LINKED ISSUE #7192: CONTRACT_REVERT_EXECUTED on estimateGas for transferFrom operation
### Description

**CONTRACT_REVERT_EXECUTED is received while calling estimateGas for transferFrom operation.**

**The transfer is executed successfully and the amount is present to account:**
     const tx2 = await contract.transferFromExternal.populateTransaction(tokenAddress, account0LongZero, account1LongZero, amount);

**While calling estimate gas:**
   const estimateGasResponse = await relay.call(RelayCalls.ETH_ENDPOINTS.ETH_ESTIMATE_GAS, [tx2]);
**the following response is observed:**

`  Error: execution reverted (no data present; likely require(false) occurred (action="estimateGas", data="0x", reason="require(false)", transaction={ "data": "0x75a85472000000000000000000000000000000000000000000000000000000000000040e000000000000000000000000000000000000000000000000000000000000040b000000000000000000000000000000000000000000000000000000000000040c0000000000000000000000000000000000000000000000000000000000000001", "to": "0x000000000000000000000000000000000000040A" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.8.0)`

### Steps to reproduce

TBD

### Additional context

_No response_

### Hedera network

other

### Version

0.90

### Operating system

None

### PR DESCRIPTION
**Pull request by 0xivanov**
**Description**:

Sender account is not being set properly in `TransferPrecompile`. The correct account should be `senderAddress` from `HtsPrecompiledContract`.
This causes incorrect behaviour compared to hedera-services.

Affected operations: `transferFrom`

**Related issue(s)**:

Fixes #7192

**Notes for reviewer**:
We have false positive tests in web3 and test modules that will be corrected with this PR.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java [hunk 1]
```diff
@@ -59,7 +60,8 @@ long getGasRequirement(
             long blockTimestamp,
             TransactionBody.Builder transactionBody,
             Store store,
-            HederaEvmContractAliases mirrorEvmContractAliases);
```
Comment (0xivanov) [inline hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java:62]: If someone has better alternative for getting the `senderAddress` from `HtsPrecompiledContract` feel free to share

File: hedera-mirror-web3/src/test/resources/contracts/DynamicEthCalls/DynamicEthCalls.sol [hunk 2]
```diff
@@ -402,3 +407,12 @@ contract DynamicEthCalls is HederaTokenService {
         if(isKyc) revert("Kyc status mismatch");
     }
 }
+
+contract SpenderContract {
+    function spendFungible(address token, uint256 amount, address from) public {
+        IERC20(token).transferFrom(from, address(this), amount);
```
Comment (IvanKavaldzhiev) [inline hedera-mirror-web3/src/test/resources/contracts/DynamicEthCalls/DynamicEthCalls.sol:413]: Here we have a case where the `spender` and `recipient` accounts are the same. It would be good to also have a test where the recipient is a different account, to cover more test cases. This can be achieved by passing the recipient address as an argument.

Comment (0xivanov) [reply hedera-mirror-web3/src/test/resources/contracts/DynamicEthCalls/DynamicEthCalls.sol]: Added `to` argument and now the function is called 4 times. 2 for nft with 2 different `to` addresses and the same for fungible.

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java:62]: In mono service, it's a class field in `TransferPrecompile` since the class is stateful and constructed for each request. Here, `TransferPrecompile` is stateless so we can't use that approach. Whenever there is per-request state that some previously stateful class needs we should use `ContractCallContext`. This minimizes changes to the copied services code. This is also the approach taken in #7177 which makes `HtsPrecompiledContract` stateless, so you wouldn't be able to use this approach if that PR is merged.

I also think `TransactionBody` should be removed from `getMinimumFeeInTinybars(Timestamp consensusTime, final TransactionBody transactionBody)` for the same reason and moved to `ContractCallContext`. But that can be outside the scope of this PR.

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java [hunk 3]
```diff
@@ -448,9 +448,12 @@ public void ercTransferFromEstimateGasWithoutApproval() {
...
     }
 
-    @And("I approve receiver account to use fungible token")
+    @And("I approve the contract to use fungible token")
     public void approveFungibleWithReceiver() {
-        networkTransactionResponse = accountClient.approveToken(fungibleTokenId, receiverAccount.getAccountId(), 10);
+        networkTransactionResponse = accountClient.approveToken(
+                fungibleTokenId, AccountId.fromSolidityAddress(ercTestContractSolidityAddress), 10);
+        networkTransactionResponse = accountClient.approveToken(
+                fungibleTokenId, AccountId.fromSolidityAddress(precompileTestContractSolidityAddress), 10);
```
Comment (steven-sheehy) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java:456]: nit: Move account ids to separate variables so approveToken fits on one line.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java (hunk 1 above)
Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/Precompile.java]: Moved the sender address to `ContractCallContext`.
About #7177 we are not sure yet if it is worth making `HtsPrecompiledContract` bean.
Also i agree with the comment about the `TransactionBody`

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java (hunk 3 above)
Comment (0xivanov) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java]: Fixed

File: hedera-mirror-web3/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java [hunk 4]
```diff
@@ -89,6 +93,11 @@ class AssociatePrecompileTest {
     private final TransactionBody.Builder transactionBody =
             TransactionBody.newBuilder().setTokenAssociate(TokenAssociateTransactionBody.newBuilder());
 
+    private MockedStatic<ContractCallContext> staticMock;
+
+    @Mock
+    private ContractCallContext contractCallContext;
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java:99]: Not sure why all these changes are necessary when currently only TransferPrecompile needs the `ContractCallContext`?

Comment (0xivanov) [reply hedera-mirror-web3/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java:99]: They call `subject.prepareFields(frame);` so we need to mock the `contractCallContext.get().setSenderAddress(senderAddress);`  method, or it will throw NPE for some tests.

Comment (steven-sheehy) [reply hedera-mirror-web3/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java:99]: Got it, thanks

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by IvanKavaldzhiev — APPROVED** [review]
LGTM
