### PR TITLE
Fix accounts query missing balance info with publickey filter

### LINKED ISSUE #2759: accounts query filtered by publickey may show incorrect balance
### Description

Querying accounts with the publickey filter may show null balance and null balance timestamp, for example:

http://testnet.mirrornode.hedera.com/api/v1/accounts?account.publickey=2b1e1b0cb3a25b21c4add7ca3ae8437c6f7a254f640dc0e9c01a92143e828d9e&limit=1&order=desc

```json
{
    "accounts": [
        {
            "account": "0.0.2523587",
            "auto_renew_period": 7890000,
            "balance": {
                "balance": null,
                "timestamp": null,
                "tokens": []
            },
            "deleted": false,
            "expiry_timestamp": null,
            "key": {
                "_type": "ED25519",
                "key": "2b1e1b0cb3a25b21c4add7ca3ae8437c6f7a254f640dc0e9c01a92143e828d9e"
            },
            "max_automatic_token_associations": 0,
            "memo": "",
            "receiver_sig_required": null
        }
    ],
    "links": {
        "next": "/api/v1/accounts?account.publickey=2b1e1b0cb3a25b21c4add7ca3ae8437c6f7a254f640dc0e9c01a92143e828d9e&limit=1&order=desc&account.id=lt:0.0.2523587"
    }
}
```

This is the result with `account.id` filter for the same account:

http://testnet.mirrornode.hedera.com/api/v1/accounts?account.id=2523587

```json
{
    "accounts": [
        {
            "account": "0.0.2523587",
            "auto_renew_period": 7890000,
            "balance": {
                "balance": 0,
                "timestamp": "1635345000.086235000",
                "tokens": []
            },
            "deleted": false,
            "expiry_timestamp": null,
            "key": {
                "_type": "ED25519",
                "key": "2b1e1b0cb3a25b21c4add7ca3ae8437c6f7a254f640dc0e9c01a92143e828d9e"
            },
            "max_automatic_token_associations": 0,
            "memo": "",
            "receiver_sig_required": null
        }
    ],
    "links": {
        "next": null
    }
}
```

### Steps to reproduce

run the queries above.

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.42.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the account query missing balance info with publickey filter.

- Remove the limit query from account/contract subquery and balance subquery for inner and left/right outer joins
- Only select token balances for accounts included in the response

**Related issue(s)**:

Fixes #2759 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/__tests__/mockpool.js [hunk 1]
```diff
@@ -115,7 +115,7 @@ class Pool {
         orderprefix = 'account_id';
         break;
       case 'accounts':
-        orderprefix = 'coalesce\\(balances.account_id, e.id\\)';
+        orderprefix = '(coalesce\\(ab.account_id, e.id\\)|id|account_id)';
```
Comment (xin-hedera) [inline hedera-mirror-rest/__tests__/mockpool.js:118]: include all possible `order` target in the accounts queries to make the mockpool based tests pass

File: hedera-mirror-rest/__tests__/specs/accounts-05-publickey.spec.json [hunk 2]
```diff
@@ -76,23 +80,24 @@
     "/api/v1/accounts?account.publickey=3c3D546321FF6F63D701D2EC5C277095874e19F4A235BEE1E6BB19258BF362be",
     "/api/v1/accounts?account.publickey=302a300506032b65700321003c3d546321ff6f63d701d2ec5c277095874e19f4a235bee1e6bb19258bf362be",
     "/api/v1/accounts?account.publickey=302A300506032B65700321003C3D546321FF6F63D701D2EC5C277095874E19F4A235BEE1E6BB19258BF362BE",
-    "/api/v1/accounts?account.publickey=302a300506032B65700321003C3D546321FF6F63D701D2EC5C277095874E19F4A235BEE1E6BB19258BF362be"
+    "/api/v1/accounts?account.publickey=302a300506032B65700321003C3D546321FF6F63D701D2EC5C277095874E19F4A235BEE1E6BB19258BF362be",
+    "/api/v1/accounts?account.publickey=302a300506032B65700321003C3D546321FF6F63D701D2EC5C277095874E19F4A235BEE1E6BB19258BF362be&limit=3"
```
Comment (xin-hedera) [inline hedera-mirror-rest/__tests__/specs/accounts-05-publickey.spec.json:84]: querying with `limit=3` will fail with account `10` balance missing without the fix.

File: hedera-mirror-rest/accounts.js [hunk 3]
```diff
@@ -38,7 +38,7 @@ const processRow = (row) => {
     row.account_balance === undefined
       ? undefined
       : {
-          balance: row.account_balance === null ? null : Number(row.account_balance),
+          balance: row.account_balance,
```
Comment (xin-hedera) [inline hedera-mirror-rest/accounts.js:41]: balance now is `string` instead of `Number`

File: hedera-mirror-rest/accounts.js [hunk 4]
```diff
@@ -55,113 +55,236 @@ const processRow = (row) => {
...
-        ab.consensus_timestamp as consensus_timestamp,
-        ab.account_id          as account_id
-      from account_balance ab
-      left outer join token_balance tb
-        on ab.account_id = tb.account_id and ab.consensus_timestamp = tb.consensus_timestamp
-      where ${balanceWhereFilter}
-      group by ab.consensus_timestamp, ab.account_id, ab.balance
-      order by ab.account_id ${order || ''}
-      ${limitQuery || ''}
+            'balance', tb.balance::text
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-rest/accounts.js]: reverted

File: hedera-mirror-rest/accounts.js (hunk 3 above)
Comment (xin-hedera) [reply hedera-mirror-rest/accounts.js]: reverted

File: hedera-mirror-rest/__tests__/specs/accounts-01-no-args.spec.json [hunk 5]
```diff
@@ -138,15 +138,15 @@
       {
         "balance": {
           "timestamp": "0.000002000",
-          "balance": 10,
+          "balance": "10",
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-rest/__tests__/specs/accounts-01-no-args.spec.json]: reverted

**Review by Nana-EC — APPROVED** [review]
LGTM

**Review by ijungmann — APPROVED** [review]

**Review by steven-sheehy — APPROVED** [review]
