### PR TITLE
Fix `ContractCallNativePrecompileTest`

### LINKED ISSUE #10080: Fix `ContractCallNativePrecompileTest` test suite
Fix failing tests for `ContractCallNativePrecompileTest` using the modularized EVM

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Add a fallback to genesis system files loaded from hedera app library
* Fix `ContractCallNativePrecompileTest`
* Move KV classes to a `keyvalue` sub-package

**Related issue(s)**:

Fixes #10080

**Notes for reviewer**:

3359 tests completed, 284 failed, 6 skipped

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/SystemFileLoader.java [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+    private Map<FileID, File> loadAll() {
+        var configuration = properties.getVersionedConfiguration();
+
+        var files = List.of(
+                load(101, fileSchema.genesisAddressBook(networkInfo)),
+                load(102, fileSchema.genesisNodeDetails(networkInfo)),
+                load(111, fileSchema.genesisFeeSchedules(configuration)),
+                load(112, fileSchema.genesisExchangeRates(configuration)),
+                load(121, fileSchema.genesisNetworkProperties(configuration)),
+                load(122, Bytes.EMPTY), // genesisHapiPermissions() fails to load files from the classpath
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/SystemFileLoader.java:61]: Probably because it looks for the default file which should be located under: "data/config/api-permission.properties". We had an empty file before but removed it in one of the PRs.

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/SystemFileLoader.java:61]: I agree with this. Initially when I read the comment in the code I though that it is not clear why the `genesisHapiPermissions()` method fails, so I tried to explain. It seems that there was no need for that.

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM

**Review by kselveliev — APPROVED** [review]
