### PR TITLE
Fix rosetta token balance reconciliation failure

### LINKED ISSUE #2504: Rosetta validation fails on token balance reconciliation
### Description

When running rosetta-cli data validation, for a newly created token, rosetta-cli will report issue on token balance reconciliation:

```
Command Failed: unable to process blocks: unable to process block: account balance response does not contain currency {
 "symbol": "0.0.3368",
 "decimals": 0
}: could not get {
 "symbol": "0.0.3368",
 "decimals": 0
} currency balance for {
 "address": "0.0.3367"
}: unable to get currency balance: unable to get previous account balance for {"address":"0.0.3367"} {"symbol":"0.0.3368","decimals":0} at {"index":232,"hash":"0x622792e6d0a0ae4c6b8d4c37b403e1fe8f1c751dfc9b79e1e9c81e494d1cc27d656ab1ef90e475f35c2ce9a99a1f7925"}: unable to add block to storage 0xfc9533792d8d6daf22ec01d4e5025654a91b1869ff1c9cd610279cb87d22fc7d8fb0aa3c1b4ce530b144bde2a81a7052:233: unable to sync to 238
```

### Steps to reproduce

1. prepare a mirror node db with a successful token create transaction after the first account balance file
2. start rosetta-server pointing to the mirror node db
3. run rosetta-cli check:data

### Additional context

_No response_

### Hedera network

previewnet

### Version

v0.39.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the token balance reconciliation issue when a token is transferred to an account and a token balance for the account doesn't exist in the latest account balance file before the transfer.

- add 0 token balance to `/account/balance` response for tokens whose first transfer-to happens in the next block
- show 0 token balance for dissociated tokens
- change `RetrieveLatest` to return the second latest block
- add `LatestIndex` to `Block` so account service can return error for requests of account balance on latest block
- remove amount in the operation for the token* transaction itself
- re-enable rosetta-cli data & construction validation with testnet live data
- update `get-genesis-balance.sh` to include token balances
- convert `block_test.go` to integration test with pg db backend
- add integration test for `cmd/db.go`

**Related issue(s)**:

Fixes #2504

 
**Notes for reviewer**:

Token account balance reconciliation issues fixed:

- add 0-value account token balance for account X and token T to the current block if in the next block T is transferred to X and the balance for <X, T> is not in the reconciled balance list of the current block
- remove amount from the rosetta operation for the token* transaction itself
- add 0-value account token balance for account X and token T for the current block at consensus end `t` if at `t` <X, T>'s relationship is dissociated and the balance for <X, T> is not in the reconciled balance list of the current block

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rosetta/app/persistence/block/block.go [hunk 1]
```diff
@@ -33,97 +33,85 @@ import (
...
+	selectSecondLatestWithIndex string = `select consensus_start,
                                            consensus_end,
                                            hash,
                                            index,
-                                           prev_hash
-                                    FROM record_file
-                                    ORDER BY consensus_end DESC
-                                    LIMIT 1`
+                                           prev_hash,
+										   (index + 1) latest_index
```
Comment (xin-hedera) [inline hedera-mirror-rosetta/app/persistence/block/block.go:44]: will fix the format

File: hedera-mirror-rosetta/test/db/db.go [hunk 2]
```diff
@@ -86,6 +105,22 @@ func (d dbParams) toDsn() string {
 func (d dbParams) toJdbcUrl(endpoint string) string {
 	return fmt.Sprintf("jdbc:postgresql://%s/%s", endpoint, d.name)
 }
+func (d dbParams) toConfig() types.Db {
```
Comment (xin-hedera) [inline hedera-mirror-rosetta/test/db/db.go:108]: will add empty line between the functions

**Review by Nana-EC — COMMENTED** [review]
1st pass, still making my way through

File: hedera-mirror-rosetta/app/persistence/block/block.go [hunk 3]
```diff
@@ -33,97 +33,85 @@ import (
...
 const (
-	tableNameRecordFile = "record_file"
-)
+	genesisConsensusStartUnset = -1
 
-const (
-	// selectLatestWithIndex - Selects the latest row
-	selectLatestWithIndex string = `SELECT consensus_start,
+	// selectSecondLatestWithIndex - Selects the second latest row
+	selectSecondLatestWithIndex string = `select consensus_start,
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-rosetta/app/persistence/block/block.go:39]: yes it's required and we have to hide the latest block from being exposed. There is no place in rosetta we need the full info of the latest block other than its `index`.

File: hedera-mirror-rosetta/test/db/db.go [hunk 4]
```diff
@@ -87,6 +106,23 @@ func (d dbParams) toJdbcUrl(endpoint string) string {
...
 }
 
+func (d dbParams) toConfig() types.Db {
+	hostPort := strings.Split(d.endpoint, ":")
+	port, _ := strconv.ParseInt(hostPort[1], 10, 32)
+	return types.Db{
+		Host:     hostPort[0],
+		Name:     d.name,
+		Password: d.password,
+		Pool: types.Pool{
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-rosetta/test/db/db.go:116]: `gofmt` prefers it

File: hedera-mirror-rosetta/app/persistence/block/block.go [hunk 5]
```diff
@@ -33,97 +33,85 @@ import (
...
                                              hash,
                                              index,
-                                             prev_hash
+                                             prev_hash,
+                                             (select max(index) from record_file) latest_index
                                       FROM record_file
                                       WHERE index = @index`
 )
 
 type recordFile struct {
```
Comment (steven-sheehy) [inline hedera-mirror-rosetta/app/persistence/block/block.go:86]: Why do we have two recordFile structs now? Is this one like a DTO of record files that's block specific? If so, we should name it something block related.

File: hedera-mirror-rosetta/app/services/base/base_service.go [hunk 6]
```diff
@@ -66,8 +66,8 @@ func (c *BaseService) RetrieveBlock(bIdentifier *rTypes.PartialBlockIdentifier)
 	}
 }
 
-func (c *BaseService) RetrieveLatest() (*types.Block, *rTypes.Error) {
-	return c.blockRepo.RetrieveLatest()
+func (c *BaseService) RetrieveSecondLatest() (*types.Block, *rTypes.Error) {
```
Comment (steven-sheehy) [inline hedera-mirror-rosetta/app/services/base/base_service.go:69]: I'm not a really a fan of leaking first vs second block across all layers, especially if we have to change it back in the future. Perhaps we should rename it to something more generic like `RetrieveLatestValid()`? Or keep it as `RetrieveLatest` but just note the difference in its documentation.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-rosetta/cmd/main.go [hunk 7]
```diff
@@ -196,7 +209,7 @@ func main() {
 		log.Info("Serving Rosetta API in OFFLINE mode")
 	}
 
-	loggedRouter := server.LoggerMiddleware(router)
+	loggedRouter := loggerMiddleware(router)
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-rosetta/cmd/main.go:212]: yes. meant to merge after your PR is merged. so will leave it as is for now

File: hedera-mirror-rosetta/app/services/base/base_service.go (hunk 6 above)
Comment (xin-hedera) [reply hedera-mirror-rosetta/app/services/base/base_service.go:69]: `RetrieveLatest` seems the better name, I'll change it back then.

File: hedera-mirror-rosetta/app/persistence/block/block.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-rosetta/app/persistence/block/block.go:39]: Sounds good

File: hedera-mirror-rosetta/test/db/db.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-rosetta/test/db/db.go:116]: Defer to `gofmt` we shall

File: hedera-mirror-rosetta/app/persistence/block/block.go (hunk 5 above)
Comment (xin-hedera) [reply hedera-mirror-rosetta/app/persistence/block/block.go]: renamed it to `recordBlock`. `LatestIndex` is added to the struct so account service know if this is not the last block and then decide to show account balances or not.

File: hedera-mirror-rosetta/app/domain/repositories/block.go [hunk 8]
```diff
@@ -27,9 +27,9 @@ import (
 
 // BlockRepository Interface that all BlockRepository structs must implement
 type BlockRepository interface {
-	FindByIndex(index int64) (*types.Block, *rTypes.Error)
 	FindByHash(hash string) (*types.Block, *rTypes.Error)
 	FindByIdentifier(index int64, hash string) (*types.Block, *rTypes.Error)
-	RetrieveGenesis() (*types.Block, *rTypes.Error)
+	FindByIndex(index int64) (*types.Block, *rTypes.Error)
 	RetrieveLatest() (*types.Block, *rTypes.Error)
+	RetrieveGenesis() (*types.Block, *rTypes.Error)
```
Comment (ijungmann) [inline hedera-mirror-rosetta/app/domain/repositories/block.go:34]: I think these need to be flipped back after the rename.

File: hedera-mirror-rosetta/test/mocks/repository/block_mock.go [hunk 9]
```diff
@@ -45,11 +45,11 @@ func (m *MockBlockRepository) FindByIdentifier(index int64, hash string) (*types
...
 
-func (m *MockBlockRepository) RetrieveGenesis() (*types.Block, *rTypes.Error) {
+func (m *MockBlockRepository) RetrieveLatest() (*types.Block, *rTypes.Error) {
 	return m.retrieveBlock(m.Called())
 }
 
-func (m *MockBlockRepository) RetrieveLatest() (*types.Block, *rTypes.Error) {
+func (m *MockBlockRepository) RetrieveGenesis() (*types.Block, *rTypes.Error) {
 	return m.retrieveBlock(m.Called())
 }
```
Comment (ijungmann) [inline hedera-mirror-rosetta/test/mocks/repository/block_mock.go:54]: Flip back

**Review by ijungmann — COMMENTED** [review]
First pass, couple nits.

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Looking good. A sql improvement suggestion

File: hedera-mirror-rosetta/app/persistence/account/account.go [hunk 10]
```diff
@@ -28,58 +28,86 @@ import (
...
-                                           from abm
-                                           left join account_balance ab
-                                             on ab.consensus_timestamp = abm.max and ab.account_id = @account_id`
+                                          on t.token_id = tb.token_id
+                                        where tb.consensus_timestamp = abm.max and tb.account_id = @account_id
+                                      ), '[]') token_balances
+                                    from abm
+                                    left join account_balance ab
+                                      on ab.consensus_timestamp = abm.max and ab.account_id = @account_id`
+	selectDissociatedTokensAtTimestamp = `with latest as (
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-rosetta/app/persistence/account/account.go:85]: the trick is we can't have `ta.associated is false` there. it will select the latest row with `associated = false`

the sql statement is supposed to select the current account token relationship at time `t` then pick the ones with `associated = false`

**Review by steven-sheehy — DISMISSED** [review]

File: hedera-mirror-rosetta/app/domain/repositories/block.go (hunk 8 above)
Comment (xin-hedera) [reply hedera-mirror-rosetta/app/domain/repositories/block.go]: done

File: hedera-mirror-rosetta/test/mocks/repository/block_mock.go (hunk 9 above)
Comment (xin-hedera) [reply hedera-mirror-rosetta/test/mocks/repository/block_mock.go]: done

**Review by steven-sheehy — APPROVED** [review]

File: hedera-mirror-rosetta/app/persistence/account/account.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-rosetta/app/persistence/account/account.go:85]: Understood

**Review by Nana-EC — APPROVED** [review]
LGTM
