### PR TITLE
Fix integration test console warning about Stream of unknown length

### LINKED ISSUE #7236: Warning about S3 SDK method in rest api integration test
### Problem

AWS SDK warns about improper usage of s3 method when running rest api integration test:

```
 console.warn
    Are you using a Stream of unknown length as the Body of a PutObject request? Consider using Upload instead from @aws-sdk/lib-storage.

      235 |       const s3ObjectKey = path.relative(dataPath, filePath);
      236 |       const fileStream = fs.createReadStream(filePath);
    > 237 |       await s3client.send(
          |       ^
      238 |         new PutObjectCommand({
      239 |           Bucket: bucketName,
      240 |           Key: s3ObjectKey,

      at node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/check-content-length-header.js:18:29
      at node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:26
      at node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
      at node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:63:20
      at node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
      at node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
      at node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
      at uploadFilesToS3 (__tests__/integration/transactions.test.js:237:7)
      at Object.<anonymous> (__tests__/integration/transactions.test.js:257:7)
``` 

### Solution

research the warning and replace the method per the recommendation.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by edwin-greene**
**Description**:
Fix console warning about Stream of unknown length

**Related issue(s)**:

Fixes #7236 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/__tests__/integration/template.js [hunk 1]
```diff
@@ -258,7 +258,7 @@ describe(`API specification tests - ${groupSpecPath}`, () => {
         new PutObjectCommand({
           Bucket: bucketName,
           Key: s3ObjectKey,
-          Body: Readable.from(fileStream),
+          Body: fileStream,
           ACL: 'public-read',
```
Comment (edwin-greene) [inline hedera-mirror-rest/__tests__/integration/template.js:262]: The `fileStream` is already a `Readable`, so it was a Readable inside a Readable. This removes the outer Readable and that removed the console warning.

**Review by steven-sheehy — APPROVED** [review]

**Review by jascks — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM
