### PR TITLE
Fix nested calls historical tests for modularized

### LINKED ISSUE #10081: Fix `ContractCallNestedCallsHistoricalTest` test suite
Fix failing tests for `ContractCallNestedCallsHistoricalTest` using the modularized EVM

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:

This PR fixes `ContractCallNestedCallsHistoricalTest` tests against modularized code.

**Related issue(s)**:

Fixes #10081 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsHistoricalTest.java [hunk 1]
```diff
@@ -60,59 +57,57 @@ void beforeEach() {
...
-        final var ownerAddress = toAddress(1065);
-        final var ownerEntityId = ownerEntityPersistHistorical(ownerAddress);
-        final var spenderAddress = toAddress(1016);
-        final var spenderPublicKeyHistorical = "3a210398e17bcbd2926c4d8a31e32616b4754ac0a2fc71d7fb768e657db46202625f34";
-        final var spenderEntityPersist = spenderEntityPersistHistorical(spenderAddress, spenderPublicKeyHistorical);
-        final var tokenAddress = toAddress(1063);
-        final var tokenMemo = "TestMemo";
+        final var ownerEntity = accountEntityNoEvmAddressPersistHistorical(
+                Range.closedOpen(recordFileBeforeEvm34.getConsensusStart(), recordFileBeforeEvm34.getConsensusEnd()));
+        final var spenderPublicKey = "3a210398e17bcbd2926c4d8a31e32616b4754ac0a2fc71d7fb768e657db46202625f34";
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsHistoricalTest.java:62]: Can't we use the key that the domain builder would generate, if we set no value at all? Or at least the `SPENDER*` constants from `ContractCallTestUtil`?

Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsHistoricalTest.java]: Refactored to use the spender constants.

Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsHistoricalTest.java]: domainBuilder.key() does not work. We have a new method which it calls -> generateSecp256k1Key which is used to generated compressed public key. But it not always generates a valid key and the test becomes flaky. This need to be fixed in another pr.

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsHistoricalTest.java]: Can you please open an issue to fix the domainBuilder.key() method then?
