### PR TITLE
Fix missing token transfers for token create/mint/burn/wipe

### LINKED ISSUE #1412: Missing token transfers for non-cryptotransfer transactions
**Detailed Description**
Currently we assume that token transfers in the record are only populated for cryptotransfer transactions. Per the requirements doc, token transfers can occur for other token related transactions including burn, wipe, create and mint. As a result, mirror node is missing token transfer entries and needs to be fixed.

**Actual Behavior**
Submit a token create, mint, burn or wipe. No new entries in token_transfer result.

Examples:
https://testnet.dragonglass.me/hedera/transactions/0047439160980754134348539
https://testnet.dragonglass.me/hedera/transactions/00474391609882483613699598

**Expected Behavior**
New entries in token_transfer. We shouldn't insert token transfers based upon transaction type, we should insert it for all types like we do for crypto transfers.

**Environment:**
- Version: 0.25.0

**Additional Context**

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
- Fix missing token transfers by always inserting them for successful transactions
- Fix minor issues with dashboards

**Which issue(s) this PR fixes**:
Fixes #1412

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java [hunk 1]
```diff
@@ -527,10 +557,12 @@ private void createTokenEntity(TokenID tokenID, String symbol, long consensusTim
...
         Transaction createTransaction = tokenCreateTransaction(setFreezeKey, setKycKey, symbol);
         TransactionBody createTransactionBody = getTransactionBody(createTransaction);
+        TokenTransferList tokenTransfer = tokenTransfer(tokenID, PAYER, INITIAL_SUPPLY);
         var createTransactionRecord = createTransactionRecord(consensusTimestamp, tokenID
-                .getTokenNum(), createTransactionBody, ResponseCodeEnum.SUCCESS, null);
+                .getTokenNum(), createTransactionBody, ResponseCodeEnum.SUCCESS, tokenTransfer);
 
-        parseRecordItemAndCommit(new RecordItem(createTransaction, createTransactionRecord));
+        RecordItem recordItem = new RecordItem(createTransaction, createTransactionRecord);
+        parseRecordItemAndCommit(recordItem);
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java:565]: nit: why the change here since `recordItem` isn't reused

**Review by Nana-EC — APPROVED** [review]
LGTM, minor variable assignment nit though

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java:565]: I did the move for an assert, but ended up moving that assert up to the tests during a refactor. Can revert this.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 2]
```diff
@@ -186,13 +183,16 @@ public void onItem(RecordItem recordItem) throws ImporterException {
                 }
             }
 
+            // Record token transfers can be populated for multiple transaction types
+            insertTokenTransfers(recordItem);
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:187]: Actually for good test coverage you should add a test in  for a transaction type not in the list below that has a token transfer part of it, you could do it for a crypto account related transaction

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Test suggestion

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java (hunk 2 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:187]: I misunderstood the additional scope.
As you noted we can rely on main node verification to ensure this is only applicable to token create/mint/burn/wipe and transfer types.
In which case we already have the coverage in tests we need

**Review by Nana-EC — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by ijungmann — APPROVED** [review]

**Comment by steven-sheehy** [comment]
Opened ticket with upstream node-flywaydb for REST CI failure: https://github.com/markgardner/node-flywaydb/issues/25
