### PR TITLE
Ignore staking fields before staking was enabled

### LINKED ISSUE #6973: Ignore staking fields before staking enabled
### Description

We need to handle the scenario in https://github.com/hashgraph/hedera-mirror-node/issues/4815 also inside the parser for new mirror nodes.

### Steps to reproduce

Run importer against old mainnet data

### Additional context

_No response_

### Hedera network

mainnet

### Version

main

### Operating system

None

### PR DESCRIPTION
**Pull request by mgoelswirlds**
**Description**:

Some accounts started to stake to a node before staking feature went alive in mainnet. 
In this PR mirror node will check for the HAPI version to check for the version when services started supporting staking.

This PR  
* Checks for the hapi version to be greater than or equal to 0.27.0 to implement staking functionality.

**Related issue(s)**:

Fixes #6973

**Notes for reviewer**:

The tests had hapi version set to 0.0 by default, so in this PR I have set them to a value greater than 0.27.0 , in order for them to pass.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java [hunk 1]
```diff
@@ -31,10 +31,13 @@
 import com.hedera.mirror.importer.util.Utility;
 import jakarta.inject.Named;
 import org.apache.commons.lang3.ArrayUtils;
+import org.springframework.data.util.Version;
 
 @Named
 class CryptoCreateTransactionHandler extends AbstractEntityCrudTransactionHandler {
 
+    static final Version HAPI_VERSION_0_27_0 = new Version(0, 27, 0);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java:39]: also remove all these duplicates

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FixStakedBeforeEnabledMigrationTest.java [hunk 2]
```diff
@@ -63,7 +63,7 @@ void empty() {
     }
 
     @ParameterizedTest
-    @ValueSource(strings = {HederaNetwork.MAINNET, HederaNetwork.TESTNET})
+    @ValueSource(strings = {HederaNetwork.MAINNET})
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/FixStakedBeforeEnabledMigrationTest.java:66]: change these `ParameterizedTest` test cases to be not parameterized and change `setupForNetwork` to `setupForMainnet`

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java [hunk 3]
```diff
@@ -207,12 +218,38 @@ void updateTransactionStakedNodeId(Long nodeId) {
                         Utility.getEpochDay(withStakedNodeIdSet.getConsensusTimestamp()), Entity::getStakePeriodStart));
     }
 
+    @ParameterizedTest
+    @ValueSource(longs = {0, 100})
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java:222]: don't need to parameterize the nodeId, can just test with one value

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java [hunk 4]
```diff
@@ -91,7 +95,10 @@ void testGetEntityIdReceipt() {
     @Test
     void updateTransactionSuccessful() {
         // given
-        var recordItem = recordItemBuilder.contractUpdate().build();
+        var recordItem = recordItemBuilder
+                .contractUpdate()
+                .recordItem(r -> r.hapiVersion(new Version(0, 28, 0)))
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java:100]: should have at least one with version 0.27.0

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandlerTest.java [hunk 5]
```diff
@@ -108,6 +112,29 @@ void updateTransactionStakedNodeId(Long nodeId) {
                         Utility.getEpochDay(withStakedNodeIdSet.getConsensusTimestamp()), Entity::getStakePeriodStart));
     }
 
+    @ParameterizedTest
+    @ValueSource(longs = {0, 100})
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandlerTest.java:116]: same, don't need to parameterize the `accountId`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java [hunk 6]
```diff
@@ -156,6 +157,9 @@ private void createContract(RecordItem recordItem, Entity entity) {
     }
 
     private void updateStakingInfo(RecordItem recordItem, Entity contract) {
+        if (recordItem.getHapiVersion().isLessThan(HAPI_VERSION_0_27_0)) {
+            return;
+        }
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandler.java:162]: nit, add an empty line after the if block

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java [hunk 7]
```diff
@@ -282,12 +284,14 @@ void updateTransactionSuccessfulAutoRenewAccountAlias() {
         assertThat(recordItem.getEntityTransactions()).containsExactlyInAnyOrderEntriesOf(expectedEntityTransactions);
     }
 
-    @Test
-    void updateTransactionStakedAccountId() {
+    @ParameterizedTest
+    @ValueSource(ints = {27, 28})
+    void updateTransactionStakedAccountId(int majorVersion) {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractCreateTransactionHandlerTest.java:289]:
```suggestion
    void updateTransactionStakedAccountId(int minorVersion) {
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java [hunk 8]
```diff
@@ -156,13 +165,14 @@ void updateTransactionSuccessfulWhenEntityTransactionDisabled() {
     }
 
     @ParameterizedTest
-    @ValueSource(longs = {0, 100})
-    void updateTransactionStakedAccountId(long accountNum) {
+    @CsvSource({"0,28", "100,27"})
+    void updateTransactionStakedAccountId(long accountNum, int majorVersion) {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandlerTest.java:169]:
```suggestion
    void updateTransactionStakedAccountId(long accountNum, int minorVersion) {
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java [hunk 9]
```diff
@@ -197,7 +199,7 @@ var record = parentRecordItem.getTransactionRecord();
 
         assertAll(
                 () -> assertEquals(2, transactionRepository.count()),
-                () -> assertEquals(4, contractRepository.count()),
```
Comment (mgoelswirlds) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java:200]: The contract count has changed since I changed the version to be > 0.23.0 after the child contracts weren't created as part of the parent.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java [hunk 10]
```diff
@@ -100,7 +100,7 @@
 @RequiredArgsConstructor(onConstructor = @__(@Autowired))
 class EntityRecordItemListenerContractTest extends AbstractEntityRecordItemListenerTest {
 
-    private static final Version HAPI_VERSION_0_23_0 = new Version(0, 23, 0);
+    private static final Version HAPI_VERSION_0_28_0 = new Version(0, 28, 0);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java:103]: will the change not reduce test coverage? Do we still have a test case for HAPI < 0.23.0 and verify the number of contracts include those in the created_contract_ids?

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandlerTest.java [hunk 11]
```diff
@@ -137,12 +140,14 @@ void updateTransactionStakedAccountId() {
                 .containsExactlyInAnyOrderEntriesOf(getExpectedEntityTransactions(recordItem, transaction));
     }
 
-    @Test
-    void updateTransactionStakedNodeId() {
+    @ParameterizedTest
+    @ValueSource(ints = {27, 28})
+    void updateTransactionStakedNodeId(int majorVersion) {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandlerTest.java:145]: this is still `majorVersion`

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandlerTest.java [hunk 12]
```diff
@@ -94,10 +99,11 @@ void updateTransactionStakedAccountId(long accountNum) {
     }
 
     @ParameterizedTest
-    @ValueSource(longs = {1, -1})
-    void updateTransactionStakedNodeId(Long nodeId) {
+    @CsvSource({"1,28", "-1,27"})
+    void updateTransactionStakedNodeId(Long nodeId, int majorVersion) {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoUpdateTransactionHandlerTest.java:103]: same here.

I may not mark all the places with the same issue, so please do a thorough check.

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java (hunk 10 above)
Comment (mgoelswirlds) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java]: It is restored to check for <0.23  in getExpectedEntityTransactions , other places changing it to 0.28 will not change coverage.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java [hunk 13]
```diff
@@ -119,6 +120,9 @@ protected void doUpdateEntity(Entity entity, RecordItem recordItem) {
     }
 
     private void updateStakingInfo(RecordItem recordItem, Entity entity) {
+        if (recordItem.getHapiVersion().isLessThan(HAPI_VERSION_0_27_0)) {
```
Comment (jascks) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java:123]: In the PR, it says:
```
Checks for the hapi version to be greater than 0.27.0 to implement staking functionality.
```
This statement allows  performing staking functionality only when the HAPI version is _not less than_ `HAPI_VERSION_0_27_0`, or greater than _or equal to_ 0.27.0. Which way does it need to be?

Comment (mgoelswirlds) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java:123]: Thanks for pointing that out. It should be >= 0.27.0. I have corrected that in the description.

Comment (jascks) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java:123]: Okay, I see `ContractCreateTransactionHandlerTest.updateTransactionStakedAccountId()` treats 0.27.0 and 0.28.0 as the same, so it looks like >= 0.27.0 is the intent.

Comment (jascks) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/ContractUpdateTransactionHandler.java:123]: 👍

**Review by jascks — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM
