### PR TITLE
Fix monitor stopped publishing

### LINKED ISSUE #3404: Monitor stopped publishing
### Description

The mainnet public monitor stopped publishing transactions during the consensus node upgrade to 0.23 on 3/10/22. After the consensus nodes came back online the monitor never recovered. The node validation process that runs every 30 minutes showed only a small subset of the nodes that were actually up as valid. A restart of the monitor resolved the issue.

Note that the mainnet-eu cluster didn't exhibit the same behavior despite pointing to the same nodes, so perhaps it's a timing issue.

### Steps to reproduce

1. Run the monitor
2. Monitor node validation passes
3. Nodes go offline for maintenance
4. Monitor doesn't publish transactions

### Additional context

[monitor-not-publishing.log.gz](https://github.com/hashgraph/hedera-mirror-node/files/8247188/monitor-not-publishing.log.gz)

### Hedera network

mainnet

### Version

v0.51.1

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:
- Use `Optional.ofNullable` to handle null `Transaction.nodeAccountIds` to avoid NPE
- Increase default node validation `maxAttempts` and `requestTimeout` to accommodate higher C2C and avoid falsely marking nodes as unavailable
- Catch unexpected exceptions in `PublishMetrics.recordMetric()`
- Bump up to SDK `v2.9.0`
 
**Related issue(s)**:

Fixes #3404 

**Notes for reviewer**:
The default node validation config of 4 maxAttempts and 0.5s min / 2s max backoffs would result in a max of (0.5s + 1s + 2s) = 3.5s retry timeout. The mainnet 0.23.x upgrade on 03/10/22 resulted in higher c2c at around 4s. The impact to monitor node validation is we see way less available nodes than with 0.22.x.

For mainnet-na, the available nodes reduced to 0 at one point (not sure if it's becoz at the time all nodes were down or all nodes had high c2c), this trigerred a NPE from Optional.of(Transaction.nodeAccountIds), and then caused unhandled error in the flux flow so the monitor publishing stopped.

For mainnet-eu, it's just that the monitor never hit the 0-node available situation so it continued publishing topic messages.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishRequest.java [hunk 1]
```diff
@@ -26,7 +26,7 @@
 
 import com.hedera.hashgraph.sdk.Transaction;
 
-@Builder
+@Builder(toBuilder = true)
```
Comment (xin-hedera) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishRequest.java:29]: make toBuilder available just for test cases

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishResponse.java [hunk 2]
```diff
@@ -29,7 +29,7 @@
 import com.hedera.hashgraph.sdk.TransactionReceipt;
 import com.hedera.hashgraph.sdk.TransactionRecord;
 
-@Builder
+@Builder(toBuilder = true)
```
Comment (xin-hedera) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishResponse.java:32]: make toBuilder available just for test cases

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java [hunk 3]
```diff
@@ -126,7 +126,7 @@ public void close() {
         if (transaction.getNodeAccountIds() == null) {
             var currentNodes = this.nodes; // Save a reference in case a COW occurs
             if (currentNodes.isEmpty()) {
-                throw new PublishException(request, new IllegalArgumentException("No valid nodes available"));
+                return Mono.error(new IllegalArgumentException("No valid nodes available"));
```
Comment (xin-hedera) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java:129]: since the function is not wrapped in a flux/mono method, throwing exception won't be caught by the refactor flow and the scenario.onError won't get a chance to record the error

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java [hunk 4]
```diff
@@ -171,6 +171,7 @@ public void close() {
         client.setMaxAttempts(validationProperties.getMaxAttempts());
         client.setMaxBackoff(validationProperties.getMaxBackoff());
         client.setMinBackoff(validationProperties.getMinBackoff());
+        client.setRequestTimeout(validationProperties.getRequestTimeout());
```
Comment (xin-hedera) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java:174]: in favor of sdk client request timeout setting

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java [hunk 5]
```diff
@@ -201,16 +202,15 @@ boolean validateNode(NodeProperties node) {
...
             Client client = validationClient.get();
 
             Status receiptStatus = new TransferTransaction()
                     .addHbarTransfer(nodeAccountId, hbar)
                     .addHbarTransfer(client.getOperatorAccountId(), hbar.negated())
                     .setNodeAccountIds(node.getAccountIds())
-                    .execute(client, properties.getRequestTimeout())
-                    .getReceipt(client, properties.getRequestTimeout())
+                    .execute(client)
+                    .getReceipt(client)
```
Comment (xin-hedera) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java:213]: v2.7.0 doesn't honor client.requestTimeout in the sync path, and v2.9.0 have it fixed.

also getReceipt(client, timeout) uses the async path internally. switching to getRecipt(client) makes it sync.

File: hedera-mirror-test/pom.xml [hunk 6]
```diff
@@ -25,7 +25,7 @@
         <dependency>
             <groupId>com.hedera.hashgraph</groupId>
             <artifactId>sdk</artifactId>
-            <version>2.7.0</version>
+            <version>2.9.0</version>
```
Comment (xin-hedera) [inline hedera-mirror-test/pom.xml:28]: need to run acceptance tests to make sure new SDK doesn't cause regression

**Review by steven-sheehy — APPROVED** [review]
LGTM where the G stands for Great

File: hedera-mirror-test/pom.xml (hunk 6 above)
Comment (xin-hedera) [reply hedera-mirror-test/pom.xml:28]: update: acceptance passed so we are good to upgrade to sdk v2.9.0

**Review by matheus-dallrosa — APPROVED** [review]
