### PR TITLE
Workaround duplicate block issue by merging blocks

### LINKED ISSUE #5370: Duplicate block number in record stream
### Description

Consensus nodes had a corner case on startup of v0.34.1 that caused two record files to have the same block number.

### Steps to reproduce

Process record files `2023-02-09T17_00_00.004340003Z.rcd.gz` and `2023-02-09T17_00_00.279682003Z.rcd.gz`

### Additional context

https://mainnet-public.mirrornode.hedera.com/api/v1/blocks?block.number=gte:44029065&limit=4&order=asc

```json
{
   "blocks":[
      {
         "count":580,
         "hapi_version":"0.33.0",
         "hash":"0x248b014e0ce6dfe214e671edae2159701b9962cee116ab6acb6be30e28e05804984a249fc95b5f00f1ae0aa3bc4e27f4",
         "name":"2023-02-09T16_59_58.027492003Z.rcd.gz",
         "number":44029065,
         "previous_hash":"0x0f2ad4051170f60c123c796a9475bed6155cf3bdc35cc83e0eb74c03fbc89bf7076c935064cd4211dedc905ef2777ed9",
         "size":142348,
         "timestamp":{
            "from":"1675961998.027492003",
            "to":"1675961999.999054149"
         },
         "gas_used":0,
         "logs_bloom":"0x"
      },
      {
         "count":92,
         "hapi_version":"0.33.0",
         "hash":"0xe35cbcd09866cfaf43b5a63278aae6c7eba27cd725dc7a3e47c036f7d36a9383fa58a1a00266ad8fd6b8148b90ed5266",
         "name":"2023-02-09T17_00_00.004340003Z.rcd.gz",
         "number":44029066,
         "previous_hash":"0x248b014e0ce6dfe214e671edae2159701b9962cee116ab6acb6be30e28e05804984a249fc95b5f00f1ae0aa3bc4e27f4",
         "size":23232,
         "timestamp":{
            "from":"1675962000.004340003",
            "to":"1675962000.231859003"
         },
         "gas_used":0,
         "logs_bloom":"0x"
      },
      {
         "count":578,
         "hapi_version":"0.34.0",
         "hash":"0xe3922f1f630081df395085df50c7450da5abed08506434e2c43ac1537e9dd6bd01aa01f50674ed510d40095bd63f2607",
         "name":"2023-02-09T17_00_00.279682003Z.rcd.gz",
         "number":44029066,
         "previous_hash":"0xe35cbcd09866cfaf43b5a63278aae6c7eba27cd725dc7a3e47c036f7d36a9383fa58a1a00266ad8fd6b8148b90ed5266",
         "size":141778,
         "timestamp":{
            "from":"1675962000.279682003",
            "to":"1675962001.984524003"
         },
         "gas_used":0,
         "logs_bloom":"0x"
      },
      {
         "count":669,
         "hapi_version":"0.34.0",
         "hash":"0x07485be7d3e070f1350655a37b533618be1ad1ee83d9c92445300068152c24fe96fc72f2b8c0cc56eae65dcb80eef07a",
         "name":"2023-02-09T17_00_02.002986853Z.rcd.gz",
         "number":44029067,
         "previous_hash":"0xe3922f1f630081df395085df50c7450da5abed08506434e2c43ac1537e9dd6bd01aa01f50674ed510d40095bd63f2607",
         "size":164197,
         "timestamp":{
            "from":"1675962002.002986853",
            "to":"1675962003.939037161"
         },
         "gas_used":0,
         "logs_bloom":"0x"
      }
   ],
   "links":{
      "next":"/api/v1/blocks?limit=4&order=asc&block.number=gt:44029067"
   }
}
```

### Hedera network

mainnet

### Version

0.72.0

### Operating system

None

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

Workaround duplicate block issue by merging blocks

**Related issue(s)**:

Fixes #5370

**Notes for reviewer**:

Writing a test.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by edwin-greene — DISMISSED** [review]
Looks good

**Review by jnels124 — DISMISSED** [review]
LGTM

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetBlockMigration.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+            ),
+            merged_block as (
+              update record_file block2 set
+              consensus_start = block1.consensus_start,
+              count = block1.count + block2.count,
+              gas_used = block1.gas_used + block2.gas_used,
+              load_start = block1.load_start,
+              name = block1.name,
+              prev_hash = block1.prev_hash,
+              sidecar_count = block1.sidecar_count + block2.sidecar_count,
```
Comment (mgoelswirlds) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetBlockMigration.java:47]: What about the HAPI version? That would not change between the 2?

Comment (mgoelswirlds) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetBlockMigration.java:47]: Got my question answered.

Comment (mgoelswirlds) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetBlockMigration.java:47]: Yes and because we don't set it , it will go with the newer one right?

**Review by mgoelswirlds — APPROVED** [review]
Numbers and sql seems fine to me.

**Review by xin-hedera — DISMISSED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetBlockMigration.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetBlockMigration.java]: Right

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetBlockMigration.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+            update transaction t
+            set index = ti.new_index
+            from transaction_index ti
+            where t.consensus_timestamp = ti.consensus_timestamp;
+            """;
+
+    private final NamedParameterJdbcOperations jdbcOperations;
+    private final MirrorProperties mirrorProperties;
+
+    protected FixMainnetBlockMigration(NamedParameterJdbcOperations jdbcOperations, MirrorProperties mirrorProperties) {
```
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetBlockMigration.java]: Thanks, hadn't actually ran it when I originally pushed. Just wanted early feedback.

**Review by mgoelswirlds — APPROVED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/MergeDuplicateBlocksMigrationTest.java [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+    @Test
+    void notMainnet() throws Exception {
+        // Given
+        mirrorProperties.setNetwork(MirrorProperties.HederaNetwork.TESTNET);
+
+        // When
+        migration.doMigrate();
+
+        // Then
+        assertThat(recordFileRepository.findById(block1.getConsensusEnd())).get().isEqualTo(block1);
```
Comment (jnels124) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/MergeDuplicateBlocksMigrationTest.java:73]: shouldn't the migration delete block 1?

**Review by jnels124 — APPROVED** [review]
LGTM
