### PR TITLE
Enhance negative web3 tests to check for expected error messages

### LINKED ISSUE #9135: Enhance negative integration tests to check error messages
### Problem

There is an idea for tests enhancement in this [comment](https://github.com/hashgraph/hedera-mirror-node/pull/9022#discussion_r1718121114). We can analyze all negative tests that throw exception and add proper check for the text messages in the exceptions.

### Solution

Analyze all integration negative tests and add checks for the detailed error messages that are expected.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by nickeynikolovv**
**Description**:
This PR adds checks for error messages that are expected to be received when an exception is thrown

**Related issue(s)**:

Fixes #9135 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileModificationTest.java [hunk 1]
```diff
@@ -953,7 +963,9 @@ void createTokenWithInvalidInitialSupplyFails() {
                 tokenToCreate, BigInteger.valueOf(10L), BigInteger.valueOf(10L));
 
         // Then
-        assertThatThrownBy(function::send).isInstanceOf(MirrorEvmTransactionException.class);
+        assertThatThrownBy(function::send)
+                .isInstanceOf(MirrorEvmTransactionException.class)
+                .hasMessage(CONTRACT_REVERT_EXECUTED.name());
```
Comment (kselveliev) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileModificationTest.java:968]: I don't see much value checking for the CONTRACT_REVERT_EXECUTED since pretty much anything can be CONTRACT_REVERT_EXECUTED. I guess we could revert the changes where we check for CONTRACT_REVERT and leave only the others which are not CONTRACT_REVERT_EXECUTED.

Comment (nickeynikolovv) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileModificationTest.java]: Yes those checks are not really needed - removed them

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java [hunk 2]
```diff
@@ -964,4 +977,11 @@ void transferToNonExistingContract() {
             assertGasLimit(serviceParameters);
         }
     }
+
+    public static String toHexWith64LeadingZeros(final Long value) {
```
[the remark this answers is not in the document]
Comment (nickeynikolovv) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java]: and done

**Review by kselveliev — APPROVED** [review]

**Review by steven-sheehy — APPROVED** [review]
LGTM
