### PR TITLE
Fix entity stake calculator issues in corner cases 

### LINKED ISSUE #6614: Entity stake calculator gets stuck in resettable environment or partial mirrornode
### Description

Entity stake calculator assumes the staking rewards account `0.0.800` exists in mirrornode database and it's created before the first node stake update transaction. However, in resettable environments, the first node stake update transaction happens before the system generated transaction which creates account `0.0.800`; also for partial mirrornode, account 800 may be completely missing in `entity` table all the time.

Both would cause entity stake calculator stuck in a loop trying to update stake information for entities as shown in the log:

```
INFO 2023-08-05T02:56:35.442406154Z 2023-08-04T20:56:35.442-0600 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Completed pending reward calculation of end stake period null in 10.42 ms
INFO 2023-08-05T02:56:35.458456713Z 2023-08-04T20:56:35.458-0600 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Completed pending reward calculation of end stake period null in 10.28 ms
INFO 2023-08-05T02:56:35.473697725Z 2023-08-04T20:56:35.473-0600 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Completed pending reward calculation of end stake period null in 9.413 ms
INFO 2023-08-05T02:56:35.489142369Z 2023-08-04T20:56:35.489-0600 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Completed pending reward calculation of end stake period null in 9.596 ms
INFO 2023-08-05T02:56:35.505654179Z 2023-08-04T20:56:35.505-0600 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Completed pending reward calculation of end stake period null in 10.44 ms
INFO 2023-08-05T02:56:35.522418590Z 2023-08-04T20:56:35.522-0600 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Completed pending reward calculation of end stake period null in 10.76 ms

```

### Steps to reproduce

Check the importer log of integration env after a stream reset.

### Additional context

_No response_

### Hedera network

other

### Version

v0.86.0-beta1

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes bugs in entity stake calculator for resettable environments and partial mirrornodes

- Calculate pending rewards from the first node stake after the staking reward account
- Validate updated staking reward account end stake period

**Related issue(s)**:

Fixes #6614 

**Notes for reviewer**:

Tested in integration environment where the first node stake update tx is before when account 800 is created. The first attempt is triggered by the first node stake update tx.

```
2023-08-16T14:44:11.245+0000 INFO task-1 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Created entity_state_start in 88.78 ms
2023-08-16T14:44:11.356+0000 WARN task-1 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Failed to calculate pending reward in 201.0 ms, last end stake period is 0, and the end stake period afterwards is null
2023-08-16T14:52:25.715+0000 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Created entity_state_start in 158.8 ms
2023-08-16T14:52:25.822+0000 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Completed pending reward calculation of end stake period 19583 in 266.2 ms
2023-08-16T14:52:25.828+0000 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Skipping since the entity stake is up-to-date
```

Tested partial mirrornode scenario, note account 800 is manually added with null `created_timestamp` and `[0,)` `timestamp_range`.

```
2023-08-16T15:09:09.922+0000 INFO task-1 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Skipping since the entity stake is up-to-date
2023-08-16T15:11:42.874+0000 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Created entity_state_start in 120.7 ms
2023-08-16T15:11:42.966+0000 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Completed pending reward calculation of end stake period 19583 in 212.1 ms
2023-08-16T15:11:42.971+0000 INFO task-2 c.h.m.i.p.r.e.s.EntityStakeCalculatorImpl Skipping since the entity stake is up-to-date
```

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java [hunk 1]
```diff
@@ -54,18 +53,32 @@ public void calculate() {
...
                     entityStakeRepository.lockFromConcurrentUpdates();
                     entityStakeRepository.createEntityStateStart();
                     log.info("Created entity_state_start in {}", stopwatch);
                     entityStakeRepository.updateEntityStake();
-                    Optional<Long> endStakePeriod = entityStakeRepository.getEndStakePeriod();
+                });
+
+                var endStakePeriod = entityStakeRepository.getEndStakePeriod();
+                if (endStakePeriod
+                        .filter(stakePeriod -> stakePeriod > lastEndStakePeriod)
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/staking/EntityStakeCalculatorImpl.java:68]: this is a loose check, just so it's future proof that if for some reason, consensus nodes are down for more than a day, the next node stake update tx will cause a end stake period gap.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java [hunk 2]
```diff
@@ -43,7 +43,19 @@ with end_period as (
...
+              where consensus_timestamp > (
+                select lower(timestamp_range) as timestamp from entity where id = 800
+                union all
+                select lower(timestamp_range) as timestamp from entity_history where id = 800
+                order by timestamp
+                limit 1
+              )
+              order by consensus_timestamp
+              limit 1
+            )
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java:58]: find the first node stake update tx's epoch day after account 800's valid timestamp. Note, for the sake of mirrornode, we can't use `created_timestamp`

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by edwin-greene — DISMISSED** [review]
Looks good

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java (hunk 2 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java:58]: update: also made the change to pick the epoch_day for pending rewards calculation to be the next one in `node_stake` table, instead of strictly 800's end_stake_period + 1

**Review by steven-sheehy — APPROVED** [review]
