### PR TITLE
Fix complex keys of size one not setting ed25519 public key

### LINKED ISSUE #1667: Complex keys of size one do not set ed25519 public key
**Problem**
We currently only populate `t_entities.ed25519_public_key_hex` if the `Key` is a simple ED25519 key. We've seen some special cases where instead it's a `KeyList` of exactly one ED25519 or a `ThresholdKey` that has a single ED25519. 

**Solution**
We should treat the complex keys of size one as simple ED25519 keys and store it into `ed25519_public_key_hex`

**Alternatives**

**Additional Context**

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
- Fix complex keys of size one not setting ed25519 public key
- Move `Utility.getResource()` to `TestUtils`

**Which issue(s) this PR fixes**:
Fixes #1667

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

**Review by ijungmann — DISMISSED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java [hunk 1]
```diff
@@ -86,6 +87,50 @@ public static String bytesToHex(byte[] bytes) {
...
+    /**
+     * If the protobuf encoding of a Key is a single ED25519 key or a complex key with exactly one ED25519 key within
+     * it, return the key as a String with lowercase hex encoding.
+     *
+     * @param protobufKey
+     * @return ED25519 public key as a String in hex encoding, or null
+     */
+    public static String convertSimpleKeyToHex(@Nullable byte[] protobufKey) {
+        try {
+            if (ArrayUtils.isEmpty(protobufKey)) {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:99]: nit: change line 83-85 to use `ArrayUtils.isEmpty` as well

**Review by xin-hedera — APPROVED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:96]: Done

**Review by xin-hedera — APPROVED** [review]
LGTM
