### PR TITLE
Fix record parser continuing to next file after exception

### LINKED ISSUE #260: Record Parser: Failing to complete a file not handled properly
**Detailed Description**
In RecordFileParser, when we complete a file `RecordFileLogger.completeFile(thisFileHash, previousFileHash);`, we don't check for true/false being returned by completeFile (it internally catches exceptions and returns false if an exception occurred).

**Actual Behavior**
Processing continues with the next file.

**Expected Behavior**
Failing to complete a file should stop processing and retry.
-Remove the true/false return from `completeFile` and let it throw the exception
or
-Handle the true/false return value in RecordFileLogger.

**Environment:**

**Additional Context**

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
- Removes try/catch and boolean return value in `RecordFileLogger.completeFile()`and lets `RecordFileParser` handle rollback and halting processing
- Also removes try/catch and boolean return for `RecordFileLogger.storeRecord()` to avoid double rollback.

**Which issue(s) this PR fixes**:
Fixes #260 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java [hunk 1]
```diff
@@ -271,324 +265,314 @@ public static boolean isSuccessful(final TransactionRecord transactionRecord) {
 		return ResponseCodeEnum.SUCCESS == transactionRecord.getReceipt().getStatus();
 	}
 
-	public static boolean storeRecord(Transaction transaction, TransactionRecord txRecord) throws Exception {
+	public static void storeRecord(Transaction transaction, TransactionRecord txRecord) throws Exception {
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: It's hard to tell but there's no changes to this method besides removing of try/catch and boolean return value
