### PR TITLE
Fix balance monitor api tests

### LINKED ISSUE #4674: Monitor not updated for current account balance
### Description

The monitor shows an error of `balances.length of 0 was expected to be 1` when pointing to a REST API v0.66.1. This occurs because we switch the balances API to use the live account balance and this check is confirming an exact timestamp from the balances list will show up with timestamp parameters.

### Steps to reproduce

https://{hostname}/api/v1/balances?timestamp=gt:1666034723.874913934&timestamp=lt:1666034725.874913934&limit=1

Replace hostname with an env that is using v0.66.1 and replace timestamp with the latest balance timestamp +/- one second.

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.66.1

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by MarcKriguerAtHedera**
**Description**:

Fix balance monitor api tests to reflect the fact that balances are now 'live' and not tied to the REST API `/balances` response timestamp.

* Change `checkBalanceFreshness` call to specify timestamp = <now>
* Remove `getBalancesWithTimeAndLimitParams` check since it no longer makes sense with live balances.

**Related issue(s)**:

Fixes #4674

**Notes for reviewer**:

```console
0|server  | 2022-10-17T17:15:59.111-07:00 INFO Running test #1
0|server  | 2022-10-17T17:15:59.126-07:00 INFO Server running on port: 3000
0|server  | 2022-10-17T17:15:59.746-07:00 INFO Completed test run #1 for testnet with 17/17 tests passed in 635 ms
0|server  | 2022-10-17T17:15:59.746-07:00 INFO Finished test run #1 in 635 ms
0|server  | 2022-10-17T17:17:00.334-07:00 INFO Completed test run #2 for testnet with 17/17 tests passed in 587 ms
0|server  | 2022-10-17T17:17:00.334-07:00 INFO Finished test run #2 in 587 ms
```

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (using testnet api_monitor)

### CODE REVIEW

File: hedera-mirror-rest/monitoring/monitor_apis/utils.js [hunk 1]
```diff
@@ -332,13 +332,16 @@ const checkElementsOrder = (elements, option) => {
...
  * @return {Promise<>}
  */
-const checkResourceFreshness = async (server, path, resource, timestamp, jsonRespKey) => {
+const checkResourceFreshness = async (server, path, resource, timestamp, jsonRespKey, query = undefined) => {
   const {freshnessThreshold} = config[resource];
   if (freshnessThreshold === 0) {
     return {skipped: true};
   }
+  if (query === undefined) {
+    query = {limit: 1, order: 'desc'};
```
Comment (steven-sheehy) [inline hedera-mirror-rest/monitoring/monitor_apis/utils.js:341]: nit: Can move to default parameter

**Review by steven-sheehy — DISMISSED** [review]

**Review by xin-hedera — DISMISSED** [review]
LGTM

File: hedera-mirror-rest/monitoring/monitor_apis/utils.js (hunk 1 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-rest/monitoring/monitor_apis/utils.js]: Done -- this was failing for me yesterday (I probably had a trailing comma or semicolon), but it's working now.

**Review by xin-hedera — APPROVED** [review]
