### PR TITLE
Fix record file mismatch race condition

### LINKED ISSUE #195: Record file hash mismatch with previous
**Detailed Description**
`File Hash Mismatch with previous` error still occurs even after the fix for #157.

**Actual Behavior**
1. Run record downloader
2. Run record parser
Wait until hash mismatch occurs.

**Expected Behavior**
Records download, verified and moved to valid with no errors.

**Environment:**
- Environment: staging
- Java: OpenJDK 11.0.4
- Version: 0.1.0

**Additional Context**
Logs when it happened (reverse order):
```console
Sep 03 22:00:36 psql-test-02 java[8100]: 2019-09-03 22:00:36,896 WARN  [main ] c.h.d.RecordFileDownloader File Hash Mismatch with previous : /var/lib/mirror-node/recordstreams/valid/2019-09-03T20_43_40.116069Z.rcd
Sep 03 22:00:36 psql-test-02 java[8100]: 2019-09-03 22:00:36,896 TRACE [main ] c.h.d.ApplicationStatus Returning application status for : RECORD_HASH_MISMATCH_BYPASS_UNTIL_AFTER,
Sep 03 22:00:36 psql-test-02 java[8100]: 2019-09-03 22:00:36,895 TRACE [main ] c.h.d.ApplicationStatus Getting application status for : RECORD_HASH_MISMATCH_BYPASS_UNTIL_AFTER
Sep 03 22:00:36 psql-test-02 java[8100]: 2019-09-03 22:00:36,894 TRACE [main ] c.h.p.RecordFileParser Read previous file hash a092fd020847f6b2206b29e7d50283c0f820e4244691eed75e4b19c301d7c97c0a7f5d1f0a24c227c84e6ee67b06b033 for file /var/lib/mirror-node/recordstreams/valid/2019-09-03T20_43_40.116069Z.rcd
Sep 03 22:00:36 psql-test-02 java[8100]: 2019-09-03 22:00:36,893 TRACE [main ] c.h.d.ApplicationStatus Returning application status for : LAST_VALID_DOWNLOADED_RECORD_FILE_HASH, d8b70aabf07659c3fd05492f3c27b50539e6535a51e6c3e3f747ae3a26a388ddc4eb47e2fffcbc7ff33fcbe436bc1573
Sep 03 22:00:36 psql-test-02 java[8100]: 2019-09-03 22:00:36,893 TRACE [main ] c.h.d.ApplicationStatus Returning application status for : LAST_VALID_DOWNLOADED_RECORD_FILE, 2019-09-03T20_42_00.092453Z.rcd
Sep 03 22:00:36 psql-test-02 java[8100]: 2019-09-03 22:00:36,893 DEBUG [main ] c.h.d.RecordFileDownloader Verified signature file matches at least 2/3 of nodes: 2019-09-03T20_43_40.116069Z.rcd_sig
```

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
Ensures that signature is validated by 2/3 of nodes _and_ the hash chain is validated before moving to valid folder and updating the db. This fixes the race condition with parser processing files that hadn't had their hash chain confirmed.

**Which issue(s) this PR fixes**:
Fixes #195

**Special notes for your reviewer**:
Note this is merging into the release branch `release/0.1` for a `v0.1.1` release. I will cherry pick it to master after.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java [hunk 1]
```diff
@@ -146,35 +119,46 @@ private void verifySigsAndDownloadRecordFiles(Map<String, List<File>> sigFilesMa
...
+					Pair<Boolean, File> rcdFileResult = downloadFile(DownloadType.RCD, validSigFile, tmpDir);
+					File rcdFile = rcdFileResult.getRight();
+					if (rcdFile != null && Utility.hashMatch(validSigFile, rcdFile)) {
+						if (verifyHashChain(rcdFile)) {
+							// move the file to the valid directory
+							File validFile = Paths.get(validDir, rcdFile.getName()).toFile();
+
+							if (moveFile(rcdFile, validFile)) {
+								log.debug("Verified signature file matches at least 2/3 of nodes: {}", fileName);
+								String hash = Utility.bytesToHex(Utility.getFileHash(validFile.getAbsolutePath()));
```
Comment (mike-burrage-hedera) [inline src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Move hash above moveFile() and call on rcdFile. As soon as it's moved it might get processed (and moved again). Longer term we shouldn't be hashing the file all these extra times.

Comment (steven-sheehy) [reply src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Good point. I had it like that then changed it for some reason. Yeah, if we encapsulated the record in a `RecordFile` object we could store such a hash there.
