### PR TITLE
Fix `ContractCallEvmCodesTest`

### LINKED ISSUE #10079: Fix `ContractCallEvmCodesTest` test suite
Fix failing tests for `ContractCallEvmCodesTest` using the modularized EVM

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Bump Hedera app library from 0.58.3 to 0.58.4
* Add a custom `MirrorBlockHashOperation` to fix latest block and not require loading last 256 block hashes
* Add a `ModularizedOperation` interface and inject all implementations into the `TransactionExecutor`
* Change executor properties to allow user defined properties to override defaults
* Change tests to not use epoch for genesis block after upstream config override fix
* Fix `CHAINID` opcode by lazily setting `contracts.chainId` in `buildTransactionProperties` so that it can be changed later by a custom network being set from config
* Fix `PREVRANDAO` opcode by populating `RunningHashes.nMinus3RunningHash` for entropy

**Related issue(s)**:

Fixes #10079

**Notes for reviewer**:

Before
`3359 tests completed, 265 failed, 6 skipped`

After
`3362 tests completed, 258 failed, 6 skipped`

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/SystemFileLoader.java [hunk 1]
```diff
@@ -53,8 +51,8 @@ private Map<FileID, File> loadAll() {
         var configuration = properties.getVersionedConfiguration();
 
         var files = List.of(
-                load(101, fileSchema.genesisAddressBook(networkInfo)),
-                load(102, fileSchema.genesisNodeDetails(networkInfo)),
+                load(101, Bytes.EMPTY), // Requires a node store but these aren't used by contracts so omit
+                load(102, Bytes.EMPTY),
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/SystemFileLoader.java:55]: This was changed upstream in 0.58.4 from `NetworkInfo` to require the node store. It wasn't worth adding a node store implementation since smart contracts internally don't use these two files.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java [hunk 2]
```diff
@@ -335,11 +331,15 @@ public int feesTokenTransferUsageMultiplier() {
...
-        mirrorNodeProperties.put("contracts.evm.version", "v" + evmVersion.major() + "." + evmVersion.minor());
-        mirrorNodeProperties.put(
-                "ledger.id", Bytes.wrap(getNetwork().getLedgerId()).toHexString());
-        return Collections.unmodifiableMap(mirrorNodeProperties);
+        var props = new HashMap<String, String>();
+        props.put("contracts.chainId", chainIdBytes32().toBigInteger().toString());
+        props.put("contracts.evm.version", "v" + evmVersion.major() + "." + evmVersion.minor());
+        props.put("contracts.maxRefundPercentOfGasLimit", String.valueOf(maxGasRefundPercentage()));
+        props.put("contracts.sidecars", "");
+        props.put("executor.maxSignedTxnSize", "262144");
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java:339]: This might clash with the change in here - https://github.com/hashgraph/hedera-mirror-node/pull/10218, depending on which PR gets merged first. Leaving this comment as a reminder.

Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java:339]: I can remove in favor of yours. Was just testing it locally.

**Review by edwin-greene — APPROVED** [review]
Looks good to me

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java (hunk 2 above)
Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java]: Done

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java]: If it is not needed for this PR - sounds good.

**Review by bilyana-gospodinova — DISMISSED** [review]
