### PR TITLE
Remove Crypto Allowance Adjust Acceptance Test

### LINKED ISSUE #3531: Crypto Allowance Acceptance Failing on modified service node API
### Description

As part of the 0.52 release the CryptoService adjustAllowance API was modified in naming on the service nodes.
`adjustAllowance` -> `adjustAllowances`

This caused failures of `io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: proto.CryptoService/adjustAllowance` when running acceptance tests

### Steps to reproduce

1. Run `@acceptance` test against service node on `0.25` using mirror node `0.54.0-rc1`

### Additional context

_No response_

### Hedera network

other

### Version

0.54.0-rc1

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by Nana-EC**
**Description**:
Acceptance tests were failing with `io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: proto.CryptoService/adjustAllowance`. Service nodes changed from `adjustAllowance` to `adjustAllowances` and the changed wasn't captured in the protobuf used by `v0.54.0-rc1` version of the mirror node.

- Remove adjust test from acceptance tests
- Update protobuf version to non snapshot version `0.25.0`

**Related issue(s)**:

Fixes #3531 

**Notes for reviewer**:
Tested against integration

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java [hunk 1]
```diff
@@ -152,6 +155,9 @@ public void accountReceivedFunds(long amount) {
     }
 
     @Then("the mirror node REST API should return status {int} for the crypto transfer transaction")
+    @Retryable(value = {AssertionError.class, AssertionFailedError.class},
+            backoff = @Backoff(delayExpression = "#{@restPollingProperties.minBackoff.toMillis()}"),
+            maxAttemptsExpression = "#{@restPollingProperties.maxAttempts}")
```
Comment (steven-sheehy) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java:160]: We already retry using the same properties inside `MirrorNodeClient.callRestEndpoint()` for each endpoint. So these `@Retryable`'s are redundant and would cause tests to take a really long time to fail.

File: hedera-mirror-test/src/test/resources/features/account/allowances/cryptoAllowance.feature [hunk 2]
```diff
@@ -7,8 +7,6 @@ Feature: Account Crypto Allowance Coverage Feature
         Then the mirror node REST API should confirm the approved <approvedAmount> tℏ crypto transfer allowance
         When <senderName> transfers <transferAmount> tℏ from their approved balance to <recipientName>
         Then the mirror node REST API should return status <httpStatusCode> for the crypto transfer transaction
-        Given I adjust <senderName> transfer allowance to <updateApprovedAmount> tℏ
```
Comment (steven-sheehy) [inline hedera-mirror-test/src/test/resources/features/account/allowances/cryptoAllowance.feature:10]: We should update the pom.xml to a non-snapshot protobuf artifact.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java]: Removed

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
LGTM
