### PR TITLE
Remove rosetta token balance workaround

### LINKED ISSUE #2997: Rosetta deprecate token initial balance workaround
### Problem

As reported in this [ticket](https://github.com/coinbase/rosetta-cli/issues/230), `rosetta-cli` will fail if an account has a newly associated token with non-zero balance in the current block as the tool expects a 0 balance of the token set in the previous block.

As a workaround, hedera rosetta server implementation always hides the latest block and report 0 balance of such a token in the block before the initial token account association. The cost is an extra 2 secs delay.

rosetta-sdk-go v0.7.2 fixed the issue and hedera rosetta server should deprecate the workaround

### Solution

Always return the latest block in db and remove the reporting 0 token balance before token-association block workaround.

### Alternatives

Leave it as is

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR removes the rosetta token balance workaround which was needed without the rosetta-sdk-go 0 token balance fix in v0.7.2:

- No more hiding the latest record file
- Get an account's ever owned tokens by the end of the current block instead of the end of the next block
- Add default for `ROSETTA_CLI_VERSION`

**Related issue(s)**:

Fixes #2997

**Notes for reviewer**:

~~Will run the `rosetta-cli` data check (balance reconciliation) in testnet with new token to confirm no regression.~~ Update, tested it locally and passed.
  
**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rosetta/scripts/validation/run-validation.sh [hunk 1]
```diff
@@ -1,6 +1,8 @@
 #!/bin/bash
 set -euo pipefail
 
+ROSETTA_CLI_VERSION=${ROSETTA_CLI_VERSION:-}
```
Comment (xin-hedera) [inline hedera-mirror-rosetta/scripts/validation/run-validation.sh:4]: ran it locally without the default, got variable not bound error

File: hedera-mirror-rosetta/app/persistence/account_test.go [hunk 2]
```diff
@@ -582,50 +547,72 @@ func (suite *accountRepositorySuite) TestRetrieveEverOwnedTokensByBlockAfter() {
...
+	db.CreateDbRecords(dbClient, cryptoTransfers, tokenTransfers, nftTransfers)
+
+	token1Amount := types.NewTokenAmount(*token1, initialTokenBalances[0].Balance+sum(token1TransferAmounts))
+	token2Amount := types.NewTokenAmount(*token2, initialTokenBalances[1].Balance+sum(token2TransferAmounts))
+	token3Amount := types.NewTokenAmount(*token3, initialTokenBalances[2].Balance+2).
+		SetSerialNumbers([]int64{1, 2, 3, 4})
+
+	return []types.Amount{&types.HbarAmount{}, token1Amount, token2Amount, token3Amount}
+}
+
```
Comment (xin-hedera) [inline hedera-mirror-rosetta/app/persistence/account_test.go:615]: dedup the code so sonar check passes

File: hedera-mirror-rosetta/app/persistence/block_test.go [hunk 3]
```diff
@@ -434,23 +447,10 @@ func (suite *blockRepositorySuite) TestRetrieveGenesisDbConnectionError() {
...
-
-	// then
-	assert.Nil(suite.T(), err)
-	assert.Equal(suite.T(), expectedGenesisBlock, actual)
-}
-
 func (suite *blockRepositorySuite) TestRetrieveLatestNonGenesisBlock() {
 	// given
-	db.CreateDbRecords(dbClient, thirdRecordFile)
+	// db.CreateDbRecords(dbClient, thirdRecordFile)
```
Comment (ijungmann) [inline hedera-mirror-rosetta/app/persistence/block_test.go:452]: Remove

**Review by ijungmann — CHANGES_REQUESTED** [review]
Looks good, one commented out line of code.

**Review by ijungmann — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
LGTM
