### PR TITLE
Fix rosetta token balance reconciliation for deleted account

### LINKED ISSUE #2793: Rosetta fails on fungible token balance reconciliation for deleted accounts
### Description

When an account is deleted, the main nodes will not report balances for the account in the account balance files.

Our rosetta implementation relies on the latest token balance snapshot relative to the queried block timestamp to calculate an account's fungible token balances at the block. As a result, if an account is deleted, for any blocks >= the first account balance snapshot in which the account's balance info has disappeared, `rosetta-cli` will report fungible token balance reconciliation error if for a fungible token, the account owns > 0 balance of that token. 

### Steps to reproduce

1. Run importer, db, and rosetta server
2. Create a fungible token with the testing account as the treasury
3. Mint
4. Delete the fungible token
5. Delete the account
6. Run `rosetta-cli` to check data

Alternatively, set importer `startDate: 2021-11-03T15:35:00Z` and ingest data from testnet, run the `check:data` validation.

### Hedera network

testnet

### Version

v0.43.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR adds support for deleted account's token balance reconciliation.

- Reconcile deleted account's token balance from latest account balance file before deletion
- Switch back to latest `rosetta-cli`
- Fix rare issue which causes `get-genesis-balance.sh` to fail
- Add support to override default rosetta configuration in github workflow CI

**Related issue(s)**:

Fixes #2793 

**Notes for reviewer**:

The solution is described in the ticket #2793.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rosetta/app/persistence/account_test.go [hunk 1]
```diff
@@ -149,19 +162,25 @@ var (
 			ConsensusTimestamp: consensusTimestamp + 1,
 			PayerAccountId:     payer,
 		},
+		{
+			EntityId:           account,
+			Amount:             -(initialAccountBalance.Balance + sum(cryptoTransferAmounts) + 155),
+			ConsensusTimestamp: accountDeleteTimestamp,
+			PayerAccountId:     account2,
+		},
```
Comment (xin-hedera) [inline hedera-mirror-rosetta/app/persistence/account_test.go:170]: https://github.com/hashgraph/hedera-protobufs/blob/368e6b2aecfbd3788f643689ab2e1fb74b4df00b/services/crypto_delete.proto#L39

in order to delete an account, the remaining balance has to be transferred to `transferAccountID` per the proto file.

File: .github/workflows/rosetta-api.yml [hunk 2]
```diff
@@ -73,8 +73,10 @@ jobs:
 
       - name: Set Importer StartDate
         run: |
-          startdate=$(date --date='15 minutes ago' -Iseconds -u)
-          startdate=${startdate%+*}Z
+          # grep extracts the data up to minute, e.g., 2021-11-15T16:48:, so as to always round down to the whole minute
+          # and avoid importer saves the first account balance file but not the account balance entries
+          startdate=$(date --date='15 minutes ago' -Iseconds -u | grep -o -e '^[0-9T:-]\+:')
+          startdate="${startdate}00Z"
```
Comment (xin-hedera) [inline .github/workflows/rosetta-api.yml:79]: fix a rare issue that `get-genesis-balance.sh` fails to get account's genesis hbar balance when the calculated startDate is less than 30s after the account balance file timestamp, e.g., 2021-11-15T16:15:05Z.

What happened is importer has a default 30s startData adjustment, i.e., importer will start downloading account balance files from 2021-11-15T16:14:35Z, however importer will only save account balance entries >= 2021-11-15T16:15:05Z. So we end up having a genesis account balance file at around 2021-11-15T16:15:00Z with no. account balance rows from the file.

File: .github/workflows/rosetta-api.yml [hunk 3]
```diff
@@ -73,16 +76,19 @@ jobs:
 
       - name: Set Importer StartDate
         run: |
-          startdate=$(date --date='15 minutes ago' -Iseconds -u)
-          startdate=${startdate%+*}Z
+          # grep extracts the data up to minute, e.g., 2021-11-15T16:48:, so as to always round down to the whole minute
```
Comment (xin-hedera) [inline .github/workflows/rosetta-api.yml:79]:
```suggestion
          # grep extracts the date up to minute, e.g., 2021-11-15T16:48:, so as to always round down to the whole minute
```

File: hedera-mirror-rosetta/app/persistence/account.go [hunk 4]
```diff
@@ -179,14 +209,42 @@ func (ar *accountRepository) RetrieveEverOwnedTokensByBlockAfter(
 		sql.Named("account_id", accountId),
 		sql.Named("consensus_timestamp", consensusEnd),
 	).Scan(&tokens).Error; err != nil {
-		log.Errorf(databaseErrorFormat, errors.ErrDatabaseError.Message, err)
-		return nil, errors.ErrDatabaseError
+		log.Errorf(
+			databaseErrorFormat,
+			hErrors.ErrDatabaseError.Message,
+			fmt.Sprintf("%v looking for tokens ever owned by %d as of %d", err, accountId, consensusEnd),
```
Comment (Nana-EC) [inline hedera-mirror-rosetta/app/persistence/account.go:215]: nit
```suggestion
			fmt.Sprintf("%v looking for tokens owned by %d as of %d", err, accountId, consensusEnd),
```

**Review by Nana-EC — APPROVED** [review]

**Review by steven-sheehy — APPROVED** [review]

**Review by ijungmann — APPROVED** [review]

File: hedera-mirror-rosetta/app/persistence/account.go (hunk 4 above)
Comment (xin-hedera) [reply hedera-mirror-rosetta/app/persistence/account.go:215]: It's correct since rosetta validation assumes if an account has ever owned a token, there should be a balance forever. To be specific, if an account was associated with a token at time t1, and later at t2 the accounts dissociated himself with the token, in rosetta implementation, the account's balance for the token will be forever 0 from time t2.
