### PR TITLE
Modularized fix ContractCallNestedCallsTest

### LINKED ISSUE #10082: Fix `ContractCallNestedCallsTest` test suite
Fix failing tests for `ContractCallNestedCallsTest` using the modularized EVM

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:
This Pr fixes all failing tests in ContractCallNestedCallsTest against modularized. 20+ test fixes. 
Including an added check in HederaTokenStore for checking if the treasury for nft update is the same then skip checks.

This PR modifies ... in order to support ...
ContractCallServicePrecompileModification - Extract token info setup and ethCall and gas assertions into an abstract class to be used from the NestedCallsTests. Since NestedCalls setup was incomplete.
ContractCallNestedCallsTest - use exctracted setup from ContractCallServicePrecompileModification for token update operations.

HederaTokenStore - added a check for nft update - 
```
!changes.getTreasury()
                .equals(token.getTreasury().getId()
                        .asGrpcAccount())

``` 
otherwise we get TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES if we try to update the token nft passing the same treasury. This was previouslly bypassed by not persisting token association with the treasury in the test setup which seems incorrect. Modularized code has similar check ->

` if (!newTreasury.equals(existingTreasury)) {`

**Related issue(s)**:

Fixes #10082 

**Notes for reviewer**:
3358 tests completed, 247 failed, 6 skipped

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java [hunk 1]
```diff
@@ -579,7 +594,9 @@ private void processAutoRenewAccount(
 
     private ResponseCodeEnum checkNftBalances(
             final Token token, final TokenID tId, final TokenUpdateTransactionBody changes) {
-        if (token.getType().equals(TokenType.NON_FUNGIBLE_UNIQUE) && changes.hasTreasury()) {
+        if (token.getType().equals(TokenType.NON_FUNGIBLE_UNIQUE)
+                && changes.hasTreasury()
+                && !changes.getTreasury().equals(token.getTreasury().getId().asGrpcAccount())) {
```
Comment (kselveliev) [inline hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java:599]: Specific check added for mono code execution other wise token update nft test fails with TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java [hunk 2]
```diff
@@ -320,6 +329,18 @@ protected void tokenAccountPersist(final Entity token, final Entity account) {
         tokenAccountPersist(token, account.toEntityId().getId());
     }
 
+    protected void tokenAccountPersist(final Entity token, final Entity account, long balance) {
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java:332]: We have a 2 similar methods in the same class - `tokenAccountPersist(final Entity token, final Entity account)` and `tokenAccountPersist(final Entity token, final Long accountId)`. Perhaps they can be rewritten to use this one in order to avoid code duplication. Example:

```
protected void tokenAccountPersist(final Entity token, final Entity account) {
        tokenAccountPersist(token, account, domainBuilder.number());
    }

    protected void tokenAccountPersist(final Entity token, final Long accountId) {
        tokenAccountPersist(token, accountId, domainBuilder.number());
    }

    protected void tokenAccountPersist(final Entity token, final Entity account, long balance) {
        tokenAccountPersist(token, account.toEntityId().getId(), balance);
    }

    protected void tokenAccountPersist(final Entity token, final Long accountId, long balance) {
        domainBuilder
                .tokenAccount()
                .customize(ta -> ta.tokenId(token.getId())
                        .accountId(accountId)
                        .freezeStatus(TokenFreezeStatusEnum.UNFROZEN)
                        .kycStatus(TokenKycStatusEnum.GRANTED)
                        .balance(balance)
                        .associated(true))
                .persist();
    }
```

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java [hunk 3]
```diff
@@ -405,6 +457,21 @@ protected ContractFunctionProviderRecord getContractFunctionProviderWithSender(
                 .build();
     }
 
+    protected ContractExecutionParameters getContractExecutionParameters(
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java:460]: Same as the other comment:

```
protected ContractExecutionParameters getContractExecutionParameters(
            final RemoteFunctionCall<?> functionCall, final Contract contract, final Long value) {
    return getContractExecutionParameters(Bytes.fromHexString(functionCall.encodeFunctionCall()),
            Address.fromHexString(contract.getContractAddress()),
            testWeb3jService.getSender(),
            value);
}
```

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java (hunk 2 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java:336]: Done

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java (hunk 3 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java:456]: Comment addressed

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java:599]: Makes sense and matches `TokenUpdateHandler` logic.

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java [hunk 4]
```diff
@@ -317,27 +325,37 @@ protected Entity accountEntityWithEvmAddressPersist() {
...
 
     protected void tokenAccountPersist(final Entity token, final Long accountId) {
+        tokenAccountPersist(token, accountId, domainBuilder.number());
+    }
+
+    protected void tokenAccountPersist(final Entity token, final Entity account, long balance) {
+        tokenAccountPersist(token, account.toEntityId().getId(), balance);
+    }
+
+    protected void tokenAccountPersist(final Entity token, final Long accountId, long balance) {
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java:339]: This is why I don't like these void helper methods since they start multiplying when we need slightly different input. The better alternative is to do:

```java
    protected TokenAccount tokenAccount(EntityId tokenId, EntityId accountId) {
        return domainBuilder.tokenAccount().customize(ta -> ta.tokenId(tokenId).accountId(accountId).freezeStatus()...).get();
    }
```

and leave it up to the caller to persist. Or if we want persistence:

```java
    protected TokenAccount tokenAccount(Consumer<TokenAccount> consumer) {
        return domainBuilder.tokenAccount().customize(ta -> ta.freezeStatus()...).customize(consumer).persist();
    }
```

Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java]: Comment addressed applied the consumer suggestion

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
