### PR TITLE
Remove data generator

### LINKED ISSUE #2312: Remove data generator module
### Problem

The data generator module, with the exception of the transaction suppliers, has not been used since its inception. It also has very little unit tests so it greatly impacts our overall code coverage.

### Solution

- Move transaction suppliers to monitor `com.hedera.mirror.monitor.publish.transaction` package
- Add basic unit test coverage for all transaction suppliers
  - There should be a test that sets all fields (or uses defaults) and verifies fields present on the generated protobuf (use `TransactionList.parseFrom(sdkTransaction.toBytes())`)
  - Any additional tests for corner cases.
- Delete data generator module

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by ijungmann**
**Description**:
Remove data generator module and add test cases for TransactionSuppliers

* Remove the data generator module and all references to it.
* Move TransactionSuppliers and anything else needed by the monitor into the monitor module
* Add unit tests for the TransactionSuppliers

**Related issue(s)**:

Fixes #2312 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+                .setAccountMemo(actual.getAccountMemo())
+                .setExpirationTime(actual.getExpirationTime())
+                .setMaxTransactionFee(Hbar.fromTinybars(1_000_000_000))
+                .setReceiverSignatureRequired(false)
+                .setTransactionMemo(actual.getTransactionMemo());
+
+        assertAll(
+                () -> assertThat(actual.getTransactionMemo()).contains("Mirror node updated test account"),
+                () -> assertThat(actual.getExpirationTime()).isNotNull(),
+                () -> assertThat(actual).usingRecursiveComparison().isEqualTo(expected)
```
Comment (ijungmann) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java:55]: Do a pass for alphabetical order on checks and sets.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+    private static final Hbar MAX_TRANSACTION_FEE_HBAR = Hbar.fromTinybars(10_000_000L);
+
+    @Test
+    void createWithMinimumData() {
+        CryptoTransferTransactionSupplier cryptoTransferTransactionSupplier = new CryptoTransferTransactionSupplier();
+        cryptoTransferTransactionSupplier.setRecipientAccountId(ACCOUNT_ID_2.toString());
+        cryptoTransferTransactionSupplier.setSenderAccountId(ACCOUNT_ID.toString());
+        TransferTransaction actual = cryptoTransferTransactionSupplier.get();
+
+        Hbar transferAmount = ONE_TINYBAR;
```
Comment (ijungmann) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java:50]: Remove

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+import com.hedera.hashgraph.sdk.AccountCreateTransaction;
+import com.hedera.hashgraph.sdk.Hbar;
+import com.hedera.hashgraph.sdk.PrivateKey;
+import com.hedera.hashgraph.sdk.PublicKey;
+import com.hedera.mirror.monitor.publish.transaction.AbstractTransactionSupplierTest;
+
+class AccountCreateTransactionSupplierTest extends AbstractTransactionSupplierTest {
+
+    @Test
+    void createWithMinimumData() {
```
Comment (ijungmann) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java:17]: Should probably be `Minimal`, no `Minimum`

**Comment by ijungmann** [comment]
Will address code smells

**Comment by steven-sheehy** [comment]
> Merging #2387 (88d4072) into main (10cbbb0) will increase coverage by 7.44%.

92% coverage now. Nice!

**Comment by ijungmann** [comment]
> > Merging #2387 ([88d4072](https://github.com/hashgraph/hedera-mirror-node/commit/88d407288dbc43835a10ea6dc2781efd195824a2)) into main ([10cbbb0](https://github.com/hashgraph/hedera-mirror-node/commit/10cbbb0ccd5fd512022d77bc07de83b07bd7a298)) will increase coverage by 7.44%.
> 
> 92% coverage now. Nice!

Yeah!  Much nicer number.

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/util/Utility.java [hunk 4]
```diff
@@ -1,10 +1,10 @@
-package com.hedera.datagenerator.common;
+package com.hedera.mirror.monitor.util;
 
-/*-
+/*
  * ‌
  * Hedera Mirror Node
  * ​
- * Copyright (C) 2019 - 2021 Hedera Hashgraph, LLC
+ * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
```
Comment (Nana-EC) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/util/Utility.java:7]: Fix year

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/AbstractTransactionSupplierTest.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
+package com.hedera.mirror.monitor.publish.transaction;/*
+ * ‌
+ * Hedera Mirror Node
+ * ​
+ * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
```
Comment (Nana-EC) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/AbstractTransactionSupplierTest.java:5]: Copy right repeated. Should also be 2021

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Seems there were merge issue with copyrights details.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+                .setKey(key)
+                .setMaxTransactionFee(ONE_TINYBAR)
+                .setReceiverSignatureRequired(true)
+                .setTransactionMemo(actual.getTransactionMemo());
+
+        assertAll(
+                () -> assertThat(actual.getTransactionMemo()).contains("Mirror node created test account"),
+                () -> assertThat(actual.getAccountMemo()).contains("Mirror node created test account"),
+                () -> assertThat(actual).usingRecursiveComparison().isEqualTo(expected)
+        );
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java:58]: I don't like creating a temporary object just do do equality on it. I'm also not a fan of `assertAll`. It would be simpler to do a single chaining assert to verify results:

```java
assertThat(actual)
    .returns(key, AccountCreateTransaction::getKey)
    .returns(ONE_TINYBAR, AccountCreateTransaction::getMaxTransactionFee)
...
```

You can chain non-equality assertions like contains using `satisfies(a -> assertThat(a.get...())` or using `extracting()` at the end.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/util/Utility.java (hunk 4 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/util/Utility.java]: Fixed.  I've removed the setup I had to add this automatically as it had all sorts of issues so this doesn't crop up again.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/util/UtilityTest.java [hunk 7]
```diff
@@ -1,10 +1,10 @@
-package com.hedera.datagenerator.common;
+package com.hedera.mirror.monitor.util;
 
-/*-
+/*
  * ‌
  * Hedera Mirror Node
  * ​
- * Copyright (C) 2019 - 2021 Hedera Hashgraph, LLC
+ * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
```
[the remark this answers is not in the document]
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/util/UtilityTest.java]: Fixed, and removed my setup for doing this automatically as it was causing other issues randomly.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/AbstractTransactionSupplierTest.java [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+
+import com.hedera.hashgraph.sdk.AccountId;
+import com.hedera.hashgraph.sdk.Hbar;
+import com.hedera.hashgraph.sdk.ScheduleId;
+import com.hedera.hashgraph.sdk.TokenId;
+import com.hedera.hashgraph.sdk.TopicId;
+
+public abstract class AbstractTransactionSupplierTest {
+    protected static final AccountId ACCOUNT_ID = AccountId.fromString("0.0.3");
+
```
[the remark this answers is not in the document]
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/AbstractTransactionSupplierTest.java]: Sure, removed.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java (hunk 6 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java:78]: The thing I like about creating the temporary object and doing equality on it is it forces someone to set every field, it protects against future fields or some of the fields that aren't as explicit (like setting `adminKey` in a supplier also gets used for `submitKey`, `freezeKey`, etc.). The other thing I'm running into as I've tried to convert over, `TokenNftTransfer` is not a public class so I don't know of a great way to go field-by-field for that.

I do see the value in the chaining you mentioned, that can be done.

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenarioProperties.java [hunk 9]
```diff
@@ -26,11 +26,13 @@
 import javax.validation.constraints.Max;
 import javax.validation.constraints.Min;
 import javax.validation.constraints.NotNull;
+
+import com.hedera.mirror.monitor.publish.transaction.TransactionType;
+
```
Comment (xin-hedera) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenarioProperties.java:31]: nit: reorder imports

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java [hunk 10]
```diff
@@ -0,0 +1,78 @@
...
+        AccountCreateTransaction expected = new AccountCreateTransaction()
+                .setAccountMemo(actual.getAccountMemo())
+                .setInitialBalance(Hbar.fromTinybars(10_000_000))
+                .setKey(actual.getKey())
+                .setMaxTransactionFee(MAX_TRANSACTION_FEE_HBAR)
+                .setReceiverSignatureRequired(false)
+                .setTransactionMemo(actual.getTransactionMemo());
+
+        assertThat(actual)
+                .satisfies(a -> assertThat(a.getAccountMemo()).contains("Mirror node created test account"))
```
Comment (xin-hedera) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java:48]: can set the expected object's `accountMemo` and `transactionMemo` to the strings directly and assert the objects equal here

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java (hunk 6 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java]: That's fair, I did have a to do something different with `ScheduleCreate` for that reason, too many internal fields that I could not get a hold of to even set the `expected` and all of the extra fields you mentioned.  I'll work on swapping things over to just checking fields and will keep an eye out for other bugs.

Comment (steven-sheehy) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java]: 2.0.11 of sdk was released with my fix for public class.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java [hunk 11]
```diff
@@ -0,0 +1,78 @@
...
+                .satisfies(a -> assertThat(a.getKey()).isNotNull())
+                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node created test account"))
+                .satisfies(a -> assertThat(a).usingRecursiveComparison().isEqualTo(expected));
```
[the remark this answers is not in the document]
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java]: Removed this line.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java (hunk 10 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java:44]: Removed the logic to compare against `expected` as per Steven's suggestion.  I also wanted to make sure that the memo contained the correct message, just setting the `expected` to what was in the `actual` and then doing an object equals means I just have to trust that the `actual` has what I want.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java (hunk 6 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountCreateTransactionSupplierTest.java]: Reworked the tests to use the chaining suggested.

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenarioProperties.java (hunk 9 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishScenarioProperties.java]: Fixed.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java [hunk 12]
```diff
@@ -0,0 +1,61 @@
...
+class AccountDeleteTransactionSupplierTest extends AbstractTransactionSupplierTest {
+
+    @Test
+    void createWithMinimumData() {
+        AccountDeleteTransactionSupplier accountDeleteTransactionSupplier = new AccountDeleteTransactionSupplier();
+        accountDeleteTransactionSupplier.setAccountId(ACCOUNT_ID.toString());
+        AccountDeleteTransaction actual = accountDeleteTransactionSupplier.get();
+
+        assertThat(actual)
+
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java:40]: Extra new line

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+                .returns(ACCOUNT_ID, AccountDeleteTransaction::getAccountId)
+                .returns(MAX_TRANSACTION_FEE_HBAR, AccountDeleteTransaction::getMaxTransactionFee)
+                .returns(AccountId.fromString("0.0.2"), AccountDeleteTransaction::getTransferAccountId)
+                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node deleted test account"));
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java:44]: For the last chain, you can use extract to make this cleaner.
```suggestion
                .extracting(AccountDeleteTransaction::getTransactionMemo)
                .contains("Mirror node deleted test account");
```

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java [hunk 14]
```diff
@@ -0,0 +1,78 @@
...
+        AccountUpdateTransaction actual = accountUpdateTransactionSupplier.get();
+
+        assertThat(actual)
+                .returns(ACCOUNT_ID, AccountUpdateTransaction::getAccountId)
+                .returns(expirationTime, AccountUpdateTransaction::getExpirationTime)
+                .returns(key, AccountUpdateTransaction::getKey)
+                .returns(ONE_TINYBAR, AccountUpdateTransaction::getMaxTransactionFee)
+                .returns(ACCOUNT_ID_2, AccountUpdateTransaction::getProxyAccountId)
+                .returns(true, AccountUpdateTransaction::getReceiverSignatureRequired)
+                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node updated test account"))
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java:75]: We can remove the transaction memos in all suppliers since we override it in TransactionPublisher anyway. But we can defer this to avoid churn.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java [hunk 15]
```diff
@@ -0,0 +1,181 @@
...
+        assertThat(actual)
+                .returns(Collections.emptyMap(), TransferTransaction::getHbarTransfers)
+                .returns(ONE_TINYBAR, TransferTransaction::getMaxTransactionFee)
+                .returns(Collections.emptyMap(), TransferTransaction::getTokenNftTransfers)
+                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node created test transfer"))
+                .extracting(TransferTransaction::getTokenTransfers)
+                .returns(1, Map::size)
+                .satisfies(transfers -> assertThat(transfers.get(TOKEN_ID))
+                        .returns(-10L, map -> map.get(ACCOUNT_ID))
+                        .returns(10L, map -> map.get(ACCOUNT_ID_2)));
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java:102]:
```suggestion
                .hasSize(1)
                .extractingByKey(TOKEN_ID, InstanceOfAssertFactories.MAP)
                .containsEntry(ACCOUNT_ID, -10L)
                .containsEntry(ACCOUNT_ID_2, 10L);
```

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java [hunk 16]
```diff
@@ -0,0 +1,181 @@
...
+
+        assertThat(actual)
+                .returns(Collections.emptyMap(), TransferTransaction::getHbarTransfers)
+                .returns(ONE_TINYBAR, TransferTransaction::getMaxTransactionFee)
+                .returns(Collections.emptyMap(), TransferTransaction::getTokenTransfers)
+                .satisfies(a -> assertThat(a.getTransactionMemo()).contains("Mirror node created test transfer"))
+                .extracting(TransferTransaction::getTokenNftTransfers)
+                .returns(1, Map::size)
+                .extracting(transfers -> transfers.get(TOKEN_ID))
+                .returns(2, List::size)
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java:126]:
```suggestion
                .hasSize(1)
                .extractingByKey(TOKEN_ID, InstanceOfAssertFactories.LIST)
                .hasSize(2)
```

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java [hunk 17]
```diff
@@ -0,0 +1,181 @@
...
+                .satisfies(transferList -> assertThat(transferList.get(0))
+                        //TODO Swap these with getters
+                        .returns(10L, transfer -> transfer.serial)
+                        .returns(ACCOUNT_ID, transfer -> transfer.sender)
+                        .returns(ACCOUNT_ID_2, transfer -> transfer.receiver))
+                .satisfies(transferList -> assertThat(transferList.get(1))
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java:132]:
```suggestion
                .last()
```

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java [hunk 18]
```diff
@@ -0,0 +1,181 @@
...
+                        .returns(11L, transfer -> transfer.serial)
+                        .returns(ACCOUNT_ID, transfer -> transfer.sender)
+                        .returns(ACCOUNT_ID_2, transfer -> transfer.receiver));
+
+//
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java:137]:
```suggestion
```

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java [hunk 19]
```diff
@@ -0,0 +1,83 @@
...
+        consensusSubmitMessageTransactionSupplier.setMaxTransactionFee(1);
+        consensusSubmitMessageTransactionSupplier.setMessageSize(14);
+        consensusSubmitMessageTransactionSupplier.setTopicId(TOPIC_ID.toString());
+        TopicMessageSubmitTransaction actual = consensusSubmitMessageTransactionSupplier.get();
+
+        assertThat(actual)
+                .returns(ONE_TINYBAR, TopicMessageSubmitTransaction::getMaxTransactionFee)
+                .returns(TOPIC_ID, TopicMessageSubmitTransaction::getTopicId)
+                .satisfies(a -> assertThat(a.getMessage()).isNotNull())
+                .satisfies(a -> assertThat(a.getMessage().size()).isEqualTo(14));
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java:64]:
```suggestion
                .extracting(TopicMessageSubmitTransaction::getMessage)
                .hasSize(14);
```

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java [hunk 20]
```diff
@@ -0,0 +1,83 @@
...
+        ConsensusSubmitMessageTransactionSupplier consensusSubmitMessageTransactionSupplier =
+                new ConsensusSubmitMessageTransactionSupplier();
+        consensusSubmitMessageTransactionSupplier.setMaxTransactionFee(1);
+        consensusSubmitMessageTransactionSupplier.setMessage(message);
+        consensusSubmitMessageTransactionSupplier.setTopicId(TOPIC_ID.toString());
+        TopicMessageSubmitTransaction actual = consensusSubmitMessageTransactionSupplier.get();
+
+        assertThat(actual)
+                .returns(true, a -> Arrays.equals(message.getBytes(StandardCharsets.UTF_8), actual.getMessage()
+                        .toByteArray()))
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java:79]: Why wouldn't this work?
```suggestion
                .returns(ByteString.copyFromUtf8(message), TopicMessageSubmitTransaction::getMessage)
```

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java (hunk 13 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java:44]: I've had some issues with `extracting`, I get build errors on this unless I have `toString()` after extracting, it doesn't recognize `contains` otherwise.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java (hunk 12 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java]: Removed.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java (hunk 14 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountUpdateTransactionSupplierTest.java]: I've removed the checks in the tests for this, I'll make a separate PR to address removing them from the `Suppliers` so that this PR doesn't continue to morph.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java (hunk 13 above)
Comment (steven-sheehy) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java]: I guess it assumes ObjectAssert unless you tell it otherwise:
```java
    .extracting(AccountDeleteTransaction::getTransactionMemo, InstanceOfAssertFactories.STRING)
    .contains("Mirror node deleted test account");
```

Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/AccountDeleteTransactionSupplierTest.java]: Did that here and in other places where there is a memo (removed transaction memo checks)

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java (hunk 15 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java]: Refactored all tests to follow this format

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java (hunk 16 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java]: Refactored all tests to follow this format

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java (hunk 17 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java]: Ended up extracting the fields into tuples and using `containsExactlyInAnyOrder`, but good to know about `last`

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java (hunk 18 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/account/CryptoTransferTransactionSupplierTest.java]: Removed.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java (hunk 19 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java]: Had to add `toStringUtf8()` because AssertJ wanted it cast to a String, but otherwise this is done.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java (hunk 20 above)
Comment (ijungmann) [reply hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/consensus/ConsensusSubmitMessageTransactionSupplierTest.java]: Done.

File: hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/token/TokenMintTransactionSupplierTest.java [hunk 21]
```diff
@@ -0,0 +1,106 @@
...
+        tokenMintTransactionSupplier.setType(TokenType.NON_FUNGIBLE_UNIQUE);
+        TokenMintTransaction actual = tokenMintTransactionSupplier.get();
+        assertThat(actual)
+                .returns(0L, TokenMintTransaction::getAmount)
+                .returns(ONE_TINYBAR, TokenMintTransaction::getMaxTransactionFee)
+                .returns(TOKEN_ID, TokenMintTransaction::getTokenId)
+                .extracting(TokenMintTransaction::getMetadata)
+                .returns(2, List::size)
+                .returns(14, metadataList -> metadataList.get(0).length)
+                .returns(14, metadataList -> metadataList.get(1).length);
```
Comment (ijungmann) [inline hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/token/TokenMintTransactionSupplierTest.java:82]: Haven't found a good chain to check this yet, if I cast it to a list in the `extracting` it won't let me use `returns`, which then I didn't see a great way to extract the length of each the byte array cleanly.  Suggestions are welcome, this is the only test that hasn't been refactored.

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/transaction/token/TokenUpdateTransactionSupplier.java [hunk 22]
```diff
@@ -67,8 +65,6 @@
     public TokenUpdateTransaction get() {
         String memo = Utility.getMemo("Mirror node updated test token");
         TokenUpdateTransaction tokenUpdateTransaction = new TokenUpdateTransaction()
-                .setAutoRenewPeriod(autoRenewPeriod)
-                .setExpirationTime(expirationTime)
```
Comment (ijungmann) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/transaction/token/TokenUpdateTransactionSupplier.java:71]: `expirationTime` is coerced by the `autoRenewPeriod`, if `setExpirationTime` is called it also sets `autoRenewPeriod` to null, so setting both does nothing.  I'll have a separate PR to address this in a couple other spots I saw in other modules.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
LGTM
