### PR TITLE
Fix NullPointerException when calculating gasConsumed

### LINKED ISSUE #7872: NPE ContractResultServiceImpl
### Description

Previewnet encountered an NPE when processing record files.

### Steps to reproduce

Process 2024-03-06T14_37_44.262349003Z.rcd.gz from the previewnet bucket and notice error

```
2024-03-06T15:17:51.048Z ERROR scheduling-2 c.h.m.i.p.r.RecordFileParser Error parsing file 2024-03-06T14_37_44.262349003Z.rcd.gz after 960.8 μs java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
	at com.hedera.mirror.importer.domain.ContractResultServiceImpl$SidecarProcessingResult.getIntrinsicGas(ContractResultServiceImpl.java:537)
	at com.hedera.mirror.importer.domain.ContractResultServiceImpl.processContractResult(ContractResultServiceImpl.java:274)
	at com.hedera.mirror.importer.domain.ContractResultServiceImpl.process(ContractResultServiceImpl.java:107)
	at com.hedera.mirror.importer.parser.record.entity.EntityRecordItemListener.onItem(EntityRecordItemListener.java:161)
	at com.hedera.mirror.importer.parser.record.entity.EntityRecordItemListener.onItem(EntityRecordItemListener.java:77)
	at com.hedera.mirror.importer.parser.record.RecordFileParser.lambda$doParse$0(RecordFileParser.java:174)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.hedera.mirror.importer.parser.record.RecordFileParser.doParse(RecordFileParser.java:166)
	at com.hedera.mirror.importer.parser.record.RecordFileParser.doParse(RecordFileParser.java:52)
	at com.hedera.mirror.importer.parser.AbstractStreamFileParser.parse(AbstractStreamFileParser.java:99)
	at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:127)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:102)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:335)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:135)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:161)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at com.hedera.mirror.importer.parser.record.RecordFileParser$$SpringCGLIB$$0.parse(<generated>)
	at com.hedera.mirror.importer.config.MessagingConfiguration.lambda$integrationFlow$1(MessagingConfiguration.java:93)
	at org.springframework.integration.handler.LambdaMessageProcessor.invokeMethod(LambdaMessageProcessor.java:208)
	at org.springframework.integration.handler.LambdaMessageProcessor.processMessage(LambdaMessageProcessor.java:121)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:95)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:145)
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleWithMetrics(AbstractMessageHandler.java:90)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:70)
	at org.springframework.integration.endpoint.PollingConsumer.handleMessage(PollingConsumer.java:158)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:481)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:467)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:419)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:355)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$5(AbstractPollingEndpoint.java:348)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source
```

### Additional context

_No response_

### Hedera network

previewnet

### Version

v0.100.0-rc1

### Operating system

None

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

**Related issue(s)**:

Fixes #7872

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 1]
```diff
@@ -447,18 +447,6 @@ private SidecarProcessingResult processSidecarRecords(
                     stopwatch);
         }
 
-        // For a contract call we need to use the function parameters from the transaction body
```
Comment (jascks) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:450]: It looks like this is deleted because the function parameters are now provided to `SidecarProcessingResult.getIntrinsicGas()`.

**Review by jascks — APPROVED** [review]
LGTM

**Review by IvanKavaldzhiev — DISMISSED** [review]
LGTM

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 2]
```diff
@@ -271,7 +271,7 @@ private void processContractResult(
 
             if (sidecarProcessingResult.totalGasUsed() != null) {
                 contractResult.setGasConsumed(
-                        sidecarProcessingResult.totalGasUsed() + sidecarProcessingResult.getIntrinsicGas());
+                        sidecarProcessingResult.getIntrinsicGas(contractResult.getFunctionParameters()));
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:274]: It’s better to encapsulate the logic into SidecarProcessingResult so we don’t check totalGasUsed != null here

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java]: Reworked

**Review by IvanKavaldzhiev — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM
