### PR TITLE
Fix NPE in StreamFileParser when items was reset to null

### LINKED ISSUE #4148: NPE when importer tries to reparse a record file after db transaction time out
### Description

Importer hits repeating NPE after db transaction of parsing a record file timed out,

```
2022-07-21T13:29:27.689-0600 INFO scheduling-6 c.h.m.i.p.r.RecordFileParser Successfully processed 1 items from 2022-07-21T16_23_58.041175003Z.rcd in 1.277 ms 
2022-07-21T13:29:27.747-0600 INFO scheduling-3 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v5 record file 2022-07-21T16_24_18.113342003Z.rcd in 95.56 μs 
2022-07-21T13:29:27.772-0600 INFO scheduling-3 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v5 record file 2022-07-21T16_24_23.358310003Z.rcd in 110.2 μs 
2022-07-21T13:29:27.813-0600 INFO scheduling-3 c.h.m.i.r.r.CompositeRecordFileReader Read 3 items successfully from v5 record file 2022-07-21T16_24_24.236074434Z.rcd in 94.80 μs 
2022-07-21T13:29:27.835-0600 INFO scheduling-3 c.h.m.i.r.r.CompositeRecordFileReader Read 2 items successfully from v5 record file 2022-07-21T16_24_26.253226003Z.rcd in 76.15 μs 
2022-07-21T13:29:57.135-0600 ERROR scheduling-6 o.h.e.j.b.i.BatchingBatch HHH000315: Exception executing batch [java.sql.BatchUpdateException: Batch entry 0 insert into record_file (bytes, consensus_start, count, digest_algorithm, file_hash, gas_used, hapi_version_major, hapi_version_minor, hapi_version_patch, hash, index, load_end, load_start, logs_bloom, name, node_account_id, prev_hash, sidecar_count, size, version, consensus_end) values (NULL, 1658420638041175003, 1, 0, '6a9cc6be99775b26b2bd96c245f65e2a80443bb261e2db394253664114f925557df358222c0fade40d909d23fc6b2e40', 0, 0, 27, 0, 'c16889e0d9de4679b5b0d71031c50c1f21e5276cc569c180334c30dbb19b0a470e3bf981848a88920a43ae6fc441838c', 23072126, 1658431767, 1658431765, ?, '2022-07-21T16_23_58.041175003Z.rcd', 3, '2c3cbc9158340597469513b4441702b10667b53591ef00db70ab42abf80e04af31f6b08a80e6b23325d453f436326b81', 0, 600, 5, 1658420638041175003) was aborted: ERROR: canceling statement due to user request  Call getNextException to see other errors in the batch.], SQL: insert into record_file (bytes, consensus_start, count, digest_algorithm, file_hash, gas_used, hapi_version_major, hapi_version_minor, hapi_version_patch, hash, index, load_end, load_start, logs_bloom, name, node_account_id, prev_hash, sidecar_count, size, version, consensus_end) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2022-07-21T13:29:57.135-0600 WARN scheduling-6 o.h.e.j.s.SqlExceptionHelper SQL Error: 0, SQLState: 57014 
2022-07-21T13:29:57.135-0600 ERROR scheduling-6 o.h.e.j.s.SqlExceptionHelper Batch entry 0 insert into record_file (bytes, consensus_start, count, digest_algorithm, file_hash, gas_used, hapi_version_major, hapi_version_minor, hapi_version_patch, hash, index, load_end, load_start, logs_bloom, name, node_account_id, prev_hash, sidecar_count, size, version, consensus_end) values (NULL, 1658420638041175003, 1, 0, '6a9cc6be99775b26b2bd96c245f65e2a80443bb261e2db394253664114f925557df358222c0fade40d909d23fc6b2e40', 0, 0, 27, 0, 'c16889e0d9de4679b5b0d71031c50c1f21e5276cc569c180334c30dbb19b0a470e3bf981848a88920a43ae6fc441838c', 23072126, 1658431767, 1658431765, ?, '2022-07-21T16_23_58.041175003Z.rcd', 3, '2c3cbc9158340597469513b4441702b10667b53591ef00db70ab42abf80e04af31f6b08a80e6b23325d453f436326b81', 0, 600, 5, 1658420638041175003) was aborted: ERROR: canceling statement due to user request  Call getNextException to see other errors in the batch. 
2022-07-21T13:29:57.135-0600 ERROR scheduling-6 o.h.e.j.s.SqlExceptionHelper ERROR: canceling statement due to user request 
2022-07-21T13:29:57.371-0600 INFO scheduling-4 c.h.m.i.p.b.BatchInserter Copied 200000 rows to token_balance table in 31.53 s 
2022-07-21T13:29:57.479-0600 ERROR scheduling-6 c.h.m.i.p.r.RecordFileParser Error parsing file 2022-07-21T16_23_58.041175003Z.rcd after 91.13 ms java.lang.NullPointerException: Cannot invoke "reactor.core.publisher.Flux.doOnNext(java.util.function.Consumer)" because "recordItems" is null\\n  at com.hedera.mirror.importer.parser.record.RecordFileParser.doParse(RecordFileParser.java:134)\\n  at com.hedera.mirror.importer.parser.record.RecordFileParser.doParse(RecordFileParser.java:52)\\n at com.hedera.mirror.importer.parser.AbstractStreamFileParser.parse(AbstractStreamFileParser.java:79)\\n  at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:117)\\n  at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:52)\\n at com.hedera.mirror.importer.parser.record.RecordFileParser$$FastClassBySpringCGLIB$$8b9310db.invoke(<generated>)\\n at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\\n  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)\\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)\\n at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\\n at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\\n at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\\n  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)\\n at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:97)\\n  at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)\\n at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)\\n at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:133)\\n  at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:160)\\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)\\n at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)\\n at com.hedera.mirror.importer.parser.record.RecordFileParser$$EnhancerBySpringCGLIB$$4e3fe02.parse(<generated>)\\n  at com.hedera.mirror.importer.config.MessagingConfiguration.lambda$integrationFlow$1(MessagingConfiguration.java:107)\\n  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\\n  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\\n  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\\n  at java.base/java.lang.reflect.Method.invoke(Method.java:568)\\n  at org.springframework.integration.handler.LambdaMessageProcessor.processMessage(LambdaMessageProcessor.java:105)\\n  at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:105)\\n  at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136)\\n at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)\\n  at org.springframework.integration.endpoint.PollingConsumer.handleMessage(PollingConsumer.java:158)\\n  at org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:475)\\n  at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:461)\\n at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:413)\\n at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:348)\\n  at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)\\n  at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)\\n  at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)\\n at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$5(AbstractPollingEndpoint.java:341)\\n  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\\n at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)\\n  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\\n at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\\n  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\\n  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\\n at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\\n at java.base/java.lang.Thread.run(Thread.java:833)
``` 

Problem is when `RecordFileParser` finishes parsing a record file, `AbstractStreamFileParser.postParse(T streamFile)` will set the items to `null`. However, under certain circumstance, the db server may not be able to flush and commit the data of the db transaction within the configured transaction timeout. A db rollback  then will happen, and a spring transaction timeout exception will throw which causes the `RecordFileParser` to retry parsing the `recordFile` object with a `null` items.

### Steps to reproduce

Set `hedera.mirror.importer.parser.record.transactionTimeout` to `1s` and let importer process very large record files should trigger the bug fairly easily.

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.60.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the NPE bug in parser.

- Remove `AbstractStreamFileParser.postParse`
- Set the cloned `StreamFile` object with `bytes` and `items` cleared as the cached `lastStreamFile` in downloader

**Related issue(s)**:

Fixes #4148 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/StreamFile.java [hunk 1]
```diff
@@ -27,6 +27,8 @@
 
 public interface StreamFile<T extends StreamItem> {
 
+    StreamFile<T> copy();
```
Comment (steven-sheehy) [inline hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/StreamFile.java:30]: Use standard `clone()` and implement `Cloneable`

Comment (xin-hedera) [reply hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/StreamFile.java]: done

**Review by steven-sheehy — DISMISSED** [review]

**Review by edwin-greene — APPROVED** [review]
Looks good.

**Review by edwin-greene — APPROVED** [review]

**Review by steven-sheehy — APPROVED** [review]
