### PR TITLE
Fix null hash on contract results in REST API

### LINKED ISSUE #4436: Null hash on contract results
### Description

The non-detail contract result API calls return a null hash in its response.

`https://{env}.mirrornode.hedera.com/api/v1/contracts/{id}/results`
`https://{env}.mirrornode.hedera.com/api/v1/contracts/results`

### Steps to reproduce

https://{env}.mirrornode.hedera.com/api/v1/contracts/{id}/results

### Additional context

```json
{
  "results": [
    {
      "amount": 0,
      "bloom": "0x00020000000000000000000000000000004000000000000000000000000000000000000001000000000000000000000040000000000000000000000000000000000401000000000000000008000000000008000000000000000000000000000000000000000000000000008000000000000000000000000000000010000410000000000000000000000000000000000000000800000000000000000000000000040000000000000800000000000000000000000000000000000000000000000000000002000000000000000000000000100000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000",
      "call_result": "0x0000000000000000000000000000000000000000000000000000000000000905",
      "contract_id": "0.0.2307",
      "created_contract_ids": [
        "0.0.2309"
      ],
      "error_message": null,
      "from": "0x00000000000000000000000000000000000008e7",
      "function_parameters": "0x0419eca500000000000000000000000000000000000000000000000000000000000003e8",
      "gas_limit": 3000000,
      "gas_used": 2400000,
      "timestamp": "1662673200.483162060",
      "to": "0x0000000000000000000000000000000000000903",
      "hash": null
    },
    {
      "amount": 10000000,
      "bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000001000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000",
      "call_result": "0x6080604052600436106100225760003560e01c80630419eca51461002e57610029565b3661002957005b600080fd5b34801561003a57600080fd5b5061005560048036038101906100509190610277565b61006b565b60405161006291906102d2565b60405180910390f35b600060405161007990610256565b604051809103906000f080158015610095573d6000803e3d6000fd5b5060006001600281106100d1577f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b0160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055507f8f5fd6a78ac856dc2d622ab0db626cf919c1911133d4b038171534ea477e5d1560405161013d906102ed565b60405180910390a160008211156101f2576000600160028110610189577f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b0160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc839081150290604051600060405180830381858888f193505050501580156101f0573d6000803e3d6000fd5b505b600060016002811061022d577f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b0160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff169050919050565b60f78061039b83390190565b60008135905061027181610383565b92915050565b60006020828403121561028957600080fd5b600061029784828501610262565b91505092915050565b6102a98161031e565b82525050565b60006102bc601d8361030d565b91506102c78261035a565b602082019050919050565b60006020820190506102e760008301846102a0565b92915050565b60006020820190508181036000830152610306816102af565b9050919050565b600082825260208201905092915050565b600061032982610330565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b7f43726561746564207365636f6e64206368696c6420636f6e7472616374000000600082015250565b61038c81610350565b811461039757600080fd5b5056fe608060405234801561001057600080fd5b5060d88061001f6000396000f3fe608060405236606d573073ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef3460405160639190607f565b60405180910390a3005b600080fd5b6079816098565b82525050565b6000602082019050609260008301846072565b92915050565b600081905091905056fea2646970667358221220b94efca641a0cf62b2bd505f79fe4be165c582520bc615e5c5fa3402156eafd864736f6c63430008040033a2646970667358221220e201e4b4097f725ce2de66f5ad3bb3d1dca2d2a58ca96a52d21a74a471da572d64736f6c63430008040033",
      "contract_id": "0.0.2307",
      "created_contract_ids": [
        "0.0.2307",
        "0.0.2308"
      ],
      "error_message": null,
      "from": "0x00000000000000000000000000000000000008e7",
      "function_parameters": "0x",
      "gas_limit": 3000000,
      "gas_used": 2400000,
      "timestamp": "1662673189.434973003",
      "to": "0x0000000000000000000000000000000000000903",
      "hash": null
    }
  ],
  "links": {
    "next": null
  }
}
```

### Hedera network

other

### Version

v0.64.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the `null` hash on contract results returned by REST api.

**Related issue(s)**:

Fixes #4436

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/controllers/contractController.js [hunk 1]
```diff
@@ -850,6 +850,7 @@ class ContractController extends BaseController {
    * @returns {Promise<void>}
    */
   getContractResultsById = async (req, res) => {
+    logger.info('xxxxx');
```
Comment (steven-sheehy) [inline hedera-mirror-rest/controllers/contractController.js:853]: Remove

**Review by steven-sheehy — APPROVED** [review]
LGTM besides a debug log

File: hedera-mirror-rest/controllers/contractController.js (hunk 1 above)
Comment (xin-hedera) [reply hedera-mirror-rest/controllers/contractController.js:853]: will remove

**Review by steven-sheehy — APPROVED** [review]
