### PR TITLE
Fix zero allowance owner

### LINKED ISSUE #3481: Rows with owner set to 0 in nft_allowance table
### Description

There are some rows with owner set to 0 in previewnet `nft_allowance` table:

```
mirror_node=> select * from nft_allowance where owner = 0;
 approved_for_all | owner | payer_account_id | serial_numbers | spender |    timestamp_range     | token_id
------------------+-------+------------------+----------------+---------+------------------------+----------
 t                |     0 |            13619 | {}             |   13495 | [1648048333917695388,) |    13620
 t                |     0 |            13619 | {}             |   15942 | [1648128458182260000,) |    15943
```

Issue is services allows `nftAllowance.owner` to be omitted, which implies the payer of the transaction is the resource owner. In mirrornode, we encode `owner` to a long as is and persist the encoded id, so when owner is not set in the protobuf message, mirrornode will persist value 0 for owner.

Note this also applies to `cryptoAllowance` and `tokenAllowance`. 

### Steps to reproduce

Run the query in the description, it'll show rows with owner set to 0. Can also execute such a `CryptoApproveAllowance` tx in previewnet and check the corresponding row in mirrornode db. 

### Additional context

_No response_

### Hedera network

previewnet

### Version

v0.53.1

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the zero allowance owner bug

- Set allowance owner to transaction payer if ower is not set in the *Allowance protobuf message

**Related issue(s)**:

Fixes #3481 

**Notes for reviewer**:

`*Allowance.owner` is allowed to be left unset, which implies the payer of the transaction is the resource owner. 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractAllowanceTransactionHandler.java [hunk 1]
```diff
@@ -60,7 +61,7 @@ public void updateTransaction(Transaction transaction, RecordItem recordItem) {
             var approvedForAll = nftApproval.hasApprovedForAll() && nftApproval.getApprovedForAll().getValue();
             NftAllowance nftAllowance = new NftAllowance();
             nftAllowance.setApprovedForAll(approvedForAll);
-            nftAllowance.setOwner(EntityId.of(nftApproval.getOwner()).getId());
+            nftAllowance.setOwner(getOwner(nftApproval.getOwner(), payerAccountId));
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractAllowanceTransactionHandler.java:64]: nit: Might consider taking advantage of the existing fallback logic in `EntityIdService` and to prepare for alias everywhere.

```suggestion
            nftAllowance.setOwner(entityIdService.lookup(nftApproval.getOwner(), payerAccountId));
```

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
LGTM

File: hedera-mirror-importer/src/main/resources/db/migration/v1/V1.56.1__fix_zero_allowance_owner.sql [hunk 2]
```diff
@@ -0,0 +1,9 @@
+-- explicitly set owner to payer_account_id if it's 0
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/resources/db/migration/v1/V1.56.1__fix_zero_allowance_owner.sql:1]: thought more about the bug and realized that not only the db migration can't handle some corner cases, but also it can fail.

- Regarding the corner case, take crypto allowance for example, when two owner accounts `o1` and `o2` approved allowances for the same spender account `s` and both crypto approve allowance transactions have `CryptoAllowance.owner` omitted, the later transaction would override the first as well as creating a historical row. Since information is lost, there's no way for the db migration to fix the data

- Suppose an owner `o` account approves crypto allowance for spender `s` with `owner` omitted in `CryptoAllowance`, later the owner adjusts the crypto allowance for spender `s`. since for crypto adjust allowance tx, importer persists data from `transaction_redord#crypto_adjustments` to db and `crypto_adjustments`'s owner will be filled by services if ommitted in the transaction body, there will be two rows for the same crypto allowance in `crypto_allowance` table, i.e., `(owner=0, spender=s)` and `(owner=o, spender=s)`. When later importer runs the db migration, it'll fail since it violates unique key constraint.

I tend to remove the db migration, and port the java code fix to previous releases.

Comment (xin-hedera) [inline hedera-mirror-importer/src/main/resources/db/migration/v1/V1.56.1__fix_zero_allowance_owner.sql:1]: thought more about the bug and realized that not only the db migration can't handle some corner cases, but also it can fail.

- Regarding the corner case, take crypto allowance for example, when two owner accounts `o1` and `o2` approved allowances for the same spender account `s` and both crypto approve allowance transactions have `CryptoAllowance.owner` omitted, the later transaction would override the first as well as creating a historical row. Since information is lost, there's no way for the db migration to fix the data

- Suppose an owner `o` account approves crypto allowance for spender `s` with `owner` omitted in `CryptoAllowance`, later the owner adjusts the crypto allowance for spender `s`. since for crypto adjust allowance tx, importer persists data from `transaction_redord#crypto_adjustments` to db and `crypto_adjustments`'s owner will be filled by services if ommitted in the transaction body, there will be two rows for the same crypto allowance in `crypto_allowance` table, i.e., `(owner=0, spender=s)` and `(owner=o, spender=s)`. When later importer runs the db migration, it'll fail since it violates unique key constraint.

I tend to remove the db migration, and port the java code fix to previous releases.

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/resources/db/migration/v1/V1.56.1__fix_zero_allowance_owner.sql:1]: Just remove it then. Allowances have made its way to testnet yet. No need to port to previous release.

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/resources/db/migration/v1/V1.56.1__fix_zero_allowance_owner.sql]: removed

**Review by steven-sheehy — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]
