### PR TITLE
Fix slow domain object ingestion

### LINKED ISSUE #1440: Utilize cache for EntityRecordItemListener bulk insert/update operations on domain objects
**Problem**
Currently we have a mixture of insert only and update logic employed in the `EntityRecordItemListener` class.
Most domain objects are created and added to a list for batch insert later in `EntityListener` implementation e.g. `SqlEntityListener`. 
However, items that require an update make the flow complex as they are currently run immediately.

The intent should be to batch insert and batch update all items.

**Solution**
Utilize the available cache manager by
- Update `EntityRecordItemListener` to insert all items into the appropriate cache
- Update `EntityRecordItemListener` to update the cache value when an update transaction is encountered for an item that was created in the same record file
- Update `EntityRecordItemListener` to insert items created in previous record file into a separate cache
- Update `SqlEntityListener` to batch insert (currently with PgCopy) all cache items in insert cache
- Update `SqlEntityListener` to batch update (currently with Repository) all cache items in update cache

**Alternatives**
- Update `SqlEntityListener` `on???` methods to do check for cache collisions and apply update/insert logic appropriately

**Additional Context**
The impact currently is that for now we have to keep checking if an item exists in the db prior to deciding how to handle an update transaction

### LINKED ISSUE #1926: Slow record parsing with high number of created entities
**Detailed Description**
Performance testing of high account and topic creation shows that it can easily slow down the importer to a crawl. Thread dumps indicate the majority of time is spent inside `EntityRepository` methods like `insertEntityId` and `findById`.

**Actual Behavior**
1. Create accounts at 2K TPS and topics at 2K TPS
2. Wait until at least 2M entities have been created
3. Record processing time begins exceeding 2m

**Expected Behavior**
Record processing time  doesn't take longer than the 2s close interval

**Environment:**
- Java: OpenJDK 11.0.10
- OS: Ubuntu 18.04
- Version: 0.32.0

**Additional Context**
```
May 04 15:47:53 java[16335]: 2021-05-04T09:47:53.483-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 5958 rows to transaction table in 112.8 ms
May 04 15:47:53 java[16335]: 2021-05-04T09:47:53.644-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 20862 rows to crypto_transfer table in 160.8 ms
May 04 15:47:53 java[16335]: 2021-05-04T09:47:53.664-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 141 rows to topic_message table in 20.05 ms
May 04 15:47:53 java[16335]: 2021-05-04T09:47:53.673-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 548 rows to token_transfer table in 8.679 ms
May 04 15:49:25 java[16335]: 2021-05-04T09:49:25.637-0600 INFO scheduling-6 c.h.m.i.p.r.e.s.SqlEntityListener Inserted 5432 entities in 1.533 min
May 04 15:49:25 java[16335]: 2021-05-04T09:49:25.637-0600 INFO scheduling-6 c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 1.538 min
May 04 15:49:25 java[16335]: 2021-05-04T09:49:25.639-0600 INFO scheduling-6 c.h.m.i.p.r.RecordFileParser Finished parsing 5958 transactions from record file 2021-05-03T23_16_40.056853000Z.rcd in 1.718 min. Success: true
May 04 15:49:38 java[16335]: 2021-05-04T09:49:38.390-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 6857 rows to transaction table in 177.4 ms
May 04 15:49:38 java[16335]: 2021-05-04T09:49:38.597-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 24011 rows to crypto_transfer table in 207.2 ms
May 04 15:49:38 java[16335]: 2021-05-04T09:49:38.628-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 144 rows to topic_message table in 30.12 ms
May 04 15:49:38 java[16335]: 2021-05-04T09:49:38.637-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 636 rows to token_transfer table in 9.452 ms
May 04 15:51:43 java[16335]: 2021-05-04T09:51:43.527-0600 INFO scheduling-6 c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6270 entities in 2.081 min
May 04 15:51:43 java[16335]: 2021-05-04T09:51:43.527-0600 INFO scheduling-6 c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 2.089 min
May 04 15:51:43 java[16335]: 2021-05-04T09:51:43.529-0600 INFO scheduling-6 c.h.m.i.p.r.RecordFileParser Finished parsing 6857 transactions from record file 2021-05-03T23_16_42.039556000Z.rcd in 2.296 min. Success: true
May 04 15:52:19 java[16335]: 2021-05-04T09:52:19.813-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 6910 rows to transaction table in 124.5 ms
May 04 15:52:20 java[16335]: 2021-05-04T09:52:20.006-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 24216 rows to crypto_transfer table in 192.5 ms
May 04 15:52:20 java[16335]: 2021-05-04T09:52:20.018-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 163 rows to topic_message table in 12.82 ms
May 04 15:52:20 java[16335]: 2021-05-04T09:52:20.031-0600 INFO scheduling-6 c.h.m.i.p.PgCopy Copied 640 rows to token_transfer table in 12.51 ms
May 04 15:54:21 java[16335]: 2021-05-04T09:54:21.213-0600 INFO scheduling-6 c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6274 entities in 2.020 min
May 04 15:54:21 java[16335]: 2021-05-04T09:54:21.213-0600 INFO scheduling-6 c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 2.025 min
May 04 15:54:21 java[16335]: 2021-05-04T09:54:21.215-0600 INFO scheduling-6 c.h.m.i.p.r.RecordFileParser Finished parsing 6910 transactions from record file 2021-05-03T23_16_44.001309000Z.rcd in 2.626 min. Success: true
```

### PR DESCRIPTION
**Pull request by Nana-EC**
**Detailed description**:
Slow entity ingestions flows exists. This is mainly because we do multiple db reference calls to check for existing entities to get the up to date info.
Insert only flows are fast with PgCopy. Taking inspiration from this update scenarios could utilize PgCopy to copy domain objects over to db server, then follow up with an upsert query to manage the insert vs update scenarios.

- Remove repository saves from `EntityRecordItemListener`
- Update `EntityRecordItemListener` to pass all entities, tokens and schedules domain objects with available info to `EntityListener` `onX()` equivalents
- Replace `onEntityId()` with `onEntityId()`
- Create a `UpsertPgCopy` class that creates a temp table for an entity, copies into this, and then runs a domain specific `insertSql` and `updateSql` queries to manage upsert to main table
- Update Transaction Handlers to ensure created timestamp and deleted are appropriately set on Entity updates
- Centralize `EntityIdSerializer` usage in `PgCopy` and remove domain field annotation usage
- Update domain fields of updatable domains to ensure custom types have a `@JsonSerialize` annotation to correctly serialize in PgCopy flow
- Remove `getNewAccountFreezeStatus()` and `getNewAccountKycStatus()` and move logic into insert sql command
- Add `NullableStringSerializer` to support differentiation of String intention to set null vs unset, since PgCipy serializes empty string and null to be null
- Update updatable domain objects with serialization support for domain field types, and serializers
- Add `hibernate-jpamodelgen` dependency to automatically generate Models based on domain classes for type safety
- Move embeddedIds out to separate files to ensure generator picks them up
- Add `UpsertQueryGenerator` interface with implementations for updatable domains that automatically generate sql queries for temp table creation, insert and update to final table
- Add cache logic to SqlEntityListener to flatten the domains that are inserted and or updated multiple times in a record file. This will ensure a domain object appears once for inserts and updates .
- Update transactionHandlers to ensure all entity updates and defaults are set e.g. deleted is false in create case and true in delete case
- Remove `NEVER_EXPIRE_LARGE` cache creation and usage
- Update Github importer workflow to exclude v2 tests from v1 group
- Add migration to drop default and not null from `entity.deleted`
- Update broken tests
 

**Which issue(s) this PR fixes**:
Fixes #1926 
Fixes #1440 

**Special notes for your reviewer**:

***multiEntityUpdate() test outputs***
****Upsert****
Inserting 6000 new entities took 78 s previously now 223.7 ms
Inserting 6000 entities with 3000 being updates took 34 s now takes 400 ms

****Insert & Update****
Inserting 6000 new entities took 78 s previously now ~160.7 ms 
Inserting 6000 entities with 3000 being updates took 34 s now takes ~180 ms

***Logs outputs***
Summary:
Ingestion times improved 97%, new time is 3% of previous time
Insert only: before ~21s, after ~600ms
Insert & Update: before: ~22s, after ~500 ms

Extended:
****Before (current master code)****
6k entities insert only (Run 1)
```
c.h.m.i.p.PgCopy Copied 6000 rows to transaction table in 112.0 ms 
c.h.m.i.p.PgCopy Copied 30000 rows to crypto_transfer table in 140.6 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6004 entities in 20.64 s 
c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 20.89 s  
```
6k entities insert only (Run 2)
```
c.h.m.i.p.PgCopy Copied 6000 rows to transaction table in 142.9 ms 
c.h.m.i.p.PgCopy Copied 30000 rows to crypto_transfer table in 147.1 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6004 entities in 21.26 s 
c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 21.56 s 
```

6k entities insert with 3k being updates (Run 1)
```
c.h.m.i.p.PgCopy Copied 6000 rows to transaction table in 69.86 ms 
c.h.m.i.p.PgCopy Copied 24000 rows to crypto_transfer table in 98.75 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6005 entities in 17.24 s 
c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 17.41 s 
```
6k entities insert with 3k being updates (Run 2)
```
c.h.m.i.p.PgCopy Copied 6000 rows to transaction table in 66.01 ms 
c.h.m.i.p.PgCopy Copied 24000 rows to crypto_transfer table in 124.9 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6005 entities in 24.87 s 
c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 25.06 s 
```

****After (PR code)****
6k entities insert only (Run 1)
```
c.h.m.i.p.PgCopy Copied 30000 rows to crypto_transfer table in 169.8 ms 
c.h.m.i.p.PgCopy Copied 6000 rows to transaction table in 98.68 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6000 Entity's in 240.5 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6004 EntityId's in 47.88 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 558.9 ms 
```
6k entities insert only (Run 2)
```
c.h.m.i.p.PgCopy Copied 30000 rows to crypto_transfer table in 165.7 ms 
c.h.m.i.p.PgCopy Copied 6000 rows to transaction table in 87.10 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6000 Entity's in 259.6 ms  
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6004 EntityId's in 43.08 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 557.5 ms 
```

6k entities insert with 3k being updates (Run 1)
```
c.h.m.i.p.PgCopy Copied 24000 rows to crypto_transfer table in 106.0 ms 
c.h.m.i.p.PgCopy Copied 6000 rows to transaction table in 78.66 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6000 Entity's in 214.6 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6005 EntityId's in 27.86 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 427.7 ms 
c.h.m.i.p.r.e.p.EntityRecordItemListenerPerformanceCryptoTest Inserting 6000 entities with 3000 updates took 483 ms
```
6k entities insert with 3k being updates (Run 2)
```
c.h.m.i.p.PgCopy Copied 24000 rows to crypto_transfer table in 119.1 ms 
c.h.m.i.p.PgCopy Copied 6000 rows to transaction table in 75.42 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6000 Entity's in 223.7 ms  
c.h.m.i.p.r.e.s.SqlEntityListener Inserted 6005 EntityId's in 40.19 ms 
c.h.m.i.p.r.e.s.SqlEntityListener Completed batch inserts in 459.0 ms 
c.h.m.i.p.r.e.p.EntityRecordItemListenerPerformanceCryptoTest Inserting 6000 entities with 3000 updates took 521 ms 
```

Still need to 
- [ ] Add micro benchmark tests
- [x] Fix broken tests
- [x] Resolve transaction test affects
- [x] Verify intricate upsert sql queries
- [ ] Explore clearing memo case. Currently hard to differentiate missing memo vs setting to empty string
- [ ] ~Consider whether expanding `OnX(domain)` of entityListener to `OnX(domain, update)` has value. This would allow it to know update vs new and would allow for insert vs update path~
- [x] Consider breaking out from Upsert to Insert & Update since Upsert is complicated and there are lots of edge cases

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java [hunk 1]
```diff
@@ -36,6 +36,19 @@
 @Entity
 @NoArgsConstructor
 public class Schedule {
+    public static final String TEMP_TABLE = "schedule_temp";
+    public static final String TEMP_TO_MAIN_INSERT_SQL = "insert into schedule select * from " + TEMP_TABLE +
+            " where consensus_timestamp is not null on conflict(schedule_id) do nothing";
+    public static final String TEMP_TO_MAIN_UPDATE_SQL = "update schedule set " +
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java:42]: For maintainability, I'd prefer a single upsert statement instead of insert and update.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java [hunk 2]
```diff
@@ -20,31 +20,65 @@
...
 @Data
 @javax.persistence.Entity
 @Log4j2
 @ToString(exclude = {"key", "submitKey"})
 public class Entity {
+    public static final String TEMP_TABLE = "entity_temp";
+    public static final String TEMP_TO_MAIN_INSERT_SQL = "insert into entity select auto_renew_account_id, " +
+            "auto_renew_period, created_timestamp, deleted, expiration_timestamp, id, key, coalesce(memo, ''), " +
+            "modified_timestamp, num, public_key, proxy_account_id, realm, shard, submit_key, type from " + TEMP_TABLE +
+            " on conflict (id) do nothing";
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java]: Yep, the location of the sql isn't final, part of why the PR is still in draft. 
I was having issues where repository sql calls where not being observed by the db connection used by PgCopy. So the repository would create the temp table but the PgCopy queries wouldn't be able to see the table.
Likely some under the hood connection context I need to figure out.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java [hunk 3]
```diff
@@ -48,33 +48,43 @@
...
 
         insertDurationMetric = Timer.builder("hedera.mirror.importer.parse.insert")
                 .description("Time to insert transactions into table")
                 .tag("table", tableName)
                 .register(meterRegistry);
     }
 
+    private String getSql() {
+        if (sql == null) {
+            sql = String.format("COPY %s(%s) FROM STDIN WITH CSV", tableName, columnsCsv);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java:82]: Code in flux, I made some modification that needed this but I should be able to revert this back now.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java [hunk 4]
```diff
@@ -20,46 +20,77 @@
...
+            "public_key = case when " + TEMP_TABLE + ".public_key = ' ' then '' " +
+            "else coalesce(" + TEMP_TABLE + ".public_key, entity.public_key) end, " +
+            "submit_key = coalesce(" + TEMP_TABLE + ".submit_key, entity.submit_key) from " + TEMP_TABLE +
+            " where entity.id = " + TEMP_TABLE + ".id and " + TEMP_TABLE + ".created_timestamp is null";
+
     @Id
     private Long id;
 
     @Convert(converter = AccountIdConverter.class)
+    @JsonSerialize(using = EntityIdSerializer.class)
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:68]: Agreed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java [hunk 5]
```diff
@@ -20,46 +20,77 @@
...
 
-    private boolean deleted;
+    private Boolean deleted;
 
     private Long expirationTimestamp;
 
     private byte[] key;
 
-    private String memo = "";
+    @JsonSerialize(using = NullableStringSerializer.class)
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:81]: I was hesitant to do this because String fields could contain varied content. 
Also the logic is dependent on if the db column isn't marked as not null. 
Due do that disconnect and ability to change one and miss the other I felt more comfortable making this one an explicit statement.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java [hunk 6]
```diff
@@ -20,46 +20,77 @@
...
 @ToString(exclude = {"key", "submitKey"})
 public class Entity {
+    public static final String TEMP_TABLE = "entity_temp";
+    public static final String TEMP_TO_MAIN_INSERT_SQL = "insert into entity select auto_renew_account_id, " +
+            "auto_renew_period, created_timestamp, deleted, expiration_timestamp, id, key, " +
+            "case when " + TEMP_TABLE + ".memo = ' ' then '' else coalesce(memo, '') end, " +
+            "modified_timestamp, num, " +
+            "case when " + TEMP_TABLE + ".public_key = ' ' then '' else public_key end, " +
+            "proxy_account_id, realm, shard, submit_key, type from " + TEMP_TABLE +
+            " on conflict (id) do nothing";
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:48]: Yep, maintainability was one of my larger concerns, this just allowed for quicker testing so I planned to resolve this before taking the PR out of draft.

I mainly wanted to get thoughts on the actual sql logic as it differs for some entities, and there were some edge cases that could be missed. 
Will look into getting it nicely wrapped up.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java:42]: I had it as upsert when I started but some queries became complex so for maintainability I split it up to make it easy to follow.
The performance numbers seemed to be similar so I can revert it to upsert and redo testing.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 7]
```diff
@@ -275,20 +339,106 @@ public void onTokenTransfer(TokenTransfer tokenTransfer) throws ImporterExceptio
...
+
+        // update vs delete operation
+        if (newEntity.getDeleted() == null) {
+            cachedEntity.setExpirationTimestamp(newEntity.getExpirationTimestamp());
+            cachedEntity.setKey(newEntity.getKey());
+            cachedEntity.setMemo(newEntity.getMemo());
+            cachedEntity.setPublicKey(newEntity.getPublicKey());
+        } else {
+            cachedEntity.setDeleted(newEntity.getDeleted());
+        }
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:381]: need to check if the fields are updated before calling the setters.

it looks less error-prone if `EntityListener` provides methods for example `getForUpdate` to retrieve cached or create a new entity/token/schedule/etc and in the `EntityRecorditemListener` and transaction handlers the individual fields are set. since then we only have to set it once for optional fields.

Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:381]: Good point. Each of the non delete cases could be done individually in separate transactions.
I was trying to find the right balance of where to manage the cache.
I intended to move the cache management into the `EntityRecordItemListener` then both `RepositoryEntityListener` and `SqlEntityListener` won't have to worry about it and can focus on just the persistence.
So I'm in agreement and will look into the `getForUpdate` suggestion

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java [hunk 8]
```diff
@@ -40,56 +43,87 @@
 @Data
 @Entity
 @NoArgsConstructor
+@ToString(exclude = {"freezeKey", "kycKey", "supplyKey", "wipeKey"})
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java:46]: Will do

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java [hunk 9]
```diff
@@ -20,46 +20,77 @@
...
 
 @Data
 @javax.persistence.Entity
 @Log4j2
 @ToString(exclude = {"key", "submitKey"})
 public class Entity {
+    public static final String TEMP_TABLE = "entity_temp";
+    public static final String TEMP_TO_MAIN_INSERT_SQL = "insert into entity select auto_renew_account_id, " +
+            "auto_renew_period, created_timestamp, deleted, expiration_timestamp, id, key, " +
+            "case when " + TEMP_TABLE + ".memo = ' ' then '' else coalesce(memo, '') end, " +
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:44]: That's the tricky part. Because the are nullable strings you can't differentiate between the field not being updated and when it's actually being cleared in an update.
To work around I reserved the use of ' ' when it's missing and rely on the upsert to catch this case.

I noted this in `NullableStringSerializer`

[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:44]: what about removing not null for `memo`, in rest we replace it with empty string when it's null.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:48]: JPA Criteria and JPQL don't support insert let alone upsert from what I'm seeing. 
Their design shines mostly around select querying and simple joins and wheres.
JPQL makes room for everything with the nativeQuery and gives you type safety, but that's essentially what I have right now building the sql string manually.

Since we're not inserting values but rather comparing already persisted column values and inserting or updating based on the comparison, the type safety benefits here are minimal.

Even with all of this I'll still need to do a string concatenation since it doesn't seem to be possible to create the upsert/insert statement using the Criteria. 

Tied in with passing this through to the PgCopy flow for run it seems like a lot more overhead than necessary, but I'll see if I can make it work without unnecessary complications.

I can at least utilize the entity Metamodel Generator  regardless to at least ensure the column names are captured correctly and no longer hardcoded.

[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:48]: I'd also be okay with using the metamodel to auto generate the sql without the use of jpql. That is, pass in a domain class, it loops through all the fields and automatically determine how to upsert based upon type. Just not sure how easy that is.

[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:48]: Yeah that will be complex because of how many variations of property updates there are but also because you don't know what's different until first comparing against the existing entity table.
I want to concentrate all comparison logic to be done on the db server.

Unless there's performance gains I think limiting it to a single upsert or sequenced insert-update query that manages all scenarios with the use of things like coalesce between the tables would be the best of both worlds (simplicity and manageability).

[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:48]: I don't think we're understanding each other. Everything I said would be server side. I'm advocating if jpql doesn't work out to use reflection to generate the sql one time on startup from the domain metamodel via reflection.

[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:48]: Yep that's my mindset also and what I've been implementing. 
I was just highlighting the intricacies of the generated sql to ensure it captures all the nuances of our various domain object when run on the db.
I have this working already, mostly just cleaning up and it should be part of the next commit

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java]: Yep, making memo nullable was something I considered/suggested also but it doesn't actually fix the main issue.
The challenge is since we get a partial update from the protobuf memo will be null when the domain object is serialized in both the case where it wasn't being set and when it's an empty string.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 7 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:393]: I agree with parts of this, just wondering if this is better in a separate ticket/PR. 
It will add more refactoring cause essentially the right thing to do would be to move all the cache logic into `EntityRecorditemListener`.
This would mean additionally moving the entity/domain logic updates into the transaction handlers where possible.
Also even if we did that `OnX()` would still be called on entities that might need updating. If `OnX()` took a list instead of individual items we could pull the cache logic totally out of `SqlEntityListener`  and `RepositoryEntityListener`.

But again more code churn for this already unintendedly large PR

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:393]: sounds good to me to leave it in a separate ticket. better focus on what's already complicated :)

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java]: Done

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Schedule.java]: Right. So this was my initial aim but each time I got it working it became glaringly clear the upsert query was doing a lot and introducing some complications.
The last straw though was this.

```sql
insert into token_account (account_id, associated, created_timestamp, freeze_status, kyc_status, modified_timestamp, token_id) select coalesce(token_account_temp.account_id, 1) as account_id,  coalesce(token_account_temp.associated, FALSE), coalesce(token_account_temp.created_timestamp, 0) as created_timestamp, coalesce(token_account_temp.freeze_status, getNewAccountFreezeStatus (token_account_temp.token_id)) as freeze_status, coalesce(token_account_temp.kyc_status,  getNewAccountKycStatus(token_account_temp.token_id)) as kyc_status, token_account_temp.modified_timestamp, coalesce(token_account_temp.token_id, 1) as token_id from token_account_temp on conflict (token_id, account_id) do update set associated = coalesce(excluded.associated, token_account.associated), freeze_status = coalesce(excluded.freeze_status, token_account.freeze_status), kyc_status = coalesce(excluded.kyc_status, token_account.kyc_status), modified_timestamp = coalesce(excluded.modified_timestamp, token_account.modified_timestamp);
```

Due to the constraints on the tables the select query has to ensure that that all fields that are not nullable have their value transformed. This is applicable when creating the domain object but not when updating. The result is that the update portion ends up having that non null value always, even in the case where the updating query should be setting it to null.

Since the select gets run first there's no way of getting the original value from the temp table. Even if there was it makes the query more complex.

The cleanest solution I believe is to do insert and update from the temp table using where conditions.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java]: Fixed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java]: Fixed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenId.java [hunk 10]
```diff
@@ -0,0 +1,44 @@
...
+ */
+@Data
+@Embeddable
+@AllArgsConstructor
+@NoArgsConstructor
+public class TokenId implements Serializable {
+    private static final long serialVersionUID = -4595724698253758379L;
+
+    @Convert(converter = TokenIdConverter.class)
+    private EntityId tokenId;
```
Comment (ijungmann) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenId.java:43]: I noticed later this leads to `token.getTokenId().getTokenId().getId()`, which is a little rough.  I wonder if we want to call this just `id` since it's the only EntityId in this class, the `token` is implied by the class name?

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 11]
```diff
@@ -260,12 +320,24 @@ public void onLiveHash(LiveHash liveHash) throws ImporterException {
 
     @Override
     public void onToken(Token token) throws ImporterException {
-        tokenRepository.save(token);
+        // entity could experience multiple updates in a single record file, handle updates in memory for this case
```
Comment (ijungmann) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:323]: I'm thinking this comment was copied from `onEntity` since none of the other `on`s have it.  I'm not opposed to having the comment multiple places, but I would put it on the others as well (and change to specify the specific entity type) or remove this here.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 12]
```diff
@@ -275,20 +347,99 @@ public void onTokenTransfer(TokenTransfer tokenTransfer) throws ImporterExceptio
...
+            cachedEntity.setDeleted(newEntity.getDeleted());
+        }
+
+        if (newEntity.getExpirationTimestamp() != null) {
+            cachedEntity.setExpirationTimestamp(newEntity.getExpirationTimestamp());
+        }
+
+        if (newEntity.getKey() != null) {
+            cachedEntity.setKey(newEntity.getKey());
+            cachedEntity.setMemo(newEntity.getMemo());
```
Comment (ijungmann) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:377]: Don't think this belongs here.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 13]
```diff
@@ -275,20 +347,99 @@ public void onTokenTransfer(TokenTransfer tokenTransfer) throws ImporterExceptio
...
+
+        if (newToken.getFreezeKey() != null) {
+            cachedToken.setFreezeKey(newToken.getFreezeKey());
+        }
+
+        if (newToken.getKycKey() != null) {
+            cachedToken.setKycKey(newToken.getKycKey());
+        }
+
+        cachedToken.setModifiedTimestamp(newToken.getModifiedTimestamp());
```
Comment (ijungmann) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:396]: Think I would prefer this outside of the chain of ifs, either before or after.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityIdRepositoryCustomImplTest.java [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+    public UpdatableDomainRepositoryCustom getUpdatableDomainRepositoryCustom() {
+        return entityIdRepositoryCustom;
+    }
+
+    @Override
+    public String getInsertQuery() {
+        return "insert into entity (id, memo, num, realm, shard, type) select entity_id_temp.id, case when " +
+                "entity_id_temp.memo = ' ' then '' else coalesce(entity_id_temp.memo, '') end, entity_id_temp.num, " +
+                "entity_id_temp.realm, entity_id_temp.shard, entity_id_temp.type from entity_id_temp on conflict (id)" +
+                " do nothing";
```
Comment (ijungmann) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityIdRepositoryCustomImplTest.java:42]: These might prove difficult to maintain, though I don't have a better option.

**Review by ijungmann — CHANGES_REQUESTED** [review]
Some really good work here, just a few things.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java [hunk 15]
```diff
@@ -653,6 +664,27 @@ private Transaction cryptoUpdateTransaction() {
...
+        Transaction updateTransaction = cryptoUpdateTransaction(AccountID.newBuilder().setShardNum(0).setRealmNum(0)
+                .setAccountNum(accountNum).build());
+        TransactionBody updateTransactionBody = getTransactionBody(updateTransaction);
+        TransactionRecord createRecord = transactionRecord(
+                updateTransactionBody,
+                ResponseCodeEnum.SUCCESS.getNumber(),
+                accountNum);
+        return new RecordItem(updateTransaction, createRecord);
+    }
+
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java:687]: Will revert. Left over from a previous refactor when I started coding the performance test in here for easy access to existing methods

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityIdRepositoryCustomImplTest.java (hunk 14 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityIdRepositoryCustomImplTest.java:42]: Yeah, the maintenance challenge is the whole inspiration for the generated sql.
In this case any tests failure produce by updating the domain or custom repositories list of selected/update fields will resort in a sort of snapshot failure in this test where the change in sql will be easy to see.
Will think on it also

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 12 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:377]: Good catch, will remove

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 13 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:396]: Yeah easier to read in that way. Will move to end

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 7 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: Opened ticket [2098](https://github.com/hashgraph/hedera-mirror-node/issues/2098)

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountId.java [hunk 16]
```diff
@@ -0,0 +1,48 @@
...
+import com.hedera.mirror.importer.converter.TokenIdConverter;
+
+/**
+ * TokenAccount embedded Id. This needs to exist as a separate class to ensure JPAMetaModelEntityProcessor picks it up
+ */
+@AllArgsConstructor
+@Data
+@Embeddable
+@NoArgsConstructor
+public class TokenAccountId implements Serializable {
```
[the remark this answers is not in the document]
Comment (ijungmann) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountId.java:40]: We could also consider making subpackages based on the service, like we have for the `TransactionSuppliers` in the data generator, but I think that would be better left to a different PR if we do that.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenId.java (hunk 10 above)
Comment (ijungmann) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenId.java:43]: Makes sense, it's only worth so much effort to try to improve.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 17]
```diff
@@ -275,20 +347,99 @@ public void onTokenTransfer(TokenTransfer tokenTransfer) throws ImporterExceptio
...
-    private void persistEntities() {
-        Stopwatch stopwatch = Stopwatch.createStarted();
-        entityIds.forEach(entityId -> {
-            entityRepository.insertEntityId(entityId);
-            entityCache.put(entityId, null);
-        });
-        log.info("Inserted {} entities in {}", entityIds.size(), stopwatch);
+    private void updateCachedEntity(Entity newEntity) {
+        Entity cachedEntity = entities.get(newEntity.getId());
+        cachedEntity.setAutoRenewPeriod(newEntity.getAutoRenewPeriod());
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:365]: Shouldn't we check if null so it doesn't get cleared?

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 18]
```diff
@@ -275,20 +347,99 @@ public void onTokenTransfer(TokenTransfer tokenTransfer) throws ImporterExceptio
...
+            cachedEntity.setExpirationTimestamp(newEntity.getExpirationTimestamp());
+        }
+
+        if (newEntity.getKey() != null) {
+            cachedEntity.setKey(newEntity.getKey());
+            cachedEntity.setMemo(newEntity.getMemo());
+        }
+
+        if (newEntity.getMemo() != null) {
+            cachedEntity.setMemo(newEntity.getMemo());
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:381]: What about all the other fields that can be updated by update transactions like autorenewaccount, submitkey, etc.?

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AbstractUpdatableDomainRepositoryCustom.java [hunk 19]
```diff
@@ -0,0 +1,328 @@
...
+import java.util.Collections;
+import java.util.Comparator;
+import java.util.List;
+import java.util.stream.Collectors;
+import javax.persistence.metamodel.SingularAttribute;
+import lombok.Getter;
+import org.apache.commons.lang3.StringUtils;
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
+import software.amazon.awssdk.utils.CollectionUtils;
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AbstractUpdatableDomainRepositoryCustom.java:40]: Wrong collection util

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java [hunk 20]
```diff
@@ -90,10 +90,14 @@ public static String bytesToHex(byte[] bytes) {
      */
     public static String convertSimpleKeyToHex(@Nullable byte[] protobufKey) {
         try {
-            if (ArrayUtils.isEmpty(protobufKey)) {
+            if (protobufKey == null) {
                 return null;
             }
 
+            if (ArrayUtils.isEmpty(protobufKey)) {
+                return ""; // Key.getDefaultInstance() case
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:98]: Why would we differentiate between null and Key.getDefaultInstance()? Most getters return `Key.getDefaultInstance()` so this will be updating key fields from null before to empty string.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java [hunk 21]
```diff
@@ -82,6 +86,14 @@
...
     protected TokenTransferRepository tokenTransferRepository;
 
+    @Qualifier(CacheConfiguration.EXPIRE_AFTER_30M)
+    @Resource
+    private CacheManager cacheManager;
+
+    void beforeAll() {
+        cacheManager.getCache("tokenaccounts").clear();
+    }
+
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java:96]: This seems to be unused as it doesn't have a `@BeforeAll`. It shouldn't be necessary as the cache is already cleared before each test via `ResetCacheTestExecutionListener`.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java [hunk 22]
```diff
@@ -317,6 +321,30 @@ private Entity getExpectedUpdatedEntity() {
...
+        // set created_timestamp and deleted based on transaction body type
+        int dataCase = defaultBody.getDataCase().getNumber();
+        switch (dataCase) {
+            case 8: // contractCreate
+            case 11: // cryptoCreate
+            case 17: // fileCreate
+            case 24: // consensusCreate
+            case 29: // tokenCreate
+            case 42: // scheduleCreate
+                entity.setCreatedTimestamp(DEFAULT_CREATED_TIMESTAMP);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java:333]: This would be slightly less hacky and more future proof if you do:
```java
if (dataCase.name().contains("Create")) {
  entity.set...
} else if (dataCase.name().contains("Delete")) {
  entity.set...
}
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ScheduleRepositoryCustomImpl.java [hunk 23]
```diff
@@ -0,0 +1,80 @@
...
+import org.springframework.stereotype.Component;
+
+import com.hedera.mirror.importer.domain.Schedule_;
+
+@Component
+@Named
+@RequiredArgsConstructor
+public class ScheduleRepositoryCustomImpl extends AbstractUpdatableDomainRepositoryCustom<Schedule_> {
+    public static final String TABLE = "schedule";
+    public static final String TEMP_TABLE = "schedule_temp";
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ScheduleRepositoryCustomImpl.java:37]: We don't need to hardcode this. It can just be `TABLE + "_temp"`.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAccountRepositoryCustomImpl.java [hunk 24]
```diff
@@ -0,0 +1,103 @@
...
+                getTableColumnName(getTemporaryTableName(), TokenAccount_.CREATED_TIMESTAMP)));
+
+        return insertWhereQueryBuilder.toString();
+    }
+
+    @Override
+    public String getUpdateWhereClause() {
+        return String.format(" where %s = %s and %s = %s and %s is null",
+                getTableColumnName(getTableName(), TokenAccountId_.TOKEN_ID),
+                getTableColumnName(getTemporaryTableName(), TokenAccountId_.TOKEN_ID),
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAccountRepositoryCustomImpl.java:88]: I'm starting to miss the giant raw sql...This is quite a bit more code. We'll have to look into adding annotations to the domain in the future that we can use to consolidate this to one SQL generating class.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java [hunk 25]
```diff
@@ -0,0 +1,48 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ * ‍
+ */
+
+import java.util.List;
+import javax.persistence.metamodel.SingularAttribute;
+
+public interface UpdatableDomainRepositoryCustom {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java:26]: These are not repositories, they are basically sql generator classes. We should use custom repository methods that hide all this complicated logic. Custom repository interfaces would be added to the existing repository interface so you can inject a `TokenRepository` and call both the CRUD methods and the upsert methods.

```java
public interface UpsertableRepository<T> {
    void createTemp();
    void insertFromTemp();
    void updateFromTemp();
}
```

Or we should rename these to something else and move them to a sub-package. Something like `com.hedera.mirror.importer.repository.upsert.UpsertQueryGenerator`.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
Still need to look at the sql generation more

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java [hunk 26]
```diff
@@ -0,0 +1,39 @@
...
+import lombok.extern.log4j.Log4j2;
+
+@Log4j2
+@Named
+public class NullableStringSerializer extends JsonSerializer<String> {
+
+    @Override
+    public void serialize(String value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
+        // empty strings are serialized as null, set to reserved space character and rely on db update sql to parse
+        gen.writeString(value.equals("") ? " " : value);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java:37]: If we do that there will never be a case where we set a NullableString to null. All nulls and "" will get written as empty.
That's problematic since in the update case values not being set are null.
The Update sql when reading from the temp file will then set potential existing valid value int he main table to "" when it shouldn't.

The logic here is
null -> null
"" -> " " for temp table to then be mapped to "" when writing to main table. This allows us to differentiate between unset cases and empty string cases

[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java:37]: Good point. Will replace the reserve character

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java [hunk 27]
```diff
@@ -20,47 +20,52 @@
...
-    private String memo = "";
+    @JsonSerialize(using = NullableStringSerializer.class)
+    private String memo;
 
     private Long modifiedTimestamp;
 
     private Long num;
 
+    @JsonSerialize(using = NullableStringSerializer.class)
+    private String publicKey;
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:64]: Agreed. Sql was doing some weirdness early on and put publicKey first. This was before I explicitly listed out the columns being inserted. I can revert this

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java [hunk 28]
```diff
@@ -48,31 +50,48 @@
...
         this.properties = properties;
-        tableName = CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, entityClass.getSimpleName());
+        this.meterRegistry = meterRegistry;
+        this.tableName = CaseFormat.UPPER_CAMEL.to(
+                CaseFormat.LOWER_UNDERSCORE,
+                tableName);
         var mapper = new CsvMapper();
         SimpleModule module = new SimpleModule();
         module.addSerializer(byte[].class, new ByteArrayToHexSerializer());
+        module.addSerializer(EntityId.class, new EntityIdSerializer());
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java:73]: Will adopt this

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java [hunk 29]
```diff
@@ -0,0 +1,134 @@
...
+        log.trace("Created temp table {} in {}", tableName, stopwatch);
+    }
+
+    public int insertToFinalTable(Connection connection) throws SQLException {
+        Stopwatch stopwatch = Stopwatch.createStarted();
+        int insertCount = 0;
+        try (PreparedStatement preparedStatement = connection.prepareStatement(insertSql)) {
+            insertCount = preparedStatement.executeUpdate();
+        }
+        log.info("Inserted {} rows from {} table to {} table in {}", insertCount, tableName, finalTableName,
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java:120]: That's fair. Will remove the others leaving the single since metrics capture the more fine grained items

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepositoryCustomImpl.java [hunk 30]
```diff
@@ -0,0 +1,83 @@
...
+import java.util.List;
+import javax.inject.Named;
+import javax.persistence.metamodel.SingularAttribute;
+import lombok.RequiredArgsConstructor;
+import org.springframework.stereotype.Component;
+
+import com.hedera.mirror.importer.domain.Entity_;
+
+@Component
+@Named
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepositoryCustomImpl.java:33]: Will adopt

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 17 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:365]: Yeah, missed this check. Will add

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java:37]: Could even be some static UUID we generate. That would be even safer.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 18 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:381]: Will add those 2 and will check if I'm missing anything else

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java (hunk 20 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:98]: Mixed up logic here since public key is a nullable String.
We never actually utilize the getter when the value is `Key.getDefaultInstance()` so we'll only ever be setting keys to null or a valid string. "" doesn't map to a valid public key so I shouldn't have it here.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java (hunk 21 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java:96]: Yeah left over from some earlier testing.
Will remove

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java (hunk 22 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java:333]: Will adopt

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAccountRepositoryCustomImpl.java (hunk 24 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TokenAccountRepositoryCustomImpl.java:88]: Yep, I noted it would be complex because of the varied data types and meanings our domain type fields take.
Upsert was even worse.
It'd be simple if we were just inserting but sometimes you need to do a join (e.g. in the token case) and when you do that there are columns that are ambiguous and require clarification by postgres. Since the code needs to be generalized you don't want to add cases by fields but rather by data types.
Which is the cause of the verbosity

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java (hunk 25 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java:26]: Agreed, it is more of a generator now than a repository.

From my previous testing the connections used by Repository classes weren't able to observe the temp table created by the `PgCopy` class. In the above case I'm guessing the reverse would be the same.

Essentially in `SqlEntityListener` I'd then have to call `UpsertableRepository<T>.createTemp()`, then `UpsertPgCopy.copy()` and then `UpsertableRepository<T>.insertFromTemp()` and then `UpsertableRepository<T>.updateFromTemp()`.
I had this in a previous iteration but sided with moving all sql query run logic as part of the upsert embedded in the `UpsertPgCopy.copy()` so that `SqlEntityListener` didn't see any difference between an Upsertable and Insert only repository.

I'll side with renaming them and moving them to their own package as I think it's a more modularized approach than calling JPA Repository logic and PgCopy ObjectWriter logic from `SqlEntityListener`.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 12 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: This was a placeholder for publicKey. Updated

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java [hunk 31]
```diff
@@ -48,31 +50,48 @@
...
 public class PgCopy<T> {
 
-    private final String tableName;
     private final String sql;
     private final ObjectWriter writer;
-    private final Timer insertDurationMetric;
     private final ParserProperties properties;
+    protected final MeterRegistry meterRegistry;
+    protected Timer insertDurationMetric;
+    protected final String tableName;
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java]: Updated

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java [hunk 32]
```diff
@@ -48,31 +50,48 @@
...
+                    .description("Time to insert transactions into table")
+                    .tag("table", tableName)
+                    .register(meterRegistry);
+        }
 
-        insertDurationMetric = Timer.builder("hedera.mirror.importer.parse.insert")
-                .description("Time to insert transactions into table")
-                .tag("table", tableName)
-                .register(meterRegistry);
+        return insertDurationMetric;
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java]: Updated to ternary. Either works for me

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java [hunk 33]
```diff
@@ -58,6 +59,7 @@
 import com.hedera.mirror.importer.parser.domain.RecordItem;
 import com.hedera.mirror.importer.util.Utility;
 
+@Log4j2
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java]: Removed

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java]: Removed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 34]
```diff
@@ -169,12 +203,17 @@ public void onError() {
     private void cleanup() {
         contractResults.clear();
         cryptoTransfers.clear();
+        entities.clear();
         entityIds.clear();
         fileData.clear();
         liveHashes.clear();
+        entityIdEntities.clear();
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: Reorganized

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 11 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: Added comments

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 13 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: Moved

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java:37]: Like the UUID idea. Hopefully the larger String size doesn't impact performance much. I'll take a look

[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java:37]: Implemented UUID replacer

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java (hunk 27 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entity.java:64]: Reverted

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java (hunk 28 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java:73]: Adopted

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java (hunk 29 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java:120]: Removed extra stopwatch and moved all but one 1 log to trace

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java [hunk 35]
```diff
@@ -0,0 +1,134 @@
...
+                    .tag("table", finalTableName)
+                    .register(meterRegistry);
+        }
+
+        return copyDurationMetric;
+    }
+
+    private void createTempTable(Connection connection) throws SQLException {
+        // create temporary table without constraints to allow for upsert logic to determine missing data vs nulls
+        Stopwatch stopwatch = Stopwatch.createStarted();
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java:107]: Removed extra

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepositoryCustomImpl.java (hunk 30 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityRepositoryCustomImpl.java:33]: Went with `@Named`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 36]
```diff
@@ -218,14 +265,27 @@ public void onTransaction(Transaction transaction) throws ImporterException {
...
 
+    @Override
+    public void onEntity(Entity entity) throws ImporterException {
+        // entity could experience multiple updates in a single record file, handle updates in memory for this case
+        if (entities.containsKey(entity.getId())) {
+            updateCachedEntity(entity);
+            return;
+        }
+
+        entities.put(entity.getId(), entity);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:276]: Adopted merge for this and others

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 37]
```diff
@@ -218,14 +265,27 @@ public void onTransaction(Transaction transaction) throws ImporterException {
...
     public void onEntityId(EntityId entityId) throws ImporterException {
         // only insert entities not found in cache
-        if (EntityId.isEmpty(entityId) || entityCache.get(entityId.getId()) != null) {
+        if (EntityId.isEmpty(entityId) || entityCache.get(entityId.getId()) != null ||
+                entities.containsKey(entityId.getId())) {
             return;
         }
 
         entityIds.add(entityId);
+        entityIdEntities.put(entityId.getId(), entityId.toEntity());
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:288]: Consolidated and removed `OnEntityId()`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 17 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:367]: Captured missing items

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 18 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:383]: Captured missing items

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AbstractUpdatableDomainRepositoryCustom.java (hunk 19 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/AbstractUpdatableDomainRepositoryCustom.java:40]: Fixed

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java (hunk 21 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java:96]: Removed

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java (hunk 22 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractTransactionHandlerTest.java:333]: This was a bit trickier than it should have been. Cases were an issue and then naming convention, but got it working

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ScheduleRepositoryCustomImpl.java (hunk 23 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/ScheduleRepositoryCustomImpl.java:37]: Fixed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java (hunk 20 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:98]: Actually circling back I recall.
If a user wanted to clear the key we'd again need to differentiate between the lack of setting and the actual setting.
For any nullable object null should imply if was left out. Otherwise we should adopt a zero value.
In this case an empty array should really map to an empty string. 

Need to look more into the key clearing scenario but seems it would map to an empty byte array key which I'm capturing here and with another adaptation to an existing Utility method

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java (hunk 25 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/UpdatableDomainRepositoryCustom.java:26]: Moved to it's own package

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java [hunk 38]
```diff
@@ -0,0 +1,100 @@
...
+import com.hedera.mirror.importer.exception.ParserException;
+import com.hedera.mirror.importer.repository.upsert.UpsertQueryGenerator;
+
+/**
+ * Stateless writer to upsert rows into PostgreSQL using COPY into a temp table then insert and update into final table
+ *
+ * @param <T> domain object
+ */
+@Log4j2
+public class UpsertPgCopy<T> extends PgCopy<T> {
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java:40]: Add a test class for this to cover Entities, Token, TokenAccount and Schedules

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java]: Regardless of the above `value.equals("")` is exactly equivalent to `StringUtils.EMPTY.equals(value)` except the latter can never throw a `NullPointerException`. It doesn't change the logic at all.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java [hunk 39]
```diff
@@ -0,0 +1,41 @@
...
+
+@Log4j2
+@Named
+public class NullableStringSerializer extends JsonSerializer<String> {
+    public static final String NULLABLE_STRING_REPLACEMENT = UUID.randomUUID().toString();
+
+    @Override
+    public void serialize(String value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
+        // empty strings are serialized as null, set to reserved space character and rely on db update sql to parse
+        gen.writeString(value.equals("") ? String.valueOf(NULLABLE_STRING_REPLACEMENT) : value);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java:39]: Meant to change, was a special char previously. Will update

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountId.java (hunk 16 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenAccountId.java:40]: Based not his will leave it here. Also right now it'd be just `TokenAccountId` and eventually we want to remove that embeddedId

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 40]
```diff
@@ -260,12 +292,14 @@ public void onLiveHash(LiveHash liveHash) throws ImporterException {
 
     @Override
     public void onToken(Token token) throws ImporterException {
-        tokenRepository.save(token);
+        // tokens could experience multiple updates in a single record file, handle updates in memory for this case
+        tokens.merge(token.getTokenId().getTokenId().getId(), token, this::mergeToken);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:296]: As discussed offline, duplicating merge logic in application (for same ID within file) and again in upsert (for temp to regular table) could become error prone or a maintenance burden in the future. It also keeps us from dropping the cache/batching here and streaming inserts to the db using pgcopy, reducing memory usage and potentially improving latency. Most likely we won't see any create -> update or update -> update for the same ID within the same file anyway, so it's probably premature optimization.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java [hunk 41]
```diff
@@ -0,0 +1,81 @@
...
+@Named
+@RequiredArgsConstructor
+public class EntityUpsertQueryGenerator extends AbstractUpsertQueryGenerator<Entity_> {
+    public static final String TABLE = "entity";
+    public static final String TEMP_TABLE = TABLE + "_temp";
+    private static final List<String> conflictTargetColumns = List.of(Entity_.ID);
+    private static final List<String> nullableColumns = List.of(Entity_.AUTO_RENEW_ACCOUNT_ID,
+            Entity_.AUTO_RENEW_PERIOD, Entity_.CREATED_TIMESTAMP, Entity_.DELETED, Entity_.EXPIRATION_TIMESTAMP,
+            Entity_.KEY, Entity_.MODIFIED_TIMESTAMP, Entity_.PUBLIC_KEY, Entity_.PROXY_ACCOUNT_ID, Entity_.SUBMIT_KEY);
+    private static final List<SingularAttribute> updatableColumns = Lists.newArrayList(Entity_.autoRenewAccountId,
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java:40]: A more maintainable approach might be to use the metamodel exclude non-updatable columns instead of whitelisting like we're doing: `Sets.difference(getSingularAttributes(), notUpdatableColumns)`.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java [hunk 42]
```diff
@@ -76,7 +76,10 @@ void setup() throws Exception {
     @Test
     @Timeout(10)
     void parse() {
-        accountBalanceFiles.forEach(balanceFileParser::parse);
+        AccountBalanceFileParser accountBalanceFileParser = balanceFileParser;
+        for (AccountBalanceFile accountBalanceFile : accountBalanceFiles) {
+            accountBalanceFileParser.parse(accountBalanceFile);
+        }
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java:82]: The IDE forced me to change to this on a previous item but I can revert this

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java (hunk 38 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java:40]: Added, but can expand

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java [hunk 43]
```diff
@@ -48,31 +52,40 @@
...
         String columnsCsv = Lists.newArrayList(schema.iterator()).stream()
                 .map(CsvSchema.Column::getName)
+                .distinct()
                 .map(name -> CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, name))
                 .collect(Collectors.joining(", "));
-        sql = String.format("COPY %s(%s) FROM STDIN WITH CSV", tableName, columnsCsv);
-
-        insertDurationMetric = Timer.builder("hedera.mirror.importer.parse.insert")
+        sql = String.format("COPY %s(%s) FROM STDIN WITH CSV", this.tableName, columnsCsv);
+        insertDurationMetric = insertDurationMetric == null ? Timer.builder("hedera.mirror.importer.parse.insert")
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java:85]: Unintentionally left over from previous logic. There should be a code change here from what's in master

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java [hunk 44]
```diff
@@ -0,0 +1,100 @@
...
+
+        try {
+            // create temp table to copy into
+            createTempTable(connection);
+            super.persistItems(items, connection);
+
+            // from temp table upsert to final table
+            int insertCount = insertToFinalTable(connection);
+            updateFinalTable(connection);
+            log.debug("Inserted {} and updated from a total of {} rows to {}", insertCount, items
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java:69]: Will put them back and modify the name to encompass upsert. Will be good to track over time the performance and see the time spent doing the upsert stages at scale

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 45]
```diff
@@ -73,76 +75,94 @@
...
+    // maps of upgradable domains
+    private final Map<Long, Entity> entities;
+    private final Map<Long, Schedule> schedules;
+    private final Map<Long, Token> tokens;
+    private final Map<TokenAccountId, TokenAccount> tokenAccounts;
+
     public SqlEntityListener(RecordParserProperties recordParserProperties, SqlProperties sqlProperties,
                              DataSource dataSource,
                              RecordFileRepository recordFileRepository, MeterRegistry meterRegistry,
-                             @Qualifier(CacheConfiguration.NEVER_EXPIRE_LARGE) CacheManager cacheManager,
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:112]: I think this comment was from an old iteration, already removed.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java [hunk 46]
```diff
@@ -0,0 +1,326 @@
...
+        return updateQueryBuilder.toString();
+    }
+
+    private String getConflictClause(String action) {
+        return String.format(
+                " on conflict (%s) do %s",
+                getConflictIdColumns().stream().map(this::getFormattedColumnName).collect(Collectors.joining(", ")),
+                action);
+    }
+}
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java:326]: can have two methods to:

1. given a column name, get `<current final table>.<snake case column name>`
2. given a column name, get `<current temp table>.<snake case column name>`

then in each generator class, can just pass the column name for either case, less error prone.

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java (hunk 43 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java]: Fixed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java [hunk 47]
```diff
@@ -0,0 +1,100 @@
...
+                        UpsertQueryGenerator upsertQueryGenerator) {
+        super(entityClass, meterRegistry, properties, upsertQueryGenerator.getTemporaryTableName());
+        createTempTableSql = upsertQueryGenerator.getCreateTempTableQuery();
+        finalTableName = upsertQueryGenerator.getTableName();
+        insertSql = upsertQueryGenerator.getInsertQuery();
+        updateSql = upsertQueryGenerator.getUpdateQuery();
+    }
+
+    @Override
+    public void persistItems(Collection<T> items, Connection connection) {
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java]: Updated

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java (hunk 44 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java:97]: No logging on the metrics, just metrics unless you think trace logs are worthwhile

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 48]
```diff
@@ -73,76 +75,94 @@
...
+    private final UpsertPgCopy<Schedule> schedulePgCopy;
+    private final UpsertPgCopy<TokenAccount> tokenAccountPgCopy;
+    private final UpsertPgCopy<Token> tokenPgCopy;
 
-    private final Collection<Transaction> transactions;
+    // lists of insert only domains
+    private final Collection<ContractResult> contractResults;
     private final Collection<CryptoTransfer> cryptoTransfers;
-    private final Collection<NonFeeTransfer> nonFeeTransfers;
+    private final Set<Long> entityIds;
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: Removed

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java (hunk 42 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java]: Reverted

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java (hunk 41 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java]: Update most use cases to use a Set

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 40 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:290]: I have my reservations on this since the deduplication allowed us to avoid ordering concerns, but I thought about it and will adopt this approach instead. 
Fundamentally I agree with shifting some of the work to the db, simplifying things and giving ourselves room for future improvements. 

Long term I think there will be some challenges with a large db and index bloat over time but we can optimize those later.

Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:290]: I'll work on adopting this and testing to make sure there's no ordering concerns.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java (hunk 41 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java]: Not sure that's always the case. 
In some cases the not updatable fields are more than the update e.g. Schedule and TokenAccount.
Also being explicit as to what should be updated seemed safer than leaving it open to filtering non updatable columns out. 
Currently adding a new column that that isn't updatable will have no effect on the logic to generate the update sql. With your suggestion adding a new column that that isn't updatable and forgetting to add it to the `notUpdatableColumns` could result in a bug.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java (hunk 46 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java:322]: Ah good suggestion, will adopt that

Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java:322]: Added `getFullTempTableColumnName(String camelCaseColumnName)` and `getFullTempTableColumnName(String camelCaseColumnName)`
Had to keep initial method since in the case of a join the class may need to specify a table name that is neither it's final or temp table e.g. in TokenAccount case it needs to join with Token

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java [hunk 49]
```diff
@@ -0,0 +1,101 @@
...
+            TokenAccount_.kycStatus, TokenAccount_.modifiedTimestamp, TokenAccountId_.tokenId);
+
+    @Override
+    public String getInsertWhereClause() {
+        StringBuilder insertWhereQueryBuilder = new StringBuilder();
+
+        // ignore entries where token not in db
+        insertWhereQueryBuilder.append(String.format(" join %s on %s = %s", TokenUpsertQueryGenerator.TABLE,
+                getTableColumnName(getTemporaryTableName(), Token_.TOKEN_ID),
+                getTableColumnName(TokenUpsertQueryGenerator.TABLE, TokenAccountId_.TOKEN_ID)));
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenAccountUpsertQueryGenerator.java:73]: Updated

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java [hunk 50]
```diff
@@ -161,7 +162,8 @@ boolean process(AccountInfo accountInfo) {
             updated = true;
         }
 
-        if (entity.getMemo().isEmpty() && accountInfo.getMemo() != null) {
+        if (entity.getMemo() == null ||
+                (entity.getMemo().isEmpty() && accountInfo.getMemo() != null)) {
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java:166]: Adopted

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java [hunk 51]
```diff
@@ -0,0 +1,42 @@
...
+import com.fasterxml.jackson.core.JsonGenerator;
+import com.fasterxml.jackson.databind.JsonSerializer;
+import com.fasterxml.jackson.databind.SerializerProvider;
+import java.io.IOException;
+import java.util.UUID;
+import javax.inject.Named;
+import lombok.extern.log4j.Log4j2;
+import org.apache.commons.lang3.StringUtils;
+
+@Log4j2
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/NullableStringSerializer.java:32]: Removed debugging logic

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 40 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:290]: To avoid churn on the PR we can defer this and get the current approach in. Just noting as a concern.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java (hunk 41 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java]: Circling back, with the coalesce logic it may be fine in most cases. 
Will circle back on this so see if there are any edge cases and if I agree with the suggestion

Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java]: Yeah this probably gives more coverage also. 
As it is an update, any new column will be automatically be considered and if it passes the valid entry it'll take on the new value.
Just have to be careful about the nullable list. Will work to adopt this

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 40 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:290]: Lol already implemented but there was an edge case around how the sql should be updated as I was seeing some interesting behavior in tests. Would feel more comfortable doing this in a separate simpler PR.
Will revert and add a ticket.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java [hunk 52]
```diff
@@ -236,4 +232,10 @@ void onTransaction() {
         repositoryEntityListener.onTransaction(transaction);
         assertThat(transactionRepository.findAll()).contains(transaction);
     }
+
+    protected Entity getEntityWithDefaultMemo(EntityId entityId) {
+        Entity entity = entityId.toEntity();
+        entity.setMemo("");
+        return entity;
+    }
```
Comment (ijungmann) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java:240]: I don't see this used.

Comment (ijungmann) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java:240]: Doesn't look like this is used.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java [hunk 53]
```diff
@@ -48,27 +52,36 @@
...
 public class PgCopy<T> {
 
-    private final String tableName;
     private final String sql;
     private final ObjectWriter writer;
-    private final Timer insertDurationMetric;
     private final ParserProperties properties;
+    protected final MeterRegistry meterRegistry;
+    protected final String tableName;
+    protected Timer insertDurationMetric;
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java:60]: final

**Review by ijungmann — COMMENTED** [review]
Will give another pass, other than the mentioned unused code I haven't seen anything.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 45 above)
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:112]: Seems like it's still not removed

[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:112]: Should be gone now. Just pushed again

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java [hunk 54]
```diff
@@ -0,0 +1,128 @@
...
+            super.persistItems(items, connection);
+            copyDurationMetric.record(stopwatch.elapsed());
+
+            // insert items from temp table to final table
+            stopwatch = Stopwatch.createStarted();
+            int insertCount = insertToFinalTable(connection);
+            finalInsertDurationMetric.record(stopwatch.elapsed());
+
+            // update items in final table from temp table
+            stopwatch = Stopwatch.createStarted();
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java:93]: Since you're creating new stopwatches regardless you should push the creation of them and metric recording into the individual methods.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java [hunk 55]
```diff
@@ -0,0 +1,78 @@
...
+import lombok.RequiredArgsConstructor;
+
+import com.hedera.mirror.importer.domain.Schedule_;
+
+@Named
+@RequiredArgsConstructor
+public class ScheduleUpsertQueryGenerator extends AbstractUpsertQueryGenerator<Schedule_> {
+    public static final String TABLE = "schedule";
+    public static final String TEMP_TABLE = TABLE + "_temp";
+    private static final List<String> conflictTargetColumns = List.of(Schedule_.SCHEDULE_ID);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java:36]: We can determine this dynamically by looking at `SingularAttribute.isId()`. For complex keys, we can expand to all nested fields in id object. Let's consider for a follow up.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java [hunk 56]
```diff
@@ -0,0 +1,78 @@
...
+    private static final Set<String> nullableColumns = Set.of(Schedule_.EXECUTED_TIMESTAMP);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java:37]: We can determine this dynamically by looking at `SingularAttribute.isOptional()`. Let's consider for a follow up.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java [hunk 57]
```diff
@@ -0,0 +1,78 @@
...
+import javax.persistence.metamodel.SingularAttribute;
+import lombok.RequiredArgsConstructor;
+
+import com.hedera.mirror.importer.domain.Schedule_;
+
+@Named
+@RequiredArgsConstructor
+public class ScheduleUpsertQueryGenerator extends AbstractUpsertQueryGenerator<Schedule_> {
+    public static final String TABLE = "schedule";
+    public static final String TEMP_TABLE = TABLE + "_temp";
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java:35]: We can lookup both of these dynamically via `EntityType.getName()`. Let's consider for a follow up.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java [hunk 58]
```diff
@@ -0,0 +1,78 @@
...
+    private static final List<String> conflictTargetColumns = List.of(Schedule_.SCHEDULE_ID);
+    private static final Set<String> nullableColumns = Set.of(Schedule_.EXECUTED_TIMESTAMP);
+    private static final Set<SingularAttribute> updatableColumns = Set.of(Schedule_.executedTimestamp);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java:38]: We can determine this dynamically from attributes on `SingularAttribute` and potentially adding custom annotations to the domain fields. Let's consider for a follow up.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java [hunk 59]
```diff
@@ -0,0 +1,51 @@
...
+ * limitations under the License.
+ * ‍
+ */
+
+import java.util.List;
+import java.util.Set;
+import javax.persistence.metamodel.SingularAttribute;
+
+public interface UpsertQueryGenerator {
+    String getAttributeSelectQuery(String attributeName);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java:28]: This interface seems to be a blend of two distinct use cases: sub-class method enforcement and final query generation. The former methods should be moved to protected abstract methods in `AbstractQueryUpsertGenerator`. What remains here should only be methods that are used by `PgCopyUpsert`: `getTemporaryTableName()`, `getCreateTempTableQuery()`, `getTableName()`, `getInsertQuery()`, and `getUpdateQuery()`.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java [hunk 60]
```diff
@@ -0,0 +1,81 @@
...
+@Named
+@RequiredArgsConstructor
+public class EntityUpsertQueryGenerator extends AbstractUpsertQueryGenerator<Entity_> {
+    public static final String TABLE = "entity";
+    public static final String TEMP_TABLE = TABLE + "_temp";
+    private static final List<String> conflictTargetColumns = List.of(Entity_.ID);
+    private static final Set<String> nullableColumns = Set.of(Entity_.AUTO_RENEW_ACCOUNT_ID,
+            Entity_.AUTO_RENEW_PERIOD, Entity_.CREATED_TIMESTAMP, Entity_.DELETED, Entity_.EXPIRATION_TIMESTAMP,
+            Entity_.KEY, Entity_.MODIFIED_TIMESTAMP, Entity_.PUBLIC_KEY, Entity_.PROXY_ACCOUNT_ID, Entity_.SUBMIT_KEY);
+    private static final Set<SingularAttribute> updatableColumns = Set.of(Entity_.autoRenewAccountId,
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java:40]: If we add `@Value`, remove static modifiers and rename to camel case we can omit almost all of the getters. Since these are singleton being static doesn't matter.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java (hunk 41 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java]: Updated logic, implementation looks a bit different as this helped me refactor a bit

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java (hunk 52 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java]: Correct, removed now.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java (hunk 53 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java]: Updated

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java [hunk 61]
```diff
@@ -77,6 +71,5 @@ void setup() throws Exception {
     @Timeout(10)
     void parse() {
         accountBalanceFiles.forEach(balanceFileParser::parse);
-        assertThat(accountBalanceFileRepository.count()).isEqualTo(accountBalanceFiles.size());
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java:80]: Will revert

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java (hunk 59 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java:28]: Yeah meant to move these out, thanks.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java (hunk 54 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java]: Added shared private methods to run logic and record

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java (hunk 59 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/UpsertQueryGenerator.java]: Refactored

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java (hunk 60 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/EntityUpsertQueryGenerator.java]: Added and updated to utilize

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 45 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:112]: Missed the ask here. Got it this time around.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 62]
```diff
@@ -275,20 +303,112 @@ public void onTokenTransfer(TokenTransfer tokenTransfer) throws ImporterExceptio
...
+        if (newEntity.getSubmitKey() != null) {
+            cachedEntity.setSubmitKey(newEntity.getSubmitKey());
+        }
+
+        return cachedEntity;
+    }
+
+    private Token mergeToken(Token cachedToken, Token newToken) {
+        if (newToken.getFreezeKey() != null) {
+            cachedToken.setFreezeKey(newToken.getFreezeKey());
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:358]: In the process of adding more SqlEntityListener tests

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java [hunk 63]
```diff
@@ -0,0 +1,345 @@
...
+
+        return updateQueryBuilder.toString();
+    }
+
+    private boolean isNullableColumn(String columnName) {
+        return getNullableColumns() == null ? false : getNullableColumns().contains(columnName);
+    }
+
+    private List<String> getConflictIdColumns() {
+        if (flywayProperties.getLocations().contains(FlywayProperties.V1)) {
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java:140]: Maybe a better approach would be create child v2 classes and adding a @ConditionalOnProperty on the classes to note which runs in v1 and which in v2
e.g for v1
```
@ConditionalOnProperty(prefix = "spring.flyway", name = "locations", havingValue = "classpath:db/migration/v1",
        matchIfMissing = true)
```

**Review by Nana-EC — COMMENTED** [review]
Might be worth using `@ConditionalOnProperty` on `AbstractUpsertQueryGenerator` extensions and removing FlywayDBPropoerties

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java (hunk 55 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java]: Yeah, got the reflective logic working for this but agreed on not adding more code churn here so I'll leave it for later.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java (hunk 54 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java]: Ok, now there's 2 methods per action instead of one. That's not very encapsulated. But don't want code to churn anymore. Consider using `metric.record(() -> someAction(foo))` in a follow up.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java (hunk 63 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java:140]: Let's not create even more classes for these upserters. Would prefer just normalizing the logic to always append created_timestamp if v2.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/FlywayProperties.java [hunk 64]
```diff
@@ -0,0 +1,40 @@
...
+
+import javax.validation.constraints.NotBlank;
+import lombok.Data;
+import org.springframework.boot.context.properties.ConfigurationProperties;
+import org.springframework.validation.annotation.Validated;
+
+@Data
+@Validated
+@ConfigurationProperties("spring.flyway")
+public class FlywayProperties {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/FlywayProperties.java:31]: There's already a `org.springframework.boot.autoconfigure.flyway.FlywayProperties` bean created by Spring Boot. Please use that instead of duplicating parts of that class.

Alternatively, it might be appropriate to just autowire in a single property directly into `AbstractUpsertQueryGenerator` to avoid leaking it to all children:

```java
@Value("${spring.flyway.locations:v1}"
private String version;
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java (hunk 63 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java:140]: This would require some domain, and table schema (column renaming and index update) modification. 
Also it still doesn't cover all cases e.g. entity doesn't use `created_timestamp` for it's primary index even though it has it.
This makes sense especially with the upserting of partial data. 
There will be cases where you may have everything but the timestamp.
In that case you would still want to hit a conflict and not insert but rather update.

Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/AbstractUpsertQueryGenerator.java:140]: Thinking on this more but agreed on not adding more classes

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/FlywayProperties.java (hunk 64 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/FlywayProperties.java]: Thanks, adopted `@Values` approach to reduce leaking as you noted.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java (hunk 54 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/UpsertPgCopy.java]: Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java (hunk 55 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java]: Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java (hunk 56 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java]: Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java (hunk 57 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java]: Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java (hunk 58 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/ScheduleUpsertQueryGenerator.java]: Captured in [Issue 2122](https://github.com/hashgraph/hedera-mirror-node/issues/2122)

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 40 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:290]: Captured in [Issue 2123)(https://github.com/hashgraph/hedera-mirror-node/issues/2123)

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]

**Review by ijungmann — APPROVED** [review]
