### PR TITLE
HIP-584: Aliases are not resolved in web3

### LINKED ISSUE #6707: HIP-584 : aliases are not resolved in web3
### Description

During precompile execution when using alias addresses we convert them to `long zero` addresses. All of the precompiles should work with `long zero` addresses, but there are some places where the addresses are not resolved to `long zero`, which breaks functionalities like `approve`, `transfer`, etc .

### Steps to reproduce

none

### Additional context

none

### Hedera network

testnet

### Version

0.86.1

### Operating system

None

### PR DESCRIPTION
**Pull request by 0xivanov**
**Description**: 

During precompile execution when using alias addresses we convert them to long zero addresses. All of the precompiles should work with long zero addresses, but there are some places (usage of `frame.getSender`) where the addresses are not resolved to long zero, which breaks functionalities like approve, transfer, etc .

This PR also addresses some bugs regarding `ApprovePrecompile` and `CreateLogic`

- [x] ApprovePrecompile has unnecessary check that reverts the transaction incorrectly
- [x] ApprovePrecompile does not set the `nftOwnerId` correctly
- [x] Added check for zero address in `StoreImpl` in case the owner of NFT is the zero address
- [x] `AssociateLogic` is not used as bean from Spring context

**Related issue(s)**:

Fixes #6707

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java [hunk 1]
```diff
@@ -173,6 +173,7 @@ public boolean hasAssociation(TokenRelationshipKey tokenRelationshipKey) {
 
     @Override
     public boolean hasApprovedForAll(Address ownerAddress, AccountID operatorId, TokenID tokenId) {
+        if (Address.ZERO.equals(ownerAddress)) return false;
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java:176]: Standard is to always use braces. Please check your auto format settings.
```suggestion
        if (Address.ZERO.equals(ownerAddress)) {
            return false;
        }

```

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java [hunk 2]
```diff
@@ -270,12 +271,15 @@ public long getMinimumFeeInTinybars(Timestamp consensusTime, TransactionBody tra
     @Override
     public RunResult run(MessageFrame frame, TransactionBody transactionBody) {
         final var store = ((HederaEvmStackedWorldStateUpdater) frame.getWorldUpdater()).getStore();
+        final var updater = ((HederaEvmStackedWorldStateUpdater) frame.getWorldUpdater());
         final var tokenCreateOp = transactionBody.getTokenCreation();
+        final var senderAddress = Address.wrap(Bytes.wrap(
+                updater.permissivelyUnaliased(frame.getSenderAddress().toArray())));
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java:277]: We should have a test for this here and in other precompiles.

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java [hunk 3]
```diff
@@ -117,9 +117,11 @@ public RunResult run(final MessageFrame frame, TransactionBody transactionBody)
 
         final var updater = ((HederaEvmStackedWorldStateUpdater) frame.getWorldUpdater());
         final var store = updater.getStore();
+        final var senderAddress = Address.wrap(Bytes.wrap(
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java:120]: Perhaps we should add a helper method to `AbstractWritePrecompile` since this logic appears in multiple sub classes?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java (hunk 3 above)
Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java:120]: The problem with this approach is that we need access to the `frame`, which is available in the `run` method. `AbstractWritePrecompile` does not have access to the frame as it is implemented now.

Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java]: Added

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java (hunk 2 above)
Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java]: Added `DYNAMIC_ETH_CALLS_CONTRACT_ALIAS` that should cover these scenarios. We will add more tests in this contract.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java (hunk 1 above)
Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/StoreImpl.java]: Fixed

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java (hunk 2 above)
Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java]: Also removed some duplicate tests, since we pass only aliases in the calldata

**Review by steven-sheehy — APPROVED** [review]
LGTM
