### PR TITLE
Fix address book update always updating 102 file

### LINKED ISSUE #1229: AddressBookService updatePreviousAddressBook only updates 102 file
**Detailed Description**
AddressBookServiceImpl has logic to update the end time of the previous address book.
Currently the retrieval logic is hardcoded to do 102 which means file 101 endtime won't get updated and file 102 will get updated in some cases instead.

https://github.com/hashgraph/hedera-mirror-node/blob/master/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java#L265 should retrieve the address book by start time reference

Suggested fix.
- Update `AddressBookRepository.findLatestAddressBook()` to not filter on fileId
- Add a `AddressBookRepository.findLatestFile102AddressBook()` with the current `AddressBookRepository.findLatestAddressBook()`logic
- Update `AddressBookServiceImpl.getCurrent()` to call `AddressBookRepository.findLatestFile102AddressBook()`
- Leave `AddressBookServiceImpl.updatePreviousAddressBook()` to call updated `AddressBookRepository.findLatestAddressBook()`

**Environment:**
- Version: v0.22.0-rc1

**Additional Context**
Might require a migration fix to correct any already closed off address books if applicable

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
- Fix address book service always updating 0.0.102 end timestamp regardless of file ID
- Add a migration that recalculates all end timestamps to fix both the 102 rows with incorrect timestamps and 101 rows missing correct timestamps
- Fix signature file not buffering the input stream

**Which issue(s) this PR fixes**:
Fixes #1229

**Special notes for your reviewer**:
Working on database migration

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 1]
```diff
@@ -366,6 +367,32 @@ void verifyAddressBookEndPointsAreSet() {
...
+
+        assertEquals(2, addressBookRepository.count());
+        assertEquals(UPDATED.getNodeAddressCount() + FINAL.getNodeAddressCount(), addressBookEntryRepository.count());
+
+        // verify end consensus timestamp was set for previous address book
+        AddressBook prevAddressBook = addressBookRepository.findById(1L).get();
+        assertThat(prevAddressBook.getStartConsensusTimestamp()).isNotNull();
+        assertThat(prevAddressBook.getEndConsensusTimestamp()).isNotNull();
+    }
+
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:395]: For complete coverage we could add a test case where both a 101 and 102 are updated, or where only one of them is updated. In either case it would verify the other addressBook entry isn't modified.

File: hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__fix_address_book_102.sql [hunk 2]
```diff
@@ -0,0 +1,7 @@
+-- Recalculate all end timestamps since we accidentally set the 0.0.102 end timestamp instead of the 0.0.101's in GH1229
+update address_book as ab
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__fix_address_book_102.sql:2]: Is there an easy way to incorporate the migration into an integration test like we do for the java migrations?
Then you could have some test coverage for a mixture of scenarios
- Only one 101 unclosed address book and one 102 incorrectly closed file
- A few 101 unclosed address books  with and a few 102 addressbooks files of which a few were incorrectly closed

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__fix_address_book_102.sql:2]: It's not easy to test migrations. It requires an application context refresh (slowing overall test execution), a custom cleanup script to not break in the future and to only use raw SQL.

In this particular case since there's no DDL statements, we can get away with manually invoking the sql. I added a test case that does that.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:444]: I added a `verify101DoesntUpdate102` test case

File: hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__fix_address_book_102.sql (hunk 2 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__fix_address_book_102.sql:2]: Gotcha. If this was more complex I would have suggested making it a java migration so testing would be made easier also.
Tests you added are satisfactory

**Review by Nana-EC — APPROVED** [review]
LGTM

**Review by ijungmann — APPROVED** [review]
LGTM
