### PR TITLE
Fix allowance acceptance tests

### LINKED ISSUE #3183: Update acceptance tests w AddressBookServiceEndpoint support
### Problem

The current acceptance test `SDKClient` does not have support for the newer AddressBook format with ServiceEndpoints.
When `AcceptanceTestProperties.retrieveAddressBook` is set to true this results in a startup failure

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SDKClient' defined in file [/Users/.../projects/hedera/hedera-mirror-node/hedera-mirror-test/target/test-classes/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hedera.mirror.test.e2e.acceptance.client.SDKClient]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: value already present: 0.0.3
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 72 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hedera.mirror.test.e2e.acceptance.client.SDKClient]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: value already present: 0.0.3
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	... 86 more
Caused by: java.lang.IllegalArgumentException: value already present: 0.0.3
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:310)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:290)
	at java.base/java.util.AbstractMap.putAll(AbstractMap.java:281)
	at com.google.common.collect.HashBiMap.create(HashBiMap.java:87)
	at com.hedera.hashgraph.sdk.Network.getNodesToRemove(Network.java:156)
	at com.hedera.hashgraph.sdk.ManagedNetwork.setNetwork(ManagedNetwork.java:232)
	at com.hedera.hashgraph.sdk.Network.<init>(Network.java:39)
	at com.hedera.hashgraph.sdk.Network.forNetwork(Network.java:46)
	at com.hedera.hashgraph.sdk.Client.forNetwork(Client.java:114)
	at com.hedera.mirror.test.e2e.acceptance.client.SDKClient.getValidatedClient(SDKClient.java:161)
	at com.hedera.mirror.test.e2e.acceptance.client.SDKClient.<init>(SDKClient.java:94)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 88 more

[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 4.465 s <<< FAILURE! - in com.hedera.mirror.test.e2e.acceptance.AcceptanceTest
```

### Solution

Update `SDKClient` class with similar logic as `AddressBookServiceImpl` to support ServiceEndpoints

### Alternatives

_No response_

### LINKED ISSUE #3752: Allowance acceptance tests fail
### Description

The acceptance tests currently fail if the allowance tests are ran. Since allowance is included in the default tag it causes the tests to fail unless explicitly excluded.

### Steps to reproduce

`./mvnw integration-test --projects hedera-mirror-test/ -P=acceptance-tests -Dcucumber.filter.tags="@acceptance"`

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.56.1

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:
* Bump Hedera SDK version
* Change broken address book retrieval to use mirror node REST API
* Change to `grpc-okhttp` to fix a problem with native netty in containers
* Convert tests to newer Cucumber Junit 5 framework
* Fix allowance acceptance tests
* Fix numerous warnings caused by not closing temporary validation clients
* Improve runtime duration from 20 min to 2 min by enabling parallel test execution
* Increase default contract balance to 10M required after https://github.com/hashgraph/hedera-services/pull/3305
* Remove `me.jvt.cucumber:reporting-plugin` in favor of built-in HTML/JSON/XML reports
* Remove required `existingTopicNum` and associated unused tests
* Remove some unnecessary tests
* Replace verbose library logs with a `WebClient` logging interceptor

**Related issue(s)**:

Fixes #3752 
Fixes #3183

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java [hunk 1]
```diff
@@ -125,13 +122,6 @@ public void approveCryptoAllowance(String accountName, long amount) {
...
 
-    @Given("I adjust {string} transfer allowance to {long} tℏ")
-    public void adjustCryptoAllowance(String accountName, long amount) {
-        senderAccountId = accountClient
-                .getAccount(AccountClient.AccountNameEnum.valueOf(accountName));
-        setCryptoAllowance(senderAccountId.getAccountId(), amount);
-    }
-
     @When("{string} transfers {long} tℏ from their approved balance to {string}")
     public void transferFromAllowance(String senderAccountName, long amount, String receiverAccountName) {
```
Comment (xin-hedera) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java:126]: The issue of this function is it's a normal crypto transfer from `sender` to `receiver`. The `sender` account has approved crypto allowance from the default operator of the client. However, the way the crypto transfer transaction is constructed will have the default operator as the transaction payer, signed by both the default operator and the sender account, and it's a crypto transfer from the `sender` to `receiver.

Comment (steven-sheehy) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java:126]: I don't think that's related to my changes?

Comment (xin-hedera) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java:126]: nope. it's tracked here #3489
