### PR TITLE
Fix inconsistent balance results with tokens REST API

### LINKED ISSUE #8395: Balance is different on two endpoints called with same account ID and timestamp
### Description

I have strange behavior when I am calling the testnet Mirror Node. 

[List token balances](https://docs.hedera.com/hedera/sdks-and-apis/rest-api#api-v1-tokens-tokenid-balances) API call returns different value for token balance than [List account balances](https://docs.hedera.com/hedera/sdks-and-apis/rest-api#api-v1-balances) API endpoint.

### Steps to reproduce

Token ID: `0.0.2661966`
Account ID: `0.0.2215735`
Timestamp: `1716885861.254421003`

https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.2661966/balances?account.id=0.0.2215735&timestamp=1716885861.254421003

But when I obtain all balances for account ID I get another value

https://testnet.mirrornode.hedera.com/api/v1/balances?account.id=0.0.2215735&timestamp=1716885861.254421003

### Additional context

Screenshot 2024-05-29 at 14 35 40
Screenshot 2024-05-29 at 14 36 22

### Hedera network

testnet

### Version

v0.105.0

### Operating system

macOS

### PR DESCRIPTION
**Pull request by edwin-greene**
**Description**:
Fixes a token balances query that produced inconsistent balance results with Citus.

**Related issue(s)**:

Fixes #8395 

**Notes for reviewer**:
Tested with testnet-eu Citus.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ x Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/tokens.js [hunk 1]
```diff
@@ -596,7 +596,7 @@ const extractSqlFromTokenBalancesRequest = async (tokenId, filters) => {
         distinct on (ti.account_id)
         ti.account_id,
         ti.balance,
-        $${params.length}::bigint as consensus_timestamp
+        $${params.length}::bigint as sentinel_timestamp
```
Comment (xin-hedera) [inline hedera-mirror-rest/tokens.js:599]: a better name would be `snapshot_timestamp`

Comment (edwin-greene) [reply hedera-mirror-rest/tokens.js]: Thanks I have updated this

File: hedera-mirror-rest/__tests__/specs/tokens/{id}/balances/column-ordering.json [hunk 2]
```diff
@@ -0,0 +1,64 @@
+{
+  "description": "v2 ordering is incorrect if column names collide, if the query used 'consensus_timestamp' instead of 'snapshot_timestamp'",
```
Comment (xin-hedera) [inline hedera-mirror-rest/__tests__/specs/tokens/{id}/balances/column-ordering.json:2]: can this repro the issue with v2 if column alias in the SQL stays `consensus_timestamp`? If so, should explicitly mention the bug ticket in the description or better the extended description, also indicate it can reproduce it

Comment (edwin-greene) [reply hedera-mirror-rest/__tests__/specs/tokens/{id}/balances/column-ordering.json]: Thanks I have added the extended description.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
