### PR TITLE
Fix the failing tests in `InternalCallsTest`

### LINKED ISSUE #10089: Fix `InternalCallsTest` test suite

### PR DESCRIPTION
**Pull request by bilyana-gospodinova**
**Description**:
Adapt the failing tests in `InternalCallsTest`. There is a difference in the behaviour in the mono code and the modularized code, so depending on the `modularizedServices` flag the test assertions are different.

Fixes #10089

### CODE REVIEW

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/InternalCallsTest.java [hunk 1]
```diff
@@ -69,17 +72,31 @@ void sendToNonExistingAccount() throws Exception {
         meterRegistry.clear();
         final var result = contract.call_sendTo(NON_EXISTING_ADDRESS).send();
 
-        assertThat(result).isEqualTo(Boolean.TRUE);
+        if (!mirrorNodeEvmProperties.isModularizedServices()) {
+            assertThat(result).isEqualTo(Boolean.TRUE);
+        } else {
+            assertThat(result)
+                    .isEqualTo(
+                            Boolean.FALSE); // In the mod code, there is a check if the address is an alias and in this
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/InternalCallsTest.java:80]: nit: Maybe add comment above assertion so it doesn't cause it to split across 4 lines.

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/InternalCallsTest.java]: Agreed. Comment addressed.
