### PR TITLE
Enhance web3 error handling with additional support

### LINKED ISSUE #5321: HIP-584: Inspect and fix proper error code response for `ContractController`
### Problem

It seems in some cases we resolve errors to common 500 error code. In stead we should return a more suitable and specific error code.

E.g.

Sending wrong media type to `api/v1/contracts/call` resolves to code 500 instead of 415.

### Solution

Test and inspect different types of error handling and fix the wrong error handling where observed.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by IvanKavaldzhiev**
**Description**:

Enhance ContractController error handling mechanism to support:

- Malformed JSON body - with `BAD_REQUEST` 400
- Unsupported media type - with `UNSUPPORTED_MEDIA_TYPE` 415

**Related issue(s)**:

Fixes #5321 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java [hunk 1]
```diff
@@ -179,6 +183,30 @@ void callInvalidValue() {
...
+    @Test
+    void callWithMalformedJsonBody() {
+        webClient.post()
+                .uri(CALL_URI)
+                .contentType(MediaType.APPLICATION_JSON)
+                .body(BodyInserters.fromValue("{from: 0x00000000000000000000000000000000000004e2"))
+                .exchange()
+                .expectStatus()
+                .isEqualTo(BAD_REQUEST)
+                .expectBody(ServerWebInputException.class);
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java:195]: I'm not sure how this passes, but we should be verifying the payload contents. Same issue for `callInvalidValue()` and `callWithUnsupportedMediaTypeBody()`.
```suggestion
                .expectBody(GenericErrorResponse.class)
                .isEqualTo(new GenericErrorResponse("something");
```

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java [hunk 2]
```diff
@@ -179,6 +183,30 @@ void callInvalidValue() {
...
+    }
+
+    @Test
+    void callWithUnsupportedMediaTypeBody() {
+        webClient.post()
+                .uri(CALL_URI)
+                .contentType(MediaType.TEXT_PLAIN)
+                .body(BodyInserters.fromValue("plain text"))
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java:203]: Probably put valid JSON just so it's clear it's not failing with json deserialization problem.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

**Review by steven-sheehy — APPROVED** [review]
