### PR TITLE
Fix issue with incomplete stubbing on RedisEntityListenerTest.onSlowPublish

### LINKED ISSUE #1484: RedisEntityListenerTest.onSlowPublish failed test
**Detailed Description**
`RedisEntityListenerTest.onSlowPublish()` failed in GitHub Actions:
https://github.com/hashgraph/hedera-mirror-node/runs/1750090529

**Actual Behavior**
```
[INFO] Running com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest

           ,:if0@@@@@@@0f1;,.
       :L@@@@@@@@@@@@@@@@@@@@@C;
     ,L@@@@@@@@@@@@@@@@@@@@@@@@@C:
    ;0@@@@@@@@@@@@@@@@@@@@@@@@@@@81
   :0@@@@@@@1 10@@@@@@@@1 1@@@@@@@8i             1@L        ;@L.                      @@t
  ,L@@@@@@@@1 1@@@@@@@@@1 1@@@@@@@@0:            1@L        ;@L.                      @@t
  ;@@@@@@@@@1  _________  1@@@@@@@@@1            1@L        ;@L.   i@@@@@;     :@@@@@;@@t   .t@@@@f,   i@@@@@@t. .f@@@@@@@i  TM
 .1@@@@@@@@@1 1@@@@@@@@@1 1@@@@@@@@@C.           1@0000000000@L. :@@;  :f@G,  C@@:'':0@@t  1@@:  :@@f. t@@@::::' t8@1'':L@@t
 .1@@@@@@@@@1 1@@@@@@@@@1 1@@@@@@@@@C.           1@@@@@@@@@@@@L. C@@@@@@@@@t i@@.     @@t ;8@@@@@@@@81 t@C      ;0@.     L@t
  ;@@@@@@@@@1  _________  1@@@@@@@@@1            1@L        ;@L. C@:         i@@.     @@t ;@@:         t@C      ;0@.    .L@t
  ,L@@@@@@@@1 1@@@@@@@@@1 1@@@@@@@@0:            1@L        ;@L. ;@@@i:;t@@;  L@@1::i@@@t  1@@t;,;f8C: t@C       t@@t;:iC@@t
   :G@@@@@@@1 1@@@@@@@@@1 1@@@@@@@8;             ;@1        :@i    ;@@@@@i.    :t@@@@;tL;   ,i@@@@t;.  i@1        ,1@@@L;1@i
    :G@@@@@@@@@@@@@@@@@@@@@@@@@@@8i
     .f8@@@@@@@@@@@@@@@@@@@@@@@@L,
        ,L8@@@@@@@@@@@@@@@@@@0C:                                          Mirror Importer 
           ':if0@@@@@@@0fi:'

2021-01-22T10:50:00.827-0600 INFO main c.h.m.i.p.r.e.r.RedisEntityListenerTest No active profile set, falling back to default profiles: default 
2021-01-22T10:50:01.686-0600 INFO main c.h.m.i.c.MetricsConfiguration Collecting table metrics: [] 
2021-01-22T10:50:01.719-0600 INFO main c.h.m.i.c.CredentialsProviderConfiguration Setting up S*** async client using AWS Default Credentials Provider 
2021-01-22T10:50:01.850-0600 INFO main o.f.c.i.c.DbMigrate Current version of schema "public": << Empty Schema >> 
2021-01-22T10:50:01.867-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.0 - Init 
2021-01-22T10:50:02.028-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.1 - update 
2021-01-22T10:50:02.041-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.2 - procedures 
2021-01-22T10:50:02.066-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.*** - procedures 
2021-01-22T10:50:02.078-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.4 - update 
2021-01-22T10:50:02.089-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.5 - file create patch 
2021-01-22T10:50:02.096-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.7 - application status 
2021-01-22T10:50:02.106-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.9 - index 
2021-01-22T10:50:02.11***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.9.1 - transactions indexes 
2021-01-22T10:50:02.124-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.10.0 - account balances 
2021-01-22T10:50:02.144-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.10.1 - freeze transaction 
2021-01-22T10:50:02.156-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.10.2 - response codes 
2021-01-22T10:50:02.167-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.10.*** - account balances 
2021-01-22T10:50:02.181-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.0 - entity key 
2021-01-22T10:50:02.19***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.1 - remove deprecated 
2021-01-22T10:50:02.207-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.2 - transactions pk 
2021-01-22T10:50:02.240-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.*** - entity key 
2021-01-22T10:50:02.245-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.4 - duplicate entities 
2021-01-22T10:50:02.25***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.5 - entity create 
2021-01-22T10:50:02.259-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.5.1 - response codes 
2021-01-22T10:50:02.264-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.6 - Missing Entities 
2021-01-22T10:50:02.267-0600 WARN main c.h.m.i.m.V1_11_6__Missing_Entities Skipping entity import due to missing file /home/runner/work/hedera-mirror-node/hedera-mirror-node/hedera-mirror-importer/./data/accountInfo.txt 
2021-01-22T10:50:02.271-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.12 - transactions maxfee duration 
2021-01-22T10:50:02.276-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.1*** - transaction hash 
2021-01-22T10:50:02.281-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.14 - response codes 
2021-01-22T10:50:02.287-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.15 - unknown transaction types 
2021-01-22T10:50:02.***02-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.16 - cryptotransferlist realm num 
2021-01-22T10:50:02.***19-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.17.0 - hcs support 
2021-01-22T10:50:02.***40-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.17.1 - f entity create 
2021-01-22T10:50:02.***46-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.17.2 - transaction bytes 
2021-01-22T10:50:02.***51-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.17.*** - drop f entity create 
2021-01-22T10:50:02.***55-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.17.4 - hcs proto changes 
2021-01-22T10:50:02.***64-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.17.5 - fix mirror api permissions 
2021-01-22T10:50:02.***69-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.18.0 - non fee transfers 
2021-01-22T10:50:02.***76-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.19.0 - drop fks trigger unused indexes 
2021-01-22T10:50:02.***90-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.20 - drop file id 
2021-01-22T10:50:02.***96-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.21 - add topicmessage seqindex 
2021-01-22T10:50:02.400-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.22 - remove unused components 
2021-01-22T10:50:02.410-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.2***.0 - r5 rc4 proto updates 
2021-01-22T10:50:02.417-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.2***.1 - add topicmessage runninghashversion 
2021-01-22T10:50:02.42***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.24.0 - remove bypass state 
2021-01-22T10:50:02.428-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.24.1 - t record files timestamps 
2021-01-22T10:50:02.4***5-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.25.0 - denormalize entities 
2021-01-22T10:50:02.45***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.25.1 - denormalize transfer tables 
2021-01-22T10:50:02.464-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.26.0 - topic message fragmentation 
2021-01-22T10:50:02.470-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.26.1 - pg notify 
2021-01-22T10:50:02.475-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.26.2 - drop notify trigger 
2021-01-22T10:50:02.480-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.27.0 - add event streams 
2021-01-22T10:50:02.485-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.27.1 - populate consensus start end for record files 
2021-01-22T10:50:02.496-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.27.2 - update name of record file to filename 
2021-01-22T10:50:02.50***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.27.*** - rename tables 
2021-01-22T10:50:02.510-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.28.0 - address book 
2021-01-22T10:50:02.52***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.28.2 - record file index consensus end 
2021-01-22T10:50:02.529-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.29.0 - store verification node in stream file tables 
2021-01-22T10:50:02.542-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***0.0 - balance entity id 
2021-01-22T10:50:02.552-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***0.1 - hts support 
2021-01-22T10:50:02.566-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***1.0 - fix address book 102 
2021-01-22T10:50:02.571-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***1.1 - token symbol size 100 
2021-01-22T10:50:02.578-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***1.2 - remove invalid entities 
2021-01-22T10:50:02.59***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***1.*** - delete token transfers transaction type 
2021-01-22T10:50:02.597-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***2.0 - Missing StreamFile Record 
2021-01-22T10:50:02.604-0600 INFO main c.h.m.i.m.V1_***2_0__Missing_StreamFile_Record No files to parse in directory ./data/accountBalances/valid for BALANCE 
2021-01-22T10:50:02.605-0600 INFO main c.h.m.i.m.V1_***2_0__Missing_StreamFile_Record Added 0 stream file records for BALANCE in 181.2 μs 
2021-01-22T10:50:02.620-0600 INFO main c.h.m.i.m.V1_***2_0__Missing_StreamFile_Record No files to parse in directory ./data/recordstreams/valid for RECORD 
2021-01-22T10:50:02.620-0600 INFO main c.h.m.i.m.V1_***2_0__Missing_StreamFile_Record Added 0 stream file records for RECORD in 215.2 μs 
2021-01-22T10:50:02.627-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***2.1 - update transaction index 
2021-01-22T10:50:02.6***4-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***.0 - drop token account id 
2021-01-22T10:50:02.645-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.***.1 - update record file 
2021-01-22T10:50:02.659-0600 INFO main o.f.c.i.c.DbMigrate Successfully applied 6*** migrations to schema "public" (execution time 00:00.812s) 
2021-01-22T10:50:02.880-0600 INFO main c.h.m.i.c.MirrorImporterConfiguration Configured to download from S*** in region us-east-1 with bucket name 'test' 
2021-01-22T10:50:04.021-0600 WARN main o.s.c.g.c.DefaultCredentialsProvider No core credentials are set. Service-specific credentials (e.g., spring.cloud.gcp.pubsub.credentials.*) should be used if your app uses services that require credentials. java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:1***4)
2021-01-22T10:50:04.590-0600 INFO main c.h.m.i.p.r.e.r.RedisEntityListenerTest Started RedisEntityListenerTest in 9.46*** seconds (JVM running for 76.014) 
2021-01-22T10:50:04.625-0600 INFO task-4 c.h.m.i.p.b.BalanceFileParser Skip watching directory: ./data/accountBalances/valid 
2021-01-22T10:50:04.629-0600 INFO task-*** c.h.m.i.c.MirrorDateRangePropertiesProcessor BALANCE: downloader will download files in time range (1970-01-01T00:00:00Z, 2262-04-11T2***:47:16.854775807Z], parser will parse items in time range [1970-01-01T00:00:00Z, 2262-04-11T2***:47:16.854775807Z] 
2021-01-22T10:50:04.652-0600 INFO task-*** c.h.m.i.c.MirrorDateRangePropertiesProcessor RECORD: downloader will download files in time range (1970-01-01T00:00:00Z, 2262-04-11T2***:47:16.854775807Z], parser will parse items in time range [1970-01-01T00:00:00Z, 2262-04-11T2***:47:16.854775807Z] 
2021-01-22T10:50:05.505-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 2 messages in 107.5 ms 
2021-01-22T10:50:05.715-0600 WARN Thread-60 c.h.m.i.p.r.e.r.RedisEntityListener topicMessagesQueue is full, will block until space is available 
2021-01-22T10:50:06.240-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 524.7 ms 
2021-01-22T10:50:06.266-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 26.55 ms 
2021-01-22T10:50:06.290-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 2***.14 ms 
2021-01-22T10:50:06.***07-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 16.99 ms 
2021-01-22T10:50:06.***20-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 1***.20 ms 
2021-01-22T10:50:06.***1-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 11.01 ms 
2021-01-22T10:50:06.***45-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 1***.7*** ms 
2021-01-22T10:50:06.***59-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 1***.76 ms 
2021-01-22T10:50:06.***8***-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 2***.95 ms 
2021-01-22T10:50:06.***9***-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying 1 messages in 9.***7*** ms 
2021-01-22T10:50:06.521-0600 INFO pool-28-thread-1 c.h.m.i.p.r.e.r.RedisEntityListener Finished notifying *** messages in 27.00 ms 
Error:  Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.451 s <<< FAILURE! - in com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest
Error:  com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish  Time elapsed: 0.768 s  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException: 

Unfinished stubbing detected here:
-> at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:156)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 ***. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed

	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:156)

[INFO] Running com.hedera.mirror.importer.parser.record.entity.EntityRecordItemListenerTokenTest
```

**Expected Behavior**
No failures

**Environment:**
- Version: v0.26.0

**Additional Context**

### PR DESCRIPTION
**Pull request by ijungmann**
**Detailed description**:

- Move tests that are closer to unit tests/rely on Mockito to a separate test file and refactor to work without Spring.
- Disable Redis by default on unit tests because most tests do not need Redis, and hitting `RedisEntityListener` is stateful, causing tests to fail if run at the same time.
- Enable Redis on Redis-specific tests

Original error here:
```org.mockito.exceptions.misusing.UnfinishedStubbingException: 

Unfinished stubbing detected here:
-> at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:156)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 ***. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed

	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:156)
```

**Which issue(s) this PR fixes**:
Fixes #1484 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by steven-sheehy** [comment]
I'm also seeing a similar error in another test in this file: https://github.com/hashgraph/hedera-mirror-node/runs/1786439070

**Comment by ijungmann** [comment]
> I'm also seeing a similar error in another test in this file: https://github.com/hashgraph/hedera-mirror-node/runs/1786439070

That's pretty wild, if I'm reading the output correctly that other test is failing because it doesn't like the stubbing in the first test, i.e. that test is fine, but it's not happy about other tests in the file.

```
Error:  Tests run: 7, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 9.567 s <<< FAILURE! - in com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest
Error:  com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish  Time elapsed: 0.692 s  <<< FAILURE!
java.lang.AssertionError
	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:156)

Error:  com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onDuplicateTopicMessages  Time elapsed: 0.062 s  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException: 

Unfinished stubbing detected here:
-> at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:156)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 ***. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed

	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.subscribe(RedisEntityListenerTest.java:71)
	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onDuplicateTopicMessages(RedisEntityListenerTest.java:92)
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerMockitoTest.java [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+        TopicMessage topicMessage3 = topicMessage();
+
+        //submitAndSave two messages, verify publish logic called twice
+        submitAndSave(topicMessage1);
+        submitAndSave(topicMessage2);
+        verify(redisOperations, timeout(500).times(2))
+                .executePipelined(any(SessionCallback.class));
+
+        //submitAndSave two duplicate messages, verify publish was not attempted
+        Mockito.reset(redisOperations);
```
Comment (ijungmann) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerMockitoTest.java:120]: Technically this does not need to be reset, but I felt it helped readability when it comes to the verify (calls would be 2, 2, 3, as opposed to 2, 0, 1 otherwise)

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java [hunk 2]
```diff
@@ -20,39 +20,22 @@
...
 import reactor.core.publisher.UnicastProcessor;
-import reactor.test.StepVerifier;
 
 import com.hedera.mirror.importer.domain.StreamMessage;
 import com.hedera.mirror.importer.domain.TopicMessage;
 import com.hedera.mirror.importer.parser.record.entity.BatchEntityListenerTest;
-import com.hedera.mirror.importer.parser.record.entity.EntityBatchCleanupEvent;
-import com.hedera.mirror.importer.parser.record.entity.EntityBatchSaveEvent;
 
+@SpringBootTest(properties = {
```
Comment (ijungmann) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java:37]: This is particularly for CircleCI, it seems to fail in that environment specifically without this, I'm assuming because we don't use test containers there.

Comment (steven-sheehy) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java:37]: I'm worried if this causes yet another application context to start, slowing down tests further. Why is this even needed if we manually `properties.setEnabled(true)` in `BatchEntityListenerTest`?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerMockitoTest.java [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+import org.springframework.data.redis.core.SessionCallback;
+
+import com.hedera.mirror.importer.MirrorProperties;
+import com.hedera.mirror.importer.domain.StreamMessage;
+import com.hedera.mirror.importer.domain.TopicMessage;
+import com.hedera.mirror.importer.parser.record.entity.EntityBatchCleanupEvent;
+import com.hedera.mirror.importer.parser.record.entity.EntityBatchSaveEvent;
+
+@ExtendWith(MockitoExtension.class)
+class RedisEntityListenerMockitoTest {
```
[the remark this answers is not in the document]
Comment (ijungmann) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerMockitoTest.java]: Sure, makes sense.  Those names are changed now.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java (hunk 2 above)
Comment (ijungmann) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java]: I think you're right that it's not needed, yesterday I pulled that line out and it failed in CCI, I put it back and it passed, but I just removed it again and it seems to be passing (3 straight passes in CCI).  I had a config typo in there at some point, so that may have been related.  Anyway, it's removed now.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by Nana-EC — DISMISSED** [review]
LGTM.
Had one nit if you do circle back

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java [hunk 4]
```diff
@@ -141,28 +93,54 @@ void onSlowPublish() {
...
+        Mockito.reset(redisOperations);
+        submitAndSave(topicMessage3);
+        entityListener.onCleanup(new EntityBatchCleanupEvent(this));
+        verify(redisOperations, timeout(500).times(1))
+                .executePipelined(any(SessionCallback.class));
+    }
+
+    private TopicMessage topicMessage() {
+        TopicMessage topicMessage = new TopicMessage();
+        topicMessage.setConsensusTimestamp(consensusTimestamp++);
```
[the remark this answers is not in the document]
Comment (ijungmann) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListenerTest.java:142]: Sure, I just moved that logic in here.

**Review by xin-hedera — APPROVED** [review]
