### PR TITLE
Moved RecordFileParser file system logic to RecordFilePoller

### LINKED ISSUE #568: Move filesystem-dependency from RecordFileParser to (new) RecordFileReader class
Right now, `RecordFileParser` class has two concerns:
- periodically - list files, read files (depends on 'where' of stream files)
- parse stream files.

We want to spit it into
- `RecordFileReader`: handles listing/reading of files. Use `FileWatcher` like in `BalanceFileParser`. Share code (if possible)
- `RecordFileParser`: Only cares about parsing of stream file (given as `InputStream` to not depend on filesystem aspects)

### LINKED ISSUE #899: Duplicate key violation error after importer restart
**Detailed Description**
Importer can sometimes not shutdown cleanly while processing a record file and leave the database with partial data from that file. This occurred in testnet yesterday. In this case it finished processing the data from the file but did not add a record file entry or update application status before shutting down. We should also investigate if this can occur in other scenarios like for stopping during multi-batch files.

**Actual Behavior**
1. Shutdown importer midway through a large file
2. Start importer
3. Importer errors with `duplicate key value violates unique constraint`

**Expected Behavior**
The record file processing is atomic.

**Environment:**
- Java: OpenJDK 11
- OS: Ubuntu 18.04
- Version: 0.15.3

**Additional Context**

```
Jul 21 16:13:32 mirrornode-stable-testnet-primary-parser-1 java[1598]:         ,L8@@@@@@@@@@@@@@@@@@0C:                                          Mirror Importer  (v0.15.2)
Jul 21 16:13:32 mirrornode-stable-testnet-primary-parser-1 java[1598]:            ':if0@@@@@@@0fi:'
Jul 21 16:13:32 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:32,394 INFO  [main ] c.h.m.i.MirrorImporterApplication No active profile set, falling back to default profiles: default
Jul 21 16:13:36 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:36,961 INFO  [main ] c.h.m.i.c.MetricsConfiguration Collecting table metrics: [account_balance_sets, account_balances, crypto_transfer, flyway_schema_history, non_fee_transfer, t_application_status, t_contract_result, t_entities, t_entity_types, t_file_data, t_livehashes, t_record_files, t_transaction_results, t_transaction_types, topic_message, transaction]
Jul 21 16:13:37 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:37,377 INFO  [main ] o.f.c.i.c.DbMigrate Current version of schema "public": 1.26.2
Jul 21 16:13:37 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:37,381 INFO  [main ] o.f.c.i.c.DbMigrate Schema "public" is up to date. No migration necessary.
Jul 21 16:13:39 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:39,571 INFO  [main ] c.h.m.i.c.MirrorImporterConfiguration Configured to download from GCP with bucket name 'hedera-stable-testnet-streams'
Jul 21 16:13:39 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:39,825 INFO  [main ] c.h.m.i.c.MirrorImporterConfiguration Setting up S3 async client using provided access/secret key
Jul 21 16:13:40 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:40,997 INFO  [main ] c.h.m.i.a.NetworkAddressBook Restoring existing address book /var/lib/hedera-mirror-importer/addressbook.bin
Jul 21 16:13:41 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:41,000 INFO  [main ] c.h.m.i.a.NetworkAddressBook Saved 3434B partial address book update to /var/lib/hedera-mirror-importer/addressbook.bin.tmp
Jul 21 16:13:41 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:41,069 INFO  [main ] c.h.m.i.a.NetworkAddressBook New address book with 4 addresses successfully parsed and saved to /var/lib/hedera-mirror-importer/addressbook.bin
Jul 21 16:13:43 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:43,705 INFO  [scheduling-3] c.h.m.i.u.Utility Loading record format version 2 from record file: 2020-07-21T16_01_12.618989Z.rcd
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:44,164 INFO  [main ] c.h.m.i.MirrorImporterApplication Started MirrorImporterApplication in 13.972 seconds (JVM running for 15.819)
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:44,174 ERROR [scheduling-3] c.h.m.i.p.r.e.s.SqlEntityListener Error committing sql insert batch
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO transaction (node_account_id, memo, valid_start_ns, type, payer_account_id, result, consensus_ns, entity_id, charged_tx_fee, initial_balance, valid_duration_seconds, max_fee, transaction_hash, transaction_bytes) VALUES (6, ?, 1595347261885000000, 27, 24105, 22, 1595347272618989000, 47536, 273693, 0, 120, 100000000, ?, NULL),(6, ?, 1595347261912000000, 27, 24105, 22, 1595347272618989001, 47536, 281679, 0, 120, 100000000, ?, NULL),(6, ?, 1595347261916000000, 27, 24105, 22, 1595347272618989002, 47536, 281556, 0, 120, 100000000, ?, NULL),(6, ?, 1595347261924000000, 27, 24105, 22, 1595347272618989003, 47536, 274124, 0, 120, 100000000, ?, NULL),(6, ?, 1595347261956000000, 27, 24105, 22, 1595347272618989004, 47536, 289357, 0, 120, 100000000, ?, NULL),(6, ?, 1595347261992000000, 27, 24105, 22, 1595347272618989005, 47536, 274063, 0, 120, 100000000, ?, NULL),(6, ?, 1595347262004000000, 27, 24105, 22, 1595347272618989006, 47536, 305020, 0, 120, 100000000, ?, NULL),(6, ?, 1595347262028000000, 27, 24105, 22, 1595347272618989007, 47536, 281249, 0, 120, 100000000, ?, NULL),(6, ?, 1595347262058000000, 27, 24105, 22, 1595347272618989008, 47536, 348264, 0, 120, 100000000, ?, NULL),(5, ?, 1595347261877000000, 27, 24105, 22, 1595347272704687000, 47536, 274370, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262063000000, 27, 24105, 22, 1595347272704687001, 47536, 541016, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262093000000, 27, 24105, 22, 1595347272704687002, 47536, 282355, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262131000000, 27, 24105, 22, 1595347272704687003, 47536, 282355, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262143000000, 27, 24105, 22, 1595347272704687004, 47536, 273571, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262163000000, 27, 24105, 22, 1595347272704687005, 47536, 287883, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262171000000, 27, 24105, 22, 1595347272704687006, 47536, 287883, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262187000000, 27, 24105, 22, 1595347272704687007, 47536, 278362, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262208000000, 27, 24105, 22, 1595347272704687008, 47536, 282232, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262212000000, 27, 24105, 22, 1595347272704687009, 47536, 287883, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262216000000, 27, 24105, 22, 1595347272704687010, 47536, 273816, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262221000000, 27, 24105, 22, 1595347272704687011, 47536, 341077, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262229000000, 27, 24105, 22, 1595347272704687012, 47536, 341016, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262238000000, 27, 24105, 22, 1595347272704687013, 47536, 273939, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262246000000, 27, 24105, 22, 1595347272704687014, 47536, 287944, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262285000000, 27, 24105, 22, 1595347272704687015, 47536, 329222, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262315000000, 27, 24105, 22, 1595347272704687016, 47536, 273878, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262323000000, 27, 24105, 22, 1595347272704687017, 47536, 278362, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262340000000, 27, 24105, 22, 1595347272704687018, 47536, 282294, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262348000000, 27, 24105, 22, 1595347272704687019, 47536, 274001, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262362000000, 27, 24105, 22, 1595347272704687020, 47536, 281310, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262366000000, 27, 24105, 22, 1595347272704687021, 47536, 282294, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262383000000, 27, 24105, 22, 1595347272704687022, 47536, 282355, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262387000000, 27, 24105, 22, 1595347272704687023, 47536, 274063, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262409000000, 27, 24105, 22, 1595347272704687024, 47536, 282416, 0, 120, 100000000, ?, NULL),(5, ?, 1595347262405000000, 27, 24105, 22, 1595347272704687025, 47536, 282355, 0, 120, 100000000, ?, NULL),(4, ?, 1595347261890000000, 27, 24105, 22, 1595347272704687027, 47536, 273632, 0, 120, 100000000, ?, NULL),(4, ?, 1595347261920000000, 27, 24105, 22, 1595347272704687028, 47536, 281617, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262009000000, 27, 24105, 22, 1595347272704687029, 47536, 273939, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262017000000, 27, 24105, 22, 1595347272704687030, 47536, 273878, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262013000000, 27, 24105, 22, 1595347272704687031, 47536, 273939, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262020000000, 27, 24105, 22, 1595347272704687032, 47536, 273939, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262024000000, 27, 24105, 22, 1595347272704687033, 47536, 281433, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262033000000, 27, 24105, 22, 1595347272704687034, 47536, 281310, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262037000000, 27, 24105, 22, 1595347272704687035, 47536, 281494, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262054000000, 27, 24105, 22, 1595347272704687036, 47536, 309013, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262118000000, 27, 24105, 22, 1595347272704687037, 47536, 282294, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262122000000, 27, 24105, 22, 1595347272704687038, 47536, 282294, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262127000000, 27, 24105, 22, 1595347272704687039, 47536, 282294, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262135000000, 27, 24105, 22, 1595347272704687040, 47536, 316876, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262147000000, 27, 24105, 22, 1595347272704687041, 47536, 281433, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262159000000, 27, 24105, 22, 1595347272704687042, 47536, 274124, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262167000000, 27, 24105, 22, 1595347272704687043, 47536, 282416, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262179000000, 27, 24105, 22, 1595347272704687044, 47536, 287944, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262196000000, 27, 24105, 22, 1595347272704687045, 47536, 329222, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262242000000, 27, 24105, 22, 1595347272704687046, 47536, 287883, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262272000000, 27, 24105, 22, 1595347272704687047, 47536, 282416, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262293000000, 27, 24105, 22, 1595347272704687048, 47536, 341016, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262297000000, 27, 24105, 22, 1595347272704687049, 47536, 273878, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262311000000, 27, 24105, 22, 1595347272704687050, 47536, 287944, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262336000000, 27, 24105, 22, 1595347272704687051, 47536, 302134, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262375000000, 27, 24105, 22, 1595347272704687052, 47536, 273878, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262379000000, 27, 24105, 22, 1595347272704687053, 47536, 340954, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262444000000, 27, 24105, 22, 1595347272704687054, 47536, 274124, 0, 120, 100000000, ?, NULL),(4, ?, 1595347262452000000, 27, 24105, 22, 1595347272704687055, 47536, 274124, 0, 120, 100000000, ?, NULL) was aborted: ERROR: duplicate key value violates unique constraint "transaction_pkey"
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:   Detail: Key (consensus_ns)=(1595347272618989000) already exists.  Call getNextException to see other errors in the batch.
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:154) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2269) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:511) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:851) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:874) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1569) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.3.jar!/:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.3.jar!/:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.executeBatch(SqlEntityListener.java:216) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.executeBatches(SqlEntityListener.java:194) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.onEnd(SqlEntityListener.java:102) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.onEnd(SqlEntityListener.java:59) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.RecordFileParser.loadRecordFile(RecordFileParser.java:159) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.RecordFileParser.loadRecordFiles(RecordFileParser.java:206) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.RecordFileParser.loadRecordFile(RecordFileParser.java:159) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.RecordFileParser.loadRecordFiles(RecordFileParser.java:206) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:261) ~[classes!/:0.15.2]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]: Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "transaction_pkey"
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:   Detail: Key (consensus_ns)=(1595347272618989000) already exists.
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268) ~[postgresql-42.2.12.jar!/:42.2.12]
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]:         ... 25 more
Jul 21 16:13:44 mirrornode-stable-testnet-primary-parser-1 java[1598]: 2020-07-21 16:13:44,174 INFO  [scheduling-3] c.h.m.i.p.r.RecordFileParser Finished parsing 115 transactions from record file /var/lib/hedera-mirror-importer/recordstreams/valid/2020-07-21T16_01_12.618989Z.rcd in 704ms (163/s)
```

### PR DESCRIPTION
**Pull request by Nana-EC**
**Detailed description**:
RecordFileParser contains both file system logic to poll for rcd files from file system as well as controller logic to parse said files and persist in DB.
This makes for a complex file.
In the case of #899 it's difficult to separate and ensure proper rollback of data persistence in cases like Shutdown.

This change:
- Add `FilePoller` interface with the poll() function
- Add `RecordFilePoller` that implements `FilePoller` and contains all the logic to poll the file system for new valid rcd files
- Update `FileParser` signature to support `StreamFileData` implementations for parsing
- Update `RecordFileParser`, renaming `loadRecordFile()` -> `parse(StreamFileData ...)` therefore implementing `FileParser`. 
- ~Also makes `parse()` `@Transactional` to ensure rollback should shutdown or other event require persisted transactions from an rcd file to be reverted.~
- Updated broken tests and moves `poll()` tests into new `RecordFilePollerTest`
- Moved record_file and application_status updates post file process into the OnEnd so as to pick up the transactional logic
- Wrapped cache managers to be able to support transactional operations 
- Added tests to verify above recovery scenarios

**Which issue(s) this PR fixes**:
Fixes #899 
Fixes #568 

**Special notes for your reviewer**:
Verified above logic running local parser against testnet bucket. Simulating error cases for mid batch, post batch,  record_file and application status errors and viewed the parser recover.

There does seem to be some further configuration that needs to be done to ensure spring date spa repositories and hibernate transaction management logic are always in sync. This is confused by the fact that we sue repositories, prepared statements and CopyManager to update the db.
Future items including using repositories only and utilizing improved ingestion options such as timescaleDb etc will simplify the code and reduce the complication.
As such we can wait on those or address the transaction management in another ticket.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java [hunk 1]
```diff
@@ -135,11 +123,13 @@ public RecordFileParser(ApplicationStatusRepository applicationStatusRepository,
...
 
     /**
-     * Given a service record name, read and parse and return as a list of service record pair
+     * Given a stream file data representing an rcd file from the service parse record items and persist changes
      *
      * @param streamFileData containing information about file to be processed
      */
-    public void loadRecordFile(StreamFileData streamFileData) {
+    @Override
+    @Transactional
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:131]: There's a problem here. In SqlEntityListener we are manually manage the commit and that can cause issues. From `connection.setAutoCommit()`:
```
If this method is called during a transaction and the auto-commit mode is changed, the transaction is committed. If setAutoCommit is called and the auto-commit mode is not changed, the call is a no-op.
```
Also, I'm not sure the impact of explicitly calling commit on a connection with an outer transaction in progress. It would be better to remove setAutoCommit and not call commit/rollback manually. This annotation should handle it for us. But please verify with tests.

I'm not sure about the connection and statements in SqlEntityListener. I'm guessing we still need to manually close those but since they're proxied they won't actually close until the outer transaction completes.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java [hunk 2]
```diff
@@ -165,6 +155,10 @@ public void loadRecordFile(StreamFileData streamFileData) {
 
             recordParserLatencyMetric(recordFile);
             success = true;
+        } catch (Exception ex) {
+            log.warn("Failed to parse {}", streamFileData.getFilename(), ex);
+            recordStreamFileListener.onError(); // rollback changes
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:160]: Can remove rollback changes comment, considering previous change.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java [hunk 3]
```diff
@@ -188,47 +166,63 @@ void bypassHashMismatch() throws Exception {
...
         });
         verify(recordItemListener, times(NUM_TXNS_FILE_1)).onItem(any());
         verify(recordStreamFileListener, times(2)).onStart(any());
         verify(recordStreamFileListener, times(1)).onEnd(any());
     }
 
+    @Test
+    void verifyRollbackOnErrorAfterPersistence() throws Exception {
+        // given
+        String fileName = file1.toString();
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java:213]: Unused

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java [hunk 4]
```diff
@@ -188,47 +166,63 @@ void bypassHashMismatch() throws Exception {
...
+        doThrow(ParserSQLException.class).when(applicationStatusRepository).updateStatusValue(any(), any());
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java:214]: I don't think it's possible to truly test database rollback with mocks. Since it's probably tricky to convert this to not use mocks, we can probably create a separate integration test file just for the rollback test.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java [hunk 5]
```diff
@@ -188,47 +166,63 @@ void bypassHashMismatch() throws Exception {
...
+
+        // when
+        Assertions.assertThrows(ParserSQLException.class, () -> {
+            recordFileParser.parse(streamFileData2);
+        });
+
+        // then
+        assertProcessedFile(streamFileData2, recordFile2, NUM_TXNS_FILE_2);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java:222]: There should be nothing processed, right? This test is suspect.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFilePollerTest.java [hunk 6]
```diff
@@ -0,0 +1,168 @@
...
+    @Test
+    void noFiles() throws Exception {
+        // when
+        recordFilePoller.poll();
+
+        // then
+        assertParsedFiles();
+        verifyNoInteractions(recordFileParser);
+    }
+
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFilePollerTest.java:126]: Please add a test for not a directory. Would also be good to check code coverage report and see if any other paths not tested.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFilePollerTest.java [hunk 7]
```diff
@@ -0,0 +1,168 @@
...
+    // Asserts that recordFileParser.parse is called wth exactly the given fileNames.
+    private void assertParse(String... fileNames) {
+        ArgumentCaptor<StreamFileData> captor = ArgumentCaptor.forClass(StreamFileData.class);
+        verify(recordFileParser, times(fileNames.length)).parse(captor.capture());
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFilePollerTest.java:130]: Sure, could achieve the same with below, since InOrder will make method less general
```
assertThat(actualArgs)
                .extracting(StreamFileData::getFilename)
                .isEqualTo(Arrays.asList(fileNames));
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFilePollerTest.java (hunk 6 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFilePollerTest.java:126]: Not sure we have to worry about that. We have a few` Utility.ensureDirectory` sprinkled around for the data path.
In addition to static final variables and enums that are used to map the valid and parsed files location using a `Path.resolve`.
Makes it difficult to set it wrong and or test.
I could force mock it but I'm not seeing a way that the parser would start with the Valid path being a file and not a directory

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java [hunk 8]
```diff
@@ -0,0 +1,121 @@
...
+        }
+    }
+
+    /**
+     * read and parse a list of record files
+     *
+     * @throws Exception
+     */
+    private void loadRecordFiles(List<String> filePaths) {
+        Collections.sort(filePaths);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java:93]: Removed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java [hunk 9]
```diff
@@ -0,0 +1,121 @@
...
+        if (ShutdownHelper.isStopping()) {
+            return;
+        }
+        Path path = parserProperties.getValidPath();
+        log.debug("Parsing record files from {}", path);
+        try {
+            File file = path.toFile();
+            if (file.isDirectory()) {
+
+                String[] files = file.list();
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java:65]: Added

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java [hunk 10]
```diff
@@ -0,0 +1,121 @@
...
+                Arrays.sort(files);           // sorted by name (timestamp)
+
+                // add directory prefix to get full path
+                List<String> fullPaths = Arrays.asList(files).stream()
+                        .map(s -> file + "/" + s)
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java:70]: Agreed, removed this additional loop.

[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java:70]: No need here as this list creation was removed. Added it when creating the File in `loadRecordFiles()`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java [hunk 11]
```diff
@@ -165,6 +155,10 @@ public void loadRecordFile(StreamFileData streamFileData) {
 
             recordParserLatencyMetric(recordFile);
             success = true;
+        } catch (Exception ex) {
+            log.warn("Failed to parse {}", streamFileData.getFilename(), ex);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:159]: Removed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java [hunk 12]
```diff
@@ -0,0 +1,121 @@
...
+                    Utility.archiveFile(file, parserProperties.getParsedPath());
+                } else {
+                    FileUtils.deleteQuietly(file);
+                }
+            } catch (FileNotFoundException e) {
+                log.warn("File does not exist {}", filePath);
+                return;
+            } catch (Exception e) {
+                log.error("Error parsing file {}", filePath, e);
+                if (!(e instanceof DuplicateFileException)) { // if DuplicateFileException, continue with other
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java:114]: DuplicateFileException catch log and ignore added to parser

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:131]: Manual close is good practice, but you're right the outer transaction close will probably handle it.
I did remove the setAutoCommit

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java (hunk 2 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:160]: Removed comment

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java (hunk 3 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java:213]: Removed leftover

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java:214]: Working on integration test.  Parse method makes it a bit tricky to force an error after commit to I'm having to at last mock the applicationStatus Repository call for such a test.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java (hunk 5 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java:222]: Actually in this test everything would have been processed as expected, expect after persistence but before file complete an error occurred.
Test is removed though

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFilePollerTest.java (hunk 6 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFilePollerTest.java:126]: Added not a directory test. Drop in code coverage seems to be related to MetricsExecutionInterceptor.java

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java]: Proving difficult to get a test that captures this. 
Maybe it's sufficient to rely on @Transactional functioning correctly based on our configuration.
I did update RecordFilePrser to use the spring version so we could get coverage for the RunTimeExceptions which are not caught and therefore don't force a rollback when the base @Transactional is used.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java [hunk 13]
```diff
@@ -135,11 +124,13 @@ public RecordFileParser(ApplicationStatusRepository applicationStatusRepository,
...
 
     /**
-     * Given a service record name, read and parse and return as a list of service record pair
+     * Given a stream file data representing an rcd file from the service parse record items and persist changes
      *
      * @param streamFileData containing information about file to be processed
      */
-    public void loadRecordFile(StreamFileData streamFileData) {
+    @Override
+    @Transactional(rollbackFor = Exception.class)
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:132]: Should remove rollbackFor. I don't see a reason to exclude Error.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 14]
```diff
@@ -198,9 +184,11 @@ private void executeBatch(PreparedStatement ps, String entity) {
...
-            sqlInsertEntityId.close();
-            sqlNotifyTopicMessage.close();
-            connection.close();
+            if (connection != null) {
+                sqlInsertEntityId.close();
+                sqlNotifyTopicMessage.close();
+                connection.close();
+            }
         } catch (SQLException e) {
             throw new ParserSQLException("Error closing connection", e);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:193]: I think it's fine to just log this instead of rethrow. Also, because we want to ensure `cleanup()` is always called.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java (hunk 13 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:132]: My understanding was without this RuntimeExceptions wouldn't result in a rollback. But yeah excluding Errors was not an intended impact.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java]: Added a rollback test to the RecordFileParserIntegrationTest.
More importantly verified against a local running parser that the rollback works for both pgcopy and prepared statement produced inserts

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java [hunk 15]
```diff
@@ -160,16 +149,19 @@ public void loadRecordFile(StreamFileData streamFileData) {
             recordFile.setLoadStart(startTime.getEpochSecond());
             recordFile.setLoadEnd(Instant.now().getEpochSecond());
             recordStreamFileListener.onEnd(recordFile);
-            applicationStatusRepository.updateStatusValue(
-                    ApplicationStatusCode.LAST_PROCESSED_RECORD_HASH, recordFile.getFileHash());
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:164]: Good point

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 16]
```diff
@@ -120,14 +137,18 @@ public SqlEntityListener(SqlProperties properties, DataSource dataSource,
...
+        partialRecordFile = null;
     }
 
     @Override
     public void onStart(StreamFileData streamFileData) {
         String fileName = FilenameUtils.getName(streamFileData.getFilename());
 
-        if (recordFileRepository.findByName(fileName).size() > 0) {
-            throw new DuplicateFileException("File already exists in the database: " + fileName);
+        List<RecordFile> matchingRecords = recordFileRepository.findByName(fileName);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: Handle method removed :)

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 17]
```diff
@@ -314,6 +339,65 @@ private void notifyTopicMessages() {
...
+    private void handleDuplicateOrPartiallyProcessedRecordFile(RecordFile recordFile) {
+        // handle faulty transaction management between spring repositories and manual java sql operations
+        DuplicateFileException duplicateFileException = new DuplicateFileException("File already exists in the " +
+                "database: " + recordFile.getName());
+        RecordFile latestRecordFile = recordFileRepository.findTopByOrderByConsensusEndDesc().get();
+        String lastRecordFileHash =
+                applicationStatusRepository.findByStatusCode(ApplicationStatusCode.LAST_PROCESSED_RECORD_HASH);
+
+        // check if latest record file is a match processed file by comparing name and hash
+        if (latestRecordFile.getName().equalsIgnoreCase(recordFile.getName()) &&
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: No longer applicable.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java [hunk 18]
```diff
@@ -160,16 +149,19 @@ public void loadRecordFile(StreamFileData streamFileData) {
...
 
             recordParserLatencyMetric(recordFile);
             success = true;
+        } catch (DuplicateFileException ex) {
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:157]: Removed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java:164]: I think it's more important for SqlEntityListener to have control of the db writes. So I stuck with this and added the hash update to the pubs flow

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 19]
```diff
@@ -241,22 +240,7 @@ public void onTransaction(Transaction transaction) throws ImporterException {
...
-            sqlInsertEntityId.setLong(F_ENTITY_ID.ENTITY_SHARD.ordinal(), entityId.getShardNum());
-            sqlInsertEntityId.setLong(F_ENTITY_ID.ENTITY_REALM.ordinal(), entityId.getRealmNum());
-            sqlInsertEntityId.setLong(F_ENTITY_ID.ENTITY_NUM.ordinal(), entityId.getEntityNum());
-            sqlInsertEntityId.setLong(F_ENTITY_ID.TYPE.ordinal(), entityId.getType());
-            sqlInsertEntityId.addBatch();
-            entityIds.add(entityId);
-        } catch (SQLException e) {
-            throw new ParserSQLException(e);
-        }
+        entityIds.add(entityId);
```
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:240]: Do we want to cache entityRepository.save() as mentioned above?

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 20]
```diff
@@ -151,39 +146,43 @@ public void onStart(StreamFileData streamFileData) {
...
-            cleanup();
-        }
+        cleanup(true, true);
     }
 
-    private void cleanup() {
+    private void cleanup(boolean isRollBackCleanup, boolean releaseConnection) {
+        if (isRollBackCleanup) {
+            // evict entities from cache from this round of batches as they were rolled back
+            entityIds.forEach(entityId -> entityCache.evict(entityId.getId()));
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java]: Good call, missed this. 
Adopted the `TransactionAwareCacheManagerProxy` and yeah with that the `transactionAwareCacheDecorator` is not needed
