### PR TITLE
Fix incorrect staking info and pending reward 

### LINKED ISSUE #4815: Mirrorrnode shows incorrect staking state
### Description

There are some issues in staking related info shown by mirrornode:

1. Some accounts have more pending reward shown by the REST API than it should
2. An account's pending reward stays 0 one full staking period after a staking reward payout is triggered
3. Some accounts started to stake to a node before staking feature went alive in mainnet. services OKed such transactions and ignored the staking info while mirrornode processed the staking info as if the accounts had staked to a node.

### Steps to reproduce

Query the affected account's pending reward and staking state through REST API

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.67.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes incorrect staking info and pending reward updated by mirrornode

- Fix incorrect stake period start after reward payout is triggered
- Use account 800's end_stake_period to check if pending reward calculation is up-to-date
- Recalculate mainnet pending reward in a db migration
- Clear account's staking setting which started to stake to a node before services 0.27.0 went alive

**Related issue(s)**:

Fixes #4815 

**Notes for reviewer**:

Tested the migration w/ latest mainnet / testnet backup

mainnet:

```
2022-11-14T20:23:40.185-0600 INFO main o.f.c.i.c.DbMigrate Current version of schema "public": 1.67.1
2022-11-14T20:23:40.199-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.0 - token account balance"
2022-11-14T20:23:40.262-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.1 - add payer account id"
2022-11-14T20:23:40.508-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.2 - fix stake period start"
2022-11-14T20:23:47.147-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.3 - Fix the staking information for accounts which configured staking before the feature is enabled"
2022-11-14T20:23:50.760-0600 INFO main c.h.m.i.m.FixStakedBeforeEnabledMigration Fixed staking information for 31 MAINNET accounts in 3.603 s
2022-11-14T20:23:50.761-0600 INFO main c.h.m.i.m.FixStakedBeforeEnabledMigration Ran migration Fix the staking information for accounts which configured staking before the feature is enabled in 3.607 s.
2022-11-14T20:23:50.785-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.4 - Recalculate pending reward"
2022-11-14T20:25:10.476-0600 INFO main c.h.m.i.m.RecalculatePendingRewardMigration Recalculated pending reward for 13562 MAINNET entities in 1.328 min
2022-11-14T20:25:10.477-0600 INFO main c.h.m.i.m.RecalculatePendingRewardMigration Ran migration Recalculate pending reward in 1.328 min.
```

testnet:

```
2022-11-14T20:56:51.431-0600 INFO main o.f.c.i.c.DbMigrate Current version of schema "public": 1.67.1
2022-11-14T20:56:51.449-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.0 - token account balance"
2022-11-14T20:56:51.566-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.1 - add payer account id"
2022-11-14T20:56:52.769-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.2 - fix stake period start"
2022-11-14T20:56:53.417-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.3 - Fix the staking information for accounts which configured staking before the feature is enabled"
2022-11-14T20:57:58.796-0600 INFO main c.h.m.i.m.FixStakedBeforeEnabledMigration Fixed staking information for 0 TESTNET accounts in 1.089 min
2022-11-14T20:57:58.797-0600 INFO main c.h.m.i.m.FixStakedBeforeEnabledMigration Ran migration Fix the staking information for accounts which configured staking before the feature is enabled in 1.090 min.
2022-11-14T20:57:58.820-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "1.68.4 - Recalculate pending reward"
2022-11-14T21:02:21.297-0600 INFO main c.h.m.i.m.RecalculatePendingRewardMigration Recalculated pending reward for 3994 TESTNET entities in 4.375 min
2022-11-14T21:02:21.298-0600 INFO main c.h.m.i.m.RecalculatePendingRewardMigration Ran migration Recalculate pending reward in 4.375 min.
```

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandlerTest.java [hunk 1]
```diff
@@ -100,29 +99,6 @@ protected EntityType getExpectedEntityIdType() {
         return EntityType.TOKEN;
     }
 
-    @Test
-    void noTreasuryUpdate() {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionHandlerTest.java:104]: remove test case which no longer applies

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java [hunk 2]
```diff
@@ -33,10 +33,12 @@ public interface EntityStakeRepository extends CrudRepository<EntityStake, Long>
...
               select coalesce((select epoch_day from node_stake order by consensus_timestamp desc limit 1), -1) as epoch_day
             ), entity_stake_info as (
-              select coalesce((select end_stake_period from entity_stake limit 1), -1) as end_stake_period
+              select coalesce((select end_stake_period from entity_stake where id = 800), -1) as end_stake_period
+            ), staking_reward_account as (
+              select (select id from entity where id = 800) as account_id
             )
-            select epoch_day = -1 or epoch_day = end_stake_period
-            from last_epoch_day, entity_stake_info
+            select account_id is null or epoch_day = -1 or epoch_day = end_stake_period
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/EntityStakeRepository.java:40]: account `0.0.800` missing in some preprod envs, so pretend to be `always update` and pending reward calculation will be skipped in those envs.

**Review by edwin-greene — APPROVED** [review]
Looks good to me!

**Review by MarcKriguerAtHedera — DISMISSED** [review]
**Huge** PR, but otherwise LGTM.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 3]
```diff
@@ -387,27 +389,35 @@ private void insertCryptoAddLiveHash(long consensusTimestamp, CryptoAddLiveHashT
...
+                        }
+                    }, () -> {
+                        // The staking reward may be paid to either an account or a contract. Create non-history
+                        // updates with the new stake period start and set the type to account, the upsert sql will
+                        // get the correct entity type from what's in db
+                        var account = accountId.toEntity();
+                        account.setStakePeriodStart(stakePeriodStart);
+                        account.setTimestampRange(null); // Don't trigger a history row
+                        entityListener.onEntity(account);
+                    });
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:420]: I think instead of modifying TransactionHandler we can just do this simple change in SqlEntityListener. It should be equivalent to the current approach and don't need to worry about nodestakeupdate.
```java
    public void onStakingRewardTransfer(StakingRewardTransfer stakingRewardTransfer) {
        stakingRewardTransfers.add(stakingRewardTransfer);

        var entity = entityState.get(stakingRewardTransfer.getAccountId());
        long consensusTimestamp = stakingRewardTransfer.getConsensusTimestamp();

        if (entity != null && entity.getTimestampLower() == consensusTimestamp && entity.getStakePeriodStart() == null) {
            entity.setStakePeriodStart(Utility.getEpochDay(consensusTimestamp) - 1);
        } else if (entity == null) {
            // The staking reward may be paid to either an account or a contract. Create non-history
            // updates with the new stake period start and set the type to account, the upsert sql will
            // get the correct entity type from what's in db
            var account = accountId.toEntity();
            account.setStakePeriodStart(stakePeriodStart);
            account.setTimestampRange(null); // Don't trigger a history row
            onEntity(account);
        }
    }
```

File: hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql [hunk 4]
```diff
@@ -0,0 +1,34 @@
+--- The migration fixes the staking settings for accounts started to stake to a node before mainnet 0.27.x release.
+--- 1658419200981687000 is the consensus end of the last mainnet HAPI 0.26.0 record file
+with mainnet_last_26_file as (
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql:3]: Move to Java migration so we can target mainnet only.

Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql:3]: Why does this SQL need to be repeatable considering it has hardcoded timestamps? And if it can be versioned than can we combine it with other java migration?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java (hunk 3 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:420]: sure. will implement and test it

File: hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql (hunk 4 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql:3]: just in case for some mirrornode deployment which run the migration before ingesting the transactions which config account/contract to stake to a node as of services < 0.27.0. so later can do some trick to rerun the migration.

**Comment by mgoelswirlds** [comment]
Still reviewing.

File: hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql (hunk 4 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql]: I don't think that's a concern. 0.26.0 is really old and any mirror node running should have already processed them or have upgraded to a version with this fix.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigration.java [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+@RequiredArgsConstructor(onConstructor_ = {@Lazy})
+public class RecalculatePendingRewardMigration extends MirrorBaseJavaMigration {
+
+    // Recalculate pending reward since for some staking periods it's accumulated more than one time.
+    // Note 1666310400447390002 is the consensus timestamp of the first node stake update tx after reward is activated
+    private static final String MIGRATION_SQL = """
+            with crypto_transfer as (
+              select *
+              from crypto_transfer
+              where consensus_timestamp > 1666310400447390002
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigration.java:42]: Can't we calculate this from network_stake where staking_reward_rate <> 0 and thus make this sql not specific to any environment? Then can move to .sql file.

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigration.java:42]: suspect there will be huge performance penalty that an index scan on crypto transfer changes to sequential scan, then the migration will run for a couple of hours

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+              update entity_stake
+              set pending_reward = 0,
+                  staked_node_id_start = -1
+              from staked_before_alive, mainnet_last_26_file
+              where id = entity_id
+            )
+            update entity
+            set staked_node_id = -1,
+                stake_period_start = -1
+            from staked_before_alive, mainnet_last_26_file
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java:66]: used to produce no output when there is no such record file in the db

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigration.java (hunk 5 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RecalculatePendingRewardMigration.java:42]: for the same reason, we can't make it generic to any environment per the suggestion.

however, we can probably parameterize the timestamp and hardcode it with values for mainnet and testnet. I just don't see much value of fixing testnet

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+import com.hedera.mirror.importer.MirrorProperties;
+
+@Named
+public class FixMainnetStakedBeforeEnabledMigration extends RepeatableMigration {
+
+    private static final String MIGRATION_SQL = """
+            --- The migration fixes the staking settings for accounts started to stake to a node before mainnet 0.27.x release.
+            --- 1658419200981687000 is the consensus end of the last mainnet HAPI 0.26.0 record file
+            with mainnet_last_26_file as (
+              select index from record_file where consensus_end = 1658419200981687000
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java:37]: it's really slow. not sure how long it'll take since I stopped at 30 minutes. As responded in the other thread, we can hard code the values for mainnet and testnet and keep it as a java migration.

File: hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql (hunk 4 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/resources/db/migration/v1/R__fix_mainnet_staked_before_enabled.sql]: changed it to a versioned non-repeatable Java migration

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java]: added support for testnet with hardcoded consensus end.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+              from entity_history h
+              join possible p on p.id = h.id and p.stake_period_start = h.stake_period_start and p.staked_node_id = h.staked_node_id
+              order by h.id, h.timestamp_range
+            ), staked_before_alive as (
+            --- mainnet 0.27.0 upgraded at round 2022-07-21 16:00:00 UTC, make sure only fix such settings
+            --- set at or before the consensus end of the last HAPI 0.26.0 record file
+              select p.id as entity_id
+              from possible p
+              left join history h on h.id = p.id
+              where coalesce(lower(h.timestamp_range), lower(p.timestamp_range)) <= 1658419200981687000
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java]: changed it to a named parameter

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+    private static final String MIGRATION_SQL = """
+            --- The migration fixes the staking settings for accounts started to stake to a node before mainnet 0.27.x release.
+            --- 1658419200981687000 is the consensus end of the last mainnet HAPI 0.26.0 record file
+            with mainnet_last_26_file as (
+              select index from record_file where consensus_end = 1658419200981687000
+            ), possible as (
+            -- find accounts / contracts whose stake period start is still on or before 2022-07-21 UTC
+              select id,deleted,decline_reward,staked_node_id,stake_period_start,timestamp_range
+              from entity
+              where stake_period_start <= 19194 and stake_period_start <> -1 and staked_node_id <> -1 and type in ('ACCOUNT', 'CONTRACT')
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java]: changed it to a named parameter and the value is calculated in application code from the corresponding consensus timestamp

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java [hunk 10]
```diff
@@ -0,0 +1,95 @@
...
+public class FixMainnetStakedBeforeEnabledMigration extends RepeatableMigration {
+
+    private static final String MIGRATION_SQL = """
+            --- The migration fixes the staking settings for accounts started to stake to a node before mainnet 0.27.x release.
+            --- 1658419200981687000 is the consensus end of the last mainnet HAPI 0.26.0 record file
+            with mainnet_last_26_file as (
+              select index from record_file where consensus_end = 1658419200981687000
+            ), possible as (
+            -- find accounts / contracts whose stake period start is still on or before 2022-07-21 UTC
+              select id,deleted,decline_reward,staked_node_id,stake_period_start,timestamp_range
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java]: removed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java [hunk 11]
```diff
@@ -0,0 +1,95 @@
...
+              left join history h on h.id = p.id
+              where coalesce(lower(h.timestamp_range), lower(p.timestamp_range)) <= 1658419200981687000
+            ), fix_entity_stake as (
+              update entity_stake
+              set pending_reward = 0,
+                  staked_node_id_start = -1
+              from staked_before_alive, mainnet_last_26_file
+              where id = entity_id
+            )
+            update entity
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixMainnetStakedBeforeEnabledMigration.java]: added CTE to also fix `entity_history`

**Review by edwin-greene — APPROVED** [review]
Looks good to me.

**Review by steven-sheehy — APPROVED** [review]
LGTM
