### PR TITLE
Regression on `contract/results/<transactionHash>` address to field as 0x

### LINKED ISSUE #6903: Regression on `contract/results/<transactionHash>` address `to` field as `0x`
### Description

After version `0.89.0-rc1` there is a regression on `contracts/results/<transactionHash>` rest API.

Example on `previewnet` with regression:

https://previewnet.mirrornode.hedera.com/api/v1/contracts/results/0xdd6e0683c742a3fd126ec8d3f8e7e3743e4250e84c6ad5e144d92f885895db32

Notice on the response the field `to` is showing just `0x`

image

Example of a similar transaction (Contract Create on a EVM Transaction) on `testnet`:

https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x521d88048ae1e08e7fe503f16d2a32ffaa6ce4af0d9799a1348f994e8ed15909

image

### Steps to reproduce

Use the provided link:

With regression on `0.89.0-rc1` deployed on `previewnet`

https://previewnet.mirrornode.hedera.com/api/v1/contracts/results/0xdd6e0683c742a3fd126ec8d3f8e7e3743e4250e84c6ad5e144d92f885895db32

Without, on `0.88.0` version on `testnet

https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x521d88048ae1e08e7fe503f16d2a32ffaa6ce4af0d9799a1348f994e8ed15909

Notice that the field `to` does show the `contractAddress` that was created as a result of the transaction.

### Additional context

Preliminary research made by @xin-hedera indicates that the regression was introduced via PR: 
https://github.com/hashgraph/hedera-mirror-node/pull/6827

### Hedera network

previewnet

### Version

v0.89.0-rc1

### Operating system

None

### PR DESCRIPTION
**Pull request by natanasow**
### Description

After version `0.89.0-rc1` there is a regression on `contracts/results/<transactionHash>` rest API.

Example on `previewnet` with regression:

https://previewnet.mirrornode.hedera.com/api/v1/contracts/results/0xdd6e0683c742a3fd126ec8d3f8e7e3743e4250e84c6ad5e144d92f885895db32

Notice on the response the field `to` is showing just `0x`

image

Example of a similar transaction (Contract Create on a EVM Transaction) on `testnet`:

https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x521d88048ae1e08e7fe503f16d2a32ffaa6ce4af0d9799a1348f994e8ed15909

image

### Steps to reproduce

Use the provided link:

With regression on `0.89.0-rc1` deployed on `previewnet`

https://previewnet.mirrornode.hedera.com/api/v1/contracts/results/0xdd6e0683c742a3fd126ec8d3f8e7e3743e4250e84c6ad5e144d92f885895db32

Without, on `0.88.0` version on `testnet

https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x521d88048ae1e08e7fe503f16d2a32ffaa6ce4af0d9799a1348f994e8ed15909

Notice that the field `to` does show the `contractAddress` that was created as a result of the transaction.

### Additional context

Preliminary research made by @xin-hedera indicates that the regression was introduced via PR: 
https://github.com/hashgraph/hedera-mirror-node/pull/6827

### Hedera network

previewnet

### Version

v0.89.0-rc1

**Related issue(s)**:

Fixes #6903 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ class ContractResultDetailsViewModel extends ContractResultViewModel {
       this.nonce = ethTransaction.nonce;
       this.r = utils.toHexStringNonQuantity(ethTransaction.signatureR);
       this.s = utils.toHexStringNonQuantity(ethTransaction.signatureS);
-      this.to = ethTransaction.toAddress ? utils.toHexStringNonQuantity(ethTransaction.toAddress) : null;
+      this.to = utils.toHexStringNonQuantity(ethTransaction.toAddress.length ? ethTransaction.toAddress : contractResult.evmAddress);
```
Comment (xin-hedera) [inline hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js:121]: `ethereum_transaction.to_address` is a nullable column, so should do `ethTransaction.toAddress?.length ?`

In addition, this changes to show evm address found from `entity` table for `contract_result.contract_id` instead of the long form address as in v0.88.0. There are two issues

- Should we change to the long form address, or should we change `ContractResultViewModel` to also show evm address?
- Better to add a check since for partial mirrornode, the contract's evm address may not be available in `entity` table

@Nana-EC @AlfredoG87

Comment (Nana-EC) [reply hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js:121]: Yeah we should add the check noted by Xin.
`ContractResultViewModel` should show evm address if there is one, if not it should show the long address.
This is for consistency for DApps as some users may never encounter the long zero address.

**Review by Nana-EC — APPROVED** [review]

File: hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js [hunk 2]
```diff
@@ -118,7 +118,7 @@ class ContractResultDetailsViewModel extends ContractResultViewModel {
       this.nonce = ethTransaction.nonce;
       this.r = utils.toHexStringNonQuantity(ethTransaction.signatureR);
       this.s = utils.toHexStringNonQuantity(ethTransaction.signatureS);
-      this.to = ethTransaction.toAddress ? utils.toHexStringNonQuantity(ethTransaction.toAddress) : null;
+      this.to = utils.toHexStringNonQuantity(ethTransaction.toAddress?.length ? ethTransaction.toAddress : contractResult.evmAddress);
```
[the remark this answers is not in the document]
Comment (natanasow) [reply hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js:121]: Added.

**Review by Nana-EC — APPROVED** [review]

**Review by AlfredoG87 — APPROVED** [review]
LG 

Thanks for the quick turnaround! 👍

File: hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js]: The `address` field already shows the evm address if available, otherwise falling back to long zero address. With this change `to` will now always be the same as `address` except if `ethereumTransaction.toAddress` is present. That's different from 0.88 plus it would not show the long zero at all. I think we should just do:

```javascript
if (ethTransaction.toAddress) {
  this.to = utils.toHexStringNonQuantity(ethTransaction.toAddress);
}
```

Comment (Nana-EC) [reply hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js]: This can work.
In non `EthereumTransaction` cases the `contractFunctionResult.evmAddress` will only be valid if the transaction creates a contract, otherwise it will be null.
Since `ContractResultViewModel` already sets this.to to the longerAddress we're assured to have a valid address.

**Comment by steven-sheehy** [comment]
Please revert and read comments.

File: hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js (hunk 1 above)
Comment (natanasow) [reply hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js]: Here is the follow-up PR https://github.com/hashgraph/hedera-mirror-node/pull/6916. I have a question but will mention you there.
