### PR TITLE
Fix slowdown finding token transfers in v2

### LINKED ISSUE #8311: Web3 acceptance test failed in testnet-citus
### Description

Some web3 acceptance tests failed in testnet-citus, potentially due to certain SQL query timing out in citus db.

Acceptance tests log:

```
 org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://mirror-web3/api/v1/contracts/call": Read timed out
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.createResourceAccessException(DefaultRestClient.java:557)
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchangeInternal(DefaultRestClient.java:482)
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.retrieve(DefaultRestClient.java:444)
	at com.hedera.mirror.test.e2e.acceptance.client.MirrorNodeClient.lambda$callPostRestEndpoint$4(MirrorNodeClient.java:393)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:335)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211)
	at com.hedera.mirror.test.e2e.acceptance.client.MirrorNodeClient.callPostRestEndpoint(MirrorNodeClient.java:392)
	at com.hedera.mirror.test.e2e.acceptance.client.MirrorNodeClient.contractsCall(MirrorNodeClient.java:270)
	at com.hedera.mirror.test.e2e.acceptance.steps.AbstractFeature.callContract(AbstractFeature.java:179)
	at com.hedera.mirror.test.e2e.acceptance.steps.AbstractFeature.callContract(AbstractFeature.java:175)
	at com.hedera.mirror.test.e2e.acceptance.steps.HistoricalFeature.getHistoricalDataForAllowance(HistoricalFeature.java:463)
	at ✽.I verify historical data for "FUNGIBLEHISTORICAL" is returned for allowance(classpath:features/contract/historical.feature:46)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(Unknown Source)
```

web3 log:

```
2024-05-14T23:24:19.917Z  WARN tomcat-handler-35525 o.h.e.j.s.SqlExceptionHelper SQL Error: 0, SQLState: 57014 
2024-05-14T23:24:19.917Z ERROR tomcat-handler-35525 o.h.e.j.s.SqlExceptionHelper ERROR: canceling statement due to statement timeout 
2024-05-14T23:24:19.918Z  WARN tomcat-handler-35525 c.h.s.s.c.p.HTSPrecompiledContract Internal precompile failure org.springframework.dao.QueryTimeoutException: JDBC exception executing SQL [with token_allowances as (
    select *
    from
    (
        select *, row_number() over (
            partition by token_id, spender
            order by lower(timestamp_range) desc
        ) as row_number
        from
        (
            (
                select *
                from token_allowance
                where owner = ?
                    and lower(timestamp_range) <= ?
            )
            union all
            (
                select *
                from token_allowance_history
                where owner = ?
                    and lower(timestamp_range) <= ?
            )
        ) as all_token_allowances
    ) as grouped_token_allowances
    where row_number = 1 and amount_granted > 0
), transfers as (
    select tt.token_id, tt.payer_account_id, tt.consensus_timestamp, sum(tt.amount) as amount
    from token_transfer tt
        join token_allowances ta on tt.account_id = ta.owner
            and tt.payer_account_id = ta.spender
            and tt.token_id = ta.token_id
    where is_approval is true
        and consensus_timestamp <= ?
        and consensus_timestamp > lower(ta.timestamp_range)
    group by tt.token_id, tt.payer_account_id, tt.consensus_timestamp
), contract_results_filtered as (
    select sender_id, consensus_timestamp
    from contract_result cr
    where cr.consensus_timestamp <= ?
        and cr.consensus_timestamp in (
            select consensus_timestamp
            from token_transfer
        )
), contract_call_transfers as (
    select cr.sender_id, tt.consensus_timestamp, tt.token_id, sum(tt.amount) as amount
    from token_transfer tt
        join token_allowances ta on tt.account_id = ta.owner
            and tt.token_id = ta.token_id,
            contract_results_filtered cr
    where tt.is_approval is true
        and cr.sender_id = ta.spender
        and tt.consensus_timestamp = cr.consensus_timestamp
        and tt.consensus_timestamp <= ?
        and tt.consensus_timestamp > lower(ta.timestamp_range)
    group by cr.sender_id, tt.token_id, tt.consensus_timestamp
)
select *
from (
    select amount_granted, owner, payer_account_id, spender, timestamp_range, token_id, amount_granted + coalesce(
        (
            select sum(amount)
            from contract_call_transfers cct
            where cct.token_id = ta.token_id
                and cct.sender_id = ta.spender
        ),
        0)
        +  coalesce(
        (
            select sum(amount)
            from transfers tr
            where tr.token_id = ta.token_id
                and tr.payer_account_id = ta.spender
                and tr.consensus_timestamp not in (
                    select consensus_timestamp
                    from contract_call_transfers
                )
        ),
        0
    ) as amount
    from token_allowances ta
) result
where amount > 0
] [ERROR: canceling statement due to statement timeout] [n/a]; SQL [n/a]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:280)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:335)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
	at jdk.proxy2/jdk.proxy2.$Proxy222.findByOwnerAndTimestamp(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:216)
	at jdk.proxy2/jdk.proxy2.$Proxy222.findByOwnerAndTimestamp(Unknown Source)
	at com.hedera.mirror.web3.evm.store.accessor.AccountDatabaseAccessor.lambda$getFungibleTokenAllowances$14(AccountDatabaseAccessor.java:166)
	at java.base/java.util.Optional.map(Unknown Source)
	at com.hedera.mirror.web3.evm.store.accessor.AccountDatabaseAccessor.lambda$getFungibleTokenAllowances$17(AccountDatabaseAccessor.java:166)
	at com.hedera.mirror.web3.utils.Suppliers.lambda$memoize$0(Suppliers.java:48)
	at com.hedera.services.store.models.Account.getFungibleTokenAllowances(Account.java:682)
	at com.hedera.mirror.web3.evm.token.TokenAccessorImpl.staticAllowanceOf(TokenAccessorImpl.java:172)
	at com.hedera.services.store.contracts.precompile.impl.AllowancePrecompile.run(AllowancePrecompile.java:78)
	at com.hedera.services.store.contracts.precompile.HTSPrecompiledContract.computeInternal(HTSPrecompiledContract.java:252)
	at com.hedera.services.store.contracts.precompile.HTSPrecompiledContract.computePrecompile(HTSPrecompiledContract.java:200)
	at com.hedera.services.store.contracts.precompile.HTSPrecompiledContract.computeCosted(HTSPrecompiledContract.java:158)
	at com.hedera.mirror.web3.evm.contracts.execution.AbstractEvmMessageCallProcessor.calculatePrecompileGasAndOutput(AbstractEvmMessageCallProcessor.java:64)
	at com.hedera.mirror.web3.evm.contracts.execution.AbstractEvmMessageCallProcessor.executeHederaPrecompile(AbstractEvmMessageCallProcessor.java:50)
	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmMessageCallProcessor.start(HederaEvmMessageCallProcessor.java:62)
	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:196)
	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.process(HederaEvmTxProcessor.java:203)
	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.execute(HederaEvmTxProcessor.java:148)
	at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessorImpl.execute(MirrorEvmTxProcessorImpl.java:105)
	at com.hedera.mirror.web3.service.ContractCallService.doProcessCall(ContractCallService.java:147)
	at com.hedera.mirror.web3.service.ContractCallService.lambda$processCall$0(ContractCallService.java:98)
	at com.hedera.mirror.web3.common.ContractCallContext.lambda$run$0(ContractCallContext.java:55)
	at java.base/java.lang.ScopedValue$Carrier$CallableAdapter.call(Unknown Source)
	at java.base/jdk.internal.vm.ScopedValueContainer.callWithoutScope(Unknown Source)
	at java.base/jdk.internal.vm.ScopedValueContainer.call(Unknown Source)
	at java.base/java.lang.ScopedValue$Carrier.get(Unknown Source)
	at java.base/java.lang.ScopedValue.getWhere(Unknown Source)
	at com.hedera.mirror.web3.common.ContractCallContext.run(ContractCallContext.java:55)
2024-05-14T23:24:19.921Z  WARN tomcat-handler-35525 c.h.m.w.c.ContractController Mirror EVM transaction error: CONTRACT_REVERT_EXECUTED 
2024-05-14T23:24:19.921Z  INFO tomcat-handler-35525 c.h.m.w.c.LoggingFilter 10.4.3.32 POST /api/v1/contracts/call in 10152 ms: 400 
```

### Steps to reproduce

check the description

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.104.0

### Operating system

None

### PR DESCRIPTION
**Pull request by jnels124**
**Description**:
* update query to find approved transfers from contract call

**Related issue(s)**:

Fixes #8311

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by jnels124** [comment]
Query Plan:
```
QUERY PLAN

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------
 Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.443..0.444 rows=9 loops=1)
   ->  Distributed Subplan 1523_1
         Subplan Duration: 4.67 ms
         Intermediate Data Size: 939 bytes
         Result destination: Send to 3 nodes, write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=1.580..1.581 rows=9 loops=1)
               Task Count: 1
               Tuple data received from nodes: 633 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 633 bytes
                     Node: host=10.4.6.5 port=7433 dbname=mirror_node
                     ->  Subquery Scan on grouped_token_allowances  (cost=11.21..11.53 rows=1 width=75) (actual time=0.040..0.048 rows=9 loops=1)
                           Filter: ((grouped_token_allowances.amount_granted > 0) AND (grouped_token_allowances.row_number = 1))
                           Rows Removed by Filter: 1
                           ->  WindowAgg  (cost=11.21..11.41 rows=8 width=83) (actual time=0.039..0.046 rows=10 loops=1)
                                 Run Condition: (row_number() OVER (?) <= 1)
                                 ->  Sort  (cost=11.21..11.23 rows=8 width=75) (actual time=0.035..0.036 rows=13 loops=1)
                                       Sort Key: token_allowance.token_id, token_allowance.spender, (lower(token_allowance.timestamp_range)) DESC
                                       Sort Method: quicksort  Memory: 26kB
                                       ->  Result  (cost=0.28..11.09 rows=8 width=75) (actual time=0.015..0.027 rows=13 loops=1)
                                             ->  Append  (cost=0.28..10.99 rows=8 width=67) (actual time=0.014..0.024 rows=13 loops=1)
                                                   ->  Index Scan using token_allowance__pk_102558 on token_allowance_102558 token_allowance  (cost=0.28..6.28 rows=3 width=62) (actual time=0.014..0.017 rows=9 loops=1)
                                                         Index Cond: (owner = 4366156)
                                                         Filter: (lower(timestamp_range) <= '1715894584220147004'::bigint)
                                                         Rows Removed by Filter: 1
                                                   ->  Index Scan using token_allowance_history__owner_spender_token_lo_8aed322d_102574 on token_allowance_history_102574 token_allowance_history  (cost=0.27..4.66 rows=5 width=70) (actual t
ime=0.005..0.006 rows=4 loops=1)
                                                         Index Cond: ((owner = 4366156) AND (lower(timestamp_range) <= '1715894584220147004'::bigint))
                         Planning Time: 0.133 ms
                         Execution Time: 0.075 ms
         Planning Time: 0.000 ms
         Execution Time: 1.595 ms
   ->  Distributed Subplan 1523_2
         Subplan Duration: 24.60 ms
         Intermediate Data Size: 0 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=56) (actual time=24.931..24.932 rows=0 loops=1)
               Task Count: 16
               Tuple data received from nodes: 0 bytes
               Tasks Shown: One of 16
               ->  Task
                     Tuple data received from node: 0 bytes
                     Node: host=10.4.2.5 port=7433 dbname=mirror_node
                     ->  GroupAggregate  (cost=132.33..132.35 rows=1 width=56) (actual time=0.199..0.203 rows=0 loops=1)
                           Group Key: tt.token_id, tt.payer_account_id, tt.consensus_timestamp
                           ->  Sort  (cost=132.33..132.33 rows=1 width=32) (actual time=0.198..0.202 rows=0 loops=1)
                                 Sort Key: tt.token_id, tt.payer_account_id, tt.consensus_timestamp
                                 Sort Method: quicksort  Memory: 25kB
                                 ->  Nested Loop  (cost=0.15..132.32 rows=1 width=32) (actual time=0.178..0.181 rows=0 loops=1)
                                       ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.32 rows=10 width=56) (actual time=0.124..0.125 rows=9 loops=1)
                                       ->  Append  (cost=0.15..12.08 rows=57 width=40) (actual time=0.004..0.004 rows=0 loops=9)
                                             ->  Index Scan using token_transfer_p2019_09_account_id_consensus_ti_7fb121a0_115678 on token_transfer_p2019_09_115678 tt_1  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2019_10_account_id_consensus_ti_353a78ad_115694 on token_transfer_p2019_10_115694 tt_2  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2019_11_account_id_consensus_ti_c669a8ff_115710 on token_transfer_p2019_11_115710 tt_3  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2019_12_account_id_consensus_ti_d7415d17_115726 on token_transfer_p2019_12_115726 tt_4  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_01_account_id_consensus_ti_157566b2_115742 on token_transfer_p2020_01_115742 tt_5  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_02_account_id_consensus_ti_fc8c3fcb_115758 on token_transfer_p2020_02_115758 tt_6  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_03_account_id_consensus_ti_dfdf51e1_115774 on token_transfer_p2020_03_115774 tt_7  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_04_account_id_consensus_ti_06b4511c_115790 on token_transfer_p2020_04_115790 tt_8  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_05_account_id_consensus_ti_48f32066_115806 on token_transfer_p2020_05_115806 tt_9  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_06_account_id_consensus_ti_3a76f946_115822 on token_transfer_p2020_06_115822 tt_10  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_07_account_id_consensus_ti_11c08448_115838 on token_transfer_p2020_07_115838 tt_11  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_08_account_id_consensus_ti_3c561931_115854 on token_transfer_p2020_08_115854 tt_12  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_09_account_id_consensus_ti_d75dcbd7_115870 on token_transfer_p2020_09_115870 tt_13  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_10_account_id_consensus_ti_857849f4_115886 on token_transfer_p2020_10_115886 tt_14  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_11_account_id_consensus_ti_453aeea4_115902 on token_transfer_p2020_11_115902 tt_15  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2020_12_account_id_consensus_ti_4de3d6bc_115918 on token_transfer_p2020_12_115918 tt_16  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_01_account_id_consensus_ti_0d0a487a_115934 on token_transfer_p2021_01_115934 tt_17  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_02_account_id_consensus_ti_c561c754_115950 on token_transfer_p2021_02_115950 tt_18  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_03_account_id_consensus_ti_a50c7c9a_115966 on token_transfer_p2021_03_115966 tt_19  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_04_account_id_consensus_ti_94f10664_115982 on token_transfer_p2021_04_115982 tt_20  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_05_account_id_consensus_ti_9852ba3e_115998 on token_transfer_p2021_05_115998 tt_21  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_06_account_id_consensus_ti_a23c666e_116014 on token_transfer_p2021_06_116014 tt_22  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_07_account_id_consensus_ti_c6e73a64_116030 on token_transfer_p2021_07_116030 tt_23  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_08_account_id_consensus_ti_1de2f253_116046 on token_transfer_p2021_08_116046 tt_24  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_09_account_id_consensus_ti_26e50a7f_116062 on token_transfer_p2021_09_116062 tt_25  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_10_account_id_consensus_ti_1571d58f_116078 on token_transfer_p2021_10_116078 tt_26  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_11_account_id_consensus_ti_999e5599_116094 on token_transfer_p2021_11_116094 tt_27  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2021_12_account_id_consensus_ti_44a37199_116110 on token_transfer_p2021_12_116110 tt_28  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_01_account_id_consensus_ti_a040e27a_116126 on token_transfer_p2022_01_116126 tt_29  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_02_account_id_consensus_ti_8e8bb57c_116142 on token_transfer_p2022_02_116142 tt_30  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_03_account_id_consensus_ti_d8826093_116158 on token_transfer_p2022_03_116158 tt_31  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_04_account_id_consensus_ti_b07e156c_116174 on token_transfer_p2022_04_116174 tt_32  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_05_account_id_consensus_ti_7ca3ca7f_116190 on token_transfer_p2022_05_116190 tt_33  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_06_account_id_consensus_ti_405511ef_116206 on token_transfer_p2022_06_116206 tt_34  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_07_account_id_consensus_ti_326275ca_116222 on token_transfer_p2022_07_116222 tt_35  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_08_account_id_consensus_ti_0111f90b_116238 on token_transfer_p2022_08_116238 tt_36  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_09_account_id_consensus_ti_c995cc32_116254 on token_transfer_p2022_09_116254 tt_37  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_10_account_id_consensus_ti_719e37a4_116270 on token_transfer_p2022_10_116270 tt_38  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_11_account_id_consensus_ti_838206da_116286 on token_transfer_p2022_11_116286 tt_39  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2022_12_account_id_consensus_ti_a9ad5c6e_116302 on token_transfer_p2022_12_116302 tt_40  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_01_account_id_consensus_ti_9b743fc1_116318 on token_transfer_p2023_01_116318 tt_41  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_02_account_id_consensus_ti_37c0350e_116334 on token_transfer_p2023_02_116334 tt_42  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_03_account_id_consensus_ti_6c664759_116350 on token_transfer_p2023_03_116350 tt_43  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_04_account_id_consensus_ti_c721e186_116366 on token_transfer_p2023_04_116366 tt_44  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_05_account_id_consensus_ti_c1330533_116382 on token_transfer_p2023_05_116382 tt_45  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_06_account_id_consensus_ti_9250afda_116398 on token_transfer_p2023_06_116398 tt_46  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_07_account_id_consensus_ti_c57f2123_116414 on token_transfer_p2023_07_116414 tt_47  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_08_account_id_consensus_ti_b542258d_116430 on token_transfer_p2023_08_116430 tt_48  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_09_account_id_consensus_ti_b942321c_116446 on token_transfer_p2023_09_116446 tt_49  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_10_account_id_consensus_ti_48e7c55d_116462 on token_transfer_p2023_10_116462 tt_50  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_11_account_id_consensus_ti_8dcc989d_116478 on token_transfer_p2023_11_116478 tt_51  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2023_12_account_id_consensus_ti_d3638243_116494 on token_transfer_p2023_12_116494 tt_52  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2024_01_account_id_consensus_ti_392c8300_116510 on token_transfer_p2024_01_116510 tt_53  (cost=0.15..0.19 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2024_02_account_id_consensus_ti_c35b6686_116526 on token_transfer_p2024_02_116526 tt_54  (cost=0.29..0.45 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2024_03_account_id_consensus_ti_da5a82c3_116542 on token_transfer_p2024_03_116542 tt_55  (cost=0.28..0.35 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2024_04_account_id_consensus_ti_0c1191c8_116558 on token_transfer_p2024_04_116558 tt_56  (cost=0.28..0.33 rows=1 width=40) (never executed)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                                             ->  Index Scan using token_transfer_p2024_05_account_id_consensus_ti_0ebff295_116574 on token_transfer_p2024_05_116574 tt_57  (cost=0.28..0.35 rows=1 width=40) (actual time=0.002..0.002 rows=0
loops=9)
                                                   Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                                   Filter: ((is_approval IS TRUE) AND (intermediate_result.spender = payer_account_id) AND (intermediate_result.token_id = token_id))
                         Planning Time: 3.686 ms
                         Execution Time: 0.766 ms
         Planning Time: 0.000 ms
         Execution Time: 24.967 ms
   ->  Distributed Subplan 1523_3
         Subplan Duration: 14.96 ms
         Intermediate Data Size: 310 bytes
         Result destination: Send to 3 nodes, write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=40) (actual time=16.228..16.230 rows=5 loops=1)
               Task Count: 16
               Tuple data received from nodes: 200 bytes
               Tasks Shown: One of 16
               ->  Task
                     Tuple data received from node: 0 bytes
                     Node: host=10.4.2.5 port=7433 dbname=mirror_node
                     ->  Nested Loop  (cost=0.15..147.41 rows=101 width=40) (actual time=0.140..0.143 rows=0 loops=1)
                           ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.32 rows=10 width=56) (actual time=0.089..0.090 rows=9 loops=1)
                           ->  Append  (cost=0.15..13.53 rows=57 width=32) (actual time=0.004..0.004 rows=0 loops=9)
                                 ->  Index Scan using token_transfer_p2019_09_account_id_consensus_ti_7fb121a0_115684 on token_transfer_p2019_09_115684 tt_1  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2019_10_account_id_consensus_ti_353a78ad_115700 on token_transfer_p2019_10_115700 tt_2  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2019_11_account_id_consensus_ti_c669a8ff_115716 on token_transfer_p2019_11_115716 tt_3  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2019_12_account_id_consensus_ti_d7415d17_115732 on token_transfer_p2019_12_115732 tt_4  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_01_account_id_consensus_ti_157566b2_115748 on token_transfer_p2020_01_115748 tt_5  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_02_account_id_consensus_ti_fc8c3fcb_115764 on token_transfer_p2020_02_115764 tt_6  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_03_account_id_consensus_ti_dfdf51e1_115780 on token_transfer_p2020_03_115780 tt_7  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_04_account_id_consensus_ti_06b4511c_115796 on token_transfer_p2020_04_115796 tt_8  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_05_account_id_consensus_ti_48f32066_115812 on token_transfer_p2020_05_115812 tt_9  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_06_account_id_consensus_ti_3a76f946_115828 on token_transfer_p2020_06_115828 tt_10  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_07_account_id_consensus_ti_11c08448_115844 on token_transfer_p2020_07_115844 tt_11  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_08_account_id_consensus_ti_3c561931_115860 on token_transfer_p2020_08_115860 tt_12  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_09_account_id_consensus_ti_d75dcbd7_115876 on token_transfer_p2020_09_115876 tt_13  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_10_account_id_consensus_ti_857849f4_115892 on token_transfer_p2020_10_115892 tt_14  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_11_account_id_consensus_ti_453aeea4_115908 on token_transfer_p2020_11_115908 tt_15  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2020_12_account_id_consensus_ti_4de3d6bc_115924 on token_transfer_p2020_12_115924 tt_16  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_01_account_id_consensus_ti_0d0a487a_115940 on token_transfer_p2021_01_115940 tt_17  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_02_account_id_consensus_ti_c561c754_115956 on token_transfer_p2021_02_115956 tt_18  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_03_account_id_consensus_ti_a50c7c9a_115972 on token_transfer_p2021_03_115972 tt_19  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_04_account_id_consensus_ti_94f10664_115988 on token_transfer_p2021_04_115988 tt_20  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_05_account_id_consensus_ti_9852ba3e_116004 on token_transfer_p2021_05_116004 tt_21  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_06_account_id_consensus_ti_a23c666e_116020 on token_transfer_p2021_06_116020 tt_22  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_07_account_id_consensus_ti_c6e73a64_116036 on token_transfer_p2021_07_116036 tt_23  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_08_account_id_consensus_ti_1de2f253_116052 on token_transfer_p2021_08_116052 tt_24  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_09_account_id_consensus_ti_26e50a7f_116068 on token_transfer_p2021_09_116068 tt_25  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_10_account_id_consensus_ti_1571d58f_116084 on token_transfer_p2021_10_116084 tt_26  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_11_account_id_consensus_ti_999e5599_116100 on token_transfer_p2021_11_116100 tt_27  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2021_12_account_id_consensus_ti_44a37199_116116 on token_transfer_p2021_12_116116 tt_28  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_01_account_id_consensus_ti_a040e27a_116132 on token_transfer_p2022_01_116132 tt_29  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_02_account_id_consensus_ti_8e8bb57c_116148 on token_transfer_p2022_02_116148 tt_30  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_03_account_id_consensus_ti_d8826093_116164 on token_transfer_p2022_03_116164 tt_31  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_04_account_id_consensus_ti_b07e156c_116180 on token_transfer_p2022_04_116180 tt_32  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_05_account_id_consensus_ti_7ca3ca7f_116196 on token_transfer_p2022_05_116196 tt_33  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_06_account_id_consensus_ti_405511ef_116212 on token_transfer_p2022_06_116212 tt_34  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_07_account_id_consensus_ti_326275ca_116228 on token_transfer_p2022_07_116228 tt_35  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_08_account_id_consensus_ti_0111f90b_116244 on token_transfer_p2022_08_116244 tt_36  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_09_account_id_consensus_ti_c995cc32_116260 on token_transfer_p2022_09_116260 tt_37  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_10_account_id_consensus_ti_719e37a4_116276 on token_transfer_p2022_10_116276 tt_38  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_11_account_id_consensus_ti_838206da_116292 on token_transfer_p2022_11_116292 tt_39  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2022_12_account_id_consensus_ti_a9ad5c6e_116308 on token_transfer_p2022_12_116308 tt_40  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_01_account_id_consensus_ti_9b743fc1_116324 on token_transfer_p2023_01_116324 tt_41  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_02_account_id_consensus_ti_37c0350e_116340 on token_transfer_p2023_02_116340 tt_42  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_03_account_id_consensus_ti_6c664759_116356 on token_transfer_p2023_03_116356 tt_43  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_04_account_id_consensus_ti_c721e186_116372 on token_transfer_p2023_04_116372 tt_44  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_05_account_id_consensus_ti_c1330533_116388 on token_transfer_p2023_05_116388 tt_45  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_06_account_id_consensus_ti_9250afda_116404 on token_transfer_p2023_06_116404 tt_46  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_07_account_id_consensus_ti_c57f2123_116420 on token_transfer_p2023_07_116420 tt_47  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_08_account_id_consensus_ti_b542258d_116436 on token_transfer_p2023_08_116436 tt_48  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_09_account_id_consensus_ti_b942321c_116452 on token_transfer_p2023_09_116452 tt_49  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_10_account_id_consensus_ti_48e7c55d_116468 on token_transfer_p2023_10_116468 tt_50  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_11_account_id_consensus_ti_8dcc989d_116484 on token_transfer_p2023_11_116484 tt_51  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2023_12_account_id_consensus_ti_d3638243_116500 on token_transfer_p2023_12_116500 tt_52  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2024_01_account_id_consensus_ti_392c8300_116516 on token_transfer_p2024_01_116516 tt_53  (cost=0.15..0.19 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2024_02_account_id_consensus_ti_c35b6686_116532 on token_transfer_p2024_02_116532 tt_54  (cost=0.29..1.12 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2024_03_account_id_consensus_ti_da5a82c3_116548 on token_transfer_p2024_03_116548 tt_55  (cost=0.29..0.62 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2024_04_account_id_consensus_ti_0c1191c8_116564 on token_transfer_p2024_04_116564 tt_56  (cost=0.29..0.68 rows=1 width=32) (never executed)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                 ->  Index Scan using token_transfer_p2024_05_account_id_consensus_ti_0ebff295_116580 on token_transfer_p2024_05_116580 tt_57  (cost=0.29..0.64 rows=1 width=32) (actual time=0.003..0.003 rows=0 loops=9)
                                       Index Cond: ((account_id = intermediate_result.owner) AND (consensus_timestamp > lower(intermediate_result.timestamp_range)) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                       Filter: ((is_approval IS TRUE) AND (intermediate_result.token_id = token_id))
                                       Rows Removed by Filter: 0
                         Planning Time: 2.659 ms
                         Execution Time: 0.611 ms
         Planning Time: 0.000 ms
         Execution Time: 16.273 ms
   ->  Distributed Subplan 1523_4
         Subplan Duration: 37.51 ms
         Intermediate Data Size: 26 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=16) (actual time=29.771..29.772 rows=1 loops=1)
               Task Count: 16
               Tuple data received from nodes: 16 bytes
               Tasks Shown: One of 16
               ->  Task
                     Tuple data received from node: 16 bytes
                     Node: host=10.4.2.5 port=7433 dbname=mirror_node
                     ->  Hash Join  (cost=0.99..140.76 rows=24211 width=16) (actual time=0.182..0.187 rows=1 loops=1)
                           Hash Cond: (cr.sender_id = intermediate_result.spender)
                           ->  Nested Loop  (cost=0.14..110.30 rows=4842 width=24) (actual time=0.120..0.125 rows=1 loops=1)
                                 ->  Function Scan on read_intermediate_result intermediate_result_1  (cost=0.00..0.14 rows=8 width=16) (actual time=0.063..0.063 rows=5 loops=1)
                                 ->  Append  (cost=0.14..12.93 rows=57 width=16) (actual time=0.009..0.010 rows=0 loops=5)
                                       ->  Index Only Scan using contract_result_p2019_09_sender_id_consensus_ti_9ff8b9da_106395 on contract_result_p2019_09_106395 cr_1  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2019_10_sender_id_consensus_ti_13af3bcd_106411 on contract_result_p2019_10_106411 cr_2  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2019_11_sender_id_consensus_ti_af87a5fe_106427 on contract_result_p2019_11_106427 cr_3  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2019_12_sender_id_consensus_ti_4be22cd4_106443 on contract_result_p2019_12_106443 cr_4  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_01_sender_id_consensus_ti_c5d6a2e9_106459 on contract_result_p2020_01_106459 cr_5  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_02_sender_id_consensus_ti_2132d340_106475 on contract_result_p2020_02_106475 cr_6  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_03_sender_id_consensus_ti_6f776bd2_106491 on contract_result_p2020_03_106491 cr_7  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_04_sender_id_consensus_ti_3c7e1d02_106507 on contract_result_p2020_04_106507 cr_8  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_05_sender_id_consensus_ti_6ef68f3d_106523 on contract_result_p2020_05_106523 cr_9  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_06_sender_id_consensus_ti_33f02736_106539 on contract_result_p2020_06_106539 cr_10  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_07_sender_id_consensus_ti_e870b5ce_106555 on contract_result_p2020_07_106555 cr_11  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_08_sender_id_consensus_ti_c4a69df3_106571 on contract_result_p2020_08_106571 cr_12  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_09_sender_id_consensus_ti_f857853d_106587 on contract_result_p2020_09_106587 cr_13  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_10_sender_id_consensus_ti_ea835012_106603 on contract_result_p2020_10_106603 cr_14  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_11_sender_id_consensus_ti_167521d1_106619 on contract_result_p2020_11_106619 cr_15  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2020_12_sender_id_consensus_ti_446148c7_106635 on contract_result_p2020_12_106635 cr_16  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_01_sender_id_consensus_ti_77d0bab6_106651 on contract_result_p2021_01_106651 cr_17  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_02_sender_id_consensus_ti_ceafca4b_106667 on contract_result_p2021_02_106667 cr_18  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_03_sender_id_consensus_ti_b74189ca_106683 on contract_result_p2021_03_106683 cr_19  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_04_sender_id_consensus_ti_4579d88b_106699 on contract_result_p2021_04_106699 cr_20  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_05_sender_id_consensus_ti_89661cea_106715 on contract_result_p2021_05_106715 cr_21  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_06_sender_id_consensus_ti_e46ad98f_106731 on contract_result_p2021_06_106731 cr_22  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_07_sender_id_consensus_ti_e54a5eba_106747 on contract_result_p2021_07_106747 cr_23  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_08_sender_id_consensus_ti_080301cd_106763 on contract_result_p2021_08_106763 cr_24  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_09_sender_id_consensus_ti_cf92e21d_106779 on contract_result_p2021_09_106779 cr_25  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_10_sender_id_consensus_ti_f01c5f4c_106795 on contract_result_p2021_10_106795 cr_26  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_11_sender_id_consensus_ti_625e4554_106811 on contract_result_p2021_11_106811 cr_27  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2021_12_sender_id_consensus_ti_e09296ed_106827 on contract_result_p2021_12_106827 cr_28  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_01_sender_id_consensus_ti_68248721_106843 on contract_result_p2022_01_106843 cr_29  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_02_sender_id_consensus_ti_5c729500_106859 on contract_result_p2022_02_106859 cr_30  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_03_sender_id_consensus_ti_ec751f23_106875 on contract_result_p2022_03_106875 cr_31  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_04_sender_id_consensus_ti_d6a174a0_106891 on contract_result_p2022_04_106891 cr_32  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_05_sender_id_consensus_ti_7ab7bee2_106907 on contract_result_p2022_05_106907 cr_33  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_06_sender_id_consensus_ti_07a826cc_106923 on contract_result_p2022_06_106923 cr_34  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_07_sender_id_consensus_ti_cf300309_106939 on contract_result_p2022_07_106939 cr_35  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_08_sender_id_consensus_ti_acf9b4a6_106955 on contract_result_p2022_08_106955 cr_36  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_09_sender_id_consensus_ti_2e69f4f5_106971 on contract_result_p2022_09_106971 cr_37  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_10_sender_id_consensus_ti_a3435f76_106987 on contract_result_p2022_10_106987 cr_38  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_11_sender_id_consensus_ti_9e611152_107003 on contract_result_p2022_11_107003 cr_39  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2022_12_sender_id_consensus_ti_2f29adc5_107019 on contract_result_p2022_12_107019 cr_40  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_01_sender_id_consensus_ti_18caa055_107035 on contract_result_p2023_01_107035 cr_41  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_02_sender_id_consensus_ti_0be9a175_107051 on contract_result_p2023_02_107051 cr_42  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_03_sender_id_consensus_ti_5b2b011e_107067 on contract_result_p2023_03_107067 cr_43  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_04_sender_id_consensus_ti_92bd7fe6_107083 on contract_result_p2023_04_107083 cr_44  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_05_sender_id_consensus_ti_8449f19e_107099 on contract_result_p2023_05_107099 cr_45  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_06_sender_id_consensus_ti_98e6b6c7_107115 on contract_result_p2023_06_107115 cr_46  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_07_sender_id_consensus_ti_59f82ff7_107131 on contract_result_p2023_07_107131 cr_47  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_08_sender_id_consensus_ti_7a4f8562_107147 on contract_result_p2023_08_107147 cr_48  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_09_sender_id_consensus_ti_d62701a8_107163 on contract_result_p2023_09_107163 cr_49  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_10_sender_id_consensus_ti_b5b11c58_107179 on contract_result_p2023_10_107179 cr_50  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_11_sender_id_consensus_ti_e379893e_107195 on contract_result_p2023_11_107195 cr_51  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2023_12_sender_id_consensus_ti_350039c4_107211 on contract_result_p2023_12_107211 cr_52  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2024_01_sender_id_consensus_ti_00a5fd30_107227 on contract_result_p2024_01_107227 cr_53  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2024_02_sender_id_consensus_ti_e7f7e511_107243 on contract_result_p2024_02_107243 cr_54  (cost=0.42..0.87 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2024_03_sender_id_consensus_ti_a53d06c2_107259 on contract_result_p2024_03_107259 cr_55  (cost=0.29..0.58 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2024_04_sender_id_consensus_ti_082240cb_107275 on contract_result_p2024_04_107275 cr_56  (cost=0.29..0.64 rows=1 width=16) (never executed)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 0
                                       ->  Index Only Scan using contract_result_p2024_05_sender_id_consensus_ti_be6fd63a_107291 on contract_result_p2024_05_107291 cr_57  (cost=0.29..1.03 rows=1 width=16) (actual time=0.008..0.008 rows=0
loops=5)
                                             Index Cond: ((sender_id = intermediate_result_1.spender) AND (consensus_timestamp = intermediate_result_1.consensus_timestamp) AND (consensus_timestamp <= '1715894584220147004'::bigint))
                                             Heap Fetches: 1
                           ->  Hash  (cost=0.56..0.56 rows=22 width=8) (actual time=0.052..0.053 rows=9 loops=1)
                                 Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                 ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.56 rows=22 width=8) (actual time=0.046..0.047 rows=9 loops=1)
                         Planning Time: 5.010 ms
                         Execution Time: 0.586 ms
         Planning Time: 0.000 ms
         Execution Time: 29.819 ms
   ->  Distributed Subplan 1523_5
         Subplan Duration: 0.95 ms
         Intermediate Data Size: 52 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.858..0.858 rows=1 loops=1)
               Task Count: 1
               Tuple data received from nodes: 34 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 34 bytes
                     Node: host=/var/run/postgresql port=5432 dbname=mirror_node
                     ->  HashAggregate  (cost=0.44..0.75 rows=25 width=56) (actual time=0.115..0.116 rows=1 loops=1)
                           Group Key: intermediate_result_1.sender_id, intermediate_result.token_id, intermediate_result.consensus_timestamp
                           Batches: 1  Memory Usage: 24kB
                           ->  Hash Join  (cost=0.02..0.19 rows=25 width=32) (actual time=0.110..0.111 rows=1 loops=1)
                                 Hash Cond: ((intermediate_result.spender = intermediate_result_1.sender_id) AND (intermediate_result.consensus_timestamp = intermediate_result_1.consensus_timestamp))
                                 ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.11 rows=6 width=32) (actual time=0.051..0.052 rows=5 loops=1)
                                 ->  Hash  (cost=0.01..0.01 rows=1 width=16) (actual time=0.032..0.033 rows=1 loops=1)
                                       Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                       ->  Function Scan on read_intermediate_result intermediate_result_1  (cost=0.00..0.01 rows=1 width=16) (actual time=0.029..0.030 rows=1 loops=1)
                         Planning Time: 0.105 ms
                         Execution Time: 0.152 ms
         Planning Time: 0.000 ms
         Execution Time: 0.872 ms
   ->  Distributed Subplan 1523_6
         Subplan Duration: 0.77 ms
         Intermediate Data Size: 849 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.773..0.773 rows=9 loops=1)
               Task Count: 1
               Tuple data received from nodes: 579 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 579 bytes
                     Node: host=/var/run/postgresql port=5432 dbname=mirror_node
                     ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.97 rows=9 width=104) (actual time=0.095..0.109 rows=9 loops=1)
                           SubPlan 1
                             ->  Aggregate  (cost=0.03..0.04 rows=1 width=32) (actual time=0.003..0.003 rows=1 loops=9)
                                   ->  Function Scan on read_intermediate_result intermediate_result_1  (cost=0.00..0.02 rows=1 width=32) (actual time=0.003..0.003 rows=0 loops=9)
                                         Filter: ((token_id = intermediate_result.token_id) AND (sender_id = intermediate_result.spender))
                                         Rows Removed by Filter: 1
                           SubPlan 3
                             ->  Aggregate  (cost=0.02..0.03 rows=1 width=32) (actual time=0.002..0.002 rows=1 loops=9)
                                   ->  Function Scan on read_intermediate_result intermediate_result_3  (cost=0.03..0.02 rows=1 width=32) (actual time=0.002..0.002 rows=0 loops=9)
                                         Filter: ((NOT (hashed SubPlan 2)) AND (token_id = intermediate_result.token_id) AND (payer_account_id = intermediate_result.spender))
                                         SubPlan 2
                                           ->  Function Scan on read_intermediate_result intermediate_result_2  (cost=0.00..0.03 rows=2 width=8) (never executed)
                         Planning Time: 0.129 ms
                         Execution Time: 0.149 ms
         Planning Time: 0.000 ms
         Execution Time: 0.782 ms
   Task Count: 1
   Tuple data received from nodes: 579 bytes
   Tasks Shown: All
   ->  Task
         Tuple data received from node: 579 bytes
         Node: host=/var/run/postgresql port=5432 dbname=mirror_node
         ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.23 rows=6 width=104) (actual time=0.030..0.032 rows=9 loops=1)
               Filter: (amount > '0'::numeric)
             Planning Time: 0.025 ms
             Execution Time: 0.040 ms
 Planning Time: 6.307 ms
 Execution Time: 84.049 ms
```

**Comment by jnels124** [comment]
This is a difficult query to optimize further. We need to find all token_transfers for a given owner on an allowance to determine if the transfer was part of a contract call. Given the low volume of these we could potentially optimize further by writing  a new table to the db `contract_call_approved_transfer(consensus_timestamp, owner, sender, token_id, contract_id)`. Need to determine best way to distribute if we go that route but this lookup table could give us the keys we need to lookup contract results, and token transfers much easier. However not sure the overall gain of doing so when weighing usage and performance gains with the update in this PR.

**Comment by jnels124** [comment]
QUERY PLAN

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------
 Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.750..0.750 rows=9 loops=1)
   ->  Distributed Subplan 1581_1
         Subplan Duration: 1.57 ms
         Intermediate Data Size: 939 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=1.768..1.769 rows=9 loops=1)
               Task Count: 1
               Tuple data received from nodes: 633 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 633 bytes
                     Node: host=10.4.6.5 port=7433 dbname=mirror_node
                     ->  Subquery Scan on grouped_token_allowances  (cost=11.21..11.53 rows=1 width=75) (actual time=0.033..0.041 rows=9 loops=1)
                           Filter: ((grouped_token_allowances.amount_granted > 0) AND (grouped_token_allowances.row_number = 1))
                           Rows Removed by Filter: 1
                           ->  WindowAgg  (cost=11.21..11.41 rows=8 width=83) (actual time=0.032..0.039 rows=10 loops=1)
                                 Run Condition: (row_number() OVER (?) <= 1)
                                 ->  Sort  (cost=11.21..11.23 rows=8 width=75) (actual time=0.029..0.030 rows=13 loops=1)
                                       Sort Key: token_allowance.token_id, token_allowance.spender, (lower(token_allowance.timestamp_range)) DESC
                                       Sort Method: quicksort  Memory: 26kB
                                       ->  Result  (cost=0.28..11.09 rows=8 width=75) (actual time=0.010..0.021 rows=13 loops=1)
                                             ->  Append  (cost=0.28..10.99 rows=8 width=67) (actual time=0.009..0.018 rows=13 loops=1)
                                                   ->  Index Scan using token_allowance__pk_102558 on token_allowance_102558 token_allowance  (cost=0.28..6.28 rows=3 width=62) (actual time=0.009..0.012 rows=9 loops=1)
                                                         Index Cond: (owner = 4366156)
                                                         Filter: (lower(timestamp_range) <= '1715894584220147004'::bigint)
                                                         Rows Removed by Filter: 1
                                                   ->  Index Scan using token_allowance_history__owner_spender_token_lo_8aed322d_102574 on token_allowance_history_102574 token_allowance_history  (cost=0.27..4.66 rows=5 width=70) (actual t
ime=0.004..0.005 rows=4 loops=1)
                                                         Index Cond: ((owner = 4366156) AND (lower(timestamp_range) <= '1715894584220147004'::bigint))
                         Planning Time: 0.118 ms
                         Execution Time: 0.067 ms
         Planning Time: 0.000 ms
         Execution Time: 1.783 ms
   ->  Distributed Subplan 1581_2
         Subplan Duration: 42.64 ms
         Intermediate Data Size: 124 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=40) (actual time=12.530..12.531 rows=2 loops=1)
               ->  Distributed Subplan 1583_1
                     Subplan Duration: 2.33 ms
                     Intermediate Data Size: 14 bytes
                     Result destination: Send to 3 nodes
                     ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.671..0.672 rows=1 loops=1)
                           Task Count: 1
                           Tuple data received from nodes: 8 bytes
                           Tasks Shown: All
                           ->  Task
                                 Tuple data received from node: 8 bytes
                                 Node: host=/var/run/postgresql port=5432 dbname=mirror_node
                                 ->  Aggregate  (cost=0.47..0.48 rows=1 width=8) (actual time=0.057..0.058 rows=1 loops=1)
                                       ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.40 rows=14 width=32) (actual time=0.050..0.051 rows=9 loops=1)
                                     Planning Time: 0.038 ms
                                     Execution Time: 0.083 ms
                     Planning Time: 0.000 ms
                     Execution Time: 0.686 ms
               Task Count: 16
               Tuple data received from nodes: 80 bytes
               Tasks Shown: One of 16
               ->  Task
                     Tuple data received from node: 0 bytes
                     Node: host=10.4.2.5 port=7433 dbname=mirror_node
                     ->  Append  (cost=0.16..136.32 rows=57 width=40) (actual time=0.131..0.134 rows=0 loops=1)
                           InitPlan 1 (returns $0)
                             ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.00 rows=1 width=8) (actual time=0.106..0.107 rows=1 loops=1)
                           ->  Index Scan using token_transfer_p2019_09_account_id_consensus_ti_7fb121a0_115675 on token_transfer_p2019_09_115675 tt_1  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2019_10_account_id_consensus_ti_353a78ad_115691 on token_transfer_p2019_10_115691 tt_2  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2019_11_account_id_consensus_ti_c669a8ff_115707 on token_transfer_p2019_11_115707 tt_3  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2019_12_account_id_consensus_ti_d7415d17_115723 on token_transfer_p2019_12_115723 tt_4  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_01_account_id_consensus_ti_157566b2_115739 on token_transfer_p2020_01_115739 tt_5  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_02_account_id_consensus_ti_fc8c3fcb_115755 on token_transfer_p2020_02_115755 tt_6  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_03_account_id_consensus_ti_dfdf51e1_115771 on token_transfer_p2020_03_115771 tt_7  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_04_account_id_consensus_ti_06b4511c_115787 on token_transfer_p2020_04_115787 tt_8  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_05_account_id_consensus_ti_48f32066_115803 on token_transfer_p2020_05_115803 tt_9  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_06_account_id_consensus_ti_3a76f946_115819 on token_transfer_p2020_06_115819 tt_10  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_07_account_id_consensus_ti_11c08448_115835 on token_transfer_p2020_07_115835 tt_11  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_08_account_id_consensus_ti_3c561931_115851 on token_transfer_p2020_08_115851 tt_12  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_09_account_id_consensus_ti_d75dcbd7_115867 on token_transfer_p2020_09_115867 tt_13  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_10_account_id_consensus_ti_857849f4_115883 on token_transfer_p2020_10_115883 tt_14  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_11_account_id_consensus_ti_453aeea4_115899 on token_transfer_p2020_11_115899 tt_15  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2020_12_account_id_consensus_ti_4de3d6bc_115915 on token_transfer_p2020_12_115915 tt_16  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_01_account_id_consensus_ti_0d0a487a_115931 on token_transfer_p2021_01_115931 tt_17  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_02_account_id_consensus_ti_c561c754_115947 on token_transfer_p2021_02_115947 tt_18  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_03_account_id_consensus_ti_a50c7c9a_115963 on token_transfer_p2021_03_115963 tt_19  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_04_account_id_consensus_ti_94f10664_115979 on token_transfer_p2021_04_115979 tt_20  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_05_account_id_consensus_ti_9852ba3e_115995 on token_transfer_p2021_05_115995 tt_21  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_06_account_id_consensus_ti_a23c666e_116011 on token_transfer_p2021_06_116011 tt_22  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_07_account_id_consensus_ti_c6e73a64_116027 on token_transfer_p2021_07_116027 tt_23  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_08_account_id_consensus_ti_1de2f253_116043 on token_transfer_p2021_08_116043 tt_24  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_09_account_id_consensus_ti_26e50a7f_116059 on token_transfer_p2021_09_116059 tt_25  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_10_account_id_consensus_ti_1571d58f_116075 on token_transfer_p2021_10_116075 tt_26  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_11_account_id_consensus_ti_999e5599_116091 on token_transfer_p2021_11_116091 tt_27  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2021_12_account_id_consensus_ti_44a37199_116107 on token_transfer_p2021_12_116107 tt_28  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_01_account_id_consensus_ti_a040e27a_116123 on token_transfer_p2022_01_116123 tt_29  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_02_account_id_consensus_ti_8e8bb57c_116139 on token_transfer_p2022_02_116139 tt_30  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_03_account_id_consensus_ti_d8826093_116155 on token_transfer_p2022_03_116155 tt_31  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_04_account_id_consensus_ti_b07e156c_116171 on token_transfer_p2022_04_116171 tt_32  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_05_account_id_consensus_ti_7ca3ca7f_116187 on token_transfer_p2022_05_116187 tt_33  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_06_account_id_consensus_ti_405511ef_116203 on token_transfer_p2022_06_116203 tt_34  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_07_account_id_consensus_ti_326275ca_116219 on token_transfer_p2022_07_116219 tt_35  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_08_account_id_consensus_ti_0111f90b_116235 on token_transfer_p2022_08_116235 tt_36  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_09_account_id_consensus_ti_c995cc32_116251 on token_transfer_p2022_09_116251 tt_37  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_10_account_id_consensus_ti_719e37a4_116267 on token_transfer_p2022_10_116267 tt_38  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_11_account_id_consensus_ti_838206da_116283 on token_transfer_p2022_11_116283 tt_39  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2022_12_account_id_consensus_ti_a9ad5c6e_116299 on token_transfer_p2022_12_116299 tt_40  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_01_account_id_consensus_ti_9b743fc1_116315 on token_transfer_p2023_01_116315 tt_41  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_02_account_id_consensus_ti_37c0350e_116331 on token_transfer_p2023_02_116331 tt_42  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_03_account_id_consensus_ti_6c664759_116347 on token_transfer_p2023_03_116347 tt_43  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_04_account_id_consensus_ti_c721e186_116363 on token_transfer_p2023_04_116363 tt_44  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_05_account_id_consensus_ti_c1330533_116379 on token_transfer_p2023_05_116379 tt_45  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_06_account_id_consensus_ti_9250afda_116395 on token_transfer_p2023_06_116395 tt_46  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_07_account_id_consensus_ti_c57f2123_116411 on token_transfer_p2023_07_116411 tt_47  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_08_account_id_consensus_ti_b542258d_116427 on token_transfer_p2023_08_116427 tt_48  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_09_account_id_consensus_ti_b942321c_116443 on token_transfer_p2023_09_116443 tt_49  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_10_account_id_consensus_ti_48e7c55d_116459 on token_transfer_p2023_10_116459 tt_50  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_11_account_id_consensus_ti_8dcc989d_116475 on token_transfer_p2023_11_116475 tt_51  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2023_12_account_id_consensus_ti_d3638243_116491 on token_transfer_p2023_12_116491 tt_52  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2024_01_account_id_consensus_ti_392c8300_116507 on token_transfer_p2024_01_116507 tt_53  (cost=0.15..2.38 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2024_02_account_id_consensus_ti_c35b6686_116523 on token_transfer_p2024_02_116523 tt_54  (cost=0.28..2.50 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2024_03_account_id_consensus_ti_da5a82c3_116539 on token_transfer_p2024_03_116539 tt_55  (cost=0.28..2.50 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2024_04_account_id_consensus_ti_0c1191c8_116555 on token_transfer_p2024_04_116555 tt_56  (cost=0.28..2.50 rows=1 width=40) (never executed)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                           ->  Index Scan using token_transfer_p2024_05_account_id_consensus_ti_0ebff295_116571 on token_transfer_p2024_05_116571 tt_57  (cost=0.42..2.65 rows=1 width=40) (actual time=0.019..0.019 rows=0 loops=1)
                                 Index Cond: ((account_id = 4366156) AND (consensus_timestamp <= '1715894584220147004'::bigint) AND (consensus_timestamp > $0))
                                 Filter: (is_approval IS TRUE)
                         Planning Time: 2.404 ms
                         Execution Time: 0.744 ms
         Planning Time: 0.000 ms
         Execution Time: 14.910 ms
   ->  Distributed Subplan 1581_3
         Subplan Duration: 1.16 ms
         Intermediate Data Size: 0 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.659..0.659 rows=0 loops=1)
               Task Count: 1
               Tuple data received from nodes: 0 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 0 bytes
                     Node: host=/var/run/postgresql port=5432 dbname=mirror_node
                     ->  HashAggregate  (cost=0.97..1.28 rows=25 width=56) (actual time=0.081..0.082 rows=0 loops=1)
                           Group Key: intermediate_result.token_id, intermediate_result.payer_account_id, intermediate_result.consensus_timestamp
                           Batches: 1  Memory Usage: 24kB
                           ->  Hash Join  (cost=0.08..0.72 rows=25 width=32) (actual time=0.080..0.081 rows=0 loops=1)
                                 Hash Cond: ((intermediate_result_1.spender = intermediate_result.payer_account_id) AND (intermediate_result_1.token_id = intermediate_result.token_id))
                                 ->  Function Scan on read_intermediate_result intermediate_result_1  (cost=0.00..0.49 rows=19 width=16) (actual time=0.039..0.040 rows=9 loops=1)
                                 ->  Hash  (cost=0.04..0.04 rows=2 width=32) (actual time=0.036..0.036 rows=2 loops=1)
                                       Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                       ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.04 rows=2 width=32) (actual time=0.032..0.032 rows=2 loops=1)
                         Planning Time: 0.094 ms
                         Execution Time: 0.111 ms
         Planning Time: 0.000 ms
         Execution Time: 0.672 ms
   ->  Distributed Subplan 1581_4
         Subplan Duration: 2.82 ms
         Intermediate Data Size: 310 bytes
         Result destination: Send to 3 nodes
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.633..0.633 rows=5 loops=1)
               Task Count: 1
               Tuple data received from nodes: 200 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 200 bytes
                     Node: host=/var/run/postgresql port=5432 dbname=mirror_node
                     ->  Hash Join  (cost=0.08..0.65 rows=12 width=40) (actual time=0.085..0.087 rows=5 loops=1)
                           Hash Cond: ((intermediate_result_1.owner = intermediate_result.account_id) AND (intermediate_result_1.token_id = intermediate_result.token_id))
                           ->  Function Scan on read_intermediate_result intermediate_result_1  (cost=0.00..0.44 rows=16 width=24) (actual time=0.038..0.039 rows=9 loops=1)
                           ->  Hash  (cost=0.05..0.05 rows=2 width=32) (actual time=0.041..0.041 rows=2 loops=1)
                                 Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                 ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.01..0.05 rows=2 width=32) (actual time=0.039..0.040 rows=2 loops=1)
                                       Filter: (NOT (hashed SubPlan 1))
                                       SubPlan 1
                                         ->  Function Scan on read_intermediate_result intermediate_result_2  (cost=0.00..0.01 rows=1 width=8) (actual time=0.018..0.018 rows=0 loops=1)
                         Planning Time: 0.103 ms
                         Execution Time: 0.110 ms
         Planning Time: 0.000 ms
         Execution Time: 0.643 ms
   ->  Distributed Subplan 1581_5
         Subplan Duration: 17.49 ms
         Intermediate Data Size: 52 bytes
         Result destination: Write locally
         ->  HashAggregate  (cost=1000.00..1002.50 rows=200 width=56) (actual time=19.945..19.947 rows=1 loops=1)
               Group Key: remote_scan.sender_id, remote_scan.token_id, remote_scan.consensus_timestamp
               Batches: 1  Memory Usage: 40kB
               ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=56) (actual time=19.929..19.930 rows=1 loops=1)
                     Task Count: 16
                     Tuple data received from nodes: 34 bytes
                     Tasks Shown: One of 16
                     ->  Task
                           Tuple data received from node: 34 bytes
                           Node: host=10.4.2.5 port=7433 dbname=mirror_node
                           ->  HashAggregate  (cost=129.59..193.79 rows=5136 width=56) (actual time=0.240..0.270 rows=1 loops=1)
                                 Group Key: cr.sender_id, intermediate_result.token_id, intermediate_result.consensus_timestamp
                                 Batches: 1  Memory Usage: 217kB
                                 ->  Nested Loop  (cost=0.14..78.23 rows=5136 width=32) (actual time=0.219..0.227 rows=1 loops=1)
                                       ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.11 rows=6 width=32) (actual time=0.078..0.079 rows=5 loops=1)
                                       ->  Append  (cost=0.14..13.03 rows=58 width=16) (actual time=0.011..0.012 rows=0 loops=5)
                                             ->  Index Only Scan using contract_result_p2019_09_sender_id_consensus_ti_9ff8b9da_106395 on contract_result_p2019_09_106395 cr_1  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2019_10_sender_id_consensus_ti_13af3bcd_106411 on contract_result_p2019_10_106411 cr_2  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2019_11_sender_id_consensus_ti_af87a5fe_106427 on contract_result_p2019_11_106427 cr_3  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2019_12_sender_id_consensus_ti_4be22cd4_106443 on contract_result_p2019_12_106443 cr_4  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_01_sender_id_consensus_ti_c5d6a2e9_106459 on contract_result_p2020_01_106459 cr_5  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_02_sender_id_consensus_ti_2132d340_106475 on contract_result_p2020_02_106475 cr_6  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_03_sender_id_consensus_ti_6f776bd2_106491 on contract_result_p2020_03_106491 cr_7  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_04_sender_id_consensus_ti_3c7e1d02_106507 on contract_result_p2020_04_106507 cr_8  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_05_sender_id_consensus_ti_6ef68f3d_106523 on contract_result_p2020_05_106523 cr_9  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_06_sender_id_consensus_ti_33f02736_106539 on contract_result_p2020_06_106539 cr_10  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_07_sender_id_consensus_ti_e870b5ce_106555 on contract_result_p2020_07_106555 cr_11  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_08_sender_id_consensus_ti_c4a69df3_106571 on contract_result_p2020_08_106571 cr_12  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_09_sender_id_consensus_ti_f857853d_106587 on contract_result_p2020_09_106587 cr_13  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_10_sender_id_consensus_ti_ea835012_106603 on contract_result_p2020_10_106603 cr_14  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_11_sender_id_consensus_ti_167521d1_106619 on contract_result_p2020_11_106619 cr_15  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2020_12_sender_id_consensus_ti_446148c7_106635 on contract_result_p2020_12_106635 cr_16  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_01_sender_id_consensus_ti_77d0bab6_106651 on contract_result_p2021_01_106651 cr_17  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_02_sender_id_consensus_ti_ceafca4b_106667 on contract_result_p2021_02_106667 cr_18  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_03_sender_id_consensus_ti_b74189ca_106683 on contract_result_p2021_03_106683 cr_19  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_04_sender_id_consensus_ti_4579d88b_106699 on contract_result_p2021_04_106699 cr_20  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_05_sender_id_consensus_ti_89661cea_106715 on contract_result_p2021_05_106715 cr_21  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_06_sender_id_consensus_ti_e46ad98f_106731 on contract_result_p2021_06_106731 cr_22  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_07_sender_id_consensus_ti_e54a5eba_106747 on contract_result_p2021_07_106747 cr_23  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_08_sender_id_consensus_ti_080301cd_106763 on contract_result_p2021_08_106763 cr_24  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_09_sender_id_consensus_ti_cf92e21d_106779 on contract_result_p2021_09_106779 cr_25  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_10_sender_id_consensus_ti_f01c5f4c_106795 on contract_result_p2021_10_106795 cr_26  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_11_sender_id_consensus_ti_625e4554_106811 on contract_result_p2021_11_106811 cr_27  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2021_12_sender_id_consensus_ti_e09296ed_106827 on contract_result_p2021_12_106827 cr_28  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_01_sender_id_consensus_ti_68248721_106843 on contract_result_p2022_01_106843 cr_29  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_02_sender_id_consensus_ti_5c729500_106859 on contract_result_p2022_02_106859 cr_30  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_03_sender_id_consensus_ti_ec751f23_106875 on contract_result_p2022_03_106875 cr_31  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_04_sender_id_consensus_ti_d6a174a0_106891 on contract_result_p2022_04_106891 cr_32  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_05_sender_id_consensus_ti_7ab7bee2_106907 on contract_result_p2022_05_106907 cr_33  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_06_sender_id_consensus_ti_07a826cc_106923 on contract_result_p2022_06_106923 cr_34  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_07_sender_id_consensus_ti_cf300309_106939 on contract_result_p2022_07_106939 cr_35  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_08_sender_id_consensus_ti_acf9b4a6_106955 on contract_result_p2022_08_106955 cr_36  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_09_sender_id_consensus_ti_2e69f4f5_106971 on contract_result_p2022_09_106971 cr_37  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_10_sender_id_consensus_ti_a3435f76_106987 on contract_result_p2022_10_106987 cr_38  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_11_sender_id_consensus_ti_9e611152_107003 on contract_result_p2022_11_107003 cr_39  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2022_12_sender_id_consensus_ti_2f29adc5_107019 on contract_result_p2022_12_107019 cr_40  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_01_sender_id_consensus_ti_18caa055_107035 on contract_result_p2023_01_107035 cr_41  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_02_sender_id_consensus_ti_0be9a175_107051 on contract_result_p2023_02_107051 cr_42  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_03_sender_id_consensus_ti_5b2b011e_107067 on contract_result_p2023_03_107067 cr_43  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_04_sender_id_consensus_ti_92bd7fe6_107083 on contract_result_p2023_04_107083 cr_44  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_05_sender_id_consensus_ti_8449f19e_107099 on contract_result_p2023_05_107099 cr_45  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_06_sender_id_consensus_ti_98e6b6c7_107115 on contract_result_p2023_06_107115 cr_46  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_07_sender_id_consensus_ti_59f82ff7_107131 on contract_result_p2023_07_107131 cr_47  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_08_sender_id_consensus_ti_7a4f8562_107147 on contract_result_p2023_08_107147 cr_48  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_09_sender_id_consensus_ti_d62701a8_107163 on contract_result_p2023_09_107163 cr_49  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_10_sender_id_consensus_ti_b5b11c58_107179 on contract_result_p2023_10_107179 cr_50  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_11_sender_id_consensus_ti_e379893e_107195 on contract_result_p2023_11_107195 cr_51  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2023_12_sender_id_consensus_ti_350039c4_107211 on contract_result_p2023_12_107211 cr_52  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2024_01_sender_id_consensus_ti_00a5fd30_107227 on contract_result_p2024_01_107227 cr_53  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2024_02_sender_id_consensus_ti_e7f7e511_107243 on contract_result_p2024_02_107243 cr_54  (cost=0.42..0.87 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2024_03_sender_id_consensus_ti_a53d06c2_107259 on contract_result_p2024_03_107259 cr_55  (cost=0.29..0.58 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2024_04_sender_id_consensus_ti_082240cb_107275 on contract_result_p2024_04_107275 cr_56  (cost=0.29..0.64 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                                             ->  Index Only Scan using contract_result_p2024_05_sender_id_consensus_ti_be6fd63a_107291 on contract_result_p2024_05_107291 cr_57  (cost=0.29..1.09 rows=1 width=16) (actual time=0.009..0.009 r
ows=0 loops=5)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 1
                                             ->  Index Only Scan using contract_result_p2024_06_sender_id_consensus_ti_e6c663c1_107307 on contract_result_p2024_06_107307 cr_58  (cost=0.14..0.18 rows=1 width=16) (never executed)
                                                   Index Cond: ((sender_id = intermediate_result.spender) AND (consensus_timestamp = intermediate_result.consensus_timestamp))
                                                   Heap Fetches: 0
                               Planning Time: 6.775 ms
                               Execution Time: 1.013 ms
         Planning Time: 0.000 ms
         Execution Time: 20.010 ms
   ->  Distributed Subplan 1581_6
         Subplan Duration: 1.07 ms
         Intermediate Data Size: 849 bytes
         Result destination: Write locally
         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.964..0.965 rows=9 loops=1)
               Task Count: 1
               Tuple data received from nodes: 579 bytes
               Tasks Shown: All
               ->  Task
                     Tuple data received from node: 579 bytes
                     Node: host=/var/run/postgresql port=5432 dbname=mirror_node
                     ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.95 rows=9 width=104) (actual time=0.119..0.134 rows=9 loops=1)
                           SubPlan 1
                             ->  Aggregate  (cost=0.03..0.04 rows=1 width=32) (actual time=0.005..0.005 rows=1 loops=9)
                                   ->  Function Scan on read_intermediate_result intermediate_result_1  (cost=0.00..0.02 rows=1 width=32) (actual time=0.004..0.004 rows=0 loops=9)
                                         Filter: ((token_id = intermediate_result.token_id) AND (sender_id = intermediate_result.spender))
                                         Rows Removed by Filter: 1
                           SubPlan 2
                             ->  Aggregate  (cost=0.02..0.03 rows=1 width=32) (actual time=0.002..0.002 rows=1 loops=9)
                                   ->  Function Scan on read_intermediate_result intermediate_result_2  (cost=0.00..0.01 rows=1 width=32) (actual time=0.002..0.002 rows=0 loops=9)
                                         Filter: ((token_id = intermediate_result.token_id) AND (payer_account_id = intermediate_result.spender))
                         Planning Time: 0.145 ms
                         Execution Time: 0.171 ms
         Planning Time: 0.000 ms
         Execution Time: 0.984 ms
   Task Count: 1
   Tuple data received from nodes: 579 bytes
   Tasks Shown: All
   ->  Task
         Tuple data received from node: 579 bytes
         Node: host=/var/run/postgresql port=5432 dbname=mirror_node
         ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.23 rows=6 width=104) (actual time=0.037..0.039 rows=9 loops=1)
               Filter: (amount > '0'::numeric)
             Planning Time: 0.033 ms
             Execution Time: 0.048 ms
 Planning Time: 3.750 ms
 Execution Time: 67.677 ms

**Review by steven-sheehy — APPROVED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java [hunk 1]
```diff
@@ -185,35 +185,29 @@ and lower(timestamp_range) <= :blockTimestamp
                             ) as all_token_allowances
                         ) as grouped_token_allowances
                         where row_number = 1 and amount_granted > 0
-                    ), transfers as (
```
Comment (xin-hedera) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java:188]: can you also change the first CTE to

```
with token_allowances as (
  select *
  from token_allowance_history
  where owner = :owner and amount_granted > 0 and timestamp_range @> :blockTimestamp
  union all
  select *
  from token_allowance
  where owner = :owner and amount_granted > 0 and :blockTimestamp >= lower(timestamp_range)
)
```

The current CTE returns too many rows from `token_allowance_history` and make everything slow afterwards.

The proposed change can use the gist index on `token_allowance_history.timestamp_range` plus the `owner = ` filter to remove unnecessary rows.

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java (hunk 1 above)
Comment (jnels124) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java:188]: Looking at this a bit more. But this change causes several test cases to fail.

Comment (xin-hedera) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAllowanceRepository.java:188]: let's address it in a follow-up

**Review by xin-hedera — APPROVED** [review]
LGTM
