### PR TITLE
HIP-584 Historical: Fix historical total supply

### LINKED ISSUE #7497: HIP:584 - Historical data is not returned correctly for getFungibleTokenInfo and getNonFungibleInfo
### Description

Executing a getFungibleTokenInfo/getNonFungibleInfo for a token that had his tokenSupply changed via burn/mint does not return proper historical data.

### Steps to reproduce

1. Create a token(X) and get the block number
2. Get eth_call for the token(X) via getFungibleTokenInfo/getNonFungibleInfo
3. Execute burn for the token(X)
4. Get eth_call for historical data for the block number from step 1 and for the token(X) via getFungibleTokenInfo/getNonFungibleInfo

### Additional context

_No response_

### Hedera network

other

### Version

0.95.0

### Operating system

None

### PR DESCRIPTION
**Pull request by 0xivanov**
**Description**:

Executing a `getFungibleTokenInfo/getNonFungibleInfo` for a token that had his `tokenSupply` changed via `burn/mint/wipe` does not return proper historical data.
Minting/burning tokens does not trigger the historical data for the `token_history table`. However, it does change the `totalSupply`, which means the "historical" `totalSupply` field might not be valid for `getTokenInfo` operation.

This PR fixes `TokenDatabaseAccessor` to return proper `totalSupply` with added historical queries.

**Related issue(s)**:

Fixes #7497

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java [hunk 1]
```diff
@@ -78,6 +79,7 @@ void pureCall() {
         assertGasUsedIsPositive(gasUsedBeforeExecution, ETH_CALL);
     }
 
+    @Disabled
```
Comment (0xivanov) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java:82]: These 2 should get fixed here https://github.com/hashgraph/hedera-mirror-node/pull/7434

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/TokenDatabaseAccessorTest.java [hunk 2]
```diff
@@ -123,7 +128,7 @@ void getTokenMappedValuesHistorical() {
                 .returns(new Id(entity.getShard(), entity.getRealm(), entity.getNum()), Token::getId)
                 .returns(TokenType.valueOf(databaseToken.getType().name()), Token::getType)
                 .returns(TokenSupplyType.valueOf(databaseToken.getSupplyType().name()), Token::getSupplyType)
-                .returns(databaseToken.getTotalSupply(), Token::getTotalSupply)
+                .returns(0L, Token::getTotalSupply)
```
Comment (0xivanov) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/TokenDatabaseAccessorTest.java:131]: This case is tested in `getTotalSupplyHistoricalFungible`, so I don't mock the repo here

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java [hunk 3]
```diff
@@ -65,4 +65,47 @@ order by lower(timestamp_range) desc
...
+                            limit 1
+                        )
+                        order by timestamp_range desc
+                        limit 1
+                    ), change as (
+                        select sum(amount) as amount
+                        from token_transfer as tt, total_supply_snapshot as s
+                        where
+                            token_id = ?1 and
+                            account_id = ?2 and
```
Comment (xin-hedera) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java:103]: token's supply change don't have to cause transfers to / from the treasury account and not all transfers with treasury involved will change total supply.

For the first category, token wipe account transaction changes total supply but in its record there's no transfer to / from the treasury account.

For the second category, an account `a` can transfer its token to the treasury `t`, this will not change token's total supply

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java [hunk 4]
```diff
@@ -65,4 +65,47 @@ order by lower(timestamp_range) desc
...
+                            s.timestamp_range @> tt.consensus_timestamp and
+                            tt.consensus_timestamp > ?3
```
Comment (0xivanov) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java:105]: @xin-hedera Should't we also include the change that happened in the passed timestamp:
`tt.consensus_timestamp >= ?3`

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java (hunk 3 above)
Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java:103]: For the second category, I came up with this where clause:
```sql
where
    token_id = ?1 and
    s.timestamp_range @> tt.consensus_timestamp and
    tt.consensus_timestamp >= ?3 and
    (tt.account_id = ?2 or tt.payer_account_id = ?2)
    or (amount < 0 and  
    token_id = ?1 and
    s.timestamp_range @> tt.consensus_timestamp and
    tt.consensus_timestamp >= ?3 and
    tt.payer_account_id <> ?2 and
    exists (
       select 1
       from token_transfer as tt2
       where
        tt2.amount = -tt.amount and
        tt2.payer_account_id = tt.payer_account_id
    )
);
```
This matches all of the transfers to/from the treasury. We know that these records are not burns/mints because they have a pair with opposing amount (10,-10). In the end the transfers negate each other and the burns/mints are calculated

Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java:103]: For the wipe case, we can do something similar (look which entries do not have matching opposite pair), but i am still thinking how to combine the 2. Any insights?

Comment (xin-hedera) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java:103]: I'm fine with just summing the amount of all token transfers in the timestamp range, even though there can be performance issue.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java (hunk 4 above)
Comment (xin-hedera) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java:105]: yes we should include any supply change happened at `blockTimestamp`, however the correct answer is `tt.consensus_timestamp > :blockTimestamp`, because the total supply from `token` / `token_history` is at a later timestamp so we should exclude supply changes > blockTimestamp, not >=

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java (hunk 3 above)
Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java]: changed

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java (hunk 4 above)
Comment (0xivanov) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java]: fixed

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
LGTM
