### PR TITLE
Updated accounts.js with the new account_balances table, and fixed th…

### LINKED ISSUE #103: Make shard_num a property of the application
It's unlikely a mirror node would be collecting data from several shards at once, as a result, the shard number can be set system wide via a configuration parameter and used to validate incoming data as per the new balance processing.

### LINKED ISSUE #174: REST API: /accounts querying wrong tables (broken).
The /accounts REST API query is broken as it is querying deprecated tables t_account_balances and t_account_balance_refresh_time.

**Detailed Description**

**Actual Behavior**

**Expected Behavior**
This REST API should be querying the new account_balances table

**Environment:**

**Additional Context**

### LINKED ISSUE #177: /balances?timestamp=xxx is broken
**Detailed Description**
/api/v1/balances?account.id=0.0.9&timestamp=1567381500 is returning:
  "timestamp": "1567380600.085806000",
    "balances": [
        {
            "account": "0.0.9",
            "balance": 6910540638
        },
        {
            "account": "0.0.9",
            "balance": 6910059191
        },
        {
            "account": "0.0.9",
            "balance": 6909955634
        },
...

**Actual Behavior**
1. Use: /api/v1/balances?account.id=0.0.9&timestamp=1567381500

**Expected Behavior**
It should just return one latest entry at-or-before the given timestamp.

**Additional Context**
This was broken in https://github.com/hashgraph/hedera-mirror-node/commit/19eeb1c3ba4f5b424d71931b9a27bce8740ff099#diff-b77669fdffdf4c67c0b9698c14a00a0b

### PR DESCRIPTION
**Pull request by atul-hedera**
**Detailed description**:
1. Updated the balances.js to re-add the inner query so that /balances?timestamp=xxx query works correctly.
2. Updated the accounts.js file to run against the new table schema for account_balances table. Moved the common code to process the query output to a processRow function.
3. Made SHARD_NUM read in via an environment variable?!

**Which issue(s) this PR fixes**:
Fixes #174 
Fixes #177 
Fixes #103

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: rest-api/accounts.js [hunk 1]
```diff
@@ -30,42 +61,36 @@ const getAccounts = function (req) {
...
+    const entitySql = 
+        "select ab.balance as account_balance\n" +
+        "    , ab.consensus_timestamp as consensus_timestamp\n" +
+        "    , " + process.env.SHARD_NUM + " as entity_shard\n" +
+            "    , ab.account_realm_num as entity_realm\n" +
+            "    , ab.account_num as entity_num\n" +
+            "    , e.exp_time_ns, e.auto_renew_period, e.admin_key, e.key, e.deleted\n" +
+            "    , et.name as entity_type\n" +
+            "from account_balances ab\n" +
+            "left outer join t_entities e on (ab.account_realm_num = e.entity_realm and ab.account_num =  e.entity_num)\n" +
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: Unless it's somehow otherwise causing a serious performance issue...
This join should be on realm_num, account_num, and type.
We want it to be clear that account balances is joining against _accounts_ in the entities table, not just accounts/files/contracts that have the same realm & num

Comment (mike-burrage-hedera) [reply rest-api/accounts.js]: Also, this needs to be made a full outer join as account balance and transaction streams come in at different times. I'll post the query here shortly.

File: rest-api/accounts.js [hunk 2]
```diff
@@ -21,6 +21,37 @@
 const utils = require('./utils.js');
 const transactions = require('./transactions.js');
 
+
+/**
+ * Processes one row of the results of the SQL query and format into API return format
+ * @param {Object} row One row of the SQL query result
+ * @return {Object} row Processed row
+ */
+const processRow = function (row) {
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: Is this function supposed to take a row and generate exactly some expected format for the row? Because it doesn't do that - it modifies the row object itself in only certain ways. New columns added just get passed through.

It would be clearer if this function didn't modify row at all and just returned a specific object (ie rowToAccountRecord) or something. Much clearer for us maintaining it.

File: rest-api/accounts.js [hunk 3]
```diff
@@ -30,42 +61,36 @@ const getAccounts = function (req) {
...
+        "select ab.balance as account_balance\n" +
+        "    , ab.consensus_timestamp as consensus_timestamp\n" +
+        "    , " + process.env.SHARD_NUM + " as entity_shard\n" +
+            "    , ab.account_realm_num as entity_realm\n" +
+            "    , ab.account_num as entity_num\n" +
+            "    , e.exp_time_ns, e.auto_renew_period, e.admin_key, e.key, e.deleted\n" +
+            "    , et.name as entity_type\n" +
+            "from account_balances ab\n" +
+            "left outer join t_entities e on (ab.account_realm_num = e.entity_realm and ab.account_num =  e.entity_num)\n" +
+            "left outer join t_entity_types et on et.id = e.fk_entity_type_id\n" +
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: Unless this was giving us some wonky query plan, we want to inner join (regular join) on entity_types. We shouldn't have an entity with a type that isn't in the t_entity_types table.

File: rest-api/accounts.js [hunk 4]
```diff
@@ -161,36 +164,28 @@ const getOneAccount = function (req, res) {
...
+        "select ab.balance as account_balance\n" +
+        "    , ab.consensus_timestamp as consensus_timestamp\n" +
+        "    , " + process.env.SHARD_NUM + " as entity_shard\n" +
+            "    , ab.account_realm_num as entity_realm\n" +
+            "    , ab.account_num as entity_num\n" +
+            "    , e.exp_time_ns, e.auto_renew_period, e.admin_key, e.key, e.deleted\n" +
+            "    , et.name as entity_type\n" +
+            "from account_balances ab\n" +
+            "left outer join t_entities e\n" +
+            "  on (ab.account_realm_num = e.entity_realm and ab.account_num =  e.entity_num)\n" +
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: and entity type is account

File: rest-api/accounts.js [hunk 5]
```diff
@@ -161,36 +164,28 @@ const getOneAccount = function (req, res) {
...
+            "left outer join t_entity_types et\n" +
+            "  on et.id = e.fk_entity_type_id\n" +
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: inner join

File: rest-api/accounts.js [hunk 6]
```diff
@@ -161,36 +164,28 @@ const getOneAccount = function (req, res) {
...
+        "where \n" +
+            "ab.consensus_timestamp =\n" +
+            "  (select consensus_timestamp from account_balances order by consensus_timestamp desc limit 1)\n" +
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: select max(consensus_timestamp) from account_balances

**Comment by mike-burrage-hedera** [comment]
Shard num is now read in via an environment variable.  Undocumented as well.
Why isn't it part of the config? Documented? With a sample that's set to 0.

File: rest-api/accounts.js (hunk 1 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 2 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 3 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 4 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 5 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 6 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 2 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js [hunk 7]
```diff
@@ -21,6 +21,56 @@
...
+ * @return {Object} accRecord Processed account record
+ */
+const processRow = function (row) {
+    let accRecord = {};
+    accRecord.balance = {};
+    accRecord.account = row.entity_shard + '.' + row.entity_realm + '.' + row.entity_num;
+    accRecord.balance.timestamp = utils.nsToSecNs(row.consensus_timestamp);
+    accRecord.balance.balance = Number(row.account_balance);
+    accRecord.expiry_timestamp = utils.nsToSecNs(row.exp_time_ns);
+    accRecord.auto_renew_period = Number(row.auto_renew_period);
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: The 4 lines above now need to handle null. If null, set to null else use those converters.

File: rest-api/accounts.js [hunk 8]
```diff
@@ -30,41 +80,22 @@ const getAccounts = function (req) {
...
-        " where et.id = e.fk_entity_type_id\n" +
-        " and ab.shard = e.entity_shard\n" +
-        " and ab.realm = e.entity_realm\n" +
-        " and ab.num = e.entity_num\n" +
-        "   and " + 
+    const entitySql = getAccountQueryPrefix() +
+        "    and \n" +
         [accountQuery, balanceQuery, pubKeyQuery].map(q => q === '' ? '1=1' : q).join(' and ') +
-        " order by num " + order + "\n" +
+        " order by ab.account_num " + order + "\n" +
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: coalesce(ab.account_num, e.entity_num)

File: rest-api/accounts.js [hunk 9]
```diff
@@ -21,6 +21,56 @@
...
+        "    , et.name as entity_type\n" +
+        "from account_balances ab\n" +
+        "full outer join t_entities e\n" +
+        "    on (ab.account_realm_num = e.entity_realm\n" +
+        "        and ab.account_num =  e.entity_num\n" +
+        "        and e.fk_entity_type_id = " + ACCOUNT_ENTITY_TYPE + ")\n" +
+        "join t_entity_types et\n" +
+        "    on et.id = " + ACCOUNT_ENTITY_TYPE + "\n" +
+        "where \n" +
+        "    ab.consensus_timestamp = (select max(consensus_timestamp) from account_balances)\n" +
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: Full outer join now, the account_balances part may not be there

(consensus_timestamp is null or its max)

File: rest-api/accounts.js [hunk 10]
```diff
@@ -21,6 +21,56 @@
...
+        "    and e.fk_entity_type_id = " + ACCOUNT_ENTITY_TYPE + "\n";
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: entity may not be there - eliminate this.

File: rest-api/accounts.js [hunk 11]
```diff
@@ -30,41 +80,22 @@ const getAccounts = function (req) {
     // Parse the filter parameters for account-numbers, balances, publicKey and pagination
     const [accountQuery, accountParams] =
         utils.parseParams(req, 'account.id',
-            [{ shard: 'entity_shard', realm: 'entity_realm', num: 'entity_num' }],
+            [{ shard: process.env.SHARD_NUM, realm: 'ab.account_realm_num', num: 'ab.account_num' }],
             'entityId');
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: We need to like run this again with different names (e.entity_realm and e.entity_num) - and combine them with an _or_ in the query below

File: rest-api/accounts.js [hunk 12]
```diff
@@ -161,36 +170,13 @@ const getOneAccount = function (req, res) {
...
-        entity_data: [],
         transactions: []
     };
 
-    const timeQuerySql =
-        "select seconds, nanos from  t_account_balance_refresh_time limit 1";
-    // Execute query & get a promise
-    const timePromise = pool.query(timeQuerySql);
+    const entitySql = getAccountQueryPrefix() +
+        "and (ab.account_realm_num  =  ? and ab.account_num  =  ?)\n";
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: or e.entity_realm and e.entity_num?
This part of the outer join?

File: rest-api/accounts.js (hunk 7 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: OK

File: rest-api/accounts.js (hunk 10 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: OK

File: rest-api/accounts.js (hunk 11 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 8 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 12 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js (hunk 9 above)
Comment (atul-hedera) [reply rest-api/accounts.js]: Done

File: rest-api/accounts.js [hunk 13]
```diff
@@ -161,36 +184,18 @@ const getOneAccount = function (req, res) {
...
-    const timeQuerySql =
-        "select seconds, nanos from  t_account_balance_refresh_time limit 1";
-    // Execute query & get a promise
-    const timePromise = pool.query(timeQuerySql);
+    // Because of the outer join on the 'account_balances ab' and 't_entities e' below, we 
+    // need to look  for the given account.id in both account_balances and t_entities table and combine with an 'or'
+    const entitySql = getAccountQueryPrefix() +
+        "and (\n" +
+        "    (ab.account_realm_num  =  ? and ab.account_num  =  ?)\n" +
+        "    or (e.entity_realm = ? and e.entity_num = ?)\n" +
```
Comment (mike-burrage-hedera) [inline rest-api/accounts.js]: and e.entity_type_id = 1?

Comment (atul-hedera) [reply rest-api/accounts.js]: Sorry for missing this. I've added it in the latest commit
