### PR TITLE
Fix v2 rest tests

### LINKED ISSUE #4654: Fix v2 REST tests
### Description

REST API tests when used with v2 schema

### Steps to reproduce

Run `npm test` with v2 schema

### Additional context

_No response_

### Hedera network

other

### Version

main

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes v2 rest tests

- Rewrite contract log SQL query
- Rewrite network unreleased supply SQL query
- Rewrite search record file by hash SQL query
- Rewrite stateproof SQL query
- Enable rest api v2 schema github workflow

**Related issue(s)**:

Fixes #4654 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by edwin-greene — APPROVED** [review]
Looks good

**Review by MarcKriguerAtHedera — APPROVED** [review]
LGTM.

**Comment by mgoelswirlds** [comment]
@xin-hedera Would it make any changes to run the tests? Might be helpful to add instructions in the ReadMe?

**Comment by xin-hedera** [comment]
> @xin-hedera Would it make any changes to run the tests? Might be helpful to add instructions in the ReadMe?

The PR changes the github workflow file to run REST v2 tests, can look at the step [here](https://github.com/hashgraph/hedera-mirror-node/blob/666c676a5b3940f7194198f73d232a492a857518/.github/workflows/rest-api.yml#L45-L49). For v2, just have to set `MIRROR_NODE_SCHEMA=v2`

**Review by mgoelswirlds — APPROVED** [review]

File: hedera-mirror-rest/service/contractService.js [hunk 1]
```diff
@@ -104,16 +104,22 @@ class ContractService extends BaseService {
...
-    ${ContractLog.getFullName(ContractLog.CONSENSUS_TIMESTAMP)} = ${ContractResult.getFullName(
-    ContractResult.CONSENSUS_TIMESTAMP
-  )}
+    left join ${ContractResult.tableName} ${ContractResult.tableAlias}
+      on ${ContractLog.getFullName(ContractLog.CONSENSUS_TIMESTAMP)} =
+        ${ContractResult.getFullName(ContractResult.CONSENSUS_TIMESTAMP)} and
+		   ${ContractLog.getFullName(ContractLog.PAYER_ACCOUNT_ID)} =
+		   ${ContractResult.getFullName(ContractResult.PAYER_ACCOUNT_ID)}
     left join lateral (
       select ${RecordFile.INDEX} as block_number, ${RecordFile.HASH} as block_hash
```
Comment (steven-sheehy) [inline hedera-mirror-rest/service/contractService.js:124]: We seem to be selecting the block_number and block_hash twice now via here and the new CTE. Is this intended? Does the lateral join filter the previous CTE?

Comment (xin-hedera) [reply hedera-mirror-rest/service/contractService.js:124]: yes intended. it's needed to just select the columns we need into the CTE and later do a lateral join, otherwise citus will report error.

Comment (xin-hedera) [reply hedera-mirror-rest/service/contractService.js:124]: if we later we hit performance issue, we can explore the add `block_number` to `contract_log` table approach...

**Review by MarcKriguerAtHedera — APPROVED** [review]
LGTM

File: hedera-mirror-rest/service/recordFileService.js [hunk 2]
```diff
@@ -138,26 +137,15 @@ class RecordFileService extends BaseService {
     const params = [];
     if (hash) {
       hash = hash.toLowerCase();
-      if (hash.length === RecordFileService.HEX_HASH_PREFIX_SIZE) {
```
Comment (xin-hedera) [inline hedera-mirror-rest/service/recordFileService.js:141]: there is a citus ticket: https://github.com/citusdata/citus/issues/5992

**Review by steven-sheehy — APPROVED** [review]
