### PR TITLE
HIP-873: Add decimals to token REST APIs

### LINKED ISSUE #7386: Decimals are not returned with the token balance in the new token relationship API
### Description

A token balance without the associated number of decimals to know how to interpret that balance is dangerous to present to an end user. 

### Steps to reproduce

1. Query for token balances using the new `/api/v1/accounts/{id}/tokens` API.
2. See that decimal information is not returned.

### Additional context

_No response_

### Hedera network

mainnet, testnet, previewnet

### Version

v1

### Operating system

None

### PR DESCRIPTION
**Pull request by edwin-greene**
**Description**:
Adds  `name` and `decimals` to: 
`/api/v1/tokens`

Adds `decimals` to:
`/api/v1/tokens/{tokenId}/balances`
`/api/v1/accounts/{idOrAliasOrEvmAddress}/tokens`

**Related issue(s)**:

Fixes #7386 

**Notes for reviewer**:
K6 test results (1500 VUS, duration 120 seconds) on staging environment: 
Baseline 0.98.0_rc1:
```
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Skipped? | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|--------|---------|
| accountTokensResults | /accounts/1007535/tokens?limit=100 | 1500 | 100.00 | 399.06/s | 399.06/s | 3693.30ms | No | |
| tokens | /tokens?limit=100 | 1500 | 100.00 | 975.43/s | 975.43/s | 1520.50ms | No | |
| tokensFungibleCommon | /tokens?type=FUNGIBLE_COMMON | 1500 | 100.00 | 3054.13/s | 3054.13/s | 486.33ms | No | |
| tokensIdBalances | /tokens/2186153/balances | 1500 | 44.93 | 67.61/s | 30.38/s | 18296.90ms | No | |
| tokensIdBalancesTimestamp | /tokens/2186153/balances?timestamp=1707518529.137 | 1500 | 100.00 | 3627.48/s | 3627.48/s | 408.88ms | No | |
```

With decimals and token cache:  
```
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Skipped? | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|--------|---------|
| accountTokensResults | /accounts/1007535/tokens?limit=100 | 1500 | 100.00 | 724.74/s | 724.74/s | 2035.72ms | No | |
| tokens | /tokens?limit=100 | 1500 | 100.00 | 1553.18/s | 1553.18/s | 947.44ms | No | |
| tokensFungibleCommon | /tokens?type=FUNGIBLE_COMMON | 1500 | 100.00 | 3601.89/s | 3601.89/s | 412.55ms | No | |
| tokensIdBalances | /tokens/2186153/balances | 1500 | 43.51 | 57.09/s | 24.84/s | 25139.34ms | No | |
| tokensIdBalancesTimestamp | /tokens/2186153/balances?timestamp=1707517070.548 | 1500 | 100.00 | 3794.78/s | 3794.78/s | 390.73ms | No | |
```

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/service/tokenService.js [hunk 1]
```diff
@@ -14,10 +14,17 @@
...
-import {TokenAccount} from '../model';
+import {Token, TokenAccount} from '../model';
 import BaseService from './baseService';
 import {OrderSpec} from '../sql';
 import _ from 'lodash';
+import quickLru from 'quick-lru';
+import config from '../config.js';
+
+const decimalsCache = new quickLru({
+  maxAge: config.cache.token.decimals.maxAge * 1000, // in millis
```
Comment (jnels124) [inline hedera-mirror-rest/service/tokenService.js:25]: The decimal is immutable so shouldn't we only configure max size?

File: hedera-mirror-rest/service/tokenService.js [hunk 2]
```diff
@@ -84,15 +96,50 @@ class TokenService extends BaseService {
...
+   * @param {BigInt} tokenId
+   * @return {Promise<BigInt>}
+   */
+  async getDecimals(tokenId) {
+    let decimals = decimalsCache.get(tokenId);
+    if (decimals) {
+      return decimals;
+    }
+
+    const rows = await super.getRows(TokenService.tokenDecimalsQuery, tokenId);
```
Comment (jnels124) [inline hedera-mirror-rest/service/tokenService.js:135]: Can just use getSingleRow

File: hedera-mirror-rest/tokens.js [hunk 3]
```diff
@@ -95,7 +95,7 @@ const tokenAccountCte = `with ta as (
   where account_id = $1
   order by token_id
 )`;
-const tokensSelectQuery = 'select t.token_id, symbol, e.key, t.type from token t';
+const tokensSelectQuery = 'select t.token_id, symbol, name, e.key, t.type, decimals from token t';
```
Comment (jnels124) [inline hedera-mirror-rest/tokens.js:98]: nit: t.

File: docs/configuration.md [hunk 4]
```diff
@@ -490,6 +490,8 @@ value, it is recommended to only populate overridden properties in the custom `a
...
 | `hedera.mirror.rest.cache.entityId.maxAge`                         | 1800                    | The number of seconds until the entityId cache entry expires                                                                                                                                  |
 | `hedera.mirror.rest.cache.entityId.maxSize`                        | 100000                  | The maximum number of entries in the entityId cache                                                                                                                                           |
+| `hedera.mirror.rest.cache.token.decimals.maxAge`                   | 1800                    | The number of seconds until the decimals cache entry expires                                                                                                                                  |
+| `hedera.mirror.rest.cache.token.decimals.maxSize`                  | 100000                  | The maximum number of entries in the decimals cache                                                                                                                                           |
```
Comment (xin-hedera) [inline docs/configuration.md:494]: we'll expand to not just cache token decimals, so to avoid renaming the property, just use `hedera.mirror.rest.cache.token.maxSize` now

File: hedera-mirror-rest/service/tokenService.js [hunk 5]
```diff
@@ -84,15 +96,50 @@ class TokenService extends BaseService {
...
+  addDecimalsToCache(tokenId, decimals) {
+    decimalsCache.set(tokenId, decimals);
+  }
+
+  /**
+   * Gets the decimals for a token
+   * @param {BigInt} tokenId
+   * @return {Promise<BigInt>}
+   */
+  async getDecimals(tokenId) {
```
Comment (xin-hedera) [inline hedera-mirror-rest/service/tokenService.js:129]: given X tokens returned from a query, here by design, in the worst case, `getDecimals` is called X times and again X db queries are needed to get the info, which is very inefficient.

File: hedera-mirror-rest/api/v1/openapi.yml [hunk 6]
```diff
@@ -3259,20 +3259,29 @@ components:
...
         symbol:
           type: string
+        name:
+          type: string
         admin_key:
           $ref: "#/components/schemas/Key"
         type:
           type: string
+        decimals:
+          format: int64
```
Comment (xin-hedera) [inline hedera-mirror-rest/api/v1/openapi.yml:3269]: it's a unit32 per hedera-protobufs

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/service/tokenService.js (hunk 1 above)
Comment (edwin-greene) [reply hedera-mirror-rest/service/tokenService.js:25]: I'm not sure, the entityId cache has a maxAge, so I based this cache off of it.

File: hedera-mirror-rest/api/v1/openapi.yml (hunk 6 above)
Comment (edwin-greene) [reply hedera-mirror-rest/api/v1/openapi.yml]: Thanks I have updated these to int32.

File: hedera-mirror-rest/service/tokenService.js (hunk 5 above)
Comment (edwin-greene) [reply hedera-mirror-rest/service/tokenService.js]: Thanks! I have updated it to a `where in clause` in the query, so the query will only occur once rather than multiple times in the loop.

File: docs/configuration.md (hunk 4 above)
Comment (edwin-greene) [reply docs/configuration.md]: Sounds good I have renamed them.

File: hedera-mirror-rest/tokens.js (hunk 3 above)
Comment (edwin-greene) [reply hedera-mirror-rest/tokens.js]: Thanks I have added the t

File: hedera-mirror-rest/service/tokenService.js (hunk 2 above)
Comment (edwin-greene) [reply hedera-mirror-rest/service/tokenService.js]: Good idea, but I changed it to accept an array of token ids, so it will now really get back multiple rows.

File: hedera-mirror-rest/service/tokenService.js [hunk 7]
```diff
@@ -84,15 +95,65 @@ class TokenService extends BaseService {
...
    *
    * @param query
-   * @return {Promise<Token[]>}
+   * @return {Promise<TokenAccount[]>}
    */
   async getTokens(query) {
     const {sqlQuery, params} = this.getTokenRelationshipsQuery(query);
     const rows = await super.getRows(sqlQuery, params);
-    return rows.map((ta) => new TokenAccount(ta));
+    const tokenIds = [];
```
Comment (steven-sheehy) [inline hedera-mirror-rest/service/tokenService.js:107]: For performance, may consider a set in case any endpoint can return the same token ID multiple times.

File: hedera-mirror-rest/service/tokenService.js (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-rest/service/tokenService.js]: Agree, we can probably remove maxAge.

File: hedera-mirror-rest/api/v1/openapi.yml (hunk 6 above)
Comment (steven-sheehy) [reply hedera-mirror-rest/api/v1/openapi.yml]: It can't be int32 since that will make numbers `(2^31, 3^32]` be shown as negative. If there's no uint32 in openapi, revert it back to int64. This is the same reason why we store as bigint in db.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/service/tokenService.js [hunk 8]
```diff
@@ -84,15 +95,65 @@ class TokenService extends BaseService {
...
+    const tokenAccounts = rows.map((row) => {
+      tokenIds.push(row[TokenAccount.TOKEN_ID]);
+      return new TokenAccount(row);
+    });
+    const decimalsMap = await this.getDecimals(tokenIds);
+    tokenAccounts.forEach((tokenAccount) => (tokenAccount.decimals = decimalsMap.get(tokenAccount.tokenId)));
```
[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-rest/service/tokenService.js]: Sounds good I have added an undefined check

File: hedera-mirror-rest/service/tokenService.js [hunk 9]
```diff
@@ -84,15 +95,65 @@ class TokenService extends BaseService {
...
+  addDecimalsToCache(tokenId, decimals) {
+    decimalsCache.set(tokenId, decimals);
+  }
+
+  /**
+   * Gets the decimals for a list of token ids
+   * @param {[BigInt]} tokenIds
+   * @return {Promise<Map<tokenId, decimals>>}
+   */
+  async getDecimals(tokenIds) {
```
[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-rest/service/tokenService.js]: Thanks I have updated the methods.

File: hedera-mirror-rest/service/tokenService.js [hunk 10]
```diff
@@ -84,15 +95,65 @@ class TokenService extends BaseService {
...
+      } else {
+        uncachedTokenIds.push(tokenId);
+      }
+    }
+
+    if (_.isEmpty(uncachedTokenIds)) {
+      return cachedDecimals;
+    }
+
+    const whereClause = `where ${Token.TOKEN_ID} in (${uncachedTokenIds})`;
```
[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-rest/service/tokenService.js:149]: I tried a few different approaches, it looks as if the `?` must match the number of parameters, such as `?, ?, ...`. Searching a bit, I wasn't able to find a way to place the where clause in the static query string.

File: hedera-mirror-rest/service/tokenService.js (hunk 1 above)
Comment (edwin-greene) [reply hedera-mirror-rest/service/tokenService.js]: Sounds good I have removed it.

File: hedera-mirror-rest/api/v1/openapi.yml (hunk 6 above)
Comment (edwin-greene) [reply hedera-mirror-rest/api/v1/openapi.yml:3269]: I didn't find an unsigned int in the openApi docs, so I switched this back to int64.

File: hedera-mirror-rest/service/tokenService.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-rest/service/tokenService.js:149]: Try https://github.com/brianc/node-postgres/issues/1452

[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-rest/service/tokenService.js]: Excellent thanks I have updated it.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM
