### PR TITLE
Fix k6 report generation when scenario failure

### LINKED ISSUE #3474: k6 report generation fails when any scenario fails
### Problem

The generation of the `report.md` does not occur if any scenario has an error that causes it to show 0 rps.

```
INFO[0695] Generating markdown report                    source=console
ERRO[0695] handleSummary() failed with error "TypeError: Cannot read property 'values' of undefined", falling back to the default summary  source=console
```

### Solution

* Provide default metric values to avoid `undefined`
* try/catch scenario generation

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:
* Fix k6 report generation when scenario failure by setting a default object and wrapping in try/catch

**Related issue(s)**:

Fixes #3474

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-test/k6/src/lib/common.js [hunk 1]
```diff
@@ -135,6 +135,29 @@ function markdownReport(data, isFirstColumnUrl, scenarios) {
   // collect the metrics
   const {metrics} = data;
   const scenarioMetrics = {};
+  const defaultMetrics = {
```
Comment (matheus-dallrosa) [inline hedera-mirror-test/k6/src/lib/common.js:138]: Nit: Since the `Object.assign` does not make a deep clone, it would be nice to make a function that return the object with the default metrics to make sure a new object is created every time someone asks for it. This is a nit, because the function is not very big.

**Review by matheus-dallrosa — DISMISSED** [review]

**Review by Nana-EC — DISMISSED** [review]
LGTM

**Review by xin-hedera — DISMISSED** [review]
LGTM

File: hedera-mirror-test/k6/src/lib/common.js (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-test/k6/src/lib/common.js]: Moved to function

**Review by xin-hedera — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]

**Review by matheus-dallrosa — APPROVED** [review]
