### PR TITLE
HIP-584: Make all parameters in request body for estimate gas optional

### LINKED ISSUE #5900: HIP-584: Make all parameters in request body for `eth_estimateGas` optional
### Problem

Currently some of the fields inside the request body used for making eth_estimateGas requests are mandatory, which contradicts with the expected behaviour in Ethereum and causes some issues. For instance having the given code in `ethers.js` would make internal eth_estimateGas request without "to" field, which is currently mandatory.

```
const factory = ethers.getContractFactory("Greeter");
await factory.deploy();
```

This causes an exception:

`"to field must not be empty"`

### Solution

Make all fields in the request body used in `api/v1/contracts/call` optional in the case of `eth_estimateGas`.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by nikolovyanko**
Currently some of the fields inside the request body used for making eth_estimateGas requests are mandatory, which contradicts with the expected behaviour in Ethereum and causes some issues. For instance having the given code in `ethers.js` would make internal eth_estimateGas request without "to" field, which is currently mandatory.

```
const factory = ethers.getContractFactory("Greeter");
await factory.deploy();
```

This causes an exception:

`"to field must not be empty"`

### Solution

Introduce additional validation group [EstimateCheck](https://github.com/hashgraph/hedera-mirror-node/blob/34cf5c2d24b50a43004fc6d643ac087c25da99e5/hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/EstimateCheck.java) to handle it.

Fixes #5900

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java [hunk 1]
```diff
@@ -55,8 +55,11 @@ public class ContractCallRequest {
     @Min(0)
     private long gasPrice;
 
-    @Hex(minLength = ADDRESS_LENGTH, maxLength = ADDRESS_LENGTH)
-    @NotEmpty
+    @Hex(
+            minLength = ADDRESS_LENGTH,
+            maxLength = ADDRESS_LENGTH,
+            groups = {TransferCheck.class, ContractCallRequest.class})
+    @NotEmpty(groups = {TransferCheck.class, ContractCallRequest.class})
```
Comment (nikolovyanko) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:62]: @steven-sheehy @xin-hedera Can I bring your attention to this for an opinion or suggestion? I can't find a working way to achieve the 3 needed flows (the first 2 are already defined):

1. Contract call with all validations(`estimate=false`)
2. Call with a `value` field specified (`TransferCheck` group, `estimate=false` again)
3. The new desired flow, `estimate=true` => omit any validations for the `to` field.

I tried with different groups, custom annotation and validator for it, but couldn't met the all 3 flows. Any ideas? 
The only working suggestion so far(which is kind of ugly) is to check for flow 3 in the `ContractController.call()` method.

Comment (xin-hedera) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:62]: why do groups for `to` include `ContractCallRequest.class`? per my understanding, `ContractCallRequest.class` acts as the default so it's always validated.

can you also clarify the exact fields to validate in the 3 different flows?

Comment (nikolovyanko) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:62]: Yes correct the `ContractCallRequest.class` is the default one. The current implementation is not working as expected anyway.

The 3 different flows:

- Default one , if any of the fields in `ContractCallRequest` is present -> validate with the provided annotations, the only mandatory field is `to`, it should be checked for null and empty value.
- Default + Transfer case:  Inherit the validation behaviour of the default flow + an additional validation constraint for non-null `from` field, in cases where `value > 0` .
- If `estimate == true`  we want to keep the default behaviour for all the fields, except for `to` field. So that we can process estimate calls without `to` field.

To meet the 3th case, I added additional validation group `EstimateCheck` which is added only when `estimate=true`. Then I added `groups = {TransferCheck.class, ContractCallRequest.class}` to both `to` validation annotations, so that they are triggered for all other cases except for `EstimateCheck` group. However, this is not working as expected, because the default group is always present, so the `to` field will be validated even for the `estimate==true` cases.  I hope this made it a bit clearer. Any ideas?

Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:62]: If you have the custom groups inherit `Default` group, then that should solve some of the problem and you don't need to `sequence.add(ContractCallRequest.class);` or add `ContractCallRequest.class` to any group. Then instead of a `EstimateCheck` have a `CallCheck` where `estimate=false`. Have `TransferCheck extends CallCheck`. Then:

```java
    @NotEmpty(groups = CallCheck.class)
    private String to;
```

Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:62]: You might also consider skipping the complicated groups and using `@AssertTrue(message = "..")` on some helper method(s) inside ContractCallRequest for estimate=false and transfer scenarios. I'm not a fan of the `DefaultGroupSequenceProvider` since you're duplicating the conditional logic in two places.

Comment (nikolovyanko) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java]: Great to hear that we can get rid of the groups, thanks for the suggestions! 🙌

**Review by xin-hedera — APPROVED** [review]
LGTM
