### PR TITLE
Fix nft balance and state tracking with nested nft transfer

### LINKED ISSUE #6008: Nest NFT transfers under transaction
### Problem

As an API user, I'd like to avoid the N+1 problem and get all my NFT transfers for a list of transactions with a single call.

### Solution

* Add an NFT transfer column to `transaction`:

```sql
alter table if exists transaction add column if not exists nft_transfer jsonb null;
```
* Update `NftTransfer` to remove top-level entity logic
* Update `Transaction` domain to nest `List<NftTransfer>`
* Update `EntityRecordItemListener` to populate it
* Update `SqlEntityListener` to remove `onNftTransfer()`

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes nft balance and state tracking after nft transfer is nested in transaction

- Add back nft account balance tracking to SqlEntityListener
- Add back nft state and balance tracking for nft treasury change
- Fix token dissociate of deleted token SQL
- Fix nft transfer assertion in test cases
- Fix incorrect flow in several `EntityRecordItemListenerTokenTest` test cases
- Fix some migration tests 

**Related issue(s)**:

Fixes #6008 

**Notes for reviewer**:

This PR also enable workflow runs on PR targeting the epic branch, should revert the changes when merging to main

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java [hunk 1]
```diff
@@ -1753,10 +1709,10 @@ void tokenMintNfts() {
         });
 
         // then
-        var allNftTransfers = collectAllNftTransfers(mintTimestamp);
-        assertThat(allNftTransfers.size()).isEqualTo(2L);
-        assertThat(allNftTransfers.contains(domainNftTransfer(PAYER2, DEFAULT_ACCOUNT_ID, 1, TOKEN_ID)));
-        assertThat(allNftTransfers.contains(domainNftTransfer(PAYER2, DEFAULT_ACCOUNT_ID, 2, TOKEN_ID)));
+        assertNftTransferInRepository(
+                mintTimestamp,
+                domainNftTransfer(PAYER, DEFAULT_ACCOUNT_ID, SERIAL_NUMBER_1, TOKEN_ID),
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java:1714]: there are several test cases with nft mint to a non-treasury account, e.g., here it was minted to `PAYER2` instead of the treasury account `PAYER`. I believe this was changed by a limechain PR.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java [hunk 2]
```diff
@@ -768,24 +736,25 @@ void tokenDissociateDeletedNonFungibleToken() {
...
                 builder -> builder.addTokenTransferLists(dissociateTransfer));
 
         // then
         assertNftInRepository(TOKEN_ID, 1L, true, mintTimestamp, dissociateTimeStamp, PAYER2, true);
-        assertNftInRepository(TOKEN_ID, 2L, true, mintTimestamp, mintTimestamp, PAYER, false);
-        assertTokenInRepository(TOKEN_ID, true, CREATE_TIMESTAMP, dissociateTimeStamp, SYMBOL, 1);
-        var allNftTransfers = collectAllNftTransfers(mintTimestamp);
-        assertThat(allNftTransfers.size()).isEqualTo(2L);
-        assertThat(allNftTransfers.contains(domainNftTransfer(PAYER, DEFAULT_ACCOUNT_ID, 1, TOKEN_ID)));
-        assertThat(allNftTransfers.contains(domainNftTransfer(PAYER, DEFAULT_ACCOUNT_ID, 2, TOKEN_ID)));
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java:784]: these assert nothing, most changes in the file are to fix the incorrect nft transfer assertion

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java [hunk 3]
```diff
@@ -1426,59 +1429,10 @@ void onNftTransferMint(boolean trackBalance) {
...
         }
-        assertThat(collectAllNftTransfers()).containsExactly(nftTransfer);
+        assertThat(transactionRepository.findAll()).containsExactly(transaction);
         assertThat(tokenAccountRepository.findAll()).containsExactly(tokenAccount);
     }
 
-    // currently broken as we are getting back all 3 transfers, instead of the merged one
-    @Test
-    void onNftTransferMultiReceiverSingleTimestamp() {
-        var nftTransfer = domainBuilder.nftTransfer();
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java:1436]: since (token_id, serial_number) is the primary key of `nft_transfer` table, we had to flatten nft transfer if in the record, for the same nft when there are more than 1 transfer. e.g., alice -> bob, then bob -> carol, after flattening, there'll be a single nft transfer from alice to carol.

Once nested, it's no long needed, thus the test case is removed

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java [hunk 4]
```diff
@@ -1426,59 +1429,10 @@ void onNftTransferMint(boolean trackBalance) {
...
-
-        // then
-        var mergedNftTransfer = nftTransfer
-                .customize(n -> n.senderAccountId(entity1).receiverAccountId(entity4))
-                .get();
-        assertThat(collectAllNftTransfers()).containsExactly(mergedNftTransfer);
-    }
-
-    @Test
-    void onNftTransferDuplicates() {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java:1467]: for the same reason that we no longer have the constraint of `(token_id, serial_number)` being the primary key, we no longer dedup nft transfers. I'm also open to add it back

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 5]
```diff
@@ -387,6 +371,29 @@ private void insertFungibleTokenTransfers(
...
+                if (transfer.getSerialNumber() == nftTransfer.getSerialNumber()
+                        && transfer.getReceiverAccountID().equals(nftTransfer.getReceiverAccountID())
+                        && transfer.getSenderAccountID().equals(nftTransfer.getSenderAccountID())) {
+                    return transfer.getIsApproval();
+                }
+            }
+        }
+
+        return false;
+    }
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:395]: logic is from `findNftTransferInsideBody`, just made it more intuitive

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java [hunk 6]
```diff
@@ -327,6 +329,12 @@ void verifyEntityTimestampMigration() throws Exception {
                                 .entityId(receiverId))
                         .get()));
 
+        persistNftTransfers(List.of(
+                // nft transfer
+                nftTransfer(transfer3.getConsensusTimestamp(), receiverId, senderId, 1L, tokenId),
+                // all transfers
+                nftTransfer(transfer5.getConsensusTimestamp(), receiverId, senderId, 2L, tokenId)));
+
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java:337]: the nft transfers were incorrectly removed by the previous PR

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java [hunk 7]
```diff
@@ -2060,7 +2013,7 @@ void nftTransfersHaveCorrectIsApprovalValue(boolean isApproval1, boolean isAppro
 
         // mint transfer / transaction 1
         long mintTimestamp1 = 20L;
-        TokenTransferList mintTransfer1 = nftTransfer(TOKEN_ID, RECEIVER, DEFAULT_ACCOUNT_ID, List.of(SERIAL_NUMBER_1));
+        TokenTransferList mintTransfer1 = nftTransfer(TOKEN_ID, PAYER, DEFAULT_ACCOUNT_ID, List.of(SERIAL_NUMBER_1));
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java:2016]: mint to treasury account `PAYER`, instead of `RECEIVER`

**Review by MarcKriguerAtHedera — APPROVED** [review]
LGTM

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/DeletedTokenDissociateTransferUpsertQueryGenerator.java [hunk 8]
```diff
@@ -24,23 +24,39 @@ public class DeletedTokenDissociateTransferUpsertQueryGenerator implements Upser
...
+                ''token_id'', tdt.token_id
+              )) as transfer
+              from {0} tdt
+              join nft_token on nft_token.token_id = tdt.token_id
+              group by tdt.consensus_timestamp
+            ), update_transaction as (
+              update transaction t
+              set nft_transfer = transfer
+              from nft_transfer nt
+              where nt.consensus_timestamp = t.consensus_timestamp
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/DeletedTokenDissociateTransferUpsertQueryGenerator.java:51]: What's the upper bound on the number of nested nft transfers that could be set on a single transaction here?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java [hunk 9]
```diff
@@ -509,6 +553,18 @@ private List<SharedTransfer> findCryptoTransfers() {
...
 
+    private List<SharedTransfer> findNftTransfers() {
+        return jdbcOperations.query("select * from nft_transfer", (rs, rowNum) -> {
+            SharedTransfer sharedTransfer = new SharedTransfer(
+                    rs.getLong("serial_number"),
+                    rs.getLong("consensus_timestamp"),
+                    EntityIdEndec.decode(rs.getLong("payer_account_id"), EntityType.ACCOUNT),
+                    EntityIdEndec.decode(rs.getLong("receiver_account_id"), EntityType.ACCOUNT),
+                    EntityIdEndec.decode(rs.getLong("sender_account_id"), EntityType.ACCOUNT));
+            return sharedTransfer;
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java:564]: can't use row mapper for `SharedTransfer`, since we map db column `serial_number` to SharedTransfer.amount

**Review by steven-sheehy — APPROVED** [review]
LGTM
