### PR TITLE
Fix get tokens query by account ID filter with shard and realm

### LINKED ISSUE #1586: Tokens REST API account filter with shard and realm
**Detailed Description**
Tokens REST API account filter with shard and realm does not work.

**Actual Behavior**
1. Go to http://mainnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.116946
```json
{"_status":{"messages":[{"message":"Unable to connect to database. Please retry later"}]}}
```
2. Go to http://mainnet.mirrornode.hedera.com/api/v1/tokens?account.id=116946
```json
{"tokens":[{"token_id":"0.0.107762","symbol":"🥩","admin_key":{"_type":"ED25519","key":"653fafb82cd43286c3c38cc9678ecce4e5e0b9c45b16482efd027fc3e0108e54"}}],"links":{"next":null}}
```

**Expected Behavior**
No error in output

**Environment:**
- Java: OpenJDK 11
- OS: Ubuntu 18.04
- Version: 0.26.0

**Additional Context**

### PR DESCRIPTION
**Pull request by xin-hedera**
**Detailed description**:
Support get tokens query by account ID of the format shard.realm.num

**Which issue(s) this PR fixes**:
Fixes #1586 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-rest/tokens.js [hunk 1]
```diff
@@ -309,20 +302,22 @@ const formatTokenBalanceRow = (row) => {
   };
 };
 
+const getEncodedTokenId = (tokenIdStr) => {
```
Comment (Nana-EC) [inline hedera-mirror-rest/tokens.js:305]: This should be in utils as `getEncodedEntityId()` with `constants.filterKeys.TOKENID` passed in as a param.
Then it can be used for all entity id query params requests

File: hedera-mirror-rest/tokens.js [hunk 2]
```diff
@@ -158,7 +158,7 @@ const getTokensRequest = async (req, res) => {
   if (accountId) {
```
Comment (Nana-EC) [inline hedera-mirror-rest/tokens.js:158]: We should be using the `getEncodedEntityId()` method noted below

File: hedera-mirror-rest/tokens.js [hunk 3]
```diff
@@ -309,20 +302,22 @@ const formatTokenBalanceRow = (row) => {
   };
 };
 
+const getEncodedTokenId = (tokenIdStr) => {
+  if (!utils.isValidEntityNum(tokenIdStr)) {
+    throw InvalidArgumentError.forParams(constants.filterKeys.TOKENID);
+  }
+
+  return EntityId.fromString(tokenIdStr).getEncodedId();
```
Comment (steven-sheehy) [inline hedera-mirror-rest/tokens.js:310]: Does this allow input in the form `x.y.z`, `y.z` and `z`? Can we add a test for shard + num?

**Review by Nana-EC — CHANGES_REQUESTED** [review]

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
Can we do a sweep of all APIs to see if any other request entity IDs have the same issue?

File: hedera-mirror-rest/tokens.js (hunk 1 above)
Comment (xin-hedera) [reply hedera-mirror-rest/tokens.js:305]: agree, but prefer to add it to entityid.js. we all don't like a bloated utils module :)

File: hedera-mirror-rest/tokens.js (hunk 3 above)
Comment (xin-hedera) [reply hedera-mirror-rest/tokens.js:310]: I'll check and also add test cases.

Comment (Nana-EC) [reply hedera-mirror-rest/tokens.js:310]: `EntityId.fromString` only does `x.y.z` and encoded `x.y.z`
 I think there's another ticket for what you're noting right?

Comment (steven-sheehy) [reply hedera-mirror-rest/tokens.js:310]: Not that I'm aware of.

Comment (xin-hedera) [reply hedera-mirror-rest/tokens.js]: changed `EntityId.fromString` to support `shard.realm.num`, `realm.num`, and `num`; also note it no longer supports encoded entity ID

renamed `EntityId.fromInt` to `EntityId.fromEncodedId` and now it supports encoded ID of type string, BigInt, and int.

File: hedera-mirror-rest/entityId.js [hunk 4]
```diff
@@ -47,41 +49,42 @@ class EntityId {
...
+  return (typeof entityId === 'string' && /^(\d{1,10}\.){0,2}\d{1,10}$/.test(entityId)) || /^\d{1,10}$/.test(entityId);
+};
+
 const of = (shard, realm, num) => {
   return new EntityId(shard, realm, num);
 };
 
 /**
- * Converts encoded entity ID BigInt to EntityId object.
+ * Converts encoded entity ID (BigInt, int or string) to EntityId object.
```
Comment (ijungmann) [inline hedera-mirror-rest/entityId.js:62]: nit:
```suggestion
 * Converts encoded entity ID (BigInt, int, or string) to EntityId object.
```

**Review by ijungmann — APPROVED** [review]
LGTM, just one Oxford comma missing if you want to go clean that up.

File: hedera-mirror-rest/tokens.js (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-rest/tokens.js]: yes agreed

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
LGTM
