### PR TITLE
Log additional details for query timeout exception

### LINKED ISSUE #8364: Log SQL Timeout Exceptions for Web3
### Problem

Some web3 calls result in a sql timeout. It is unclear what data is triggering this to occur. 

### Solution

We should log all sql timeout exceptions  and include the entire request object in logs if data field is not to big. 

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by jnels124**
**Description**:
* log additional details when queury timeout exception occurs 

**Related issue(s)**:

Fixes #8364

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jascks — DISMISSED** [review]
LGTM

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java [hunk 1]
```diff
@@ -79,12 +79,36 @@ ContractCallResponse call(@RequestBody @Valid ContractCallRequest request) {
...
+                        .append(params.getGas())
+                        .append(" value: ")
+                        .append(params.getValue());
+
+                if (params.getCallData() != null
+                        && params.getCallData().size()
+                                < ((evmProperties.getMaxDataSize().toBytes()) * .75)) {
+                    paramsString.append(" data: ").append(params.getCallData().toHexString());
+                }
+            }
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java:109]: This is verbose and brittle. We should just log the `ContractCallRequest` directly. I don't think we need to truncate the call data since query time outs should be infrequent.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java [hunk 2]
```diff
@@ -79,12 +79,36 @@ ContractCallResponse call(@RequestBody @Valid ContractCallRequest request) {
...
+
+            throw new QueryTimeoutException(e.getMessage() + " Params: " + paramsString);
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java:111]: Seems like we're creating this wrapper exception just so we can capture the request and use it to log in `ContractController.queryTimeout()`. Instead, we should just remove that log in the exception handler and log here but still throw.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java (hunk 1 above)
Comment (jnels124) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java:109]: I agree. When discussed in standup this was requested. I can remove the data size limitation.

Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java:109]: Yeah, I waffled on the truncating. But if we were to truncate we would just `request.setData(truncate(request.getData())` then use its `toString()`.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java (hunk 2 above)
Comment (jnels124) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java:111]: I can do that. Was hesitant to remove the log from the exception handler in case future code changes introduce a timeout exception outside of this block.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java [hunk 3]
```diff
@@ -79,12 +79,16 @@ ContractCallResponse call(@RequestBody @Valid ContractCallRequest request) {
...
+        CallServiceParameters params = null;
         try {
             validateContractData(request);
             validateContractMaxGasLimit(request);
 
-            final var params = constructServiceParameters(request);
+            params = constructServiceParameters(request);
             result = contractCallService.processCall(params);
+        } catch (QueryTimeoutException e) {
+            log.error("Query timed out: {}", e.getMessage() + " request: " + request);
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java:90]:
```suggestion
            log.error("Query timed out: {}, request: {}", e.getMessage(), request);
```

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java [hunk 4]
```diff
@@ -79,12 +79,16 @@ ContractCallResponse call(@RequestBody @Valid ContractCallRequest request) {
         }
 
         String result;
+        CallServiceParameters params = null;
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java:82]: Revert

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java (hunk 2 above)
Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java]: If we want to capture the request object in the handler we could use `webRequest.setAttribute("request", request, RequestAttributes.SCOPE_REQUEST);` in the controller to set it and retrieve in handler.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java (hunk 4 above)
Comment (jnels124) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java]: ya caught that. thanks.

**Review by steven-sheehy — APPROVED** [review]
LGTM

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java (hunk 3 above)
Comment (jnels124) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java]: caught that too you were too quick
