### PR TITLE
Fix Internal error with shard.realm.evmAddress in entityId parsing

### LINKED ISSUE #3658: Internal error with shard.realm.evmAddress parameter to contract APIs
### Description

When calling contract REST APIs with the `shard.realm.evmAddress` as a path parameter we return an internal server error.

Additionally, a partner complained that sending the EVM address with a `0x` prefix no longer works when it used to. I believe we removed it because it looks strange with the shard and realm e.g. `0.0.0x000000000000000000000000000000000186Fb1b`.

Instead, we should support `000000000000000000000000000000000186Fb1b` OR `0x000000000000000000000000000000000186Fb1b` OR `0.0.000000000000000000000000000000000186Fb1b` but not `0.0.0x000000000000000000000000000000000186Fb1b`.

### Steps to reproduce

https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.000000000000000000000000000000000186Fb1b/results
https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.000000000000000000000000000000000186Fb1b/results/logs

```json
{"_status":{"messages":[{"message":"Internal error"}]}}
```

https://testnet.mirrornode.hedera.com/api/v1/contracts/0x000000000000000000000000000000000186Fb1b/results/logs

```json
{"_status":{"messages":[{"message":"Invalid parameter: contractid"}]}}
```

### Additional context

```
8|6558  | 2022-04-26T15:54:49.787Z ERROR 23853ab7 75.12.148.71 GET /api/v1/contracts/0.0.000000000000000000000000000000000186Fb1b/results/logs in 1 ms: 500 Internal error SyntaxError: Cannot convert 0x0.0.0000 to a BigInt
8|6558  |     at BigInt (<anonymous>)
8|6558  |     at parseFromEvmAddress (/opt/restapi/entityId.js:184:5)
8|6558  |     at /opt/restapi/entityId.js:238:29
8|6558  |     at /opt/restapi/node_modules/mem/dist/index.js:46:27
8|6558  |     at Object.parse (/opt/restapi/entityId.js:284:41)
8|6558  |     at ContractService.computeContractIdFromString (/opt/restapi/service/contractService.js:281:21)
8|6558  |     at getContractLogs (/opt/restapi/controllers/contractController.js:458:44)
8|6558  |     at wrappedMiddleware (/opt/restapi/node_modules/@awaitjs/express/index.js:62:26)
8|6558  |     at Layer.handle [as handle_request] (/opt/restapi/node_modules/express/lib/router/layer.js:95:5)
8|6558  |     at next (/opt/restapi/node_modules/express/lib/router/route.js:137:13)
```

### Hedera network

testnet

### Version

v0.54.0

### Operating system

macOS

### PR DESCRIPTION
**Pull request by edwin-greene**
**Description**:
Fix the internal error with parsing an evmAddress that includes `0.0.` at the beginning of the address.

**Related issue(s)**:

Fixes #3658

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/entityId.js [hunk 1]
```diff
@@ -179,7 +179,7 @@ const parseFromEncodedId = (id, error) => {
  */
 const parseFromEvmAddress = (evmAddress) => {
   // extract shard from index 0->8, realm from 8->23, num from 24->40 and parse from hex to decimal
-  const hexDigits = evmAddress.replace('0x', '');
+  const hexDigits = evmAddress.replace('0x', '').replace('0.0.', '');
```
Comment (steven-sheehy) [inline hedera-mirror-rest/entityId.js:182]: We can't assume that shard or realm is always zero as that will break in the future once we have non-zero values.

File: hedera-mirror-rest/__tests__/specs/contracts-results-10-period-including-address.spec.json [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+        "gas_limit": 987654,
+        "gas_used": 123,
+        "payer_account_id": 8001
+      }
+    ]
+  },
+  "urls": [
+    "/api/v1/contracts/0.0.000000000000000000000000000000000186Fb1b/results",
+    "/api/v1/contracts/000000000000000000000000000000000186Fb1b/results"
+  ],
```
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-rest/__tests__/specs/contracts-results-10-period-including-address.spec.json:56]: Can you open a P1 ticket for it then?

[the remark this answers is not in the document]
Comment (matheus-dallrosa) [reply hedera-mirror-rest/__tests__/specs/contracts-results-10-period-including-address.spec.json:56]: I think we can do it all here on this PR. I will push the fix soon.

File: hedera-mirror-rest/entityId.js (hunk 1 above)
Comment (matheus-dallrosa) [reply hedera-mirror-rest/entityId.js]: Fixed.

File: hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json [hunk 3]
```diff
@@ -0,0 +1,94 @@
+{
+  "description": "Contract results api call for a specific contract using contract id",
```
Comment (Nana-EC) [inline hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json:2]: Update description

File: hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+        "function_result": [8, 8],
+        "gas_limit": 987654,
+        "gas_used": 123,
+        "payer_account_id": 8001
+      }
+    ]
+  },
+  "urls": [
+    "/api/v1/contracts/0.0.000000000000000000000000000000000186Fb1b/results",
+    "/api/v1/contracts/000000000000000000000000000000000186Fb1b/results",
```
Comment (Nana-EC) [inline hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json:55]: nit: add the single `0.` option also

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Looking good, minor test update suggestions on 1st pass

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by xin-hedera — DISMISSED** [review]
LGTM

File: hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json:55]: I'd presume `0.000000000000000000000000000000000186Fb1b` is a supported format since we usually support `0.0.x/0.x/x`

Comment (matheus-dallrosa) [reply hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json:56]: Done.

File: hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json (hunk 3 above)
Comment (matheus-dallrosa) [reply hedera-mirror-rest/__tests__/specs/contracts-results-10-evm-address-path-param.spec.json]: Done.

**Review by steven-sheehy — DISMISSED** [review]

File: hedera-mirror-rest/__tests__/entityId.test.js [hunk 5]
```diff
@@ -132,6 +132,19 @@ describe('EntityId parse from entityId string', () => {
       expected: EntityId.of(32767, 65535, 4294967295),
       paramName: constants.filterKeys.FROM,
     },
+    {
+      entityIdStr: '0.0.000000000000000000000000000000000186Fb1b',
+      expected: EntityId.of(0, 0, 25623323),
+    },
+    {
```
Comment (Nana-EC) [inline hedera-mirror-rest/__tests__/entityId.test.js:139]: Nit: Add the `0.000000000000000000000000000000000186Fb1b` test

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Minor test missing then it'll be good to go

File: hedera-mirror-rest/__tests__/entityId.test.js (hunk 5 above)
Comment (matheus-dallrosa) [reply hedera-mirror-rest/__tests__/entityId.test.js:139]: Done.

**Review by Nana-EC — APPROVED** [review]
LGTM
