### PR TITLE
Enhance web3 error response with detail message

### LINKED ISSUE #5399: HIP-584: Add revert reason for failing requests in web3 module
### Problem

Currently when we call `api/v1/contracts/call` under the web3 module and there is a failure in the execution, we return only the error code in the message field of the JSON error response. It looks like this:

```
{
    "_status": {
        "messages": [
            {
                "message": "CONTRACT_REVERT_EXECUTED"
            }
        ]
    }
}
```

Currently on the json-rpc-relay side, failing `eth_call` requests sent to the consensus node return also the detailed revert reason, which is consumed from the relay. It would be useful this revert reason to be also enhanced in the web3 module on mirror-node side.

### Solution

Add additional field `detail` to the json error response body under web3 submodule.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by IvanKavaldzhiev**
**Description**:

This PR enhances the GenericResponse used by web3 module with a human readable detail revert message (when applicable). This message is then used by the json-relay to be propagated to the end user. 

**Related issue(s)**:

Fixes #5399 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import com.esaulpaugh.headlong.abi.ABIType;
+import com.esaulpaugh.headlong.abi.Tuple;
+import com.esaulpaugh.headlong.abi.TypeFactory;
+import org.apache.commons.lang3.StringUtils;
+import org.apache.tuweni.bytes.Bytes;
+
+public class BytesDecoder {
+
+    private BytesDecoder() {
+        //Utility class
```
Comment (nikolovyanko) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java:32]: You can remove the private constructor and use the `@UtilityClass` lombok annotation instead.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+        Bytes encodedMessage = revertReason;
+
+        if(ERROR_SIGNATURE_BYTES.equals(revertReason.slice(0, SIGNATURE_BYTES_LENGTH))) {
+            encodedMessage = revertReason.slice(SIGNATURE_BYTES_LENGTH);
+        }
+
+        return STRING_DECODER.decode(encodedMessage.toArray()).get(0);
+    }
+}
```
Comment (edwin-greene) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java:54]: Would be good to have a `BytesDecoderTest.java` that tests inputs and expected outputs (and exceptions if there are any), similar to this type of test: 

```
    @ParameterizedTest(name = "Convert {0} to snake case")
    @CsvSource({
            ",",
            "\"\",\"\"",
            "Foo,foo",
            "FooBar,foo_bar",
            "foo_bar,foo_bar"
    })
    void toSnakeCase(String input, String output) {
        assertThat(Utility.toSnakeCase(input)).isEqualTo(output);
    }
    ```

Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java:54]: Agreed but please use the newer `@CsvSource(textBlock = """` as seen in `GraphQlUtilsTest`.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/GenericErrorResponse.java [hunk 3]
```diff
@@ -39,12 +39,19 @@ public GenericErrorResponse(String message) {
...
+    }
+
     public GenericErrorResponse(List<String> errorMessages) {
         errorMessages.forEach(m -> messages.add(new ErrorMessage(m)));
     }
 
     @Data
     public static class ErrorMessage {
         private final String message;
+        private String detail;
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/GenericErrorResponse.java:55]: Would prefer this mutable subclass of an immutable parent also be made immutable via `@Value` and final fields.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+    }
+
+    //Error(string)
+    private static final String ERROR_SIGNATURE = "0x08c379a0";
+    private static final Bytes ERROR_SIGNATURE_BYTES = Bytes.fromHexString(ERROR_SIGNATURE);
+    private static final ABIType<Tuple> STRING_DECODER = TypeFactory.create("(string)");
+    private static final int SIGNATURE_BYTES_LENGTH = 4;
+
+    public static String decodeBytesToReadableMessage(final Bytes revertReason) {
+        if(revertReason.isEmpty()) {
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java:42]: Is there any chance it can be null?

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+            return StringUtils.EMPTY;
+        }
+
+        Bytes encodedMessage = revertReason;
+
+        if(ERROR_SIGNATURE_BYTES.equals(revertReason.slice(0, SIGNATURE_BYTES_LENGTH))) {
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java:48]: Need to do bounds checking first to see if bytes is > SIGNATURE_BYTES_LENGTH (to see if at least one byte past signature)

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+            encodedMessage = revertReason.slice(SIGNATURE_BYTES_LENGTH);
+        }
+
+        return STRING_DECODER.decode(encodedMessage.toArray()).get(0);
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java:52]: I'm not sure on the headlong API, but we should probably do bounds checking before accessing the first element.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good
