### PR TITLE
Fix REST Java fallback exception handling

### LINKED ISSUE #8078: Fix controller advice to catch all exceptions
### Description

Referring to https://github.com/hashgraph/hedera-mirror-node/pull/8026#discussion_r1562919240
Exceptions thrown by the controller are not being handled by the Exception handler in the Controller advice in the rest-java module.Need to handle it.

### Steps to reproduce

1. Provide invalid Input or method to the nft allowances rest endpoint.
2. The exception response does not follow the Error message format from the rest java module.

### Additional context

_No response_

### Hedera network

mainnet

### Version

v.0.103.0

### Operating system

None

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Move CORS handling to common advice
* Fix fallback exception handling to use our error response message
* Some minor code cleanup

**Related issue(s)**:

Fixes #8078

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java [hunk 1]
```diff
@@ -54,7 +52,6 @@ public class AllowancesController {
     private final NftAllowanceService service;
     private final NftAllowanceMapper nftAllowanceMapper;
 
-    @CrossOrigin(origins = "*")
     @GetMapping(value = "/nfts")
     @SuppressWarnings("java:S5122")
```
Comment (mgoelswirlds) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java:56]: nit: Probably need to move this suppression as well.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by mgoelswirlds — APPROVED** [review]

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java]: Thanks, fixed
