### PR TITLE
Fix failed crypto transfers with non-fee transfers enabled crashing importer

### LINKED ISSUE #647: Crash importing records into non_fee_transfers
**Detailed Description**
There are a few transfers in mainnet where the entity_num > 2147483647.  When the mirror node attempts to put these transfers into the non_fee_transfers table it crashes since the value is outside the range.

**Actual Behavior**
1. Set up a mirror node where it saves non_fee_transfers.
2. Create a transaction and have the receiving account be 0.0. 100000000000 and send.
3. The server will charge you a fee and then return ACCOUNT_ID_DOES_NOT_EXIST
4. When the mirror node attempt to add this transfer to the non_fee_transfers table it will throw and exception and get stuck on that file.

**Expected Behavior**
Not sure exactly - if the mainnet server allows invalid account numbers via the API then I guess the mirror node needs to throw the non_fee_transfer parts away. I guess checks should also be in place for the t_crytotransferlist and t_entities tables.
FYI - the t_entities table has entity_num as a "bigint"

**Environment:**
- 0.5.4 mirror node, saving non_fee_transfers
- mainnet

**Additional Context**

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
Only add non-fee transfers for successful transactions.

**Which issue(s) this PR fixes**:
Fixes #647 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 1]
```diff
@@ -112,7 +112,12 @@ public void onItem(RecordItem recordItem) throws ImporterException {
...
         if ((txRecord.hasTransferList()) && entityProperties.getPersist().isCryptoTransferAmounts()) {
-            processNonFeeTransfers(consensusNs, body, txRecord);
+            // Don't add failed non-fee transfers as they can contain invalid data and we don't add failed
+            // transactions for aggregated transfers
+            if (isSuccessful) {
+                processNonFeeTransfers(consensusNs, body, txRecord);
+            }
+
             if (body.hasCryptoCreateAccount() && isSuccessful(txRecord)) {
                 insertCryptoCreateTransferList(consensusNs, txRecord, body);
```
Comment (apeksharma) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:122]: Just realized that logic in `insertCryptoCreateTransferList` may be duplicating transfers related to initialBalance which have already been processed by processNonFeeTransfers.
PTAL.

Comment (apeksharma) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:122]: It's weird that we store initialBalance related transfers in t_ctl for cryptoCreate txns, but not for contractCreate or contractCall(amount transferred).
We need to define this clearly. couple options being:
- all transfers in `t_ctl` table, only non-fee transfer in `non_fee_transfers` table
- all fee transfers in one table, all non-fee transfers in another (not good since it'll require more merges and restarting from clean slate)

Comment (apeksharma) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:122]: we can actually replace this if-else with just `insertTransferList(consensusNs, txRecord.getTransferList());`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 2]
```diff
@@ -112,7 +112,12 @@ public void onItem(RecordItem recordItem) throws ImporterException {
...
             } else {
```
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:123]: We cannot do this for successful only. A contract call is different than other transactions since it could've been executed but been unsuccessful part way through due to contract logic. We still want to show those results so users can debug the transaction output (e.g. callResult) and also show how much gas was used. It does however make sense to only insert to t_contract result if `transactionRecord.hasContractCreateResult()` or `transactionRecord.hasContractCallResult()`. I can make that change.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:122]: It looks to be necessary. The `insertCryptoCreateTransferList()` normalizes the transfer list to include an entry for zero initial balance because the `record.transferList` does not include such an entry. `record.transferList` only includes an entry for initial balance if it's non-zero. Technically it doesn't check for zero directly but for any missing transfers for the created account, so this may also have been necessary for some past bug in transfer list generation.

Either way, I don't think we should change it as I'm not sure how this logic is depended upon. It definitely doesn't impact the fix for this particular ticket, so if you feel it should be changed still please discuss with subject matter experts first and create a ticket if they agree.

Here's a crypto create account with a non-zero initial balance of 100000000 (expand the raw transaction):
https://app.dragonglass.me/hedera/transactions/0077781589999433221364021

Here's the same transaction's CTL:
```
mirror_node=> select * from t_cryptotransferlists where consensus_timestamp = 1589999434016444000;
 consensus_timestamp | realm_num | entity_num |   amount
---------------------+-----------+------------+------------
 1589999434016444000 |         0 |         13 |    1586062
 1589999434016444000 |         0 |         98 |   25303227
 1589999434016444000 |         0 |       7778 | -126889289
 1589999434016444000 |         0 |      42871 |  100000000
```

Here's a crypto create account with a zero initial balance:
https://app.dragonglass.me/hedera/transactions/00281441590000047689000000

Here's the same transaction's CTL:
```
mirror_node=> select * from t_cryptotransferlists where consensus_timestamp = 1590000058306981003;
 consensus_timestamp | realm_num | entity_num |  amount
---------------------+-----------+------------+-----------
 1590000058306981003 |         0 |          3 |   1647073
 1590000058306981003 |         0 |         98 |  26096244
 1590000058306981003 |         0 |      28144 |         0
 1590000058306981003 |         0 |      28144 | -27743317
 1590000058306981003 |         0 |      42873 |         0
```

Note that it does create an extra zero transfer to payer account that the first transaction does not, which is a little strange.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 3]
```diff
@@ -93,11 +93,11 @@ public void onItem(RecordItem recordItem) throws ImporterException {
         TransactionRecord txRecord = recordItem.getRecord();
         TransactionBody body = recordItem.getTransactionBody();
         TransactionHandler transactionHandler = transactionHandlerFactory.create(body);
-        log.trace("Processing transaction : {}", () -> Utility.printProtoMessage(body));
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:96]: We already log the full transaction proto in RecordFileParser

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java (hunk 1 above)
Comment (apeksharma) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:122]: Separate ticket is good since it's unrelated and not clear at this point.
