### PR TITLE
Only update entities, via the record stream, if the transaction was successful

### LINKED ISSUE #240: Record stream processor updates entities even when transaction failed
**Detailed Description**
Entities (account, file, contract) are updated by the record stream processor even when the transaction failed

**Actual Behavior**

**Expected Behavior**

**Environment:**

**Additional Context**

### PR DESCRIPTION
**Pull request by mike-burrage-hedera**
**Detailed description**:

Update RecordFileLogger to only update an entity if the transaction was successful.

**Which issue(s) this PR fixes**:
Fixes #240 

**Special notes for your reviewer**:

The entity may be created (empty) even on failure due to the fact that it should have been validated pre-consensus and this allows the t_transactions record to still refer to it.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java [hunk 1]
```diff
@@ -390,15 +414,20 @@ public static boolean storeRecord(Transaction transaction, TransactionRecord txR
...
-                    entities.createOrGetEntity(body.getCryptoDelete().getDeleteAccountID());
-                    entityId = entities.deleteEntity(body.getCryptoDelete().getDeleteAccountID());
+                    var accountId = body.getCryptoDelete().getDeleteAccountID();
+                    if (doUpdateEntity) {
+						entityId = entities.deleteEntity(accountId);
+					} else {
+						entityId = entities.createOrGetEntity(accountId);
+					}
                 }
             } else if (body.hasCryptoDeleteClaim()) {
```
Comment (gregscullard) [inline src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: This will need review (not now), claims aren't supported at OA. But we're not marking the claim (live hash) as deleted, neither is there a column on the database to store that. Will raise an issue to track post OA.

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java [hunk 2]
```diff
@@ -459,10 +497,12 @@ public static boolean storeRecord(Transaction transaction, TransactionRecord txR
...
-
+            	if (doUpdateEntity) {
+					long proxy_account_id = 0;
+					entityId = entities.updateEntity(fileId, expiration_time_sec, expiration_time_nanos, auto_renew_period, key, proxy_account_id);
+				} else {
+            		entityId = entities.createOrGetEntity(fileId);
+				}
 			} else if (body.hasSystemDelete()) {
 				if (body.getSystemDelete().hasContractID()) {
 					entities.createOrGetEntity(body.getSystemDelete().getContractID());
```
Comment (gregscullard) [inline src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: Appears to be missing doUpdateEntity check

Comment (gregscullard) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: likewise for systemUndelete

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java [hunk 3]
```diff
@@ -501,18 +541,20 @@ public static boolean storeRecord(Transaction transaction, TransactionRecord txR
...
-                insertCryptoAddClaim(consensusNs, body.getCryptoAddClaim());
-            } else if (body.hasFileAppend()) {
-                insertFileAppend(consensusNs, body.getFileAppend());
-            } else if (body.hasFileCreate()) {
-                insertFileCreate(consensusNs, body.getFileCreate(), txRecord);
-            } else if (body.hasFileUpdate()) {
-                insertFileUpdate(consensusNs, body.getFileUpdate());
+			if (doUpdateEntity) {
+				if (body.hasContractCall()) {
+					insertContractCall(consensusNs, body.getContractCall(), txRecord);
```
Comment (gregscullard) [inline src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: I think we should still call insertContractCall, results will be empty, but functionParams and gasSupplied will be valid data to store.

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java [hunk 4]
```diff
@@ -501,18 +541,20 @@ public static boolean storeRecord(Transaction transaction, TransactionRecord txR
...
+				} else if (body.hasContractCreateInstance()) {
+					insertContractCreateInstance(consensusNs, body.getContractCreateInstance(), txRecord);
```
Comment (gregscullard) [inline src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: Same as insertContractCall

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 1 above)
Comment (gregscullard) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: Raised issue #243

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 4 above)
Comment (mike-burrage-hedera) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: Are both these 2 comments for the same line?

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 2 above)
Comment (mike-burrage-hedera) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: will do

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 4 above)
Comment (gregscullard) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: One was `insertContractCall`, the other was `insertContractCreateInstance`

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 1 above)
Comment (mike-burrage-hedera) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: I think this comment can be resolved now that the PR's in.

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 2 above)
Comment (mike-burrage-hedera) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: Done.

Comment (mike-burrage-hedera) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: FYI - undelete on file was broken.

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 3 above)
Comment (mike-burrage-hedera) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: done.

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 4 above)
Comment (mike-burrage-hedera) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: Why should the insertContractCreateInstance that failed update the entity?

Comment (gregscullard) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: The entity shouldn't be updated but `insertContractCall` should be called, this inserts into the `t_contract_result` table, which includes `function_params` and `gas_supplied` which are supplied by the transaction. If the status is `INSUFFICIENT_GAS` this information could be useful to users of mirror node even though there is no `call_result`, `gas_used` could also yield useful information.

Comment (mike-burrage-hedera) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: Done.
