### PR TITLE
Fix invalid next link when the last pagination param has eq operator

### LINKED ISSUE #8407: RestJava LinkFactory creates invalid next link when the last pagination param has eq operator
### Description

Given the request url `http://mirror-restjava/api/v1/accounts/99550/allowances/nfts?limit=2&account.id=gte:0.0.99700&token.id=0.0.99800`, and there are more than the `limit` number of matching results, the link factory will create such a next link:

```json
"links": {
  "next": "/api/v1/accounts/99550/allowances/nfts?limit=2&token.id=0.0.99800&token.id=gt:0.0.99800&account.id=gte:0.0.99701"
}
```

Following the link will get a 400 code with the body

```json
{
  "_status": {
    "messages": [
      {
        "data": null,
        "detail": null,
        "message": "Can't support both range and equal for token.id"
      }
    ]
  }
}
```

The correct next link should be `/api/v1/accounts/99550/allowances/nfts?limit=2&token.id=0.0.99800&account.id=gt:0.0.99701`.

In general, with the pagination parameters in the order from the left most to the right most, if the current pagination parameter's operator is `eq`, the link factory should copy the existing `p=v` pair from the request URL, and the operator for the pagination parameter before it should be exclusive.

### Steps to reproduce

check the description

### Additional context

_No response_

### Hedera network

other

### Version

v0.106.0-rc1

### Operating system

None

### PR DESCRIPTION
**Pull request by edwin-greene**
**Description**:

Fixes the next link generation and corrects the succeeding query parameter operators.

**Related issue(s)**:

Fixes #8407

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 1]
```diff
@@ -62,39 +64,79 @@ private <T> String createNextLink(
         var sortOrders = pageable.getSort();
         var primarySort = Iterables.getFirst(sortOrders, null);
         var order = primarySort == null ? Direction.ASC : primarySort.getDirection();
-        var lastSort = Iterables.getLast(sortOrders, null);
-        // Only the last sort param's value is exclusive
-        var exclusiveParam = lastSort != null ? lastSort.getProperty() : null;
         var builder = UriComponentsBuilder.fromPath(request.getRequestURI());
         var paramsMap = request.getParameterMap();
         var paginationParamsMap = extractor.apply(lastItem);
+        var linkedMultiValueMap = new LinkedMultiValueMap<String, String>();
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:70]: this is really bad variable name.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 2]
```diff
@@ -62,39 +64,79 @@ private <T> String createNextLink(
...
 
+        addParamMapToLink(paramsMap, paginationParamsMap, order, linkedMultiValueMap);
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:72]: the function name reads as add them to link, actually it adds items to a map. Adding to link is an operation which happens later.

```suggestion
        addParamMapToLink(paramsMap, paginationParamsMap, order, linkedMultiValueMap);
```

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 3]
```diff
@@ -62,39 +64,79 @@ private <T> String createNextLink(
...
             if (isSameDirection(order, value)) {
                 continue;
             }
 
-            builder.queryParam(entry.getKey(), value);
+            linkedMultiValueMap.add(entry.getKey(), value);
+            if (hasEq(value)) {
+                // Only 1 eq is allowed, return without adding additional values
+                return;
+            }
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:107]: remove. this is invalid, and the factory should not assume rules enforced by controllers.

```suggestion
```

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 4]
```diff
@@ -62,39 +64,79 @@ private <T> String createNextLink(
...
+            Map<String, String> paginationParamsMap,
+            Direction order,
+            LinkedMultiValueMap<String, String> linkedMultiValueMap) {
+        var sortKeys = sort.map(Sort.Order::getProperty).toList();
+        if (sortKeys.isEmpty()) {
+            for (var entry : paginationParamsMap.entrySet()) {
+                linkedMultiValueMap.add(entry.getKey(), entry.getValue());
+            }
+            return;
+        }
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:122]: if somehow no sort keys provided, run the other logic to determine whether the operator should be exclusive or not. We should not short cut here.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 5]
```diff
@@ -62,39 +64,79 @@ private <T> String createNextLink(
...
+
+        for (int i = 0; i < sortKeys.size(); i++) {
+            var key = sortKeys.get(i);
+            if (linkedMultiValueMap.containsKey(key) && containsEq(linkedMultiValueMap.get(key))) {
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:126]: the containsEq logic runs twice for the same query parameter, instead, we should preprocess if for the sort columns and store the result for reuse.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 6]
```diff
@@ -62,39 +64,79 @@ private <T> String createNextLink(
...
+                // This query parameter has already been added with an eq
+                continue;
+            }
+
+            var entry = paginationParamsMap.get(key);
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:131]:
```suggestion
            var value = paginationParamsMap.get(key);
```

since `entry` is misleading.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 7]
```diff
@@ -112,4 +154,21 @@ private static boolean isSameDirection(Direction order, String value) {
             case DESC -> normalized.startsWith("lt:") || normalized.startsWith("lte:");
         };
     }
+
+    private static boolean containsEq(List<String> values) {
+        if (values != null) {
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:159]: no need to do null check
```suggestion
```

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 8]
```diff
@@ -112,4 +154,21 @@ private static boolean isSameDirection(Direction order, String value) {
...
+                }
+            }
+        }
+
+        return false;
+    }
+
+    private static boolean hasEq(String value) {
+        var normalized = value.toLowerCase();
+        return normalized.startsWith("eq:") || (!normalized.startsWith("gt") && !normalized.startsWith("lt"));
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:172]: what if a value starts with `gt` or `lt` however it's not an operator?

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 2 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Thanks I have updated these method names.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 3 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Sounds good I have removed it.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 4 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Got it, I have removed this section.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 5 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Thanks I have updated it to perform the `containsEq` for each sort prior to the rest.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 6 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Thanks I have updated it.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 7 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:151]: I have removed it.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 8 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Got it ok, I have updated it to include the ":" and each operator to validate that the string is believed to be an operator.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 7 above)
Comment (xin-hedera) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:151]: it's still here

Comment (xin-hedera) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:151]: Since the logic has changed I see now null check is needed. Just a nit, short cut return false, so we have less nested logic.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 9]
```diff
@@ -62,39 +65,70 @@ private <T> String createNextLink(
...
+            queryParams.add(entry.getKey(), value);
+        }
+    }
+
+    private void addExtractedParamsToQueryParams(
+            Sort sort,
+            Map<String, String> paginationParamsMap,
+            Direction order,
+            LinkedMultiValueMap<String, String> queryParams) {
+        var sortEqMap = new TreeMap<String, Boolean>();
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:113]: `TreeMap` sorts keys in its natural order, so it's not the order the pagination params.

Naive way is just use a for loop and create both a linkedList and map.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java [hunk 10]
```diff
@@ -62,39 +65,70 @@ private <T> String createNextLink(
...
+            if (queryParams.containsKey(key) && Boolean.TRUE.equals(sortEqMap.get(key))) {
+                // This query parameter has already been added with an eq
+                continue;
+            }
+
+            var exclusive = true;
+            if (sortKeys.length > i + 1) {
+                var succeedingKey = sortKeys[i + 1];
+                exclusive = sortEqMap.get(succeedingKey);
+            }
```
Comment (xin-hedera) [inline hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java:128]: shorten it to a ternary expression.

```suggestion
            boolean exclusion = sortKeys.size() > i + 1 ? sortEqMap.get(sortKeys.get(i + 1)) : true;
```

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 7 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Thanks I originally mistook it for another item I removed. I have updated it to have the short cut.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 9 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Thanks!! I have fixed it so that the order will be correct, it won't use the map for iterating anymore.

File: hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java (hunk 10 above)
Comment (edwin-greene) [reply hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/LinkFactoryImpl.java]: Thanks I have made this update

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by jnels124 — APPROVED** [review]
LGTM
