### PR TITLE
Recover from account balance files with different timestamps

### LINKED ISSUE #804: Recover from account balance files with different timestamps
**Detailed Description**
Twice on mainnet we have seen a scenario where a particular account balance signature is failing to verify. The logs will repeatedly print every polling period (30s):

```
c.h.m.i.d.b.AccountBalancesDownloader Signature verification failed for 2020-06-03T17_00_01.985229Z_Balances.csv_sig: {MISSING=[0.0.10, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9], VERIFIED=[0.0.11]}
```

Investigation revealed one node had a balance file with a close, but slightly different timestamp for its filename than other nodes. In the above case, node 0.0.11 had `2020-06-03T17_00_01.985229Z_Balances.csv_sig` while every other node had `2020-06-03T17_00_00.672290001Z_Balances.csv_sig`.

**Actual Behavior**
Signature fails to verify

**Expected Behavior**
Importer should detect and recover from the scenario until main nodes can implement a permanent fix.

**Environment:**
- Java: OpenJDK 11.0.2
- OS: Ubuntu 18.04
- Version: v0.10.1

**Additional Context**

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
- Add `hedera.mirror.importer.downloader.(balance|event|record).closeInterval` for use in calculating expected buckets
- Move stream close metric to parent so it can be used later with events
- Change signature verification to group files into time buckets then group by filename within that bucket and ensure at least one file in bucket reaches 1/3 consensus

**Which issue(s) this PR fixes**:
Fixes #804 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java [hunk 1]
```diff
@@ -401,6 +403,17 @@ public static File getResource(String path) {
         }
     }
 
+    public static final long getTimestampFromFilename(String filename) {
+        if (StringUtils.isBlank(filename)) {
+            return 0L;
+        }
+
+        String nameWithoutExtension = FilenameUtils.removeExtension(filename);
+        String date = StringUtils.removeEnd(nameWithoutExtension, StreamType.BALANCE.getSuffix()).replace('_', ':');
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:412]: method name seems to be general and therefore not concerned  with file type (balance/record/event), but removeEnd() applied to only Balances.
You should either rename the function to highlight Balance or make it work for all 3 types for shared use.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java [hunk 2]
```diff
@@ -299,15 +302,64 @@ void overwriteOnDownload() throws Exception {
...
+    }
+
+    @Test
+    @DisplayName("Different filenames, next interval")
+    void differentFilenamesNextInterval() throws Exception {
+        differentFilenames(downloaderProperties.getCloseInterval().dividedBy(2L));
+    }
+
+    private void differentFilenames(Duration offset) throws Exception {
+        fileCopier.filterFiles(file2 + "*").copy();
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java:344]: nit: quite the involved setup on files. A few comments might make it easier to read and therefore easier to maintain

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java [hunk 3]
```diff
@@ -211,18 +215,36 @@ protected void downloadNextBatch() {
...
+                                } else {
+                                    double interval = (double) (currentTimestamp - lastValidTimestamp);
+                                    long bucket = Math.round(interval / closeInterval);
+                                    long groupTimestamp = lastValidTimestamp + bucket * closeInterval +
+                                            closeInterval / 2;
+
+                                    if (bucket > 0) {
+                                        sigFilesMap.put(groupTimestamp, fileStreamSignature);
+                                    } else {
+                                        log.warn("Ignoring signature file {} from node {} associated with the " +
```
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:240]: It does, doesn't it? It says it's associated with the previous close interval. You want me to tweak it to say "the previously processed interval"?

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:412]: The method is named general and does work for all 3 types, as its test shows. True, it's a bit of a hack to do something specific to balance but it saves me from either having 3 different methods or passing in streamtype. Balance file is the only file with an extra suffix of `_Balance` after the date and before the extension. What do you suggest?

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:240]: On 2nd read it does. Didn't jump out at me so yeah I'd say "previously processed stream file" is more clear.

[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:240]: Done

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:412]: Yeah the 2 options you noted would have been my 1st suggestions.
Although only need to add the 1 extra method below right. Then modify this method to take in a `String suffix`.

`
public static final long getTimestampFromBalanceFile(String filename) {
         return getTimestampFromFilename(filename, StreamType.BALANCE.getSuffix());
     }
`

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:412]: Having a concrete named getTimestampFromBalanceFile means I can no longer use it from the generic Downloader

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java (hunk 2 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java:344]: done

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java:412]: Used another approach

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java [hunk 4]
```diff
@@ -211,18 +215,36 @@ protected void downloadNextBatch() {
...
-                                File sigFile = pd.getFile();
+                                File sigFile = pendingDownload.getFile();
                                 FileStreamSignature fileStreamSignature = new FileStreamSignature();
                                 fileStreamSignature.setFile(sigFile);
                                 fileStreamSignature.setNode(nodeAccountId);
-                                sigFilesMap.put(sigFile.getName(), fileStreamSignature);
+                                long currentTimestamp = Utility.getTimestampFromFilename(sigFile.getName());
+
+                                // Initial file has no previous so we can't calculate offset from that
+                                if (lastValidTimestamp <= 0) {
```
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:229]: Done
