### PR TITLE
fix the issue importer gets stuck when >=2 groups of signature files in same bucket

### LINKED ISSUE #914: importer gets stuck with DEMO bucket streams
**Detailed Description**

With the latest 0.16.0-SNAPSHOT docker environment and the DEMO bucket streams, the importer will get stuck when >= 2 groups of signature files fall into the same bucket.

**Actual Behavior**
1. check out latest master
2. ./mvnw install -DskipTests
3. docker-compose up -d
4. docker logs -f hedera-mirror-node_importer_1

The log messages contain a log of HashMismatchException errors:

```
2020-07-27 16:21:12,800 ERROR [scheduling-3] c.h.m.i.d.r.RecordFileDownloader Error downloading data file from node 0.0.4 corresponding to 2019-10-11T16_17_50.389374Z.rcd_sig. Will retry another node
java.lang.IllegalArgumentException: Error parsing bad record file 2019-10-11T16_17_50.389374Z.rcd
	at com.hedera.mirror.importer.util.Utility.parseRecordFile(Utility.java:217) ~[classes/:?]
	at com.hedera.mirror.importer.downloader.record.RecordFileDownloader.verifyDataFile(RecordFileDownloader.java:79) ~[classes/:?]
	at com.hedera.mirror.importer.downloader.Downloader.verifySigsAndDownloadDataFiles(Downloader.java:403) [classes/:?]
	at com.hedera.mirror.importer.downloader.Downloader.downloadNextBatch(Downloader.java:144) [classes/:?]
	at com.hedera.mirror.importer.downloader.record.RecordFileDownloader.download(RecordFileDownloader.java:58) [classes/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.hedera.mirror.importer.exception.HashMismatchException: Hash mismatch for file {}. Expected = {}, Actual = {}
	at com.hedera.mirror.importer.util.Utility.parseRecordFile(Utility.java:173) ~[classes/:?]
	... 15 more
```

**Expected Behavior**
Importer was able to import and parse all files from the DEMO bucket and there shouldn't be any HashMismatchExceptions.

**Environment:**
- Java: [e.g. OpenJDK 11.0.4]
- Node: [e.g. v12.9.1-x86]
- OS: [e.g. Ubuntu 18.04]
- Version: [e.g. 1.0.1]

**Additional Context**

### PR DESCRIPTION
**Pull request by xin-hedera**
Signed-off-by: Xin Li <xin.li@swirlds.com>

**Detailed description**:

There are a couple of occurrences in the DEMO bucket that adjacent groups of record signature files' timestamp difference 
< 2s, and all these signature files are **VALID**.

The fix to address the balance files timestamp issue assumed that when >= 2 groups of signature files fall into the same bucket (based on predefined close interval), only one is valid and all but the verified group will be dropped. In addition, the dropped groups will be again dropped on next try since its timestamp falls into the bucket of **last** processed signature files.

So the importer will get stuck and could not continue processing the record files in the DEMO bucket.

To fix it, most part of the previous fix is reverted and a loose restriction is adopted:

1. signatures files are grouped by its timestamp as before
2. when a group of signature files fail to verify and its not the last in the batch, we will skip it and try to process the next group of signature files

This can address the balance file issue, since the single balance file will fail the signature verification:

* if it's not the last in the batch, the next group of balance signature files will pass verification so the single file will be skipped forever
* if it's the last in the batch, it'll be downloaded again in the next batch and become the first, then it'll be skipped and the next group of signature files in the new batch will pass verification so the single file will be skipped forever

**Which issue(s) this PR fixes**:
Fixes #914 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java [hunk 1]
```diff
@@ -362,17 +324,24 @@ private void verifySigsAndDownloadDataFiles(Multimap<Long, FileStreamSignature>
...
 
             Instant startTime = Instant.now();
+            long groupId = groupIdIterator.next();
             Collection<FileStreamSignature> signatures = sigFilesMap.get(groupId);
             boolean valid = false;
 
             try {
                 nodeSignatureVerifier.verify(signatures);
+            } catch (SignatureVerificationException ex) {
+                if (groupIdIterator.hasNext()) {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:340]: This still is not quite correct. It could potentially discard valid files just because one node is really quick at uploading. For a better fix, we should only skip file once next batch has reached consensus. Currently it skips file when only one file is in next batch. This may require separating signature verification loop from signed file download/verification loop.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java [hunk 2]
```diff
@@ -67,43 +66,18 @@ private static boolean consensusReached(long actualNodes, long expectedNodes) {
...
-     * filename reaches consensus.
-     *
-     * @param signatures grouped by filename
-     * @return whether this file was verified
-     * @throws SignatureVerificationException
-     */
-    private boolean verifyFileGroup(Collection<FileStreamSignature> signatures) {
         Multimap<String, FileStreamSignature> signatureHashMap = HashMultimap.create();
-        String filename = null;
+        String filename = !signatures.isEmpty() ? signatures.stream().findFirst().get().getFile().getName() : null;
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java:70]: nit: `signatures.stream().map(FileStreamSignature::getFile).map(File::getName).findFirst().orElse(null);`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java (hunk 1 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:340]: no it will not. in case < 1/3 nodes are quick at uploading, from one point on, all sig files from those nodes will fail verification since consensus can't be reached. in the next batch of downloaded signature files, if some nodes catch up to satisfy the 1/3 consensus requirement, the previously skipped groups will get successfully verified.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java [hunk 3]
```diff
@@ -362,17 +324,24 @@ private void verifySigsAndDownloadDataFiles(Multimap<Long, FileStreamSignature>
...
+                    log.warn("Signature verification failed but still have files in the batch, try to process the next group", ex);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:341]: Please add the filename to the log. This log statement is the only indication that we might've skipped a non-consensus file. We should update to reflect that.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:340]: Talked it over offline and agreed current solution looks good.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java (hunk 3 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:341]: The SignatureVerificationException's message has the filename, so I don't want to duplicate it here.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java [hunk 4]
```diff
@@ -223,15 +221,8 @@ protected void downloadNextBatch() {
...
-                                long groupTimestamp = getGroupTimestamp(lastValidTimestamp, closeInterval,
-                                        fileStreamSignature);
-
-                                if (groupTimestamp > 0) {
-                                    sigFilesMap.put(groupTimestamp, fileStreamSignature);
-                                } else {
-                                    log.warn("Ignoring signature associated with the previously processed stream " +
-                                            "file: {}", fileStreamSignature);
-                                }
+                                long timestamp = Utility.getTimestampFromFilename(sigFile.getName());
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java]: done

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java [hunk 5]
```diff
@@ -67,43 +66,18 @@ private static boolean consensusReached(long actualNodes, long expectedNodes) {
      * @throws SignatureVerificationException
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java:71]: done

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java [hunk 6]
```diff
@@ -322,25 +321,25 @@ void differentFilenamesSameInterval() throws Exception {
...
     void differentFilenamesPreviousInterval() throws Exception {
-        differentFilenames(downloaderProperties.getCloseInterval().dividedBy(2L).negated().minusNanos(2));
+        differentFilenames(getCloseInterval().dividedBy(2L).negated().minusNanos(2));
     }
 
     @Test
     @DisplayName("Different filenames, next interval")
     void differentFilenamesNextInterval() throws Exception {
-        differentFilenames(downloaderProperties.getCloseInterval().dividedBy(2L));
+        differentFilenames(getCloseInterval().dividedBy(2L));
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java:342]: added

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java [hunk 7]
```diff
@@ -122,22 +96,22 @@ private boolean verifyFileGroup(Collection<FileStreamSignature> signatures) {
         for (String key : signatureHashMap.keySet()) {
             Collection<FileStreamSignature> validatedSignatures = signatureHashMap.get(key);
 
-            if (consensusReached(validatedSignatures.size(), nodeIDPubKeyMap.size())) {
+            if (canReachConsensus(validatedSignatures.size(), nodeIDPubKeyMap.size())) {
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java]: done

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java (hunk 2 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java]: done
