### PR TITLE
Ensure 404 repsonse for unmatched routes

### LINKED ISSUE #751: REST API Not Returning 404 on expected scenarios
**Detailed Description**
In recent testing The REST API does' seem to be returning 404 in the following expected scenarios
* non matched endpoints e.g. In v0.10 topics/messages does not exist. When testing it The REST API did not return the expected 404
* Topic not found : /api/v1/topics. Should return 404 for both topic non existent and entity not a topic, just like gRPC API

**Actual Behavior**
1. Go to http://localhost:6551/api/v1/topics/messages

**Expected Behavior**
404

**Environment:**
- Java: [e.g. OpenJDK 11.0.4]
- Node: [e.g. v12.9.1-x86]
- OS: [e.g. Ubuntu 18.04]
- Version: v0.10

**Additional Context**
Non matching issue might not be the single endpoint and could be a regression for all non existent endpoints

### PR DESCRIPTION
**Pull request by Nana-EC**
**Detailed description**:
Unmatched route end points were not being handled as 404's

This change
- Adds a pageNotFound middleware method to the httpErrorHandler
- Updates the responseHandler to call the next() function when response data is not defined.
- Updates server.js to use pageNotFound middleware
- Adds 2 integration tests to verify 404's are sent in response cases

**Which issue(s) this PR fixes**:
Fixes #751 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-rest/middleware/responseHandler.js [hunk 1]
```diff
@@ -21,11 +21,18 @@
...
-// response middleware that pull response data passed through request and sets in json response
+// response middleware that pulls response data passed through request and sets in json response
 // next param is required to ensure express maps to this middleware and can also be used to pass onto future middleware
-const responseHandler = (req, res, next) => {
-  // set response json
-  res.json(res.locals[constants.responseDataLabel]);
+const responseHandler = async (req, res, next) => {
+  const responseData = res.locals[constants.responseDataLabel];
+  if (responseData === undefined) {
+    // unmatched route will have no response data
```
Comment (steven-sheehy) [inline hedera-mirror-rest/middleware/responseHandler.js:29]: Would be preferable to throw NotFoundError here and let it be handled by httpErrorHandler instead of deal with next() and adding new middleware

File: hedera-mirror-rest/middleware/httpErrorHandler.js [hunk 2]
```diff
@@ -62,6 +62,14 @@ const handleError = (err, req, res, next) => {
       logger.trace(`Unhandled error encountered: ${err.message}`);
       res.status(httpStatusCodes.INTERNAL_ERROR).json(errorMessageFormat(httpErrorMessages.INTERNAL_ERROR));
   }
+
```
Comment (steven-sheehy) [inline hedera-mirror-rest/middleware/httpErrorHandler.js:65]: handleError should be async, right?

File: hedera-mirror-rest/middleware/responseHandler.js (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-rest/middleware/responseHandler.js:29]: Considered that option. I'm okay with doing that too. Will just have to reorganize uses

File: hedera-mirror-rest/middleware/httpErrorHandler.js (hunk 2 above)
Comment (Nana-EC) [reply hedera-mirror-rest/middleware/httpErrorHandler.js:65]: Should be yeah. But dependency handles it well. I'll set them async

File: hedera-mirror-rest/middleware/responseHandler.js (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-rest/middleware/responseHandler.js]: More like remove the use().
Updated

File: hedera-mirror-rest/middleware/httpErrorHandler.js (hunk 2 above)
Comment (Nana-EC) [reply hedera-mirror-rest/middleware/httpErrorHandler.js:65]: Done

File: hedera-mirror-rest/server.js [hunk 3]
```diff
@@ -33,7 +33,7 @@ const transactions = require('./transactions.js');
 const balances = require('./balances.js');
 const accounts = require('./accounts.js');
 const topicmessage = require('./topicmessage.js');
-const {handleError} = require('./middleware/httpErrorHandler');
+const {handleError, pageNotFound} = require('./middleware/httpErrorHandler');
```
Comment (steven-sheehy) [inline hedera-mirror-rest/server.js:36]: Can be removed as this is no longer exported

File: hedera-mirror-rest/middleware/responseHandler.js [hunk 4]
```diff
@@ -20,12 +20,20 @@
...
+// response middleware that pulls response data passed through request and sets in json response
 // next param is required to ensure express maps to this middleware and can also be used to pass onto future middleware
-const responseHandler = (req, res, next) => {
-  // set response json
-  res.json(res.locals[constants.responseDataLabel]);
+const responseHandler = async (req, res, next) => {
+  const responseData = res.locals[constants.responseDataLabel];
+  if (responseData === undefined) {
+    // unmatched route will have no response data, pass NotFoundError to next middleware
+    logger.debug(`Unsupported API endpoint: ${req.originalUrl}`);
```
Comment (steven-sheehy) [inline hedera-mirror-rest/middleware/responseHandler.js:31]: Log not necessary, error handler already logs URL and error message at error level

File: hedera-mirror-rest/middleware/httpErrorHandler.js [hunk 5]
```diff
@@ -62,6 +62,8 @@ const handleError = (err, req, res, next) => {
...
+  next();
```
Comment (steven-sheehy) [inline hedera-mirror-rest/middleware/httpErrorHandler.js:66]: Do we still need this?

File: hedera-mirror-rest/middleware/httpErrorHandler.js [hunk 6]
```diff
@@ -21,7 +21,7 @@
 
 const {DbError} = require('../errors/dbError');
 const {InvalidArgumentError} = require('../errors/invalidArgumentError');
-const {NotFoundError} = require('../errors/notFoundError');
+const {NotFoundError, NotFoundErrorMessage} = require('../errors/notFoundError');
```
Comment (steven-sheehy) [inline hedera-mirror-rest/middleware/httpErrorHandler.js:24]: Not needed

File: hedera-mirror-rest/middleware/httpErrorHandler.js (hunk 5 above)
Comment (Nana-EC) [reply hedera-mirror-rest/middleware/httpErrorHandler.js:66]: It's good practice to pass this along, unless we 100% want to mark this as the end of the flow and block any middleware placed after this.

I'm fine as is since I didn't want to make it hard for someone to be wondering why their middleware wasn't getting picked up. I can remove it if you prefer.

File: hedera-mirror-rest/middleware/httpErrorHandler.js (hunk 6 above)
Comment (Nana-EC) [reply hedera-mirror-rest/middleware/httpErrorHandler.js:24]: Removed

File: hedera-mirror-rest/middleware/responseHandler.js (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-rest/middleware/responseHandler.js:31]: Removed

File: hedera-mirror-rest/server.js (hunk 3 above)
Comment (Nana-EC) [reply hedera-mirror-rest/server.js:36]: Removed

File: hedera-mirror-rest/middleware/httpErrorHandler.js (hunk 5 above)
Comment (steven-sheehy) [reply hedera-mirror-rest/middleware/httpErrorHandler.js:66]: I'm fine with keeping, just more of a question to make sure it wasn't a refactoring leftover

Comment (apeksharma) [reply hedera-mirror-rest/middleware/httpErrorHandler.js:66]: just a fyi for future: https://stackoverflow.com/questions/16810449/when-to-use-next-and-return-next-in-node-js
