### PR TITLE
Fix remaining Sonar code smells

### LINKED ISSUE #5189: Fix remaining sonar code smells
### Description

SonarCloud lists a number of remaining code smells that we should fix except for #5187 to have cleaner code.

### Steps to reproduce

View the [list](https://sonarcloud.io/project/issues?id=hedera-mirror-node&resolved=false) of code smells in SonarCloud

### Additional context

_No response_

### Hedera network

other

### Version

0.73.0-SNAPSHOT

### Operating system

Other

### PR DESCRIPTION
**Pull request by MarcKriguerAtHedera**
**Description**:
Fixes one "blocker" code smell (by adding an assert) and suppresses 14 "critical" code smell (8 for oo-high Cognitive Complexity; 6 for where a  generic type is being returned (changing it to a common base class type did not work).

**Related issue(s)**:

Fixes #5189 

**Notes for reviewer**:
Except for the one "blocker" with 4 new lines of code, all this does is @SuppressWarning of the two smells indicated above.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by edwin-greene — DISMISSED** [review]
Looks good to me.

**Review by mgoelswirlds — DISMISSED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java [hunk 1]
```diff
@@ -52,20 +54,25 @@ void scenarios() {
         long startTime = System.currentTimeMillis();
         long endTime = startTime;
         var recordFile = recordFileBuilder.recordFile();
+        AtomicLong workDone = new AtomicLong(0);
 
         performanceProperties.getTransactions().forEach(p -> {
             int count = (int) (p.getTps() * interval / 1000);
             recordFile.recordItems(i -> i.count(count).entities(p.getEntities()).type(p.getType()));
+            workDone.getAndIncrement();
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java:62]: remove this line then we can change `workDone` to a primitive long. also add a comment to why the dummy variable and the `assert` at the end is needed

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java (hunk 1 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java]: Done.  I realized that I really didn't need a count, per se; just "is it still 0 or more?" -- so I made it a primitive boolean, instead.   But I did add a couple of comments.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java [hunk 2]
```diff
@@ -167,7 +167,7 @@ private AccountInfo parse(String line) {
         return null;
     }
 
-    @SuppressWarnings("java:S1874")
+    @SuppressWarnings({"java:S1874", "java:S3776"})
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java:170]: This one is probably fine to keep

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 3]
```diff
@@ -124,6 +124,7 @@ public class EntityRecordItemListener implements RecordItemListener {
     private final RecordParserProperties parserProperties;
     private final TransactionHandlerFactory transactionHandlerFactory;
 
+    @SuppressWarnings("java:S3776")
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:127]: We can move the `if (body.has...)` section to a separate method like `processTransaction(RecordItem recordItem)`.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 4]
```diff
@@ -840,6 +841,7 @@ private void transferNftOwnership(long modifiedTimeStamp, long serialNumber, Ent
         entityListener.onNft(nft);
     }
 
+    @SuppressWarnings("java:S3776")
     private void insertTokenUpdate(RecordItem recordItem) {
         if (entityProperties.getPersist().isTokens()) {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:846]:
```suggestion
    private void insertTokenUpdate(RecordItem recordItem) {
        if (!entityProperties.getPersist().isTokens()) {
            return;
        }
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java [hunk 5]
```diff
@@ -611,6 +611,7 @@ private CryptoAllowance mergeCryptoAllowance(CryptoAllowance previous, CryptoAll
         return current;
     }
 
+    @SuppressWarnings("java:S3776")
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:614]: Don't think we can refactor anything here.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java [hunk 6]
```diff
@@ -120,6 +120,7 @@ public static String getFilename(StreamType streamType, FileType fileType, Insta
         return StringUtils.joinWith(".", StringUtils.join(timestamp, suffix), extension);
     }
 
+    @SuppressWarnings("java:S3776")
     private static TypeInfo extractTypeInfo(String filename) {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java:124]: The `TypeInfo` is a bit useless. Perhaps we can turn `StreamFilename` itself into a builder and use that to clean this up.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 7]
```diff
@@ -277,6 +277,7 @@ private void processCreatedContractEntity(RecordItem recordItem, EntityId contra
         entityListener.onEntity(entity);
     }
 
+    @SuppressWarnings("java:S3776")
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:280]: We can move `++migrationCount;` to the other `if (migration)` block.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java [hunk 8]
```diff
@@ -308,7 +308,7 @@ private StreamFilename getStartAfterFilename() {
      *
      * @param sigFilesMap signature files grouped by filename
      */
-    @SuppressWarnings("java:S135")
+    @SuppressWarnings({"java:S135","java:S3776"})
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java]: Done; this eventually ended up with 3 submethods, but all are within the complexity limit.

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java [hunk 9]
```diff
@@ -50,6 +50,7 @@ class SubscriberController {
     private final MirrorSubscriber mirrorSubscriber;
 
     @GetMapping
+    @SuppressWarnings("java:S1452")
     public Flux<Scenario<?, ?>> subscriptions(@RequestParam Optional<ScenarioProtocol> protocol,
                                               @RequestParam Optional<List<ScenarioStatus>> status) {
         return mirrorSubscriber.getSubscriptions()
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java]: Done.  (Nice!)

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java [hunk 10]
```diff
@@ -59,6 +60,7 @@ class SubscriberController {
     }
 
     @GetMapping("/{name}")
+    @SuppressWarnings("java:S1452")
     public Flux<Scenario<?, ?>> subscriptions(@PathVariable String name,
                                               @RequestParam Optional<List<ScenarioStatus>> status) {
         return subscriptions(Optional.empty(), status)
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java]: Done.

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java [hunk 11]
```diff
@@ -67,6 +69,7 @@ class SubscriberController {
     }
 
     @GetMapping("/{name}/{id}")
+    @SuppressWarnings("java:S1452")
     public Mono<Scenario<?, ?>> subscription(@PathVariable String name, @PathVariable int id) {
         return subscriptions(name, Optional.empty())
                 .filter(s -> s.getId() == id)
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/controller/SubscriberController.java]: Done.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java (hunk 2 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java:170]: OK with me.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java (hunk 3 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java]: Done.  That nicely split the 28 into the 2 methods!

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java (hunk 4 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java]: Done.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java (hunk 5 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java:614]: Agreed.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java (hunk 6 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java:124]: This started getting sloppy/ugly very quickly.  I gave myself a time bound of 2 hours, but I wasn't able to accomplish this change in that time.  I am leaving it with suppressing the warning (for now), but this can be revisited later.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java (hunk 7 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:280]: I did that, and it brought the complexity down from 18 to 16.  I'm keeping the change, but still suppressing the warning (which is down to 1 over the limit).

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SubscriptionResponse.java [hunk 12]
```diff
@@ -39,13 +39,15 @@ public class SubscriptionResponse {
     private List<MirrorHCSResponse> mirrorHCSResponses = new ArrayList<>();
     private Stopwatch elapsedTime;
     private Throwable responseError;
+    private boolean responseEncountered = false;
```
Comment (xin-hedera) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SubscriptionResponse.java:42]: revert changes in this file and just verify `subscriptionResponse.getMirrorHCSResponses().size() > 0` in `MirrorNodeClient.subscribeToTopic`

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java [hunk 13]
```diff
@@ -69,4 +69,18 @@ public String toString() {
...
+        if (!(o instanceof RestSubscription)) return false;
+        if (!super.equals(o)) return false;
+
+        return super.equals(o);
+    }
+
+    @Override
+    public int hashCode() {
+        return super.hashCode();
+    }
```
Comment (xin-hedera) [inline hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java:85]: use lombok `@Value` on the class to generate `equals` and `hashCode`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java [hunk 14]
```diff
@@ -321,99 +320,117 @@ private void verifySigsAndDownloadDataFiles(Multimap<StreamFilename, StreamFileS
...
+                log.debug("Verified signature file {} reached consensus", sigFilename);
+            } else if (consensusCount > 0) {
+                log.warn("Verified signature file {} reached consensus but with some errors: {}", sigFilename,
+                        statusMap(signatures, nodeIds));
+            }
+        } catch (SignatureVerificationException ex) {
+            var statusMapMessage = statusMap(signatures, nodeIds);
+            if (sigFilenameIter.hasNext()) {
+                log.warn("{}. Trying next group: {}", ex.getMessage(), statusMapMessage);
+                verifySigsAndDownloadDataFiles(sigFilesMap, nodeIds, sigFilenameIter);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:352]: this becomes a dead loop since it recursively calls itself and will go all the way blow up the stack

due to the complexity of the function, I strongly recommend we revert the changes and just suppress it on the original `verifySigsAndDownloadDataFiles` method

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java (hunk 14 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:352]: If there's a risk we got the refactor wrong then I agree we should revert and suppress.

**Review by steven-sheehy — APPROVED** [review]

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
Meant to request changes, not approve...

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java (hunk 14 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java:352]: it's not as bad as I thought (endless recursive call): we advance the `sigFilenameIter` at the beginning of the new function, so even though it calls itself, the signature files to verify would be the next group.

however, this is still not the way we want to refactor the function because

- it makes it more difficult to understand and most likely more error-prone
- the same cognitive complexity smell still exists, just moved to the new function

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SubscriptionResponse.java (hunk 12 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SubscriptionResponse.java]: Done.

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java (hunk 13 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java]: Done.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java (hunk 14 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java]: Done.

File: hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java [hunk 15]
```diff
@@ -197,6 +197,7 @@ public RecordItem build() {
             return buildInternal();
         }
 
+        @SuppressWarnings("java:S6213")
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java]: Removing the suppression, so we can do this later.

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java [hunk 16]
```diff
@@ -69,4 +69,18 @@ public String toString() {
         String name = getName();
         return getProperties().getSubscribers() <= 1 ? name : name + " #" + getId();
     }
+
+    @Override
+    public boolean equals(Object o) {
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscription.java]: Undid the count move.  The equals and hashcode methods were newly-created code smells since this class inherited from an abstract class.  But Xin's suggestion to just use @Value worked even better.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 17]
```diff
@@ -231,6 +190,55 @@ public void onItem(RecordItem recordItem) throws ImporterException {
         log.debug("Storing transaction: {}", transaction);
     }
 
+    // reduce Cognitive Complexity of onItem() by moving the "dispatcher" part of the code into a separate method.
+    // This still has Cognitive Complexity of 19, but it really doesn't make sense to split into two parts.
+    @SuppressWarnings("java:S3776")
+    private void processTransaction(RecordItem recordItem, long consensusTimestamp, int transactionTypeValue,
+                                    TransactionRecord txRecord) {
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java]: Done.  The additional 3 variables just get generated in this method (in the exact same way they are generated in the calling method).

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java [hunk 18]
```diff
@@ -77,7 +80,10 @@ public SubscriptionResponse subscribeToTopic(SDKClient sdkClient, TopicMessageQu
         subscriptionResponse.setSubscription(subscription);
 
         // allow time for connection to be made and error to be caught
-        Thread.sleep(5000, 0);
+        await("responseEncountered").dontCatchUncaughtExceptions()
+                .atMost(Durations.FIVE_SECONDS)
+                .pollDelay(Durations.ONE_MILLISECOND)
+                .until(subscriptionResponse::getMirrorHCSResponses().size() > 0);
```
Comment (xin-hedera) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java:86]: this won't compile

```suggestion
                .until(subscriptionResponse::getMirrorHCSResponses().size() > 0);
```

Comment (MarcKriguerAtHedera) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java]: I had accidentally deleted the leading "() ->" just after `until(` -- fixed.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 19]
```diff
@@ -231,6 +190,57 @@ public void onItem(RecordItem recordItem) throws ImporterException {
         log.debug("Storing transaction: {}", transaction);
     }
 
+    // reduce Cognitive Complexity of onItem() by moving the "dispatcher" part of the code into a separate method.
+    // This still has Cognitive Complexity of 19, but it really doesn't make sense to split into two parts.
+    @SuppressWarnings("java:S3776")
+    private void processTransaction(RecordItem recordItem) {
+        TransactionRecord txRecord = recordItem.getTransactionRecord();
+        int transactionTypeValue = recordItem.getTransactionType();
+        long consensusTimestamp = DomainUtils.timeStampInNanos(txRecord.getConsensusTimestamp());
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:199]: It's already parsed.

```suggestion
        long consensusTimestamp = recordItem.getConsensusTimestamp());
```

**Review by steven-sheehy — APPROVED** [review]

**Review by xin-hedera — APPROVED** [review]
LGTM

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java (hunk 19 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java]: Done.

**Review by xin-hedera — APPROVED** [review]
