### PR TITLE
Fix MessageDeliveryException in importer

### LINKED ISSUE #6828: Import halts ingestion with a MessageDeliveryException
### Description

The importer stopped ingesting files after `2023-09-05T22:26:23.701910003Z` in the performance environment with a `MessageDeliveryException`. Investigation revealed that a `HashMismatchException` had occurred around this time due to bad data in the bucket. The importer was restarted later and instead of continuing to produce the expected `HashMismatchException`, it began producing the `MessageDeliveryException` which indicates the queue between downloader and parser threads was full. Thread dumps indicate the parser thread is stuck infinitely retrying a file.

The files with the invalid hash chain were mistakenly verified and sent to the parser thread. Luckily the parser thread also validates the hash chain so it was failing there. Due to a bug we could not see the exception in the parser. Due to a different bug in how we calculate the next file to download we were setting the `verifyHashAfter` property to now since the balance file table was empty. Performance environment is testing with balance file disabled.

### Steps to reproduce

1. Run with `startDate=2023-09-05T22:00:00Z` until it reaches file with broken hash chain
2. Stop importer
3. Run with `startDate=""` so it defaults to now

### Additional context

Startup logs:
```bash
2023-09-07T00:12:31Z    2023-09-07T00:12:31.964+0000 INFO main c.h.m.i.MirrorImporterApplication Started MirrorImporterApplication in 27.354 seconds (process running for 29.858)
2023-09-07T00:12:32Z    2023-09-07T00:12:32.137+0000 INFO scheduling-3 c.h.m.i.c.MirrorDateRangePropertiesProcessor BALANCE: downloader will download files in time range (2023-09-07T00:12:26.090248337Z, 2262-04-11T23:47:16.854775807Z] 
2023-09-07T00:12:32Z    2023-09-07T00:12:32.144+0000 INFO scheduling-5 c.h.m.i.c.MirrorDateRangePropertiesProcessor RECORD: downloader will download files in time range (2023-09-05T22:26:23.701910003Z, 2262-04-11T23:47:16.854775807Z] 
2023-09-07T00:12:38Z    2023-09-07T00:12:38.869+0000 INFO scheduling-3 c.h.m.i.d.b.AccountBalancesDownloader No new signature files to download after file: 2023-09-07T00_12_26.090248337Z_Balances.csv. Retrying in 30.0 s  
```

The beginning of the `MessageDeliveryException` logs:

```bash
2023-09-07T00:12:59Z    2023-09-07T00:12:59.933+0000 INFO scheduling-5 c.h.m.i.d.r.RecordFileDownloader Downloaded 2975 signatures in 27.60 s (107/s): {2023-09-05T22_28_03.343966003Z.rcd_sig=35, 2023-09-05T22_28_53.422410289Z.rcd_sig=31, 2023-09-05T22_27_43.421208298Z.rcd_sig=41, 2023-09-05T22_29_13.882290003Z.rcd_sig=31, 2023-09-05T22_28_13.675805361Z.rcd_sig=34, 2023-09-05T22_27_53.393808939Z.rcd_sig=41, 2023-09-05T22_29_03.379350003Z.rcd_sig=31, 2023-09-05T22_28_33.825448288Z.rcd_sig=33, 2023-09-05T22_28_23.732842711Z.rcd_sig=32, 2023-09-05T22_28_43.688455003Z.rcd_sig=30}
2023-09-07T00:13:00Z    2023-09-07T00:13:00.211+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 706 items successfully from v6 record file 2023-09-05T22_27_43.421208298Z.rcd.gz in 108.5 ms
2023-09-07T00:13:00Z    2023-09-07T00:13:00.351+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_27_53.393808939Z.rcd.gz in 953.2 μs
2023-09-07T00:13:00Z    2023-09-07T00:13:00.454+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_28_03.343966003Z.rcd.gz in 693.1 μs
2023-09-07T00:13:00Z    2023-09-07T00:13:00.541+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_28_13.675805361Z.rcd.gz in 604.3 μs
2023-09-07T00:13:00Z    2023-09-07T00:13:00.632+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_28_23.732842711Z.rcd.gz in 622.7 μs
2023-09-07T00:13:00Z    2023-09-07T00:13:00.846+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_28_33.825448288Z.rcd.gz in 672.1 μs
2023-09-07T00:13:00Z    2023-09-07T00:13:00.942+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_28_43.688455003Z.rcd.gz in 666.4 μs
2023-09-07T00:13:01Z    2023-09-07T00:13:01.045+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_28_53.422410289Z.rcd.gz in 639.0 μs
2023-09-07T00:13:01Z    2023-09-07T00:13:01.145+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_29_03.379350003Z.rcd.gz in 780.7 μs
2023-09-07T00:13:01Z    2023-09-07T00:13:01.235+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_29_13.882290003Z.rcd.gz in 601.3 μs
2023-09-07T00:13:01Z    2023-09-07T00:13:01.318+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_29_23.332610235Z.rcd.gz in 621.6 μs
2023-09-07T00:13:01Z    2023-09-07T00:13:01.436+0000 INFO scheduling-5 c.h.m.i.r.r.CompositeRecordFileReader Read 1 items successfully from v6 record file 2023-09-05T22_29_33.551488955Z.rcd.gz in 599.6 μs
2023-09-07T00:13:09Z    2023-09-07T00:13:09.141+0000 INFO scheduling-4 c.h.m.i.d.b.AccountBalancesDownloader No new signature files to download after file: 2023-09-07T00_12_26.090248337Z_Balances.csv. Retrying in 30.0 s 
2023-09-07T00:13:31Z    2023-09-07T00:13:31.441+0000 ERROR scheduling-5 c.h.m.i.d.r.RecordFileDownloader Error downloading data file from node 28 corresponding to 2023-09-05T22_29_33.551488955Z.rcd_sig. Will retry another node org.springframework.messaging.MessageDeliveryException: Failed to send message to channel 'bean 'stream.record'; defined in: 'class path resource [com/hedera/mirror/importer/config/MessagingConfiguration.class]'; from source: 'com.hedera.mirror.importer.config.MessagingConfiguration.channelRecord(com.hedera.mirror.importer.parser.record.RecordParserProperties)'' within timeout: 30000, failedMessage=GenericMessage [payload=RecordFile(hapiVersion=0.40, consensusStart=1693952973551488955, consensusEnd=1693952973551488955, count=1, digestAlgorithm=SHA_384, gasUsed=0, hapiVersionMajor=0, hapiVersionMinor=40, hapiVersionPatch=0, index=11, loadEnd=null, loadStart=1694045581, name=2023-09-05T22_29_33.551488955Z.rcd.gz, nodeId=28, sidecarCount=0, size=715, version=6), headers={replyChannel=nullChannel, errorChannel=, id=1edcae2c-4d87-cdc1-09fb-58c19254f8e3, timestamp=1694045581437}]
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:190)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
        at org.springframework.integration.router.AbstractMessageRouter.doSend(AbstractMessageRouter.java:217)
        at org.springframework.integration.router.AbstractMessageRouter.handleMessageInternal(AbstractMessageRouter.java:199) 
        at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
        at org.springframework.integration.handler.AbstractMessageHandler.handleWithMetrics(AbstractMessageHandler.java:90) 
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:70)
        at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
        at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
        at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:373)
        at org.springframework.integration.channel.AbstractMessageChannel.sendWithMetrics(AbstractMessageChannel.java:344)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:324)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:151)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:143)
        at org.springframework.integration.gateway.MessagingGatewaySupport.send(MessagingGatewaySupport.java:466)
        at org.springframework.integration.gateway.GatewayProxyFactoryBean.sendOrSendAndReceive(GatewayProxyFactoryBean.java:669)
        at org.springframework.integration.gateway.GatewayProxyFactoryBean.invokeGatewayMethod(GatewayProxyFactoryBean.java:584)
        at org.springframework.integration.gateway.GatewayProxyFactoryBean.doInvoke(GatewayProxyFactoryBean.java:550)
        at org.springframework.integration.gateway.GatewayProxyFactoryBean.invoke(GatewayProxyFactoryBean.java:540)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
```

Thread dump shows the RecordFileParser is stuck retrying a file despite no logs occurring for that thread:

```bash
"scheduling-2" #41 prio=5 os_prio=0 cpu=8040.25ms elapsed=46205.30s tid=0x000078cc133dd7a0 nid=0x34 waiting on condition  [0x000078cbe08fd000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@17.0.8/Native Method)
        at org.springframework.retry.backoff.ThreadWaitSleeper.sleep(ThreadWaitSleeper.java:31)
        at org.springframework.retry.backoff.ExponentialBackOffPolicy.backOff(ExponentialBackOffPolicy.java:245)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:349)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:135)
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:160)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.hedera.mirror.importer.parser.record.RecordFileParser$$SpringCGLIB$$0.parse(<generated>)
        at com.hedera.mirror.importer.config.MessagingConfiguration.lambda$integrationFlow$1(MessagingConfiguration.java:107)
        at com.hedera.mirror.importer.config.MessagingConfiguration$$Lambda$2077/0x000078cb94ed6120.handle(Unknown Source)
        at org.springframework.integration.handler.LambdaMessageProcessor.invokeMethod(LambdaMessageProcessor.java:208)
        at org.springframework.integration.handler.LambdaMessageProcessor.processMessage(LambdaMessageProcessor.java:121)
        at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:95)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136)
        at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
        at org.springframework.integration.handler.AbstractMessageHandler.handleWithMetrics(AbstractMessageHandler.java:90)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:70)
        at org.springframework.integration.endpoint.PollingConsumer.handleMessage(PollingConsumer.java:158)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:474)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:460)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint$$Lambda$2508/0x000078cb94fad920.call(Unknown Source)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:412)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:348)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint$$Lambda$2510/0x000078cb94fae8f8.run(Unknown Source)
        at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
        at org.springframework.integration.util.ErrorHandlingTaskExecutor$$Lambda$2511/0x000078cb94faeb20.run(Unknown Source)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
        at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$5(AbstractPollingEndpoint.java:341)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint$$Lambda$2509/0x000078cb94fadb48.run(Unknown Source)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.8/Unknown Source)
        at java.util.concurrent.FutureTask.run(java.base@17.0.8/Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@17.0.8/Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.8/Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.8/Unknown Source)
        at java.lang.Thread.run(java.base@17.0.8/Unknown Source)
```

### Hedera network

other

### Version

0.87.0

### Operating system

None

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

Fix underlying issue that the global `verifyHashAfter` was being set when the balance file table was empty despite the fact that this property should not apply to balances since they don't have hash chains.

* Add `synchronized` to parsers as a fail-safe
* Change parser retry properties to not retry as often
* Fix `AbstractStreamFileParser` not logging `HashMismatchException`
* Fix downloader verifying files with broken hash chains
* Fix `ImporterNoBalanceFile` alert
* Fix last stream file in parser not getting set last
* Remove `hedera.mirror.importer.verifyHashAfter` since it causes issues and didn't work without parser support anyway

**Related issue(s)**:

Fixes #6828

**Notes for reviewer**:

Will cherry pick to 0.88.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java [hunk 1]
```diff
@@ -86,13 +86,13 @@ public void parse(T streamFile) {
...
-            } finally {
-                Timer timer = success ? parseDurationMetricSuccess : parseDurationMetricFailure;
-                timer.record(stopwatch.elapsed());
             }
+        } catch (Throwable e) {
+            log.error("Error parsing file {} after {}", streamFile.getName(), stopwatch, e);
+            throw e;
+        } finally {
+            Timer timer = success ? parseDurationMetricSuccess : parseDurationMetricFailure;
+            timer.record(stopwatch.elapsed());
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java:95]: since by default `success` is false, this will record those skipped stream files into the failure metric.

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java:97]: Inverted logic

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java [hunk 2]
```diff
@@ -45,9 +46,9 @@
 import org.springframework.transaction.support.TransactionTemplate;
 
 @ConditionalOnProperty(
-        prefix = "hedera.mirror.importer.parser.record.historical-balances",
         name = "enabled",
-        matchIfMissing = true)
+        matchIfMissing = true,
+        prefix = "hedera.mirror.importer.parser.record.historical-balances")
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java:51]: I missed it in my PR...
```suggestion
        prefix = "hedera.mirror.importer.parser.record.historical-balance")
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java [hunk 3]
```diff
@@ -86,12 +87,9 @@ public HistoricalBalanceService(
                 (int) properties.getTransactionTimeout().toSeconds());
 
         // metrics
-        var generateDurationTimerBuilder = Timer.builder("hedera.mirror.importer.historicalbalance")
-                .description("The duration in seconds it took to generate historical balances information");
-        generateDurationMetricFailure =
-                generateDurationTimerBuilder.tag("success", "false").register(meterRegistry);
-        generateDurationMetricSuccess =
-                generateDurationTimerBuilder.tag("success", "true").register(meterRegistry);
+        var timer = Timer.builder(STREAM_PARSE_DURATION_METRIC_NAME);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java:90]: missing tag "type=BALANCE"?

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java (hunk 2 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java]: Fixed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java (hunk 3 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java]: Good catch. Added

**Review by xin-hedera — APPROVED** [review]
LGTM

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java [hunk 4]
```diff
@@ -72,27 +72,29 @@ public ParserProperties getProperties() {
...
+            doParse(streamFile);
+            log.info(
+                    "Successfully processed {} items from {} in {}",
+                    streamFile.getCount(),
+                    streamFile.getName(),
+                    stopwatch);
+
+            Instant consensusInstant = Instant.ofEpochSecond(0L, streamFile.getConsensusEnd());
+            parseLatencyMetric.record(Duration.between(consensusInstant, Instant.now()));
+        } catch (Throwable e) {
```
Comment (edwin-greene) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java:91]: Looks like sonar is flagging this as a code smell.

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java:91]: I saw it, but it's not related to my changes.

File: docs/configuration.md [hunk 5]
```diff
@@ -157,12 +157,12 @@ value, it is recommended to only populate overridden properties in the custom `a
...
 | `hedera.mirror.importer.parser.record.sidecar.persistBytes`                      | false                                            | Whether to persist the sidecar file bytes to the database                                                                                                                                                                                                          |
-| `hedera.mirror.importer.parser.record.sidecar.types`                             | []                                               | Which types of transaction sidecar records to process. By default it is empty to indicate all types                                                                                                                                                                |
+| `hedera.mirror.importer.parser.record.sidecar.types`                             | []                                               | Which types of transaction sidecar records to process. By default it is empty to indicate all types. Accepts `CONTRACT_ACTION`, `CONTRACT_BYTECODE`, or `CONTRACT_STATE_CHANGE`.                                                                                   |
```
Comment (jascks) [inline docs/configuration.md:165]: I take it this is in response to the question in Slack this morning and not part of the ticket? 😄

**Review by edwin-greene — APPROVED** [review]
Looks good

File: docs/configuration.md (hunk 5 above)
Comment (steven-sheehy) [reply docs/configuration.md:165]: Snuck in a doc improvement
