### PR TITLE
Utilize plural rest api endpoints without breaking support

### LINKED ISSUE #700: Topic REST API Endpoints utilize both singular and plural paths
**Detailed Description**
Currently our topic rest api endpoints fluctuate between using singular and plural paths for resource.

Current
- /topic/message/:consensusTimestamp
- /topic/:id/message/:sequencenumber
- /topics/:id/messages/:sequencenumber
- /topics/:id/messages
- /topic/:id/messages

We should be consistent in resource reference 

**Actual Behavior**
Resources use both singular and plural

**Expected Behavior**
Resources are consistently plural or singular unless an exception is required

**Solution**
Employ plural throughout and be consistent with most design standards and the rest of our current REST API's
- /topics/messages/:consensusTimestamp
- /topics/:id/messages/:sequencenumber
- /topics/:id/messages

**Alternatives**
Make them singular. This would be inconsistent with the rest of the REST endpoints

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

Examples of popular REST API's 
https://developer.github.com/v3/
https://cloud.google.com/apis/design/resource_names
https://developers.google.com/maps/documentation/urls/guide
https://docs.aws.amazon.com/apigateway/api-reference/resource/ 
https://developers.facebook.com/docs/graph-api/reference
https://developer.twitter.com/en
https://www.instagram.com/developer/endpoints/
https://www.meetup.com/meetup_api/
https://developer.foursquare.com/docs/places-api/endpoints/
https://developers.soundcloud.com/docs/api/guide
https://www.dropbox.com/developers/documentation/http/documentation
https://developer.wordpress.org/rest-api/reference/

Most of them employ plural in general with an exception for singular where it's not necessarily a static resource being employed but a dynamic

### PR DESCRIPTION
**Pull request by Nana-EC**
**Detailed description**:
The /api/v1/topic(s) endpoint introduced inconsistencies in resource path names.
This change subscribes to consistently use plural resource names as they refer to collections unless an exception resource or path arises.

- Update servers.js topic routes to use plural. 
- Utilize regex ? to still match old non plurals to not break any customers.
- Updates singular references in tests and comments 

**Which issue(s) this PR fixes**:
Fixes #700 

**Special notes for your reviewer**:
This is a non breaking change and utilizes expresses support of regex match.
Going forward we should conform to the plural

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: hedera-mirror-rest/server.js [hunk 1]
```diff
@@ -101,20 +101,21 @@ if (config.api.metrics.enabled) {
...
+app.getAsync(apiPrefix + '/balances', balances.getBalances);
+
+// transactions routes
+app.getAsync(apiPrefix + '/transactions', transactions.getTransactions);
+app.getAsync(apiPrefix + '/transactions/:id', transactions.getOneTransaction);
 
-app.getAsync(apiPrefix + '/topics/:id/messages', topicmessage.getTopicMessages);
-app.getAsync(apiPrefix + '/topic/:id/messages', topicmessage.getTopicMessages);
+// topics routes
+app.getAsync(apiPrefix + '/topics/:id/messages?', topicmessage.getTopicMessages);
```
Comment (apeksharma) [inline hedera-mirror-rest/server.js:116]: When do we plan to remove '?' regex match?
No need for backward compatibility - that's the whole premise everyone agreed on when adding these apis. I intend to use it.
There should be only 2 users for these apis. Let's talk to atul, get in touch with these guys, notify them and removing '?' in 0.12.0

Comment (Nana-EC) [reply hedera-mirror-rest/server.js:116]: Agreed. I'm happy to not use '?' added it as @steven-sheehy had concerns of us breaking customers back to back.

I like the option of removing in 0.12.0 after notifying the 2 users.

Comment (Nana-EC) [reply hedera-mirror-rest/server.js]: Reached out to customer and verified with logs usage of other endpoints. For now just support the concensustimestamp singular till v0.12.0
