### PR TITLE
Exclude fee-free transactions in monitor check

### LINKED ISSUE #1829: Monitor reports error "accNum is 0"
**Detailed Description**
The integration environment's monitor reports error "accNum is 0". The error is from the check `getTransactionsWithAccountCheck`. When there are transactions with no crypto transfer list (fee free transactions by system accounts), the check fails to find a valid account id from the crypto transfer list.

**Actual Behavior**

**Expected Behavior**
The check should pass

**Environment:**

**Additional Context**

### PR DESCRIPTION
**Pull request by xin-hedera**
**Detailed description**:
Add `type=credit` filter to exclude fee-free transactions so selecting an account id from the account ids of the transfers will not fail.

**Which issue(s) this PR fixes**:
Fixes #1829 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ const checkTransactionTransfers = (transactions, option) => {
  * @param {String} server API host endpoint
  */
 const getTransactionsWithAccountCheck = async (server) => {
-  let url = getUrl(server, transactionsPath, {limit: resourceLimit});
+  let url = getUrl(server, transactionsPath, {limit: resourceLimit, type: 'credit'});
```
Comment (steven-sheehy) [inline hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js:75]: Do we still need `_.filter(transactions[0].transfers, (xfer) => xfer.amount > 0)`?

Comment (xin-hedera) [reply hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js:75]: looks like it's better to not filter it by amount > 0. in case it's a non cryptotransfer transaction, the account id will alway end up to be the treasury.

Comment (xin-hedera) [reply hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js:75]: spoke too soon. the test will later query with the `highestAccount`:

```javascript
  url = getUrl(server, transactionsPath, {
    'account.id': highestAccount,
    type: 'credit',
    limit: 1,
  });
```

without the filter, the query may end up with 0 transaction in the response.

**Review by steven-sheehy — APPROVED** [review]
