### PR TITLE
Fix incorrect fixed fee denominating token id

### LINKED ISSUE #2357: Importer fails to handle fixed fee with denominating token id 0.0.0 in token create properly
### Description

Importer missed the change in services 0.16.0-rc1 that when creating a token with a fixed custom fee charged in denominating token id `0.0.0`, it means the fee should be charged in the newly created token itself.

HAPI protobuf reference:

https://github.com/hashgraph/hedera-protobufs/blob/d67d34da9820269f13ec453a0bd512dfb74f92dc/services/CustomFees.proto#L43

### Steps to reproduce

1. create a token with a fixed fee entry with denominating token id set to `0.0.0`
2. query the mirror node rest api, the denominating token id of the fixed fee entry shows up as `null` 

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.38.0-SNAPSHOT

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

- Set the denominating token id of a fixed fee to the attached token id when it's the sentinel token `0.0.0`

**Related issue(s)**:

Fixes #2357

**Notes for reviewer**:

Please refer to the ticket for the context.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by Nana-EC — APPROVED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 1]
```diff
@@ -873,7 +873,7 @@ private void insertCustomFees(List<com.hederahashgraph.api.proto.java.CustomFee>
             var feeCase = protoCustomFee.getFeeCase();
             switch (feeCase) {
                 case FIXED_FEE:
-                    parseFixedFee(customFee, protoCustomFee.getFixedFee());
+                    parseFixedFee(customFee, protoCustomFee.getFixedFee(), tokenId);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:876]: This will also be called for fee schedule update. Can the sentinel value also appear for that? The docs seem to indicate no.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java [hunk 2]
```diff
@@ -895,9 +895,17 @@ private void insertCustomFees(List<com.hederahashgraph.api.proto.java.CustomFee>
...
         customFee.setAmount(fixedFee.getAmount());
-        customFee.setDenominatingTokenId(EntityId.of(fixedFee.getDenominatingTokenId()));
+
+        if (fixedFee.hasDenominatingTokenId()) {
+            TokenID denominatingTokenId = fixedFee.getDenominatingTokenId();
+            if (denominatingTokenId.equals(TokenID.getDefaultInstance())) {
+                customFee.setDenominatingTokenId(tokenId);
+            } else {
+                customFee.setDenominatingTokenId(EntityId.of(denominatingTokenId));
+            }
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:907]: nit: Can avoid the duplication of setter:
```suggestion
            EntityId denominatingTokenId = EntityId.of(fixedFee.getDenominatingTokenId());
            customFee.setDenominatingTokenId(denominatingTokenId == EntityId.EMPTY ? tokenId : denominatingTokenId);
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java (hunk 1 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java:876]: services code indicates the same logic for fee schedule update, though it's not mentioned in the doc:

https://github.com/hashgraph/hedera-services/blob/59247534d82522e537c7c3db621b5ad92b091457/hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java#L749

https://github.com/hashgraph/hedera-services/blob/59247534d82522e537c7c3db621b5ad92b091457/hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java#L438

https://github.com/hashgraph/hedera-services/blob/59247534d82522e537c7c3db621b5ad92b091457/hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java#L498-L502

**Review by steven-sheehy — APPROVED** [review]
LGTM
