### PR TITLE
Fix partial mirror nodes stuck with incomplete address book

### LINKED ISSUE #5604: Mirror node stuck after syncing ~1 week of transactions
Mirror node was setup syncing starting at the first of the year. 2023-01-01

In our log files all we see is the following. We are not syncing any new tranasctions past the 12th 

2023-03-16 12:46:38.282 PDT
2023-03-16T13:46:38.282-0600 WARN scheduling-1 c.h.m.i.d.r.RecordFileDownloader Consensus not reached for file 2023-01-12T17_38_07.462886003Z.rcd_sig with 120185333500000000/3094846749785185185 stake. Trying next group: {NOT_FOUND=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12], VERIFIED=[11]}
2023-03-16 12:46:38.282 PDT
2023-03-16T13:46:38.282-0600 WARN scheduling-1 c.h.m.i.d.r.RecordFileDownloader Consensus not reached for file 2023-01-12T17_38_10.137266003Z.rcd_sig with 120185333500000000/3094846749785185185 stake. Trying next group: {NOT_FOUND=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12], VERIFIED=[11]}
2023-03-16 12:46:38.282 PDT
2023-03-16T13:46:38.282-0600 WARN scheduling-1 c.h.m.i.d.r.RecordFileDownloader Consensus not reached for file 2023-01-12T17_38_12.063222003Z.rcd_sig with 120185333500000000/3094846749785185185 stake. Trying next group: {NOT_FOUND=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12], VERIFIED=[11]}
2023-03-16 12:46:38.282 PDT
2023-03-16T13:46:38.282-0600 WARN scheduling-1 c.h.m.i.d.r.RecordFileDownloader Consensus not reached for file 2023-01-12T17_38_14.999736299Z.rcd_sig with 120185333500000000/3094846749785185185 stake. Trying next group: {NOT_FOUND=[0, 1, 2, 3, 4, 5,

### PR DESCRIPTION
**Pull request by MarcKriguerAtHedera**
**Description**:

* Add a new `hedera.mirror.importer.consensusMode` property with 3 values:
  * `EQUAL`: Add nodes equally weighted (1 for each node)
  * `STAKE`: All nodes specify their node stake (current behavior)
  *  `STAKE_IN_ADDRESS_BOOK`: Only nodes in the address book count their node stake. (new default)
* Modify `AddressBookServiceImpl::getNodes()` to take into account the consensus mode

**Related issue(s)**:

Fixes #5604 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 1]
```diff
@@ -138,14 +139,36 @@ public Collection<ConsensusNode> getNodes() {
...
+          addressBook.getEntries().forEach(e -> {
+              var nodeStake = nodeStakes.get(e.getNodeId());
+              if (nodeStake != null) {
+                totalStake.addAndGet(nodeStake.getStake());
+              }
+          });
+          long newTotalStake = totalStake.get();
+          if (oldTotalStake != newTotalStake) {
+            log.warn("Using address book with {}/{} nodes for node staking, total stake of {}/{}",
+                addressBook.getNodeCount(), nodeStakes.size(), newTotalStake, oldTotalStake);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:169]: I think it would be better and simpler to just warn if the size differs. Also, would be better for researching to print the timestamps of each. Just pick one timestamp from nodestakes.

```suggestion
          if (addressBook.getNodeCount() != nodeStakes.size()) {
            log.warn("Using address book {} with {} nodes and node stake {} with {} nodes",
                addressBook.getConsensusTimestamp(), addressBook.getNodeCount(), nodeStakeTimestamp, nodeStakes.size());
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 2]
```diff
@@ -971,30 +972,83 @@ void getNodesWithNodeStake() {
...
                 .allSatisfy(c -> assertThat(c.getPublicKey()).isNotNull())
                 .allMatch(c -> c.getStake() > 1L)
                 .extracting(ConsensusNode::getNodeId)
                 .containsExactly(0L, 1L, 2L, 3L);
+
+        // consensusMode == ConsensusMode.EQUAL (each node gets stake of 1L)
+        MirrorProperties otherMirrorProperties = new MirrorProperties();
+        otherMirrorProperties.setConsensusMode(ConsensusMode.EQUAL);
+        AddressBookService customAddressBookService = new AddressBookServiceImpl(addressBookRepository,
+                fileDataRepository, otherMirrorProperties, nodeStakeRepository, transactionTemplate);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:988]: We should not be recreating the class under test. Especially since it's a Spring bean and we're creating it manually. To test different consensusModes, simply set that mode on the already injected `mirrorProperties`.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 3]
```diff
@@ -971,30 +972,83 @@ void getNodesWithNodeStake() {
...
+
+        assertThat(customAddressBookService.getNodes())
+                .hasSize(TEST_INITIAL_ADDRESS_BOOK_NODE_COUNT)
+                .allSatisfy(c -> assertThat(c).returns(4L, ConsensusNode::getTotalStake))
+                .allSatisfy(c -> assertThat(c.getPublicKey()).isNotNull())
+                .allMatch(c -> c.getStake() == 1L)
+                .extracting(ConsensusNode::getNodeId)
+                .containsExactly(0L, 1L, 2L, 3L);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:996]: Revert changes to existing tests. It makes it hard to verify no regression and we should have different test for different consensus modes.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 4]
```diff
@@ -971,30 +972,83 @@ void getNodesWithNodeStake() {
...
+                .allMatch(c -> c.getTotalStake() == 4L)
                 .allMatch(c -> c.getNodeAccountId().getEntityNum() - 3 == c.getNodeId())
-                .allSatisfy(c -> assertThat(c.getPublicKey()).isNotNull());
+                .extracting(ConsensusNode::getNodeId)
+                .containsExactly(0L, 1L, 2L, 3L);
+    }
+
+    @Test
+    void getNodesWithNodesNotInAddressBook() {
+        // consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK (the default)
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:1035]: Remove this comment and explicitly set it so it's self documenting and protects against changes to default properties in any config.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 5]
```diff
@@ -971,30 +972,83 @@ void getNodesWithNodeStake() {
...
-                .allMatch(c -> c.getTotalStake() == 5L)
+                .allMatch(c -> c.getTotalStake() == 4L)
                 .allMatch(c -> c.getNodeAccountId().getEntityNum() - 3 == c.getNodeId())
-                .allSatisfy(c -> assertThat(c.getPublicKey()).isNotNull());
+                .extracting(ConsensusNode::getNodeId)
+                .containsExactly(0L, 1L, 2L, 3L);
+    }
+
+    @Test
+    void getNodesWithNodesNotInAddressBook() {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:1034]: We should be able to consolidate the logic to one parameterized test.
```suggestion
    @CsvSource(textBlock = """
    EQUAL, 6, 6
    ...
    """)
    @ParameterizedTest
    void getNodes(ConsensusMode mode, long stake, int nodeCount) {
```

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

**Comment by steven-sheehy** [comment]
Should also have on test in `AbstractDownloaderTest` that verifies stuck scenario in ticket.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java [hunk 6]
```diff
@@ -40,6 +40,7 @@
 @Validated
 @ConfigurationProperties("hedera.mirror.importer")
 public class MirrorProperties {
+    private ConsensusMode consensusMode = ConsensusMode.STAKE_IN_ADDRESS_BOOK; // see options at bottom of file
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java]: Done.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 7]
```diff
@@ -138,14 +139,36 @@ public Collection<ConsensusNode> getNodes() {
         var totalStake = new AtomicLong(0L);
         var nodes = new TreeSet<ConsensusNode>();
         var nodeStakes = new HashMap<Long, NodeStake>();
+        ConsensusMode consensusMode = mirrorProperties.getConsensusMode();
 
         nodeStakeRepository.findLatest().forEach(nodeStake -> {
+            if (consensusMode == ConsensusMode.EQUAL) {
+              nodeStake.setStake(1L);
+            }
             totalStake.addAndGet(nodeStake.getStake());
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java]: Done.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java (hunk 1 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java]: Done.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 3 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java]: Done.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 4 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java]: Done.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 5 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java]: Done.

**Comment by MarcKriguerAtHedera** [comment]
I couldn't access the address book from `AbstractDownloaderTest` (to create a parameterized test with different ConsensusModes, and have it be successful only from STAKE_IN_ADDRESS_BOOK), so instead I added a test to that suite that simply has stakes at 1/4 the total and fails to validate.  Let me know if you had something else in mind for `AbstractDownloaderTest.`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 8]
```diff
@@ -138,14 +139,32 @@ public Collection<ConsensusNode> getNodes() {
...
+            nodeStakeMaxTimestamp.getAndAccumulate(nodeStake.getConsensusTimestamp(), Math::max);
         });
 
         // For partial mirror nodes, node stake will provide a more accurate count
-        long nodeCount = !nodeStakes.isEmpty() ? nodeStakes.size() : addressBook.getNodeCount();
+        long nodeCount = (consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK || nodeStakes.isEmpty()) ?
+            addressBook.getNodeCount() : nodeStakes.size();
+
+        // if only including address book nodes in stake count, warn if any nodes are excluded
+        if (consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK && addressBook.getNodeCount() != nodeStakes.size()) {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:163]: don't warn when node stake is empty

```suggestion
        if (consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK && addressBook.getNodeCount() != nodeStakes.size() && !nodeStakes.isEmpty()) {
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 9]
```diff
@@ -138,14 +139,32 @@ public Collection<ConsensusNode> getNodes() {
...
         nodeStakeRepository.findLatest().forEach(nodeStake -> {
-            totalStake.addAndGet(nodeStake.getStake());
+            if (consensusMode == ConsensusMode.EQUAL) {
+              nodeStake.setStake(1L);
+            } else if (consensusMode != ConsensusMode.STAKE_IN_ADDRESS_BOOK ||
+                  nodesInAddressBook.contains(nodeStake.getNodeId())) {
+              totalStake.addAndGet(nodeStake.getStake());
+            }
             nodeStakes.put(nodeStake.getNodeId(), nodeStake);
+            nodeStakeMaxTimestamp.getAndAccumulate(nodeStake.getConsensusTimestamp(), Math::max);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:155]: node stakes from `findLatest` all have the same consensus timestamp

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 10]
```diff
@@ -962,39 +966,78 @@ void getNodesEmptyNodeStake() {
...
+                .allMatch(c -> c.getStake() == stake)
                 .extracting(ConsensusNode::getNodeId)
                 .containsExactly(0L, 1L, 2L, 3L);
     }
 
-    @Test
-    void getNodesWithNodeStakeCountMoreThanAddressBook() {
+    @CsvSource(textBlock = """
+    STAKE, 0, 5, 5
+    STAKE_IN_ADDRESS_BOOK, 0, 5, 4
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:994]: why the stake is set to 0?

should hard code it to 2 without parameterize it, then the expected total stake should be 10 and 8

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 11]
```diff
@@ -138,14 +139,36 @@ public Collection<ConsensusNode> getNodes() {
...
             totalStake.addAndGet(nodeStake.getStake());
             nodeStakes.put(nodeStake.getNodeId(), nodeStake);
         });
 
         // For partial mirror nodes, node stake will provide a more accurate count
-        long nodeCount = !nodeStakes.isEmpty() ? nodeStakes.size() : addressBook.getNodeCount();
+        long nodeCount = (consensusMode == ConsensusMode.STAKE_IN_ADDRESS_BOOK || nodeStakes.isEmpty()) ?
+            addressBook.getNodeCount() : nodeStakes.size();
+
+        // if only including address book nodes in stake count, reset and readd only address book nodes' stakes.
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java]: The original code (that this comment went along with) set totalStake back to 0, and looped over the address book's entries, re-adding the value back to totalStaek.  Steven had me change the code to only loop/add once, but this comment (now updated) was stale.  And "re-add" or "readd" was (originally) accurate, but now it's moot.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java (hunk 9 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:155]: ok, got rid of the `getAndAccumulate` and `Math::max` -- now it only sets `nodeStakeTimestamp` once.  (Since all the timestamps are the same, I dropped the "Max" from the variable name.)

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 12]
```diff
@@ -962,39 +966,78 @@ void getNodesEmptyNodeStake() {
                 .containsExactly(0L, 1L, 2L, 3L);
     }
 
-    @Test
-    void getNodesWithNodeStake() {
+    @CsvSource(textBlock = """
+    STAKE_IN_ADDRESS_BOOK, 10000, 4, 40000
+    EQUAL, 1, 4, 4
+    """)
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:972]: Done.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 13]
```diff
@@ -962,39 +966,78 @@ void getNodesEmptyNodeStake() {
...
+                .allMatch(c -> c.getTotalStake() == expectedTotalStake)
+                .allMatch(c -> c.getNodeAccountId().getEntityNum() - 3 == c.getNodeId())
+                .extracting(ConsensusNode::getNodeId)
+                .containsExactly(0L, 1L, 2L, 3L);
+    }
+
+    @CsvSource(textBlock = """
+    STAKE_IN_ADDRESS_BOOK, 10000, 6, 40000, 10000
+    STAKE, 10000, 6, 60000, 10000
+    EQUAL, 10000, 6, 6, 1
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:1020]: Done.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 14]
```diff
@@ -138,14 +139,33 @@ public Collection<ConsensusNode> getNodes() {
...
         nodeStakeRepository.findLatest().forEach(nodeStake -> {
-            totalStake.addAndGet(nodeStake.getStake());
+            if (consensusMode == ConsensusMode.EQUAL) {
+              nodeStake.setStake(1L);
+            } else if (consensusMode != ConsensusMode.STAKE_IN_ADDRESS_BOOK ||
+                  nodesInAddressBook.contains(nodeStake.getNodeId())) {
+              totalStake.addAndGet(nodeStake.getStake());
+            }
             nodeStakes.put(nodeStake.getNodeId(), nodeStake);
+            // rather than calling getAndUpdate with Math.max, this just sets the variable a single time.
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:155]: it's better to just say, all the node stake rows have the consensus timestamp, in case a comment is really needed

**Review by xin-hedera — DISMISSED** [review]
LGTM

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 15]
```diff
@@ -138,14 +139,33 @@ public Collection<ConsensusNode> getNodes() {
...
+        ConsensusMode consensusMode = mirrorProperties.getConsensusMode();
+        var nodesInAddressBook = addressBook.getEntries().stream().map(AddressBookEntry::getNodeId)
+            .collect(Collectors.toSet());
 
+        var nodeStakeTimestamp = new AtomicLong(0L);
         nodeStakeRepository.findLatest().forEach(nodeStake -> {
-            totalStake.addAndGet(nodeStake.getStake());
+            if (consensusMode == ConsensusMode.EQUAL) {
+              nodeStake.setStake(1L);
+            } else if (consensusMode != ConsensusMode.STAKE_IN_ADDRESS_BOOK ||
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:150]: Looks like this should be a separate if so it runs for all consensus modes, including EQUAL. Right now, totalStake is not being accumulated for EQUAL. I think it happens to work because of the `totalStake > 0 ? totalStake : nodeCount` logic in `ConsensusNodeWrapper`, but that's brittle to rely on that.
```suggestion
            }

            if (consensusMode != ConsensusMode.STAKE_IN_ADDRESS_BOOK ||
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 16]
```diff
@@ -962,39 +966,77 @@ void getNodesEmptyNodeStake() {
...
         long timestamp = domainBuilder.timestamp();
-        var nodeStake0 = domainBuilder.nodeStake().customize(n -> n.consensusTimestamp(timestamp).nodeId(0)).persist();
-        var nodeStake1 = domainBuilder.nodeStake().customize(n -> n.consensusTimestamp(timestamp).nodeId(1)).persist();
-        var nodeStake2 = domainBuilder.nodeStake().customize(n -> n.consensusTimestamp(timestamp).nodeId(2)).persist();
-        var nodeStake3 = domainBuilder.nodeStake().customize(n -> n.consensusTimestamp(timestamp).nodeId(3)).persist();
-        long totalStake = nodeStake0.getStake() + nodeStake1.getStake() + nodeStake2.getStake() + nodeStake3.getStake();
+        var nodeId = new AtomicInteger(0);
+        for (int i = 0; i < TEST_INITIAL_ADDRESS_BOOK_NODE_COUNT; i++) {
+            var nodeStake = domainBuilder.nodeStake().customize(n -> n.consensusTimestamp(timestamp)
+                .nodeId(nodeId.getAndIncrement()).stake(expectedNodeStake)).persist();
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:979]: We should hardcode this to 10000 and not pass the expectedNodeStake otherwise we're not testing the new logic.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 17]
```diff
@@ -962,39 +966,77 @@ void getNodesEmptyNodeStake() {
...
     }
 
-    @Test
-    void getNodesWithNodeStakeCountMoreThanAddressBook() {
+    @CsvSource(textBlock = """
+    STAKE, 5, 10
+    STAKE_IN_ADDRESS_BOOK, 5, 8
+    """)
+    @ParameterizedTest
+    void getNodesWithNodeStateCountMoreThanAddressBook(ConsensusMode mode, int nodeCount, long expectedTotalStake) {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:997]: This test seems to duplicate what `getNodesWithNodesNotInAddressBook` but without as much coverage. And strange that it has a nodeCount parameter that doesn't vary. Recommend it be removed.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 18]
```diff
@@ -962,39 +966,77 @@ void getNodesEmptyNodeStake() {
...
+                .containsExactly(0L, 1L, 2L, 3L);
+    }
+
+    @CsvSource(textBlock = """
+    STAKE_IN_ADDRESS_BOOK, 40000, 10000
+    STAKE, 60000, 10000
+    EQUAL, 6, 1
+    """)
+    @ParameterizedTest
+    void getNodesWithNodesNotInAddressBook(ConsensusMode mode, long expectedTotalStake, long expectedNodeStake) {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:1022]: Swap the order of the params to be consistent with the order from the other tests. Also can revert to the previous method name for clarity.
```suggestion
    void getNodesWithNodeStakeCountMoreThanAddressBook(ConsensusMode mode, long expectedNodeStake, long expectedTotalStake) {
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 19]
```diff
@@ -962,39 +966,77 @@ void getNodesEmptyNodeStake() {
                 .containsExactly(0L, 1L, 2L, 3L);
     }
 
-    @Test
-    void getNodesWithNodeStake() {
+    @CsvSource(textBlock = """
+    STAKE_IN_ADDRESS_BOOK, 10000, 40000
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:970]: Should add a STAKE test

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 20]
```diff
@@ -962,39 +966,77 @@ void getNodesEmptyNodeStake() {
...
+    EQUAL, 1, 4
+    """)
+    @ParameterizedTest
```
Comment (edwin-greene) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:973]: Might be good to have tests with 0 for the staked value for `STAKE` and `STAKE_IN_ADDRESS_BOOK`.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java (hunk 14 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java]: Done.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 16 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java]: Done.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 17 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java]: Done (and then renamed the latter to this name, as the later comment suggested).

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 18 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java]: Done/

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 19 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java]: Done.  (Per Edwin's later comment, ended up adding two).

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 21]
```diff
@@ -138,14 +139,33 @@ public Collection<ConsensusNode> getNodes() {
         var totalStake = new AtomicLong(0L);
         var nodes = new TreeSet<ConsensusNode>();
         var nodeStakes = new HashMap<Long, NodeStake>();
+        ConsensusMode consensusMode = mirrorProperties.getConsensusMode();
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java]: Done.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 20 above)
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:977]: Done.  Also added one for EQUAL (to make sure when specifying the stake as 0, that it (also) comes back as 1)

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 22]
```diff
@@ -962,39 +966,57 @@ void getNodesEmptyNodeStake() {
...
 
-    @Test
-    void getNodesWithNodeStakeCountMoreThanAddressBook() {
+    @CsvSource(textBlock = """
+    EQUAL, 1, 6
+    STAKE, 10000, 60000
+    STAKE_IN_ADDRESS_BOOK, 10000, 40000
+    """)
+    @ParameterizedTest
+    void getNodesWithNodeStateCountMoreThanAddressBook(ConsensusMode mode, long expectedNodeStake, long expectedTotalStake) {
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:1002]: Done.  (Thanks for catching that typo.)

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 23]
```diff
@@ -962,39 +966,57 @@ void getNodesEmptyNodeStake() {
                 .containsExactly(0L, 1L, 2L, 3L);
     }
 
-    @Test
-    void getNodesWithNodeStake() {
+    @CsvSource(textBlock = """
+    EQUAL, 1, 1, 4
```
[the remark this answers is not in the document]
Comment (MarcKriguerAtHedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:970]: Done.

**Review by xin-hedera — APPROVED** [review]
LGTM
