### PR TITLE
Clear topic notifications on error

### LINKED ISSUE #1028: Memory leak in NotifyingEntityListener
**Detailed Description**
Perfnet had a `ERROR: duplicate key value violates unique constraint "topic_message__topic_num_realm_num_seqnum"` repeatedly occurring due to an environment reset issue. This in turn triggered the heap size to grow until an OutOfMemoryError occurred.

**Actual Behavior**
```
Sep 10 14:51:54 mirrornode-performance-parser-1 java[27549]: 2020-09-10 14:51:54,913 WARN  [scheduling-1] c.h.m.i.d.NodeSignatureVerifier Verified signature file 2020-09-10T14_51_29.213794001Z.rcd_sig reached consensus but with some errors: {MISSING=[0.0.5]}
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: Aborting due to java.lang.OutOfMemoryError: Java heap space
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: # A fatal error has been detected by the Java Runtime Environment:
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #  Internal Error (debug.cpp:321), pid=27549, tid=27657
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #  fatal error: OutOfMemory encountered: Java heap space
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: # JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9)
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: # Java VM: OpenJDK 64-Bit Server VM (11.0.2+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /usr/lib/hedera-mirror-importer/core.27549)
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: # An error report file with more information is saved as:
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: # /usr/lib/hedera-mirror-importer/hs_err_pid27549.log
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: 2020-09-10 14:52:04,139 INFO  [scheduling-1] c.h.m.i.u.Utility Loading record format version 2 from record file: 2020-09-10T14_51_29.213794001Z.rcd
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: # If you would like to submit a bug report, please visit:
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #   http://bugreport.java.com/bugreport/crash.jsp
Sep 10 14:52:04 mirrornode-performance-parser-1 java[27549]: #
Sep 10 14:52:04 mirrornode-performance-parser-1 systemd[1]: hedera-mirror-importer.service: Main process exited, code=killed, status=6/ABRT
Sep 10 14:52:04 mirrornode-performance-parser-1 systemd[1]: hedera-mirror-importer.service: Failed with result 'signal'.
Sep 10 14:52:06 mirrornode-performance-parser-1 systemd[1]: hedera-mirror-importer.service: Service hold-off time over, scheduling restart.
Sep 10 14:52:06 mirrornode-performance-parser-1 systemd[1]: hedera-mirror-importer.service: Scheduled restart job, restart counter is at 35.
```

**Expected Behavior**
No OutOfMemoryError

**Environment:**
- Java: OpenJDK 11.0
- OS: Ubuntu 18.04
- Version: master

**Additional Context**

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
- Add `hedera.mirror.importer.publish.duration` metric to track pg notifications
- Fix `NotifyingEntityListener` not being notified of rollbacks and cleaning up its list of topic messages
- Fix `NotifyingEntityListener.onSave(..)` still attempting to notify when disabled

**Which issue(s) this PR fixes**:
Fixes #1028

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/notify/NotifyingEntityListener.java [hunk 1]
```diff
@@ -66,9 +83,17 @@ public void onTopicMessage(TopicMessage topicMessage) throws ImporterException {
...
 
     @EventListener
-    public void onBatch(EntityBatchEvent event) {
-        jdbcTemplate.execute(SQL, callback(topicMessages));
-        log.info("Finished notifying {} messages", topicMessages.size());
+    public void onSave(EntityBatchSaveEvent event) {
+        if (isEnabled()) {
+            Stopwatch stopwatch = Stopwatch.createStarted();
+            timer.record(() -> jdbcTemplate.execute(SQL, callback(topicMessages)));
+            log.info("Finished notifying {} messages in {}", topicMessages.size(), stopwatch);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/notify/NotifyingEntityListener.java:90]: nit: have you considered adding try... finally.. and move topicMessage.clear to the finally block? that way, we don't need the onCleanup listener

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/notify/NotifyingEntityListener.java:90]: We still need it for rollback scenario. onSave is only called after pgcopy batch is successful but if it's not then we need to clear the buffer.

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/notify/NotifyingEntityListener.java:90]: I see, missed the case that rollback is needed when exception happens before onSave is called

**Review by xin-hedera — APPROVED** [review]
LGTM

**Comment by steven-sheehy** [comment]
We need to revisit this batching in the future. I wanted to make minimal changes here. Later we should make the `EntityListener` classes stateless and move state to a parameter or use a framework like Spring Integration to do aggregation.
