### PR TITLE
Fix acceptance tests network race conditions

### LINKED ISSUE #6417: Acceptance test consensus node race condition
### Description

Acceptance tests frequently submit a transaction to consensus nodes then query consensus nodes to verify it has the expected data. The problem is consensus nodes reach consensus for any particular transaction at different wall clock times. So if you verify that node A has you receipt for transaction 1, then you query node B (since SDK queries/transactions are sent to random nodes by default) it may or may not have handled transaction 1 so its query may return incorrect data.

### Steps to reproduce

Run acceptance tests multiple times until it occurs.

### Additional context

```
2023-07-17T15:10:55.572-0600 I Pool-1-worker-2 c.h.m.t.e.a.s.FileFeature Executing step: the network confirms an append update 
2023-07-17T15:10:55.587-0600 E Pool-1-worker-2 c.h.m.t.e.a.s.FileFeature Scenario failure: 
I successfully create a file
the network confirms file presence
the mirror node REST API should return status 200 for the file transaction
I successfully update the file
the network confirms partial file contents
the mirror node REST API should return status 200 for the file transaction
I successfully append to the file
the network confirms an append update <- 
expected: 32L
 but was: 15L
the mirror node REST API should return status 200 for the file transaction
I successfully delete the file
the network confirms file absence
the mirror node REST API should return status 200 for the file transaction
 org.opentest4j.AssertionFailedError: 
expected: 32L
 but was: 15L
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at com.hedera.mirror.test.e2e.acceptance.steps.FileFeature.verifyFileInfo(FileFeature.java:137)
	at com.hedera.mirror.test.e2e.acceptance.steps.FileFeature.verifyNetworkUpdateResponse(FileFeature.java:121)
	at com.hedera.mirror.test.e2e.acceptance.steps.FileFeature.verifyNetworkFileAppendResponse(FileFeature.java:115)
	at ✽.the network confirms an append update(classpath:features/file/file.feature:13)
```

### Hedera network

other

### Version

main

### Operating system

None

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Remove racy consensus node queries in favor of mirror node queries

**Related issue(s)**:

Fixes #6417

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java [hunk 1]
```diff
@@ -171,82 +144,26 @@ public void verifyDeletedScheduleFromMirror() {
...
+        var signatureSet = mirrorSchedule.getSignatures().stream()
+                .map(MirrorScheduleSignature::getPublicKeyPrefix)
+                .collect(Collectors.toSet());
+        assertThat(signatureSet).hasSize(currentSignersCount);
+
+        switch (scheduleStatus) {
+            case DELETED, NON_EXECUTED -> assertThat(mirrorSchedule.getExecutedTimestamp())
+                    .isNull();
+            case EXECUTED -> assertThat(mirrorSchedule.getExecutedTimestamp()).isNotNull();
+            default -> {}
```
Comment (jascks) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java:163]: You can remove `default` since you've exhausted all possibilities for `ScheduleStatus`.

Comment (steven-sheehy) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java:163]: I didn't write this code, just removed the wrapper retryTemplate as it was unnecessary since the webClient will retry already.

**Review by jascks — APPROVED** [review]
LGTM

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java (hunk 1 above)
Comment (jascks) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java:163]: Okay, no worries. All looks good to me.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good

**Review by mgoelswirlds — APPROVED** [review]
