### PR TITLE
Optimize web3 fungible token historical total supply query

### LINKED ISSUE #8217: Web3 historical fungible token total supply query times out frequently
### Description

The web3 TokenRepository historical fungible token total supply query times out and causes `CONTRACT_REVERT_EXECUTED ` error.

### Steps to reproduce

Check mainnet web3 logs 

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.103.0

### Operating system

None

### LINKED ISSUE #8667: Flaky web3 integration tests
### Description

Many new web3 integration tests fail when running `./gradlew web3:test` locally, they seem to share the same problem, one sample log:

```
ContractDebugServiceTest > failedNestedCallWithHardcodedResult(ContractFunctionProviderEnum) > [6] function=MINT_TOKEN FAILED
    java.lang.RuntimeException: java.lang.ArithmeticException: BigInteger divide by zero
        at com.hedera.mirror.web3.ContextExtension.lambda$intercept$0(ContextExtension.java:70)
        at com.hedera.mirror.web3.common.ContractCallContext.lambda$run$0(ContractCallContext.java:83)
        at java.base/java.lang.ScopedValue$Carrier$CallableAdapter.call(ScopedValue.java:461)
        at java.base/jdk.internal.vm.ScopedValueContainer.callWithoutScope(ScopedValueContainer.java:162)
        at java.base/jdk.internal.vm.ScopedValueContainer.call(ScopedValueContainer.java:147)
        at java.base/java.lang.ScopedValue$Carrier.get(ScopedValue.java:448)
        at java.base/java.lang.ScopedValue.getWhere(ScopedValue.java:623)
        at com.hedera.mirror.web3.common.ContractCallContext.run(ContractCallContext.java:83)
        at com.hedera.mirror.web3.ContextExtension.intercept(ContextExtension.java:65)
        at com.hedera.mirror.web3.ContextExtension.interceptTestTemplateMethod(ContextExtension.java:58)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:218)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:214)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
        at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:142)
        at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:110)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:110)
        at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:44)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy2/jdk.proxy2.$Proxy5.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        java.lang.ArithmeticException: BigInteger divide by zero
            at java.base/java.math.MutableBigInteger.divideKnuth(MutableBigInteger.java:1184)
            at java.base/java.math.BigInteger.divideKnuth(BigInteger.java:2441)
            at java.base/java.math.BigInteger.divide(BigInteger.java:2422)
            at com.hedera.services.hapi.utils.fees.FeeBuilder.getAFromB(FeeBuilder.java:229)
            at com.hedera.services.hapi.utils.fees.FeeBuilder.getTinybarsFromTinyCents(FeeBuilder.java:84)
            at com.hedera.services.fees.calculation.UsageBasedFeeCalculator.gasPriceInTinybars(UsageBasedFeeCalculator.java:125)
            at com.hedera.services.fees.calculation.UsageBasedFeeCalculator.estimatedGasPriceInTinybars(UsageBasedFeeCalculator.java:115)
            at com.hedera.services.store.contracts.precompile.utils.PrecompilePricingUtils.computeGasRequirement(PrecompilePricingUtils.java:177)
            at com.hedera.services.store.contracts.precompile.impl.AbstractWritePrecompile.getGasRequirement(AbstractWritePrecompile.java:49)
            at com.hedera.services.store.contracts.precompile.HTSPrecompiledContract.computePrecompile(HTSPrecompiledContract.java:198)
            at com.hedera.services.store.contracts.precompile.HTSPrecompiledContract.computeCosted(HTSPrecompiledContract.java:158)
            at com.hedera.mirror.web3.evm.contracts.execution.AbstractEvmMessageCallProcessor.calculatePrecompileGasAndOutput(AbstractEvmMessageCallProcessor.java:64)
            at com.hedera.mirror.web3.evm.contracts.execution.AbstractEvmMessageCallProcessor.executeHederaPrecompile(AbstractEvmMessageCallProcessor.java:50)
            at com.hedera.node.app.service.evm.contracts.execution.HederaEvmMessageCallProcessor.start(HederaEvmMessageCallProcessor.java:62)
            at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:196)
            at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.process(HederaEvmTxProcessor.java:209)
            at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.process(HederaEvmTxProcessor.java:208)
            at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.execute(HederaEvmTxProcessor.java:154)
            at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.execute(HederaEvmTxProcessor.java:113)
            at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessorImpl.execute(MirrorEvmTxProcessorImpl.java:106)
            at com.hedera.mirror.web3.service.ContractDebugServiceTest.lambda$setUpArgumentCaptors$1(ContractDebugServiceTest.java:103)
            at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessorImpl.execute(MirrorEvmTxProcessorImpl.java:95)
            at com.hedera.mirror.web3.service.ContractCallService.doProcessCall(ContractCallService.java:109)
            at com.hedera.mirror.web3.service.ContractCallService.callContract(ContractCallService.java:102)
            at com.hedera.mirror.web3.service.ContractDebugService.lambda$processOpcodeCall$0(ContractDebugService.java:64)
            at com.hedera.mirror.web3.common.ContractCallContext.lambda$run$0(ContractCallContext.java:83)
            at java.base/java.lang.ScopedValue$Carrier$CallableAdapter.call(ScopedValue.java:461)
            at java.base/jdk.internal.vm.ScopedValueContainer.callWithoutScope(ScopedValueContainer.java:162)
            at java.base/jdk.internal.vm.ScopedValueContainer.call(ScopedValueContainer.java:147)
            at java.base/java.lang.ScopedValue$Carrier.get(ScopedValue.java:448)
            at java.base/java.lang.ScopedValue.getWhere(ScopedValue.java:623)
            at com.hedera.mirror.web3.common.ContractCallContext.run(ContractCallContext.java:83)
            at com.hedera.mirror.web3.service.ContractDebugService.processOpcodeCall(ContractDebugService.java:59)
            at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
            at java.base/java.lang.reflect.Method.invoke(Method.java:580)
            at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
            at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
            at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
            at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:174)
            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
            at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
            at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
            at com.hedera.mirror.web3.service.ContractDebugService$$SpringCGLIB$$0.processOpcodeCall(<generated>)
            at com.hedera.mirror.web3.service.ContractDebugServiceTest.verifySuccessfulOpcodeTracerCall(ContractDebugServiceTest.java:185)
            at com.hedera.mirror.web3.service.ContractDebugServiceTest.verifyOpcodeTracerCall(ContractDebugServiceTest.java:156)
            at com.hedera.mirror.web3.service.ContractDebugServiceTest.failedNestedCallWithHardcodedResult(ContractDebugServiceTest.java:135)
``` 

They seem to pass in github workflow runs with retry on and the [logs](https://productionresultssa17.blob.core.windows.net/actions-results/cf33964a-0aa7-43a8-b18c-31a565265029/workflow-job-run-e404a9d2-d793-5909-68d4-0aa66c96c1ed/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-06-28T14%3A33%3A16Z&sig=o0DyS4HTBz4A7IvB%2FVgASUC87WBvXwAIIkc8ccpzQUk%3D&ske=2024-06-28T22%3A51%3A31Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-06-28T10%3A51%3A31Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-06-28T14%3A23%3A11Z&sv=2023-11-03) also show the same failures.

### Steps to reproduce

`./gradlew web3:test`

### Additional context

_No response_

### Hedera network

other

### Version

v0.109.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR optimizes web3 fungible token historical total supply query

- Get base total supply from token balance snapshot
- Fix flaky integration tests

**Related issue(s)**:

Fixes #8217
Fixes #8667 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java [hunk 1]
```diff
@@ -17,13 +17,18 @@
...
 import com.hedera.mirror.web3.evm.store.Store;
 import jakarta.annotation.Resource;
 import org.junit.jupiter.api.extension.ExtendWith;
+import org.springframework.boot.test.mock.mockito.SpyBean;
 
 @ExtendWith(ContextExtension.class)
 public abstract class Web3IntegrationTest extends CommonIntegrationTest {
 
+    @SpyBean
+    protected MirrorEvmTxProcessor processor;
```
Comment (xin-hedera) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java:30]: the spy bean is the root cause of the integration test flakiness...

For two integration tests with the same configuration however only one with a spybean, spring boot test framework will decide to use the same test application context. However it'll reload the context, and the consequence in our web3 integration tests from that point on is, there are two beans of each class and it also creates two PostgreSQL test containers.

When we run any integration tests which read data from the db container, and the subject being tested tries to read exchange rate / fee schedule files from the database, there is 50% chance it uses the hikari pool which connects to the empty database (not the one with those file populated). thus it will fail.

In github workflow gradle job, those failed test cases will get retried, and only those with the spybean are retried, so they'll pass.

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java [hunk 2]
```diff
@@ -1708,30 +1697,6 @@ private void nftCustomFeePersist(final EntityId senderEntityId, final EntityId n
                 .persist();
     }
 
-    protected void fileDataPersist() {
```
Comment (xin-hedera) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java:1711]: there is already a dedicated `exchangeRatesPersist()` function, so remove the reduandancy

**Review by jascks — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
LGTM
