### PR TITLE
Make `MirrorEntityAccess.isUsable` **not** consider expiry

### LINKED ISSUE #6928: web3 module MirrorEntityAccess.isUsable is missing logic for autorenew consideration
### Description

In 0.88 a change was made to the MirrorEntityAccess.isUsable() awas refactored to enable contract deployment cases.
This introduced a regression in which contract accounts expiration is now always considered and teh account is considered unusable if expiration is behind the current timestamp.

Conceptually this is correct, however expiry consideration are not yet enabled on the network and should therefore not be used to discount an accounts usability.

### Steps to reproduce

Query contracts where the to value is an expired contract.
This will result in the isUsable returning false and in some method cases returning the wrong value in response.

### Additional context

_No response_

### Hedera network

mainnet

### Version

0.88.0

### Operating system

None

### PR DESCRIPTION
**Pull request by david-bakin-sl**
**Description**:

`MirrorEntityAccess` is using expiry as a gate for `isUsable` for accounts, incl contracts

Should be gated on feature flags - but isn't.  Expiry isn't enabled now but this code thought it was.

Solution for now is to simply _not_ check for expiry as that is the network behavior right now.

Also, make sure balance behaves properly: >0 balance means isUsable, <0 balance means _not_ isUsable, and ==0 balance is a special case.

**Related issue(s)**:

Fixes #6928

Will need #6941  to reimplement expiry here, properly

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java [hunk 1]
```diff
@@ -52,11 +57,19 @@ public boolean isUsable(final Address address) {
...
+        if (balance < 0) {
+            return false;
+        }
+
         if (Address.ZERO.equals(address)) {
             return false;
         }
 
-        return account.getExpiry() >= Instant.now().getEpochSecond();
+        if (account.isEmptyAccount()) {
```
Comment (Nana-EC) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java:68]: Q: Is this already covered by an existing test or does it need a new one in `MirrorEntityAccessTest`?

**Review by Nana-EC — COMMENTED** [review]
LG, one test clarification

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java [hunk 2]
```diff
@@ -52,11 +57,19 @@ public boolean isUsable(final Address address) {
             return true;
         }
 
+        if (balance < 0) {
```
Comment (Nana-EC) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java:60]: Q: not possible right. Do we need this given the accessor?

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java (hunk 1 above)
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java:68]: I don't see how this scenario is possible against a real db. The empty account is the zero address and there should never be a `0.0.0` in the db.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java (hunk 2 above)
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java:60]: I don't see how this scenario is possible against a real db. There's no negative balance accounts or we'd have a serious problem with the mirror node.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java (hunk 2 above)
Comment (david-bakin-sl) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java:60]: It's not not possible because of the accessor, it's "not possible" because we think that there's no way for an account to be in arrears, given the network behaving properly.  A unit test covers this.  Sort of belt-and-suspenders I guess.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java (hunk 1 above)
Comment (david-bakin-sl) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java:68]: Test `MirrorEntityAccessTest.isNotUsableWithWrongAlias` says this is what happens with a "wrong alias". It's a given to mockito in that test.  Whether it actually happens in the codebase I don't know.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java (hunk 2 above)
Comment (david-bakin-sl) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java:60]: Well I agree with you.  But someone thought it was worth testing at `MirrorEntityAccessTest.isNotUsableWithNegativeBalance'.   I don't have enough information to know what triggered the writing of that test.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java (hunk 1 above)
Comment (david-bakin-sl) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java:68]: Are you referring to new L68?  This condition is tested in `MirrorEntityAccessTest.isNotUsableWithWrongAlias`.  As I mention in a separate comment below, I don't know if this actually happens in real life.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java (hunk 2 above)
Comment (david-bakin-sl) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java]: removed the test and the code (per offline discussion)

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java (hunk 1 above)
Comment (david-bakin-sl) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java]: removed the test and the code (per offline discussion)

Comment (david-bakin-sl) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccess.java]: removed the test and the code (per offline discussion)

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java [hunk 3]
```diff
@@ -85,37 +86,23 @@ void isUsableWithPositiveBalance() {
...
-        final long balance = -1L;
-        when(store.getAccount(ADDRESS, OnMissing.DONT_THROW)).thenReturn(account);
-        when(account.getBalance()).thenReturn(balance);
-        final var result = mirrorEntityAccess.isUsable(ADDRESS);
-        assertThat(result).isFalse();
-    }
-
-    @Test
-    void isNotUsableWithWrongAlias() {
-        final var address = Address.fromHexString("0x3232134567785444e");
```
Comment (Nana-EC) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java:99]: This was wrong due to to bad entry. I had changed it to 
```suggestion
   final var address = Address.fromHexString("0x0");
```

**Review by Nana-EC — APPROVED** [review]
LG, one suggestion on the address.

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java (hunk 3 above)
Comment (david-bakin-sl) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/MirrorEntityAccessTest.java:99]: Accepted (but I did my own push of a new commit to _reinclude_ the test)

**Review by steven-sheehy — APPROVED** [review]
