### PR TITLE
181 incorrect hash calculations

### LINKED ISSUE #181: Utility: File Hash Calculation incorrect for v2 record files
**Detailed Description**
Prior attempts to streamline code around file hash calculation omitted to take into account that v2 file hashes aren't calculated the same way as v1 files.

**Actual Behavior**
Download v2 record files from testnet bucket, files fail to pass hash match validation against signature files.

**Expected Behavior**
Files, either v1 or v2 should pass the signature hash match.

**Environment:**

**Additional Context**

### PR DESCRIPTION
**Pull request by gregscullard**
Corrects the previously sanitised file hash calculations to bring back the necessary v2 changes.

**Detailed description**:
See issue for bug description.
In addition, this PR resolves a few issues related to rolling back a database transaction in the event of errors and avoids double calculation of file hash (prior to and during processing).

**Which issue(s) this PR fixes**:
Fixes #181 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [X] Tested with V2 files (v1 file really no longer need testing)

### CODE REVIEW

File: src/main/java/com/hedera/utilities/Utility.java [hunk 1]
```diff
@@ -135,22 +131,189 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+			md = MessageDigest.getInstance(FileDelimiter.HASH_ALGORITHM);
+
+			int eventStreamFileVersion = dis.readInt();
+			md.update(Utility.integerToBytes(eventStreamFileVersion));
+
+			log.debug("Loading event file {} with version {}", filename, eventStreamFileVersion);
+			if (eventStreamFileVersion < FileDelimiter.EVENT_STREAM_FILE_VERSION_LEGACY) {
+				log.error("EventStream file format version doesn't match. File is: {}", filename);
+				return null;
+			} else if (eventStreamFileVersion >= FileDelimiter.EVENT_STREAM_FILE_VERSION_CURRENT) {
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/utilities/Utility.java]: If it's greater than EVENT_STREAM_FILE_VERSION_CURRENT then should it be an error as unsupported?

File: src/main/java/com/hedera/utilities/Utility.java [hunk 2]
```diff
@@ -135,22 +131,189 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+	}
+	
+	private static byte[] getRecordFileHash(String filename) {
+		byte[] readFileHash = new byte[48];
+		
+		try (DataInputStream dis = new DataInputStream(new FileInputStream(filename))) {
+			MessageDigest md = MessageDigest.getInstance(FileDelimiter.HASH_ALGORITHM);
+			MessageDigest mdForContent = MessageDigest.getInstance(FileDelimiter.HASH_ALGORITHM);
+
+			int record_format_version = dis.readInt();
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/utilities/Utility.java]: Should verify version is not less than or greater than supported versions and throw an error if so.

File: src/main/java/com/hedera/parser/RecordFileParser.java [hunk 3]
```diff
@@ -70,7 +64,7 @@ public RecordFileParser() throws Exception {
 	 * @return return previous file hash
```
Comment (mike-burrage-hedera) [inline src/main/java/com/hedera/parser/RecordFileParser.java]: Please update the javadoc and explain what the parameters are for

File: src/main/java/com/hedera/parser/RecordFileParser.java [hunk 4]
```diff
@@ -84,17 +78,11 @@ static public boolean loadRecordFile(String fileName, String previousFileHash) t
 		INIT_RESULT initFileResult = RecordFileLogger.initFile(fileName);
 		Stopwatch stopwatch = Stopwatch.createStarted();
 
-		if ((initFileResult == INIT_RESULT.OK) || (initFileResult == INIT_RESULT.SKIP)) {
```
Comment (mike-burrage-hedera) [inline src/main/java/com/hedera/parser/RecordFileParser.java]: Why did this change?

File: src/main/java/com/hedera/utilities/Utility.java [hunk 5]
```diff
@@ -135,22 +131,189 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+				return fileHash;
+	
+			} catch (NoSuchAlgorithmException e) {
 				log.error("Exception {}", e);
+				return null;
+			}
+		}
+	}
+	
+	private static byte[] getEventFileHash(String filename) {
```
Comment (mike-burrage-hedera) [inline src/main/java/com/hedera/utilities/Utility.java]: At least add comment "returns null on error"

File: src/main/java/com/hedera/utilities/Utility.java [hunk 6]
```diff
@@ -135,22 +131,189 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+						break;
+					case FileDelimiter.EVENT_STREAM_START_WITH_VERSION:
+						if (calculateContentHash) {
+							mdForContent.update(typeDelimiter);
+						} else {
+							md.update(typeDelimiter);
+						}
+						break;
+					default:
+						log.error("Unknown file delimiter {} for event file {}", typeDelimiter, file);
```
Comment (mike-burrage-hedera) [inline src/main/java/com/hedera/utilities/Utility.java]: return null?

File: src/main/java/com/hedera/utilities/Utility.java (hunk 1 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: There are confusing variable declarations for event versions
```
	public static final byte EVENT_STREAM_FILE_VERSION_LEGACY = 2;
	public static final byte EVENT_STREAM_VERSION = 2;
	public static final byte EVENT_STREAM_FILE_VERSION_CURRENT = 3;
```
I'd rather confer with engineering before making a call on this one.

File: src/main/java/com/hedera/utilities/Utility.java (hunk 2 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: I'd prefer to confer with engineering before making a decision one way or another.

File: src/main/java/com/hedera/parser/RecordFileParser.java (hunk 4 above)
Comment (gregscullard) [reply src/main/java/com/hedera/parser/RecordFileParser.java]: If the file already exists, the `initFile` method returns SKIP instead of OK, indicating there is no need to reload the file into the database. Prior to this change, the logger would fail later on duplicate primary keys/foreign key constraints on file_id. Skipping altogether is more efficient.

File: src/main/java/com/hedera/parser/RecordFileParser.java [hunk 7]
```diff
@@ -224,6 +188,7 @@ static public boolean loadRecordFile(String fileName, String previousFileHash) t
 	 */
 	static public void loadRecordFiles(List<String> fileNames) throws Exception {
 		String prevFileHash = applicationStatus.getLastProcessedRcdHash();
+		String thisFileHash = "";
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/parser/RecordFileParser.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java [hunk 8]
```diff
@@ -135,22 +131,188 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+
+							break;
+						case FileDelimiter.RECORD_TYPE_SIGNATURE:
+							int sigLength = dis.readInt();
+							byte[] sigBytes = new byte[sigLength];
+							dis.readFully(sigBytes);
+							log.trace("File {} has signature {}", filename, Hex.encodeHexString(sigBytes));
+							break;
+						default:
+							log.error("Unknown record file delimiter {} for file {}", typeDelimiter, filename);
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java [hunk 9]
```diff
@@ -135,22 +131,188 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+			MessageDigest md = MessageDigest.getInstance(FileDelimiter.HASH_ALGORITHM);
+			MessageDigest mdForContent = MessageDigest.getInstance(FileDelimiter.HASH_ALGORITHM);
+
+			int record_format_version = dis.readInt();
+			int version = dis.readInt();
+
+			md.update(Utility.integerToBytes(record_format_version));
+			md.update(Utility.integerToBytes(version));
+
+			log.info("Calculating hash for version {} record file: {}", record_format_version, filename);
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java [hunk 10]
```diff
@@ -135,22 +131,188 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+								md.update(Utility.integerToBytes(byteLength));
+								md.update(rawBytes);
+							}
+
+							break;
+						case FileDelimiter.RECORD_TYPE_SIGNATURE:
+							int sigLength = dis.readInt();
+							byte[] sigBytes = new byte[sigLength];
+							dis.readFully(sigBytes);
+							log.trace("File {} has signature {}", filename, Hex.encodeHexString(sigBytes));
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java [hunk 11]
```diff
@@ -135,22 +131,188 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
-			return fileHash;
 
-		} catch (NoSuchAlgorithmException e) {
-			log.error("Exception {}", e);
+			if (record_format_version >= FileDelimiter.RECORD_FORMAT_VERSION) {
+				md.update(mdForContent.digest());
+			}
+			readFileHash = md.digest();
+			
+			log.trace("Calculated file hash for the current file {}", Hex.encodeHexString(readFileHash));
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java [hunk 12]
```diff
@@ -135,22 +131,188 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+						case FileDelimiter.RECORD_TYPE_SIGNATURE:
+							int sigLength = dis.readInt();
+							byte[] sigBytes = new byte[sigLength];
+							dis.readFully(sigBytes);
+							log.trace("File {} has signature {}", filename, Hex.encodeHexString(sigBytes));
+							break;
+						default:
+							log.error("Unknown record file delimiter {} for file {}", typeDelimiter, filename);
+					}
+				} catch (Exception e) {
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java [hunk 13]
```diff
@@ -135,22 +131,189 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+			}
+			log.trace("Successfully calculated hash for {}", filename);
+		} catch (Exception e) {
+			log.error("Error parsing event file {}", filename, e);
+			return null;
+		}
+
+		if (calculateContentHash) {
+			byte[] contentHash = mdForContent.digest();
+			md.update(contentHash);
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java [hunk 14]
```diff
@@ -135,22 +131,189 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+
+		try (DataInputStream dis = new DataInputStream(new FileInputStream(file))) {
+			md = MessageDigest.getInstance(FileDelimiter.HASH_ALGORITHM);
+
+			int eventStreamFileVersion = dis.readInt();
+			md.update(Utility.integerToBytes(eventStreamFileVersion));
+
+			log.debug("Loading event file {} with version {}", filename, eventStreamFileVersion);
+			if (eventStreamFileVersion < FileDelimiter.EVENT_STREAM_FILE_VERSION_LEGACY) {
+				log.error("EventStream file format version doesn't match. File is: {}", filename);
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/parser/RecordFileParser.java (hunk 3 above)
Comment (gregscullard) [reply src/main/java/com/hedera/parser/RecordFileParser.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java (hunk 5 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java (hunk 6 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/parser/RecordFileParser.java [hunk 15]
```diff
@@ -173,7 +141,7 @@ static public boolean loadRecordFile(String fileName, String previousFileHash) t
 									}
 								}
 								break;
-							case TYPE_SIGNATURE:
+							case FileDelimiter.RECORD_TYPE_SIGNATURE:
 								int sigLength = dis.readInt();
 								byte[] sigBytes = new byte[sigLength];
 								dis.readFully(sigBytes);
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/parser/RecordFileParser.java]: Comment appears out of place ?

File: src/main/java/com/hedera/utilities/Utility.java (hunk 1 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Raised issue #184 for engineering input.

File: src/main/java/com/hedera/utilities/Utility.java (hunk 2 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Raised issue #184 for engineering input.

Comment (steven-sheehy) [reply src/main/java/com/hedera/utilities/Utility.java]: Defer to #184

File: src/main/java/com/hedera/utilities/Utility.java (hunk 1 above)
Comment (steven-sheehy) [reply src/main/java/com/hedera/utilities/Utility.java]: Defer to #184

File: src/main/java/com/hedera/utilities/Utility.java [hunk 16]
```diff
@@ -135,22 +131,189 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
 			try {
-				array = Files.readAllBytes(Paths.get(fileName));
-			} catch (IOException e) {
+				md = MessageDigest.getInstance(FileDelimiter.HASH_ALGORITHM);
+	
+				byte[] array = new byte[0];
+				try {
+					array = Files.readAllBytes(Paths.get(fileName));
+				} catch (IOException e) {
+					log.error("Exception {}", e);
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Consolidated error handling.
