### PR TITLE
Fix stale accounts REST API

### LINKED ISSUE #1177: Accounts Info REST API responses are often stale
**Detailed Description**
The account endpoints sometimes return stale info for a few minutes i.e. after account creation the api's don't return the account info.

This is likely because it relies on balance info which is provided by the balance stream which is at a slower frequency thant the record stream.
The result is the db can contain account info immediately after network creation but the api will return a 404 until the csv file is process and `account_balance` table is updated.

**Actual Behavior**
1. Submit a `CRYPTOCREATEACCOUNT` Transaction to create a new account `x.y.z`
2. Make a query to the `/api/v1/accounts?account.id=x.y.z` or `/api/v1/accounts/x.y.z` endpoints 
3. Endpoints return 404's

**Expected Behavior**
Endpoint should return account info

**Environment:**
- Version: v0.21.0

**Additional Context**
sql for those endpoints use balances first in their joins, which is likely why no results are provided. 
Potentially change it to go to entities first and then balances, so it at least shows account info with empty balances when first added to show it's existence.

### PR DESCRIPTION
**Pull request by Nana-EC**
**Detailed description**:
Initial balance inner joins used by account rest api's resulted in info being stale.
In some cases there would be no balance and therefore new accounts were accidentally filter out.

- Rearrange join to start with entity filter to get all accounts then pick up balances
- Add 3 integration spec files to cover cases were accounts had no balance yet
- Remove cases of doubling up on entity and account_id filter 

**Which issue(s) this PR fixes**:
Fixes #1177 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-rest/accounts.js [hunk 1]
```diff
@@ -191,15 +180,9 @@ const getOneAccount = async (req, res) => {
 
   // Because of the outer join on the 'account_balance ab' and 't_entities e' below, we
   // need to look  for the given account.id in both account_balance and t_entities table and combine with an 'or'
```
Comment (ijungmann) [inline hedera-mirror-rest/accounts.js:182]: I think this comment might be out of date.

File: hedera-mirror-rest/accounts.js [hunk 2]
```diff
@@ -80,12 +82,11 @@ const getAccountQuery = (extraWhereCondition, orderClause, order, query) => {
...
        ) as token_balances
-    from account_balance ab
-    full outer join t_entities e on (
-      ab.account_id = e.id
-      and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}
-    )
-    where ab.consensus_timestamp = (select max(consensus_timestamp) from account_balance) ${extraWhereCondition || ''}
+    from (select id, fk_entity_type_id, exp_time_ns, auto_renew_period, key, deleted, ed25519_public_key_hex from t_entities where fk_entity_type_id < ${
+      utils.ENTITY_TYPE_FILE
+    }) as e
```
Comment (xin-hedera) [inline hedera-mirror-rest/accounts.js:87]: it's easier to read in this way:
```
from t_entities e
```
then move the condition `e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}` to the top level where clause

assume there is no performance difference.

File: hedera-mirror-rest/accounts.js [hunk 3]
```diff
@@ -80,12 +82,11 @@ const getAccountQuery = (extraWhereCondition, orderClause, order, query) => {
...
+    left outer join account_balance ab on ab.account_id = e.id
+    where ${startWhereCondition} (ab.consensus_timestamp = (select max(consensus_timestamp) from account_balance) or ab.consensus_timestamp is null)
```
Comment (xin-hedera) [inline hedera-mirror-rest/accounts.js:89]: adding `or ab.consensus_timestamp is null` here may have big performance impact, suggest to analyze it with testnet db.

File: hedera-mirror-rest/accounts.js [hunk 4]
```diff
@@ -80,12 +82,11 @@ const getAccountQuery = (extraWhereCondition, orderClause, order, query) => {
...
-    from account_balance ab
-    full outer join t_entities e on (
-      ab.account_id = e.id
-      and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}
-    )
-    where ab.consensus_timestamp = (select max(consensus_timestamp) from account_balance) ${extraWhereCondition || ''}
+    from (select id, fk_entity_type_id, exp_time_ns, auto_renew_period, key, deleted, ed25519_public_key_hex from t_entities where fk_entity_type_id < ${
+      utils.ENTITY_TYPE_FILE
+    }) as e
+    left outer join account_balance ab on ab.account_id = e.id
```
Comment (ijungmann) [inline hedera-mirror-rest/accounts.js:88]: Would there ever be a scenario where we have an account balance without the entity?  Just want to make sure getting rid of the full outer join doesn't cause side effects.

**Review by ijungmann — COMMENTED** [review]
Looks good to me, just a couple minor things.

File: hedera-mirror-rest/accounts.js (hunk 4 above)
Comment (xin-hedera) [inline hedera-mirror-rest/accounts.js:88]: it was a `full outer join`, which based on my understanding covers the corner case that an account is not in `t_entities` but has balance record in `account_balance` table.

I'm not sure if that's a valid case or if it has happened before though.

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/accounts.js (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js:88]: No. All account balances are for existing accounts created on the network.
The worst case scenario is the balance file gets serialized right after account creation, but even then at the most it would be 2 seconds later that the record file with the account creation transaction would be serialized.

Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js:88]: Xin reminded me of partial data.
even in accounts where mirror node was started after the parser has logic to create that entity for any applicable transaction that comes across.
So I take it back it could happen it could happen and that might have been the reasoning for the dual id logic between entity and account_balance

Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js:88]: Yes good point.
The importer does have logic to create entities it comes across when parsing the record file.
However, yes that would miss account with balances who don't have a transaction come across for a while.

I might have to revert back to some of the logic here and simple just reorganize.

Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js]: Fixed this by doing an early inner join to get balances from max timestamp. This gives last balance for all accounts know by network.
Then kept the outer join which will add any mismatches from records.
This now picks up all accounts even those without balances

File: hedera-mirror-rest/accounts.js (hunk 2 above)
Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js]: Reverted back to original query with modification so this shouldn't apply anymore

File: hedera-mirror-rest/accounts.js (hunk 3 above)
Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js]: You were right. Had atrocious performance.
Fixed this by doing an early inner join to get balances from max timestamp. This gives last balance for all accounts know by network.
Then kept the outer join which will add any mismatches from records.
This now picks up all accounts even those without balances.

Tested on dev with all testnet data. Change was marginal with an increase of about 30-40ms in query time

File: hedera-mirror-rest/accounts.js (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js]: Fixed, see note above

File: hedera-mirror-rest/accounts.js (hunk 1 above)
Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js:194]: With revert comment is not still applicable

**Review by ijungmann — APPROVED** [review]

File: hedera-mirror-rest/accounts.js [hunk 5]
```diff
@@ -81,11 +83,12 @@ const getAccountQuery = (extraWhereCondition, orderClause, order, query) => {
            and ab.account_id = tb.account_id
        ) as token_balances
     from account_balance ab
+    inner join (select max(consensus_timestamp) as time_stamp_max from account_balance) as abm on ab.consensus_timestamp = abm.time_stamp_max
     full outer join t_entities e on (
-      ab.account_id = e.id
-      and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}
+        ab.account_id = e.id
+        and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}
```
Comment (xin-hedera) [inline hedera-mirror-rest/accounts.js:89]: per the offline discussion, `e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}` intends to include only `account` and `contract` entities but it won't work because of the full outer join. This results in entities of other types, e.g., `topic` being included in the query output.

should also add entities of other types to integration tests

File: hedera-mirror-rest/accounts.js [hunk 6]
```diff
@@ -191,13 +192,9 @@ const getOneAccount = async (req, res) => {
...
   // need to look  for the given account.id in both account_balance and t_entities table and combine with an 'or'
-  const entitySql = getAccountQuery(` and (
-      (ab.account_id  =  ?)
-      or (e.id = ?
-          and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}
-          )
-       )`);
-
+  const entitySql = getAccountQuery(
+    ` (ab.account_id = ? or (e.id = ? and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}))`
```
Comment (xin-hedera) [inline hedera-mirror-rest/accounts.js:196]: should remove `and e.fk_entity_type_id < ${utils.ENTITY_TYPE_FILE}` after moving the same condition out of the full outer join into where clause

line 115 needs the same update

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/accounts.js (hunk 5 above)
Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js:89]: Yes, I'm changing the table that the outer join uses from 
```
full outer join t_entities e
```
to
```
full outer join (select id, exp_time_ns, auto_renew_period, key, deleted, fk_entity_type_id, ed25519_public_key_hex from t_entities where fk_entity_type_id < 3) e
```
This will ensure only account and contracts are considered

Will also update added tests with other entities

File: hedera-mirror-rest/accounts.js (hunk 6 above)
Comment (Nana-EC) [reply hedera-mirror-rest/accounts.js:196]: Removed along with above noted change

**Review by xin-hedera — APPROVED** [review]
