### PR TITLE
Fix failing selfdestruct estimate gas test

### LINKED ISSUE #7592: Estimate gas selfdestruct operation acceptance test fails
### Problem

After the introduction of custom self destruct operations in mirror-node acceptance test fails -> 
I call estimateGas with function that performs self destruct

### Solution

Add from parameter in request body of the acceptance test call for self destruct

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:
The self destruct estimate gas test is failing since currently estimate gas tests do not pass from value in request body.
The newly added custom self destruct operation makes validations on the from address which causes the test to fail.
Passing a valid from address in request body fixes the issue. 

Modified classes:
Added new method in `AbstractEstimateFeature` -> `validateGasEstimationWithSender` which now passes a from address
Modified self destruct test to use the new method 

**Related issue(s)**:

Fixes #7592

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by 0xivanov — DISMISSED** [review]

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java [hunk 1]
```diff
@@ -80,6 +80,32 @@ protected void validateGasEstimation(String data, ContractMethodInterface actual
...
+                .data(data)
+                .to(solidityAddress)
+                .from(contractClient.getClientAddress())
+                .estimate(true)
+                .build();
+        ContractCallResponse msgSenderResponse = mirrorClient.contractsCall(contractCallRequestBody);
+        int estimatedGas = msgSenderResponse.getResultAsNumber().intValue();
+
+        assertWithinDeviation(actualGasUsed.getActualGas(), estimatedGas, lowerDeviation, upperDeviation);
+    }
```
Comment (IvanKavaldzhiev) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java:107]: To avoid code duplication we can define a private method with `Optional<Address>` argument for the sender, and this method could have all of the duplicated logic with a check whether a sender account was passed - if so we set it to the builder, if not - we don't. Then the original `validateGasEstimation` could pass `Optional.empty()` and the new .`validateGasEstimationWithSender` could pass `contractClient.getClientAddress()`.

Comment (kselveliev) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java:84]: Comment addressed

**Review by steven-sheehy — APPROVED** [review]
LGTM
