### PR TITLE
HTS REST Performance Tests

### LINKED ISSUE #1108: HTS: Stability and performance testing
**Problem**
The newly added HTS functionality needs to be thoroughly tested for stability and performance before it can be delivered to production.

**Solution**
- Add HTS support to existing REST performance tests or investigate use of a standard REST test harness
- Add HTS support to existing system test publisher for all transaction types
- Add HTS support to test E2E latency via JMeter (HAPI publish and REST receiving)
- Performance test the importer to see what throughput of HTS transactions we support
- Performance test the importer to see what throughput of non-HTS transactions we support to verify no regressions
- Performance test the importer and gRPC API HCS messages to ensure no regressions in E2E throughput or latency
- Performance test the HTS REST APIs with a sufficiently large HTS dataset.

**Alternatives**

**Additional Context**

### PR DESCRIPTION
**Pull request by ijungmann**
Signed-off-by: Ian Jungmann <ian.jungmann@hedera.com>

**Detailed description**:

- Add REST performance tests for `/tokens`, `/tokens/{id}`, and `/tokens/{id}/balances`
- Add support for performance testing endpoints that require id values (e.g. `/tokens/{id}`)

**Which issue(s) this PR fixes**:
Fixes #1108 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-rest/__performancetests__/generateQuerySets.js [hunk 1]
```diff
@@ -151,6 +170,34 @@ const makeQuerySet = async (test) => {
...
 };
 
+const makeIdsQuerySet = async (test) => {
+  let idValues;
+  if (test.idAxis === 'TOKENID') {
+    idValues = await populateIdValues(test, sampleTokenIds, (sample) => {
+      return '' + sample;
+    });
+  }
+  console.log('Here there be ' + idValues);
```
Comment (steven-sheehy) [inline hedera-mirror-rest/__performancetests__/generateQuerySets.js:180]: Leftover log?

File: hedera-mirror-rest/__performancetests__/generateQuerySets.js [hunk 2]
```diff
@@ -151,6 +170,34 @@ const makeQuerySet = async (test) => {
   };
 };
 
+const makeIdsQuerySet = async (test) => {
+  let idValues;
+  if (test.idAxis === 'TOKENID') {
```
Comment (Nana-EC) [inline hedera-mirror-rest/__performancetests__/generateQuerySets.js:175]: I believe this should also cover the ACCOUNTID also right?
You could add that case

File: hedera-mirror-rest/__performancetests__/tests.yml [hunk 3]
```diff
@@ -72,3 +72,23 @@ tests:
...
+    filterAxis: TOKENID
+    count: 100
+  - name: 'tokens - token ids range (100)'
+    query: '/tokens'
+    filterAxis: TOKENID
+    count: 5
+    rangeNumTokens: 100
+    # Tests for /tokens/{id}
+  - name: 'token info - tokenid point lookup'
+    query: '/tokens/%d'
```
Comment (Nana-EC) [inline hedera-mirror-rest/__performancetests__/tests.yml:87]: With the added logic you can also support e.g.
```
- name: 'account transactions - accountid point lookup'
     query: '/accounts/%d'
	 idAxis: ACCOUNTID
     count: 100
```

File: docs/testing.md [hunk 4]
```diff
@@ -47,16 +48,20 @@ Where
...
     It should NOT include `http://host:port/api/v1` as prefix. It should also NOT include param set by `filterAxis`.
--   `filterAxis` is primary axis to filter results. It can have one of the three values:
+-   `filterAxis` is primary axis to filter results based on query params. It can have one of the four values.  Either it or `idAxis` are required:
     -   `ACCOUNTID`: Sets `account.id` param. Values for this param are sampled from `entity_num` column in `t_entities`.
     -   `CONSENSUS_TIMESTAMP`: Sets `timestamp` param. Values for this param are sampled from `consensus_ns` column in
         `transaction`.
     -   `BALANCE`: Sets `account.balance` param. Values for this param are sampled from `balance` column in
         `account_balance`.
+    -   `TOKENID`: Sets `token.id` param. Values for this param are sampled from `token_id` column in `token`.
+-   `idAxis` is the primary axis to filter results based on ids (e.g. `/tokens/{id}`).  It can only have one value.
```
Comment (Nana-EC) [inline docs/testing.md:58]:
```suggestion
-   `idAxis` is the primary axis to filter results based on ids in the query path (e.g. `/tokens/{id}`).  It can only have one value.
```

File: hedera-mirror-rest/__performancetests__/tests.yml (hunk 3 above)
Comment (ijungmann) [reply hedera-mirror-rest/__performancetests__/tests.yml:91]: Good call, added

File: hedera-mirror-rest/__performancetests__/generateQuerySets.js (hunk 1 above)
Comment (ijungmann) [reply hedera-mirror-rest/__performancetests__/generateQuerySets.js]: Yep, removed.

File: hedera-mirror-rest/__performancetests__/generateQuerySets.js (hunk 2 above)
Comment (ijungmann) [reply hedera-mirror-rest/__performancetests__/generateQuerySets.js:175]: Correct, I have added that

**Comment by steven-sheehy** [comment]
DCO failed

**Review by Nana-EC — APPROVED** [review]
