### PR TITLE
Record file hash mismatch

### LINKED ISSUE #157: Record file hash mismatch
**Detailed Description**
Occasionally, the recordDownloader reports a mismatch between the previous hash contained in the (n) file and the hash of the (n-1) file. This only occurs when the downloader and the parser run together.

**Actual Behavior**
Ensure the t_application_status table is clear for the following status_values
```
update t_application_status set status_value = '' where status_code ='LAST_PROCESSED_RECORD_HASH';
update t_application_status set status_value = '' where status_code ='LAST_VALID_DOWNLOADED_RECORD_FILE';
update t_application_status set status_value = '' where status_code ='LAST_VALID_DOWNLOADED_RECORD_FILE_HASH';
```

Start the recordParser
Start the recordDownloader
Observe the output from the recordDownloader, it will eventually complain about mismatching hashes when there isn't.

If you stop the parser, clear the t_application_values table again and delete any downloaded files, then run the downloader alone, previously reported mismatches no longer occur. This proves that the file hash sequence is correct and the mirror node is incorrectly reporting errors.

**Expected Behavior**
There is no reported mismatch of hashes when the files themselves are perfectly fine. Only true mismatches are reported.

**Environment:**
N/A

### PR DESCRIPTION
**Pull request by gregscullard**
**Detailed description**:
This fixes a number of issues related to record file hash mismatches
-When downloading and parsing files in parallel, the two processes would overlap on files in /valid and a parsed file would move from /valid to /processed resulting in a gap during hash sequence validation in the downloader

**Which issue(s) this PR fixes**:
Fixes #157 

**Checklist**
- [ ] Documentation added
- [X] Tested against version 2 record files.

### CODE REVIEW

File: src/main/java/com/hedera/databaseUtilities/ApplicationStatus.java [hunk 1]
```diff
@@ -162,7 +163,7 @@ public String getBypassEventHashMismatchUntilAfter() throws Exception {
 	public void updateBypassEventHashMismatchUntilAfter(String bypassUntilAfter) throws Exception {
 		updateStatus(ApplicationStatusCode.EVENT_HASH_MISMATCH_BYPASS_UNTIL_AFTER, bypassUntilAfter);
 	}
-	public String getLastProcessedRcdHash() throws Exception {
+	public String getLastProcessedRecdordHash() throws Exception {
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/databaseUtilities/ApplicationStatus.java]: Spelling

File: src/test/java/com/hedera/UtilityTest.java [hunk 2]
```diff
@@ -85,4 +86,11 @@ public void getTripleFromS3SummaryKey_Event_Test() {
 		Assert.assertEquals("2019-07-25T19_57_21.217420Z", triple.getMiddle());
 		Assert.assertEquals("evts_sig", triple.getRight());
 	}
+
+	@Test
+	public void hashMatchTest() {
+		boolean match = Utility.hashMatch(new File("src/test/resources/2019-08-29T21_40_26.063806Z.rcd_sig"),
+				new File("src/test/resources/2019-08-29T21_40_26.063806Z.rcd"));
+		System.out.println(match);
```
Comment (steven-sheehy) [inline src/test/java/com/hedera/UtilityTest.java]: Remove println and use `Assertions.assertTrue(match)`. Also add a test for bad hash and event stream hash.

File: src/main/resources/db/migration/V1.10.1__freeze_transaction.sql [hunk 3]
```diff
@@ -0,0 +1,18 @@
+INSERT INTO t_transaction_types (proto_id, name) values (23,'FREEZE');
```
Comment (steven-sheehy) [inline src/main/resources/db/migration/V1.10.1__freeze_transaction.sql]: Why does it show this file as new? It's already checked in. Maybe need to merge from master?

File: src/main/java/com/hedera/utilities/Utility.java [hunk 4]
```diff
@@ -148,6 +156,80 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+	/**
+	 * Calculate SHA384 hash of a recordStream file
+	 *
+	 * @param fileName
+	 * 		file name
+	 * @return byte array of hash value
+	 */
+	public static byte[] getRecordFileHash(String fileName) {
+		try (FileInputStream stream = new FileInputStream(new File(fileName)); DataInputStream dis =
+				new DataInputStream(
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/utilities/Utility.java]: Move DataInputStream into try declaration. `try (DataInputStream dis = new DataInputStream(new FileInputStream...`

File: src/main/java/com/hedera/utilities/Utility.java [hunk 5]
```diff
@@ -148,6 +156,80 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
 	}
 
+	/**
+	 * Calculate SHA384 hash of a recordStream file
+	 *
+	 * @param fileName
+	 * 		file name
+	 * @return byte array of hash value
+	 */
+	public static byte[] getRecordFileHash(String fileName) {
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/utilities/Utility.java]: So is the different hash constructions necessary since the different streams (event and record) have different versions they support? As in only records have a version 1 & 2 but events just have a 1?

File: src/main/java/com/hedera/downloader/EventStreamFileDownloader.java [hunk 6]
```diff
@@ -138,7 +138,7 @@ public static void verifyValidFiles() throws Exception {
 				if (newLastValidEventFileHash.isEmpty() ||
 						newLastValidEventFileHash.equals(prevFileHash) ||
 						prevFileHash.equals(Hex.encodeHexString(new byte[48]))) {
-					newLastValidEventFileHash = Utility.bytesToHex(Utility.getFileHash(fileName));
+					newLastValidEventFileHash = Utility.bytesToHex(Utility.getRecordFileHash(fileName));
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/downloader/EventStreamFileDownloader.java]: Why do event streams use `Utility.getRecordFileHash()` here but `Utility.getFileHash()` in hashMatch?

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java [hunk 7]
```diff
@@ -130,18 +127,23 @@ public static void verifyValidRecordFiles(String validDir) throws Exception {
...
-					newLastValidRcdFileHash = Utility.bytesToHex(Utility.getFileHash(rcdName));
+					newLastValidRcdFileHash = Utility.bytesToHex(Utility.getRecordFileHash(rcdName));
 					newLastValidRcdFileName = new File(rcdName).getName();
 				} else if (applicationStatus.getBypassRecordHashMismatchUntilAfter().compareTo(new File(rcdName).getName()) > 0) {
 					newLastValidRcdFileName = new File(rcdName).getName();
-					newLastValidRcdFileHash = Utility.bytesToHex(Utility.getFileHash(rcdName));
+					newLastValidRcdFileHash = Utility.bytesToHex(Utility.getRecordFileHash(rcdName));
 				} else {
+					log.warn("File Hash Mismatch with previous : {}, expected {}, got {}", rcdName, newLastValidRcdFileHash, prevFileHash);
+					log.warn("Expected {}", newLastValidRcdFileHash);
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/downloader/RecordFileDownloader.java]: These next three logging statements can be removed since the first has all the parameters contained in the next.

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java [hunk 8]
```diff
@@ -151,6 +153,45 @@ public static void verifyValidRecordFiles(String validDir) throws Exception {
...
 
+	/**
+	 * Verify the .rcd files to see if the file Hash matches prevFileHash
+	 * @param fileToCheck
+	 * @throws Exception 
+	 */
+	public static boolean verifyValidRecordFile(File objfileToCheck) throws Exception {
+		String lastValidRecordFileName =  applicationStatus.getLastValidDownloadedRecordFileName();
+		String lastValidRecordFileHash = applicationStatus.getLastValidDownloadedRecordFileHash();
+		if (!objfileToCheck.exists()) {
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Move fail fast if statement to be first to avoid potential db lookup.

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java [hunk 9]
```diff
@@ -193,14 +234,25 @@ private void verifySigsAndDownloadRecordFiles(Map<String, List<File>> sigFilesMa
...
-					if (moveFile(rcdFile, fTo)) {
-						log.debug("Verified signature file matches at least 2/3 of nodes: {}", fileName);
-						valid = true;
+							if (moveFile(rcdFile, fTo)) {
+								log.debug("Verified signature file matches at least 2/3 of nodes: {}", fileName);
+								valid = true;
+								break;
+							}
+						} else {
+							valid = false;
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/downloader/RecordFileDownloader.java]: You can remove the valid = false statements. It's set to false by default.

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java [hunk 10]
```diff
@@ -712,7 +712,8 @@ private static int getTransactionTypeId (TransactionBody body) {
 		if (transactionTypes.containsKey(transactionName)) {
 			return transactionTypes.get(transactionName);
 		} else {
-			return transactionTypes.get("unknown");
+			log.error("Transaction type {} not known to mirror node, storing 'UNKNOWN'", transactionName);
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: Merge issue?

File: src/main/java/com/hedera/utilities/Utility.java [hunk 11]
```diff
@@ -70,11 +71,18 @@ public static boolean checkStopFile() {
...
 	/**
-	 * Verify if a .rcd file's hash is equal to the hash contained in .rcd_sig file
+	 * Verify if a file's hash is equal to the hash contained in sig file
 	 * @return
 	 */
-	public static boolean hashMatch(File sigFile, File rcdFile) {
-		byte[] fileHash = Utility.getFileHash(rcdFile.getPath());
+	public static boolean hashMatch(File sigFile, File file) {
+		byte[] fileHash;
+		if (isRecordFile(file.getPath())) {
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/utilities/Utility.java]: Recommend to centralize get hash logic in `Utility.getFileHash()` and use that everywhere. `getFileHash()` can have these if statements and call the appropriate hashing method.

File: src/main/java/com/hedera/utilities/Utility.java [hunk 12]
```diff
@@ -70,11 +71,18 @@ public static boolean checkStopFile() {
...
+			fileHash = Utility.getRecordFileHash(file.getPath());
+		} else if (isEventStreamFile(file.getPath())) {
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/utilities/Utility.java]: else if not necessary since else is identical

File: src/main/java/com/hedera/parser/RecordFileParser.java [hunk 13]
```diff
@@ -70,17 +69,19 @@ public RecordFileParser() throws Exception {
 	 * @return return previous file hash
 	 * @throws Exception 
 	 */
-	static public boolean loadRecordFile(String fileName, String previousFileHash) throws Exception {
+	static public boolean loadRecordFile(String fileName) throws Exception {
 
+		String previousFileHash = applicationStatus.getLastProcessedRecdordHash();
 		File file = new File(fileName);
-		String newFileHash = "";
+		String thisFileHash = ""; //Hex.encodeHexString(Utility.getFileHash(file.getPath()));
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/parser/RecordFileParser.java]: Can we remove this commented out code?

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java [hunk 14]
```diff
@@ -69,7 +66,7 @@ public static void downloadNewRecordfiles(RecordFileDownloader downloader) throw
 
 			if (validDir != null) {
 //				new Thread(() -> {
-					verifyValidRecordFiles(validDir);
+//					verifyValidRecordFiles(validDir);
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Is this supposed to commented out? I'm guessing because similar validation is done now by parser? This is the only place this method is called so we should remove it if so.

File: src/main/java/com/hedera/utilities/Utility.java (hunk 5 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Events will need fixing too - raised an issue for this. Focussing on records as a priority.

File: src/main/java/com/hedera/utilities/Utility.java (hunk 12 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: else is for balance files (the else if will need fixing when we fix event hash calculations later)

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java (hunk 14 above)
Comment (gregscullard) [reply src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Agreed

File: src/main/java/com/hedera/databaseUtilities/ApplicationStatus.java (hunk 1 above)
Comment (gregscullard) [reply src/main/java/com/hedera/databaseUtilities/ApplicationStatus.java]: Fixed

File: src/test/java/com/hedera/UtilityTest.java (hunk 2 above)
Comment (gregscullard) [reply src/test/java/com/hedera/UtilityTest.java]: Done

File: src/main/resources/db/migration/V1.10.1__freeze_transaction.sql (hunk 3 above)
Comment (gregscullard) [reply src/main/resources/db/migration/V1.10.1__freeze_transaction.sql]: Odd, unsure how to fix

File: src/main/java/com/hedera/downloader/EventStreamFileDownloader.java (hunk 6 above)
Comment (gregscullard) [reply src/main/java/com/hedera/downloader/EventStreamFileDownloader.java]: Event streams will need fixing later - focussing on recordStreams as a priority - issue has been raised

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java (hunk 7 above)
Comment (gregscullard) [reply src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Done

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java (hunk 8 above)
Comment (gregscullard) [reply src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Done

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java (hunk 9 above)
Comment (gregscullard) [reply src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Done

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java (hunk 10 above)
Comment (gregscullard) [reply src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: No longer there

File: src/main/java/com/hedera/utilities/Utility.java (hunk 11 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Event file hash calculation may be different to record file hash calculation which will be determined when the event hash issue is tackled.

File: src/main/java/com/hedera/downloader/RecordFileDownloader.java (hunk 14 above)
Comment (gregscullard) [reply src/main/java/com/hedera/downloader/RecordFileDownloader.java]: Done

File: src/main/java/com/hedera/downloader/EventStreamFileDownloader.java (hunk 6 above)
Comment (steven-sheehy) [reply src/main/java/com/hedera/downloader/EventStreamFileDownloader.java]: Agree, but this is definitely the wrong method to call her. Recommend this change be undone.

File: src/main/java/com/hedera/utilities/Utility.java (hunk 5 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: #158 is the issue referenced above

File: src/main/java/com/hedera/utilities/Utility.java (hunk 11 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: #158 is the issue tracking event hash changes

File: src/main/java/com/hedera/parser/RecordFileParser.java (hunk 13 above)
Comment (gregscullard) [reply src/main/java/com/hedera/parser/RecordFileParser.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java (hunk 5 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Events also have 1 & 2

File: src/main/java/com/hedera/downloader/EventStreamFileDownloader.java (hunk 6 above)
Comment (gregscullard) [reply src/main/java/com/hedera/downloader/EventStreamFileDownloader.java]: Totally right here. Change applied.

File: src/main/java/com/hedera/utilities/Utility.java (hunk 12 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: #158 is the issue tracking event hash changes

File: src/main/java/com/hedera/downloader/EventStreamFileDownloader.java (hunk 6 above)
Comment (steven-sheehy) [reply src/main/java/com/hedera/downloader/EventStreamFileDownloader.java]: Change not applied?

File: src/main/java/com/hedera/utilities/Utility.java [hunk 15]
```diff
@@ -148,6 +156,80 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+					default:
+						log.error("Exception Unknown record file delimiter {}", typeDelimiter);
+				}
+			}
+			if (record_format_version >= RECORD_FORMAT_VERSION) {
+				md.update(mdForContent.digest());
+			}
+			return md.digest();
+		} catch (Exception e) {
+			log.error("Exception {}", e);
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/utilities/Utility.java]: This is logging statement isn't very helpful. Also don't need to use {} for exceptions, log4j2 automatically adds message and stacktrace if it's the last parameter. I suggest `log.error("Unable to calculate hash for file: {}", fileName);`

File: src/main/java/com/hedera/downloader/Downloader.java [hunk 16]
```diff
@@ -361,8 +361,7 @@ protected void downloadBalanceFiles() throws Exception {
 
 						String s3ObjectKey = summary.getKey();
 
-						if (((isNeededSigFile(s3ObjectKey, type) && s3KeyComparator.compare(s3ObjectKey, prefix + lastValidFileName) > 0))
-								|| (lastValidFileName.isEmpty())) {
+						if (isNeededSigFile(s3ObjectKey, type) && (s3KeyComparator.compare(s3ObjectKey, prefix + lastValidFileName) > 0 || lastValidFileName.isEmpty())) {
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/downloader/Downloader.java]: Wow, that's a nasty bug. I just ran into this locally and spent an hour or two on this tracking it down to find out you have a fix. Would be nice if you added some bullet items to PR description listing the various fixes. Or separate them to different PRs so they can be reviewed and approved quicker.

Comment (steven-sheehy) [reply src/main/java/com/hedera/downloader/Downloader.java]: Note my PR #170 also made this change and was merged, so this can be removed from this PR

**Comment by steven-sheehy** [comment]
My PR #170 added record download tests, but the test records are probably the old format. Hopefully the tests still pass and we can add some v2 test data in a later PR.

File: src/main/java/com/hedera/utilities/Utility.java [hunk 17]
```diff
@@ -148,6 +156,80 @@ public static boolean hashMatch(File sigFile, File rcdFile) {
...
+							mdForContent.update(rawBytes);
+
+						} else {
+							md.update(Utility.integerToBytes(byteLength));
+							md.update(rawBytes);
+						}
+						break;
+
+					default:
+						log.error("Exception Unknown record file delimiter {}", typeDelimiter);
```
[the remark this answers is not in the document]
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/utilities/Utility.java (hunk 15 above)
Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

File: src/main/java/com/hedera/downloader/Downloader.java (hunk 16 above)
Comment (gregscullard) [reply src/main/java/com/hedera/downloader/Downloader.java]: Done

**Comment by steven-sheehy** [comment]
Other than still needing to calculate the event hash with the correct method this LGTM

**Comment by gregscullard** [comment]
> Other than still needing to calculate the event hash with the correct method this LGTM

Done, also removed now obsolete `getRecordFileHash`

File: src/main/java/com/hedera/utilities/Utility.java [hunk 18]
```diff
@@ -62,8 +62,9 @@
 
   private static final Long SCALAR = 1_000_000_000L;
 
-//	private static final byte TYPE_PREV_HASH = 1;       // next 48 bytes are hash384 of previous files
-//	private static final byte TYPE_RECORD = 2;          // next data type is transaction and its record
+	static final int RECORD_FORMAT_VERSION = 2;
```
Comment (steven-sheehy) [inline src/main/java/com/hedera/utilities/Utility.java]: Remove these added static variables as they're not used.

Comment (gregscullard) [reply src/main/java/com/hedera/utilities/Utility.java]: Done

**Comment by gregscullard** [comment]
> Also remove the src/test/resources/*.rcd and sig files that were added and not used.
Done
