### PR TITLE
Fix ContractCallServiceERCTokenReadOnlyFunctionsTest for modularized

### LINKED ISSUE #10053: Fix ContractCallServiceERCTokenReadOnlyFunctionsTest failing tests
### Problem

Currently there are some failing tests in ContractCallServiceERCTokenReadOnlyFunctionsTest suite especially negative tests against modularized code.

### Solution

Fix failing ContractCallServiceERCTokenReadOnlyFunctionsTest tests.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by kselveliev**
This PR fixes the 17 failing tests when run against modularized in `ContractCallServiceERCTokenReadOnlyFunctionsTest`.

Few negative test have different behaviours where we need to be checking the flag to assert the proper error. Described and discussed here -> https://github.com/hashgraph/hedera-services/issues/17245

If we try to mimic modularized behaviour we might introduce some breaking changes since we are still using the mono code.
For now I'm asserting the differences based on which flag is up.

**Description**:

This PR modifies 
`ContractCallServiceERCTokenReadOnlyFunctionsTest` - change account persist setup and new assertions bases on the modularized flag.

**Related issue(s)**:

Fixes #10053 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java [hunk 1]
```diff
@@ -1034,7 +1068,7 @@ private EntityId accountPersistWithAlias(final Address alias, final ByteString p
     private EntityId accountPersist() {
         return domainBuilder
                 .entity()
-                .customize(e -> e.evmAddress(null).balance(12L))
+                .customize(e -> e.evmAddress(null).alias(null).balance(12L))
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java:1071]: Can't we reuse the `AbstractContractCallServiceTest#accountEntityPersist` method?

**Review by bilyana-gospodinova — CHANGES_REQUESTED** [review]

**Review by steven-sheehy — APPROVED** [review]

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java (hunk 1 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java:1071]: Let's leave it as it is since accountEntityPersist returns Entity while accountPersist here returns EntityId.
Changing to use accountEntityPersist + added transformations of .toEntityId will add around 100+ line changes to the PR.

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java:1071]: Ok, but we should definitely try to reduce such duplications in another refactor PR.

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM
