### PR TITLE
HIP-16 Support contract expiry

### LINKED ISSUE #3606: HIP-16 Support contract expiry
### Problem

[HIP-16](https://hips.hedera.com/hip/hip-16), [HIP-372](https://hips.hedera.com/hip/hip-372), and [HIP-449](https://hips.hedera.com/hip/hip-449) details entity renewal functionality. In services 0.26, contract expiry will be worked on so mirror node needs to support it.

### Solution

* Add `bigint auto_renew_account_id null` and `boolean permanent_removal null` to `contract` and `contract_history`
* Migrate previous `permanent_removal` values to false
* Add new fields to `DomainBuilder`
* Add new proto fields to `RecordItemBuilder`
* Move `Entity.autoRenewAccountId` to `AbstractEntity`
* Update merge logic in `SqlEntityListener`
* Add new fields to `/api/v1/contracts` and `/api/v1/contracts/{id}` REST API

### Alternatives

_No response_

### LINKED ISSUE #3624: Unable to clear a topic auto renew account
### Description

The mirror node missed a requirement to clear the [ConsensusUpdateTopicTransactionBody.autoRenewAccount](https://github.com/hashgraph/hedera-protobufs/blob/main/services/consensus_update_topic.proto) if it's set to a sentinel value:

> If specified as the default value (0.0.0), the autoRenewAccount will be removed. If unspecified, no change.

### Steps to reproduce

1. Submit a `ConsensusCreateTopicTransaction` with an `autoRenewAccount` set to an existing account ID
2. Submit a `ConsensusUpdateTopicTransactionBody` with a sentinel `0.0.0` `autoRenewAccount`
3. The database should have null but has the previous ID

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.54.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

- Supports contract auto expiry
- Fix unable to clear topic auto renew account

**Related issue(s)**:

Fixes #3606
Fixes #3624

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/entityId.js [hunk 1]
```diff
@@ -126,13 +138,14 @@ const isCreate2EvmAddress = (evmAddress) => {
...
- * @param {BigInt} num
+ * @param {BigInt|Number} shard
+ * @param {BigInt|Number} realm
+ * @param {BigInt|Number} num
  * @return {EntityId}
  */
 const of = (shard, realm, num) => {
-  return new EntityId(shard, realm, num);
+  const toNumber = (val) => (typeof val === 'bigint' ? Number(val) : val);
+  return new EntityId(toNumber(shard), toNumber(realm), toNumber(num));
```
Comment (xin-hedera) [inline hedera-mirror-rest/entityId.js:148]: `shard`, `realm`, and `num` can fit into a js `Number` since per the encoding their values won't be > js Number.MAX_SAFE_INTEGER.

The change is needed so EntityId.isAllZero can just compare the three parts to `0` instead of conditionally checking against `0` or `0n`.

File: hedera-mirror-rest/api/v1/openapi.yml [hunk 2]
```diff
@@ -1209,6 +1209,8 @@ components:
       properties:
         admin_key:
           $ref: '#/components/schemas/Key'
+        auto_renew_account:
```
Comment (xin-hedera) [inline hedera-mirror-rest/api/v1/openapi.yml:1212]: keep it consistent with `TokenInfo`

**Review by edwin-greene — APPROVED** [review]
Looks good!

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/entityId.js (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-rest/entityId.js:148]: I'm not a fan of having invalid data in the db. We'll have to clean this up when we add an `@UpsertColumn`.

File: hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.5__contract_expiry.sql [hunk 3]
```diff
@@ -0,0 +1,8 @@
+alter table if exists contract
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.5__contract_expiry.sql:1]: V1.58.7?

[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/resources/db/migration/v1/V1.58.5__contract_expiry.sql:1]: There's a Java migration as well

**Review by steven-sheehy — APPROVED** [review]
