### PR TITLE
Throw correct error when multiple contract type transactions are found

### LINKED ISSUE #4740: 500 on api/v1/contracts/results/{transactionId}
### Description

The following query returns 500:

https://mainnet-public.mirrornode.hedera.com/api/v1/contracts/results/0.0.706113-1666377820-433121761

It should return 404.

### Steps to reproduce

https://mainnet-public.mirrornode.hedera.com/api/v1/contracts/results/0.0.706113-1666377820-433121761

### Additional context

Quote from Steven:

`It's not an EVM related transaction so won't have results so should return 404. But returns 500 because it is a scheduled transaction that has the same transaction ID as a cryptotransfer tx except scheduled flag, which we don't take into account here.`

Logs:

```
GET /api/v1/contracts/results/0.0.706113-1666377820-433121761 in 3 ms: 500 Internal error Error: Transaction invariance breached
```
### Hedera network

mainnet

### Version

v0.1.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by edwin-greene**
Signed-off-by: Edwin Greene <edwin.greene@swirldslabs.com>

**Description**:
Instead of throwing a 500 error, throw the correct 404 error if more than one transaction is found for specific contract related transaction types.

**Related issue(s)**:

Fixes #4740 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by MarcKriguerAtHedera — DISMISSED** [review]
LGTM

File: hedera-mirror-rest/controllers/contractController.js [hunk 1]
```diff
@@ -75,9 +75,10 @@ const contractWithBytecodeSelectFields = [
 ];
 const {default: defaultLimit} = getResponseLimit();
 
+const contractCallType = Number(TransactionType.getProtoId('CONTRACTCALL'));
+const contractCreateType = Number(TransactionType.getProtoId('CONTRACTCREATEINSTANCE'));
 const duplicateTransactionResult = TransactionResult.getProtoId('DUPLICATE_TRANSACTION');
 const wrongNonceTransactionResult = TransactionResult.getProtoId('WRONG_NONCE');
-const ethereumTransactionType = TransactionType.getProtoId('ETHEREUMTRANSACTION');
```
Comment (steven-sheehy) [inline hedera-mirror-rest/controllers/contractController.js:80]: Should also check for ETHEREUMTRANSACTION

File: hedera-mirror-rest/controllers/contractController.js [hunk 2]
```diff
@@ -1078,6 +1079,12 @@ class ContractController extends BaseController {
       if (transactions.length === 0) {
         throw new NotFoundError();
       } else if (transactions.length > 1) {
+        for (const transaction of transactions) {
+          if (transaction.type === contractCallType || transaction.type === contractCreateType) {
```
Comment (steven-sheehy) [inline hedera-mirror-rest/controllers/contractController.js:1083]: The logic should be inverted. The [example](https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.706113-1666377820-433121761) transaction in the ticket is a SCHEDULECREATE and CRYPTOTRANSFER. So probably the best option is to find the user submitted transaction in `transactions` and throw a not found error it it's not a contract call, contract create, or ethereum transaction. A user initiated transaction should have both `nonce=0` and `scheduled=false`.

File: hedera-mirror-rest/__tests__/specs/contracts/results/{id}/multiple-transactions-not-found.json [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+  "description": "Contract results api call that results in multiple transactions",
+  "setup": {
+    "transactions": [
+      {
+        "consensus_timestamp": 167654000123456,
+        "payerAccountId": "8001",
+        "scheduled": true,
+        "transaction_hash": "519a008fabde4d",
+        "valid_start_timestamp": 167654000123400,
+        "type": 7
```
Comment (steven-sheehy) [inline hedera-mirror-rest/__tests__/specs/contracts/results/{id}/multiple-transactions-not-found.json:11]: Test case should reflect the types in the ticket.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/controllers/contractController.js (hunk 2 above)
Comment (edwin-greene) [reply hedera-mirror-rest/controllers/contractController.js]: Thanks I have fixed this logic.

File: hedera-mirror-rest/__tests__/specs/contracts/results/{id}/multiple-transactions-not-found.json (hunk 3 above)
Comment (edwin-greene) [reply hedera-mirror-rest/__tests__/specs/contracts/results/{id}/multiple-transactions-not-found.json]: Got it, the test case has been updated to be correct.

File: hedera-mirror-rest/controllers/contractController.js (hunk 1 above)
Comment (edwin-greene) [reply hedera-mirror-rest/controllers/contractController.js:80]: Thanks I have added a check for Ethereum transactions.

File: hedera-mirror-rest/controllers/contractController.js [hunk 4]
```diff
@@ -1078,6 +1080,14 @@ class ContractController extends BaseController {
       if (transactions.length === 0) {
         throw new NotFoundError();
       } else if (transactions.length > 1) {
+        for (const transaction of transactions) {
+          const one = isUserInitiatedTransaction(transaction);
+          const two = !isContractTransaction(transaction);
+          if (isUserInitiatedTransaction(transaction) && !isContractTransaction(transaction)) {
```
Comment (xin-hedera) [inline hedera-mirror-rest/controllers/contractController.js:1086]: I don't think we should do `isUserInitiatedTransaction`,

- contract transactions can't be scheduled -> so if transaction id + nonce = 0 maps to multiple transactions, none can be contract transactions
- the get transaction by transaction id query in the function always has a `nonce = ?` condition and defaults to 0 if not provided in the query param

We only need to check if any transaction is not a contract related transaction here.

In addition, if contract transactions ever become schedulable, additional logic is needed here to find the scheduled contract transaction and retrieve contract result,  instead of returning 404 or 500

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/controllers/contractController.js [hunk 5]
```diff
@@ -1259,6 +1269,17 @@ const exportControllerMethods = (methods = []) => {
...
+const isContractTransaction = (transaction) => {
+  return transaction.type === contractCallType || transaction.type === contractCreateType
+    || transaction.type === ethereumTransactionType ?
+    true : false;
+};
+
+const isUserInitiatedTransaction = (transaction) => {
+  return !transaction.scheduled && transaction.nonce === 0 ?
+    true : false;
+};
```
[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-rest/controllers/contractController.js]: Thanks, according to the suggestion below I have removed this method.

File: hedera-mirror-rest/controllers/contractController.js [hunk 6]
```diff
@@ -1259,6 +1269,17 @@ const exportControllerMethods = (methods = []) => {
   }, {});
 };
 
+const isContractTransaction = (transaction) => {
+  return transaction.type === contractCallType || transaction.type === contractCreateType
+    || transaction.type === ethereumTransactionType ?
+    true : false;
```
[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-rest/controllers/contractController.js]: Thanks for spotting that, I have simplified it.

File: hedera-mirror-rest/controllers/contractController.js [hunk 7]
```diff
@@ -1078,6 +1080,14 @@ class ContractController extends BaseController {
       if (transactions.length === 0) {
         throw new NotFoundError();
       } else if (transactions.length > 1) {
+        for (const transaction of transactions) {
+          const one = isUserInitiatedTransaction(transaction);
+          const two = !isContractTransaction(transaction);
```
[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-rest/controllers/contractController.js]: Removed!

File: hedera-mirror-rest/controllers/contractController.js (hunk 4 above)
Comment (edwin-greene) [reply hedera-mirror-rest/controllers/contractController.js]: Sounds good, I have fixed it to only use `isContractTransaction`.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM
