### PR TITLE
fix: Fix contract deployment with value

### LINKED ISSUE #9636: Gas estimation on contract deployment with payable constructor reverts
### Description

If we try to estimate gas for a contract deployment with a payable constructor, the web3 module reverts instead of returning a proper gas value.

### Steps to reproduce

We have a simple contract:

```
pragma solidity ^0.8.24;

contract PayableConstructor {
    constructor() payable {}
}
```

The bytecode is: 
```
0x6080604052603e80600f5f395ff3fe60806040525f80fdfea2646970667358221220a38ca427a091f1d38af455b9ec034fe31be0290310c3e2888017a1fce83553d464736f6c634300081a0033
```

---

- if we execute a gas estimation against the mirror node web 3 module via POST to https://testnet.mirrornode.hedera.com/api/v1/contracts/call with that body:
```
{
    "value":1000000,
    "estimate": true,
    "from":"0x6e5d3858f53fc66727188690946631bde0466b1a",
    "data":"0x6080604052603e80600f5f395ff3fe60806040525f80fdfea2646970667358221220a38ca427a091f1d38af455b9ec034fe31be0290310c3e2888017a1fce83553d464736f6c634300081a0033"
}
```

it reverts with a:
```
{
    "_status": {
        "messages": [
            {
                "message": "Bad Request",
                "detail": "to field must not be empty",
                "data": ""
            }
        ]
    }
}
```

- if we remove the value from the body:
```
{
    "estimate": true,
    "from":"0x6e5d3858f53fc66727188690946631bde0466b1a",
    "data":"0x6080604052603e80600f5f395ff3fe60806040525f80fdfea2646970667358221220a38ca427a091f1d38af455b9ec034fe31be0290310c3e2888017a1fce83553d464736f6c634300081a0033"
}
```
then we get a expected result:
```
{
    "result": "0x000000000000e228"
}
```

I also tried passing "to" as a null or empty string but it failed again.

### Additional context

_No response_

### Hedera network

_No response_

### Version

testnet

### Operating system

None

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:

This PR fixes contract deployment when the contract deployment is made with value.

This PR modifies :
Modified `ContractCallRequest` - change the 'to' validation to check if the call is for contract deployment

`BytecodeUtils` - Added a new method `isInitBytecode` which checks if a given data is an init bytecode - needed in `ContractCallRequest` validation

`ContractControllerTest` - Added new test and modified a few existing ones based on the new changes to the validation of the to field.

Modified `ContractCallAddressThisTest` - added tests for deployment of payable contract with and without value
Modified `ContractCallServiceERCTokenModificationFunctionsTest` - added tests for deployment of non payable contract with and without value.

**Related issue(s)**:

Fixes #9636 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java [hunk 1]
```diff
@@ -60,9 +59,4 @@ public class ContractCallRequest {
     private boolean hasFrom() {
         return value <= 0 || from != null;
     }
-
-    @AssertTrue(message = "must not be empty")
```
[the remark this answers is not in the document]
Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:64]: I think it is safer if we move the old check in the `ContractController` and add additional check before that if the `data` contains an init bytecode (and if it does - skip the other `to` checks, if not - make the old checks for `value`, `from`, empty `to`). This way we will cover the scenario in the issue and cut the failing requests as soon as possible and we will avoid doing any unnecessary computations while preserving the old validations.
If we just remove all validations of the `to` field, the response will change a bit in some situations. For example: a contract call with `to == null`. The controller will not cut the request, the users would not get a message that the "to" field is missing, the receiver will be assigned to `Address.ZERO`. the `ContractExecutionService` will be called, some address lookups of the sender and receiver will be made. Since the receiver is empty, the call will be assumed to be a contract create case instead of a contract call and so on. As a result the returned error might be misleading.

[the remark this answers is not in the document]
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:64]: I just added a new validation to check if data contains init bytecode. Can you check it

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java [hunk 2]
```diff
@@ -66,4 +67,22 @@ private static String getRuntimeBytecode(final String initBytecode) {
...
+        if (data == null || data.isEmpty()) {
+            return false;
+        }
+
+        // CODECOPY (0x39) and RETURN (0xf3)
+        boolean hasCodeCopy = data.contains(CODECOPY);
+        boolean hasReturn = data.contains(RETURN);
+
+        // Check if both CODECOPY and RETURN opcodes are present
+        return hasCodeCopy && hasReturn;
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:86]: I am concerned about this check. If we have a normal contract call with function selector such as: "0xf30039" this check will say that this is a contract create and clearly it is not. I think that the position of these opcodes is important. We need to research this further.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java [hunk 3]
```diff
@@ -63,6 +64,6 @@ private boolean hasFrom() {
 
     @AssertTrue(message = "must not be empty")
     private boolean hasTo() {
-        return value <= 0 || from == null || StringUtils.isNotEmpty(to);
+        return RuntimeBytecodeExtractor.isInitBytecode(data) || StringUtils.isNotEmpty(to);
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:67]: Why do we remove the old check for `value <= 0 || from == null`? If there is a direct transfer, there needs to have `from`, `to` and `value` set. This was validated in the `ContractControllerTest#callInvalidToDueToTransfer` which is now removed but I think it shouldn't be.

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:67]: Also, this way we verify twice if the `to` field is empty - once in `RuntimeBytecodeExtractor.isInitBytecode` and a second time in `StringUtils.isNotEmpty(to)` but I think this validation needs to be changed anyway as explained in my other comments.

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java [hunk 4]
```diff
@@ -118,14 +119,13 @@ private ResultActions contractCall(ContractCallRequest request) {
...
-    @ValueSource(strings = {"0x00000000000000000000000000000000000007e7"})
     @ParameterizedTest
-    void estimateGas(String to) throws Exception {
+    void estimateGasWithEmptyTo(String to) throws Exception {
         final var request = request();
         request.setEstimate(true);
         request.setValue(0);
         request.setTo(to);
-        contractCall(request).andExpect(status().isOk());
+        contractCall(request).andExpect(status().isBadRequest());
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java:128]: Changing this test indicates there is a modification in the previous logic that was unexpected.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java (hunk 2 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:86]: Yes this is correct. I see that the minimum size of the init bytecode for a valid contract deployment is around 14 bytes so I will add this in the check.

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java (hunk 4 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java:128]: I don't think so. Previous version of the test did:

data: randomFunctionSelector(not init code)
to: empty
from: address

and expect success - which is not correct in my opinion.
As far as I understand the only time we can allow the "to" to be empty is when we do contract deployment.

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java:128]: Correct - the only time when "to" can be empty is on contract deploy. So, we need 2 parameterized tests:
1.  One in which the data is set as a correct init bytecode and the old check for success or we wouldn't have a test to verify the positive path for estimate gas.
2. Second parameterized test without "to" and non init bytecode data (but contract call) which is expected to return bad request response code.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java (hunk 3 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:67]: If we are looking only at the ‘to’ validation

As far as I know we can only allow empty ‘to’ when we do contract deployment
meaning: 
```
to: empty 
data: init code for contract deployment
```


In the case where we have direct transfer as you said we want to have 

```
from: address (not empty)
to: address (not empty)
value: some value set
```

from is already handled by its own validation 
to - it will verify that the address is not init bytecode and then it will just do the not empty check for 'to'
value - already has a positiveOrZero validation 

so this scenario should be covered. So this old check only confuses the reader `value <= 0 || from == null` - thats why I removed it.

Maybe I’m missing a corner case.

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:67]: Maybe you are right.

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java (hunk 4 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java:150]: Comment addressed I added a couple more estimate gas tests.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java (hunk 2 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java]: Added one more condition to check for min size of the data

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java]: I still don't think this check is enough. Example: "getCustomFeesForToken(address)" -> function selector is: "44**f3**8bc8". And if you pass the address of token "00..0**39**", the data would look like: "0x44f38bc8000...039" and this method will identify it as an init bytecode.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java (hunk 3 above)
Comment (IvanKavaldzhiev) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java:67]: I think removing the previous check will require `to` to be set even if `from` is `null` and value is <=0. I think, we should add additional validation on top of the current one.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java [hunk 5]
```diff
@@ -24,15 +24,17 @@
...
+ * Smart contracts have init bytecode (constructor bytecode) and runtime bytecode (the code executed when the contract
+ * is called). This class helps in extracting the runtime bytecode from the given init bytecode by searching for
+ * specific patterns.
  * </p>
  */
 @UtilityClass
 public class RuntimeBytecodeExtractor {
 
     private static final String CODECOPY = "39";
+    private static final String RETURN = "f3";
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:36]: What if the return code is in uppercase ("F3")? The check will be bypassed.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java [hunk 6]
```diff
@@ -53,17 +55,37 @@ private static String getRuntimeBytecode(final String initBytecode) {
...
+    /**
+     * Checks if a given data string is likely init bytecode.
+     *
+     * @param data the data string to check.
+     * @return true if it is init bytecode, false otherwise.
+     */
+    public static boolean isInitBytecode(final String data) {
+        if (data == null || data.isEmpty()) {
+            return false;
+        }
```
Comment (IvanKavaldzhiev) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:81]: We can add additional logic checking if the data starts with `606060` or `608060` sequence, as this is the current format, where PUSH1 operation is inserting a free memory pointer. In this way we can fail fast, if the `data` doesn't even begin with this sequence. I believe in a lot of cases this check might be very efficient and enough to distinguish between a `bytecode` and `calldata`.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java (hunk 3 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java]: Comment addressed. I added the new logic on top of the current check.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java (hunk 5 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:36]: Correct, I fixed that

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java (hunk 6 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:81]: This is a great suggestion -> however doing that there was another corner case here you can observe one of the autogenerated solidity classes EthCall.sol init code starts with 6104d25. I'm not sure what this case is but perhaps we should handle it as well. I'm now thinking if there can be other cases like that which we might miss.

Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:81]: I found [a great article](https://medium.com/coinmonks/evm-part-ii-the-journey-of-smart-contracts-from-solidity-code-to-bytecode-a21300b23dee) that explains the structure of the init bytecode. It seems that in each init bytecode there is the sequence "60806040" which is responsible for assigning a free memory pointer. Before that there could be some other instructions for constructing the contract. In your example for `EthCall.sol` the bytecode starts with "6104d2" and this means: "PUSH2 0x4D2", which is "push 1234" which is one of the fields in the contract. And also in each contract there is a `codecopy` instruction afterwards followed by the runtime bytecode. I think this method can be enhanced with these findings and also the position of the opcodes is important. For example - to contain "f3" for the `return` opcode after the `codecopy` and not anywhere in the string. The `codecopy` should be after the free memory pointer "60806040" and so on.

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java [hunk 7]
```diff
@@ -79,6 +88,7 @@ class ContractControllerTest {
     private static final String CALL_URI = "/api/v1/contracts/call";
     private static final String ONE_BYTE_HEX = "80";
     private static final long THROTTLE_GAS_LIMIT = 10_000_000L;
+    private static final String INIT_CODE = "0x60006000556000526000526000f3";
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java:91]: Perhaps it will be better to add a valid example of an init bytecode that is in compliance with the latest changes to avoid confusion.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java [hunk 8]
```diff
@@ -24,15 +24,19 @@
...
- * Smart contracts have init bytecode (constructor bytecode) and runtime bytecode (the code
- * executed when the contract is called). This class helps in extracting the runtime bytecode from the
- * given init bytecode by searching for specific patterns.
+ * Smart contracts have init bytecode (constructor bytecode) and runtime bytecode (the code executed when the contract
+ * is called). This class helps in extracting the runtime bytecode from the given init bytecode by searching for
+ * specific patterns.
  * </p>
  */
 @UtilityClass
 public class RuntimeBytecodeExtractor {
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:33]: This class should be renamed as now it does not only extract runtime bytecode.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java (hunk 6 above)
Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java:83]: Thanks. Looks good now.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java (hunk 8 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java]: Renamed to BytecodeUtils

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java (hunk 7 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java]: Comment addressed I added a valid init code of and empty contract

**Review by bilyana-gospodinova — DISMISSED** [review]
LGTM

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java [hunk 9]
```diff
@@ -53,17 +57,57 @@ private static String getRuntimeBytecode(final String initBytecode) {
...
+     */
+    public static boolean isInitBytecode(String data) {
+        if (data == null || data.isEmpty()) {
+            return false;
+        }
+
+        String lowerCaseData = data.toLowerCase();
+
+        // Check if bytecode meets minimum length requirement
+        if (lowerCaseData.length() < MINIMUM_INIT_CODE_SIZE) {
```
[the remark this answers is not in the document]
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java]: With the new pattern I added this lowercase checking is removed and added in the pattern.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java [hunk 10]
```diff
@@ -53,17 +57,57 @@ private static String getRuntimeBytecode(final String initBytecode) {
...
+        int codeCopyIndex = lowerCaseData.indexOf(CODECOPY, freeMemoryPointerIndex + FREE_MEMORY_POINTER.length());
+        if (codeCopyIndex == -1) {
+            return false;
+        }
+
+        // Check if RETURN occurs after CODECOPY
+        int returnIndex = lowerCaseData.indexOf(RETURN, codeCopyIndex + CODECOPY.length());
+
+        // If all conditions are met, this is likely init bytecode
+        return returnIndex != -1;
```
[the remark this answers is not in the document]
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java]: Comment addressed

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java [hunk 11]
```diff
@@ -53,17 +57,57 @@ private static String getRuntimeBytecode(final String initBytecode) {
...
         return initBytecode.substring(runtimeCodePrefixIndex);
     }
+
+    /**
+     * Checks if a given data string is likely init bytecode.
+     *
+     * @param data the data string to check.
+     * @return true if it is init bytecode, false otherwise.
+     */
+    public static boolean isInitBytecode(String data) {
```
[the remark this answers is not in the document]
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java:98]: If not in properties you mean like having this in our code right? ->  
```
private static final boolean CHECK_INIT_CODE_ENABLED = 
        Boolean.parseBoolean(System.getenv("HEDERA_MIRROR_WEB3_EVM_CHECKINITCODE"));
```

[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java:98]: Correct

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java [hunk 12]
```diff
@@ -0,0 +1,105 @@
...
+     * initialization bytecode. - .* matches any sequence of characters (including none) after the free memory pointer
+     * setup. - %s matches the CODECOPY opcode, which copies code to memory and typically follows the memory pointer
+     * setup in init bytecode. - .* matches any sequence of characters (including none) between CODECOPY and RETURN. %s
+     * matches the RETURN opcode, signaling the end of the initialization bytecode.
+     * <p>
+     * Example pattern: (?i)(60806040|60606040).*39.*f3 This example would match any sequence where either "60806040" or
+     * "60606040" appears, followed by "39" (CODECOPY) and then "f3" (RETURN), with any characters in between.
+     */
+    private static final Pattern INIT_BYTECODE_PATTERN = Pattern.compile(
+            String.format("(?i)(%s|%s).*%s.*%s", FREE_MEMORY_POINTER, FREE_MEMORY_POINTER_2, CODECOPY, RETURN));
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java:59]: Can pass Pattern.CASE_INSENSITIVE as a parameter to compile.

Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java:59]: Believe we should have anchoring `^...$` to ensure strings start and end at beginning. Add test.

Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java:59]: Instead of .* we can use \w* since it should be valid hex. BTW, are you sure it shouldn't be + instead of *?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java (hunk 12 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java:59]: Don’t think we can achor we have some scenarios like EthCall.java binary 

where we have some characters before the begin 60806040 pattern → 6104d25…. 60806040

And for the ending achor we pretty much in all cases have f3… and then followed by some extra characters

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java]: Added the env variable similarly to -> HEDERA_MIRROR_IMPORTER_PARSER_HALTONERROR.
Env variable - HEDERA_MIRROR_WEB3_EVM_SKIPINITCODECHECK
Currently it defaults to false. If false it does the init bytecode check.
If set to true it skips the init bytecode check and the 'to" check works similarly as before

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java (hunk 12 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java]: Comment addressed

Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/BytecodeUtils.java]: Changed to [0-9a-z]*. It think + is better than * so changed it to +.

I experimented with getting the minimum initialization bytecode for an empty contract but could never achieve it with zero characters between the pattern variables.

**Review by steven-sheehy — APPROVED** [review]
LGTM
