### PR TITLE
ignore NodeAddress fields not set in protobuf

### LINKED ISSUE #968: Address book defaults node_id and port to 0
**Detailed Description**
For address books that don't have the node_id or port field populated, a default of 0 is put. Zero is a valid node_id and port and should not be used as the default.

**Actual Behavior**
node_id and port have an incorrect entry

**Expected Behavior**
node_id and port should be null

**Environment:**
- Version: v0.17.0-rc1

**Additional Context**

### PR DESCRIPTION
**Pull request by xin-hedera**
Signed-off-by: Xin Li <xin.li@swirlds.com>

**Detailed description**:

- Change `port` and `nodeId` in `AddressBookEntry` to boxed types to allow `null` values
- Remove default value of `port`
- Set `port` to `null` in `AddressBookEntry` if in protobuf it's 0
- Set `nodeId` to `null` in `AddressBookEntry` if in protobuf all nodes have the same `nodeId`

**Which issue(s) this PR fixes**:
Fixes #968 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 1]
```diff
@@ -220,26 +225,52 @@ private AddressBook buildAddressBook(byte[] addressBookBytes, long consensusTime
...
-                        .ip(nodeAddressProto.getIpAddress().toStringUtf8())
-                        .port(nodeAddressProto.getPortno())
-                        .publicKey(nodeAddressProto.getRSAPubKey())
-                        .nodeCertHash(nodeAddressProto.getNodeCertHash().toByteArray())
-                        .nodeId(nodeAddressProto.getNodeId())
-                        .nodeAccountId(EntityId.of(nodeAddressProto.getNodeAccountId()))
-                        .build();
-                builder.add(addressBookEntry);
-            }
+        if (nodeAddressBook == null) {
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:228]: Is this a valid scenario? When would we ever pass in a null NodeAddressBook? Should this rather throw?

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:228]: The change here is a refactor of the original negative check `nodeAddressBook != null`.

Indeed the check is redundant since the only place `retrieveNodeAddressesFromAddressBook` is called has already made sure `nodeAddressBook` is not NULL. I'll remove the null check here then.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java [hunk 2]
```diff
@@ -220,26 +225,48 @@ private AddressBook buildAddressBook(byte[] addressBookBytes, long consensusTime
...
-                builder.add(addressBookEntry);
-            }
+        ImmutableList.Builder<AddressBookEntry> listBuilder = ImmutableList.builder();
+
+        for (NodeAddress nodeAddressProto : nodeAddressBook.getNodeAddressList()) {
+            AddressBookEntry.AddressBookEntryBuilder builder = AddressBookEntry.builder()
+                    .consensusTimestamp(consensusTimestamp);
+
+            nodeAddressFieldDescriptors.stream()
+                    .filter(nodeAddressProto::hasField)
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java:235]: I don't think the implementation of this is correct. It's also unnecessarily complex and uses reflection. Both nodeId and port are primitives, so the `hasField()` implementation returns true if they don't equal the default value (which is zero for both). However, zero is still a valid value for these fields so we still want to set it if it's zero (e.g. testnet's node 0-3).

I think we can revert to previous logic and use some smarter conditional logic to control them being set. For port, I think it's safe to assume that the main nodes aren't going to use port zero so we can just not set it if it's zero. For nodeId, we can first collect all nodeIds into a set and only set nodeId if the size of that set is greater than one.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java [hunk 3]
```diff
@@ -335,9 +344,103 @@ void verifyAddressBookEndPointsAreSet() {
         assertThat(prevAddressBook.getEndConsensusTimestamp()).isNotNull();
     }
 
+    @Test
+    void verifyAddressBookWithEmptyAddressBookEntryFields() {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java:348]: This test and `addressBookWithEmptyAddressBookEntryFields()` are very hard to understand and not maintainable. It'd be much simpler to just `NodeAddressBook.newBuilder().ip()...build()` all fields manually except nodeId and port then assert the current address book has null for those fields.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java (hunk 2 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java]: thanks. reverted the changes and implemented the new logic

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java (hunk 3 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java]: test cases updated

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
