### PR TITLE
Fix install/upgrade to use of application.yml for DB config (instead of config.json)

### LINKED ISSUE #309: Fix mirror-node install/upgrade script
**Detailed Description**
- upgrade script needs to take DB configuration out of config.json and put it in application.yml (if no such file exists)
- mirror-node.service needs `--spring.config.additional-location=file:/usr/etc/mirror-node/application.yml` added (that's where the application.yml should go)

**Environment:**
- mirror-node: v0.3.0-rc1

### PR DESCRIPTION
**Pull request by mike-burrage-hedera**
**Detailed description**:
- Update the mirror-node.service system config to add `--spring.config.additional-location=file:/usr/etc/mirror-node/application.yml` (application.yml config file will be read from /usr/etc/mirror-node
- `scripts/deploy-mirror-node.sh` to create an application.yml for db params from config.json and remove those params from config.json

**Which issue(s) this PR fixes**:
Fixes #309

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: scripts/deploy-mirror-node.sh [hunk 1]
```diff
@@ -33,10 +34,30 @@ if [ -f "${usrlib}/mirror-node.jar" ]; then
...
+        if [ -n "${dbport}" ]; then
+            sudo echo "      port: ${dbport}" >> "${appyml}"
+        fi
+        sudo sed -ie '/apiPassword/d;/apiUsername/d;/dbName/d;/dbUsername/d;/dbPassword/d;/dbUrl/d' "${usretc}/config.json"
+    fi
 else
     echo "Fresh install of ${version}"
     echo "Copying config (will need to be edited)"
-    cp -n config/* /usr/etc/mirror-node/
+    cp -n config/* "#{usretc}"
```
Comment (steven-sheehy) [inline scripts/deploy-mirror-node.sh]: `${usretc}`

File: scripts/mirror-node.service [hunk 2]
```diff
@@ -4,7 +4,7 @@ Description=Hedera Mirror Node
 
 [Service]
 Environment=HEDERA_MIRROR_CONFIG_PATH=/usr/etc/mirror-node/config.json
-ExecStart=/usr/bin/java -jar mirror-node.jar -Djavax.net.ssl.trustStorePassword=changeit -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
+ExecStart=/usr/bin/java -jar mirror-node.jar -Djavax.net.ssl.trustStorePassword=changeit -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector --spring.config.additional-location=file:/usr/etc/mirror-node/application.yml
```
Comment (steven-sheehy) [inline scripts/mirror-node.service]: `--spring.config.additional-location=file:/usr/etc/mirror-node` so it will automatically pickup any application-*.yml in case we need different environment profiles.

File: scripts/deploy-mirror-node.sh [hunk 3]
```diff
@@ -33,10 +34,30 @@ if [ -f "${usrlib}/mirror-node.jar" ]; then
     echo "Backing up binaries"
     sudo rm -rf "${usrlib}/lib"* "${usrlib}/logs" "${usrlib}/mirror-node.jar."*
     sudo mv "${usrlib}/mirror-node.jar" "${usrlib}/mirror-node.jar.${ts}.old"
+
+    # Handle the upgrade from config.json database params to application.yml database params
+    appyml="${usretc}/application.yml"
+    if [ -f "${usretc}/config.json" ] && [ ! -f  "${appyml}" ]; then
+        sudo echo -e "hedera:\n  mirror:\n    db:" > "${appyml}"
```
Comment (steven-sheehy) [inline scripts/deploy-mirror-node.sh]: Unless the script as a whole is run as sudo, then this will fail with permission denied. If the script is a whole is run as sudo, then why have sudo on every line? If it's not ran as sudo, then you need to fix this with something like `echo foo | sudo tee`

File: scripts/deploy-mirror-node.sh [hunk 4]
```diff
@@ -33,10 +34,30 @@ if [ -f "${usrlib}/mirror-node.jar" ]; then
...
+        sudo cat "${usretc}/config.json" | awk -F: '{gsub(/ |\"/, "", $0); gsub(/,$/, "", $0); print}' | grep -E "^(api|db)" | \
```
Comment (steven-sheehy) [inline scripts/deploy-mirror-node.sh]: Again sudo for cat, grep, echo is not necessary unless the input file is not readable otherwise. And the file appending will fail if the `deploy-mirror-node.sh` is not run as sudo. All of these should be reworked.

File: scripts/mirror-node.service (hunk 2 above)
Comment (mike-burrage-hedera) [reply scripts/mirror-node.service]: That didn't work for me when I tried it... are you sure?

File: scripts/deploy-mirror-node.sh (hunk 3 above)
Comment (mike-burrage-hedera) [reply scripts/deploy-mirror-node.sh]: I can take out the sudos (including all the ones above that were untouched by this change). It should be just run as sudo (the whole script).

File: scripts/mirror-node.service (hunk 2 above)
Comment (mike-burrage-hedera) [reply scripts/mirror-node.service]: I must have missed a daemon-reload or something, it does work.

Comment (mike-burrage-hedera) [reply scripts/mirror-node.service]: Nope - that doesn't work.

File: scripts/deploy-mirror-node.sh (hunk 1 above)
Comment (mike-burrage-hedera) [reply scripts/deploy-mirror-node.sh]: Fixed

File: scripts/deploy-mirror-node.sh (hunk 3 above)
Comment (mike-burrage-hedera) [reply scripts/deploy-mirror-node.sh]: Fixed

File: scripts/deploy-mirror-node.sh (hunk 4 above)
Comment (mike-burrage-hedera) [reply scripts/deploy-mirror-node.sh]: Fixed.

File: scripts/mirror-node.service (hunk 2 above)
Comment (mike-burrage-hedera) [reply scripts/mirror-node.service]: ditching `file:` works - making the change

Comment (mike-burrage-hedera) [reply scripts/mirror-node.service]: Trailing slash with or without `file:` prefix works. Fixed.
