### PR TITLE
Add version migrations to fix entity type mismatches in db

### LINKED ISSUE #1201: Importer incorrectly persists non existent entity on ConsensusSubmitMessage
**Detailed Description**
Currently the importer persists an entity into the t_entities table so long as it has an associated entityId that can be extracted from the transaction.

In some case this is resulting in the persistence of entities prematurely and with incorrect information that future correct entity persistence attempts don't overwrite 

e.g. In one case a `CONSENSUSSUBMITMESSAGE` transaction resulted in a `INVALID_TOPIC_ID` response.
However, that transaction when processed by mirror_node still goes through the `OnEntityId` logic which created the entity row with type topic.
Later, a `CRYPTOCREATEACCOUNT` transaction which was successful came through with the same but valid enittyId.
This time the `OnEntity` flow utilizes the update logic an modifies certain details but not the type.
Leaving an incorrect entity row value.

This seems to be the reason that topic id's were showing up in account requests

**Actual Behavior**
1. Submit a `CONSENSUSSUBMITMESSAGE ` to a non existent topic id x (where x is non existent entity id)
2. Confirm it fails with a `INVALID_TOPIC_ID` response
3. Check db for entry in `t_entities` table but no entry in `topic_message` table

**Expected Behavior**
`t_entities` table should not be populated with an entity

use below query to get related db info
Find non account/contract entities with a balance
```sql
select * from account_balance ab join t_entities e on ab.account_num = e.id where e.fk_entity_type_id > 2;
```

List entity info
```sql
select id, fk_entity_type_id, deleted, proxy_account_id from t_entities where id = x;
```

Find associated transcations
```sql
select consensus_ns, type, result, payer_account_id , node_account_id, entity_id, initial_balance from transaction where entity_id = x order by consensus_ns desc;
```
**Environment:**
- Java: [e.g. OpenJDK 11.0.4]
- Node: [e.g. v12.9.1-x86]
- OS: [e.g. Ubuntu 18.04]
- Version: [e.g. 1.0.1]

**Additional Context**
EntityRecordItemListener.java currently contain the following note and logic causing the issue
```java
// Irrespective of transaction failure/success, if entityId is not null, it will be inserted into repo since
// it is guaranteed to be valid entity on network (validated to exist in pre-consensus checks).
entityListener.onEntityId(entityId);
```

We may need to revisit whether this statement still always holds true.

### PR DESCRIPTION
**Pull request by Nana-EC**
**Detailed description**:
Currently mirror node will create entities that don't exist even on failed transactions.
We should create entities only on the 5 create transactions and accounts in the record transfer list

- Add sql migration v1.31.2 that removes all entities above max entity id observed by transactions table
- Add logic to sql migration to update `t_transaction_types` with relating entityTypes for a transaction
- Add logic to sql migration to scan for entities who's entity type doesn't match expected type and update them
- Add migration test class to verify migration cases

**Which issue(s) this PR fixes**:
Fixes #1201 

**Special notes for your reviewer**:
Verified logic in dev environment based on test net data. 
Migration takes just under 1/. mins for `t_entities` table of size 79,300 and `transaction` table size 10,6572,222

Migration log below
```sql
...
UPDATE 4
Time: 80767.893 ms (01:20.768)
```

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 1]
```diff
@@ -0,0 +1,332 @@
...
+public class V1_31_1__Entity_Type_Mismatch extends BaseJavaMigration {
+    private final EntityRepository entityRepository;
+    private final TransactionRepository transactionRepository;
+    private final DataSource dataSource;
+    private final FlywayMigrationProperties flywayMigrationProperties;
+    private JdbcTemplate jdbcTemplate;
+
+    private final String TRANSACTION_MAX_ENTITY_ID_SQL = "select max(entity_id) from transaction where entity_id is " +
+            "not null";
+    private final String CREATED_ENTITIES_TRANSACTION_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
```
Comment (ijungmann) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:63]: Nit: I'm wondering if the variable name could be enhanced a little, I had to read the SQL to really understand the sentiment but I'm failing to come up with something better.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 2]
```diff
@@ -0,0 +1,332 @@
...
+     * @return
+     */
+    private int getCorrectedEntityType(EntityTypeEnum expectedEntityType, int currentEntityType) {
+        // check if EntityTypeEnum matches given currentEntityType.
+        // Return 0 on match otherwise return expected EntityTypeEnum id
+        if (expectedEntityType.getId() == currentEntityType) {
+            return 0;
+        }
+
+        return expectedEntityType.getId();
```
Comment (ijungmann) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:237]: Nit: not sure how you feel about ternary operators, but this method could be replaced with one I believe.
```suggestion
        return expectedEntityType.getId() == currentEntityType ? 0 :  expectedEntityType.getId();
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 3]
```diff
@@ -0,0 +1,332 @@
...
+        timestampCap = new AtomicLong(Utility.convertToNanosMax(now.getEpochSecond(), now.getNano()));
+        entityTransactionCount = new AtomicLong(0);
+        entityTransactionMismatchCount = new AtomicLong(0);
+
+        // batch retrieve entities whose entity type does not match the type noted in the appropriate create
+        // transactions
+        // batch update retrieved entities and pull next set until no type mismatched entities are retrieved
+        // entity id and transaction timestamp are used to optimally search through tables
+        List<EntityIdType> entityIdTypeList = getEntityIdTypes(entityIdCap.get() + 1, timestampCap
+                .get() + 1, flywayMigrationProperties.getEntityMismatchReadPageSize());
```
Comment (ijungmann) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:109]: I understand incrementing the entity id cap by 1, I'm not sure I understand incrementing the timestamp cap though, if the cap is already set to the current time.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java [hunk 4]
```diff
@@ -0,0 +1,302 @@
...
+                        .extracting(Entities::getEntityTypeId).isEqualTo(EntityTypeEnum.FILE.getId()),
+                () -> assertThat(entityRepository.findById(typeMismatchedTopicEntityId.getId())).isPresent().get()
+                        .extracting(Entities::getEntityTypeId).isEqualTo(EntityTypeEnum.TOPIC.getId()),
+                () -> assertThat(entityRepository.findById(typeMismatchedTokenEntityId.getId())).isPresent().get()
+                        .extracting(Entities::getEntityTypeId).isEqualTo(EntityTypeEnum.TOKEN.getId())
+        );
+    }
+
+    @Test
+    void verifyEntityTypeMigrationInValidEntitiesMultiBatch() throws Exception {
```
Comment (ijungmann) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java:184]: Nit:
```suggestion
    void verifyEntityTypeMigrationInvalidEntitiesMultiBatch() throws Exception {
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java [hunk 5]
```diff
@@ -0,0 +1,302 @@
...
+        EntityId typeMismatchedFileEntityId = entityId(3, EntityTypeEnum.CONTRACT);
+        EntityId typeMismatchedTopicEntityId = entityId(4, EntityTypeEnum.ACCOUNT);
+        EntityId typeMismatchedTokenEntityId = entityId(5, EntityTypeEnum.FILE);
+        entityRepository.insertEntityId(typeMismatchedAccountEntityId);
+        entityRepository.insertEntityId(typeMismatchedContractEntityId);
+        entityRepository.insertEntityId(typeMismatchedFileEntityId);
+        entityRepository.insertEntityId(typeMismatchedTopicEntityId);
+        entityRepository.insertEntityId(typeMismatchedTokenEntityId);
+        entityRepository.insertEntityId(entityId(50, EntityTypeEnum.TOPIC));
+        entityRepository.insertEntityId(entityId(100, EntityTypeEnum.TOPIC));
```
Comment (ijungmann) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java:138]: I'm a little confused on not checking these last two in any of the invalid tests.  I'm sure it's a use case I'm just not understanding.

**Review by ijungmann — CHANGES_REQUESTED** [review]
Looks good, I like the tests.  Just some really minor things and a couple questions.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 3 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:109]: True, +1 on timestamp is not needed

File: hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql [hunk 6]
```diff
@@ -0,0 +1,10 @@
+-------------------
+-- Fix entity type mismatches
+-------------------
+
+-- Backup t_entities prior to type mismatch fix
+create table t_entities_archive as table t_entities;
+
+--- Delete entities above the max entity id witnessed by transactions
+delete from t_entities where id > (select max(entity_id) from transaction where entity_id is not null);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql:9]: I'm not convinced this is correct. I believe we should be deleting anything above the max for only successful transaction results. Below results for mainnet indicate everything above 58743 should be deleted:
```
select max(entity_id) as max, result from transaction where entity_id is not null group by result order by result asc;
  max   | result
--------+--------
  45009 |      4
  56708 |      7
  51273 |     10
  45009 |     11
  40319 |     15
  58743 |     22
  24586 |     30
  54356 |     33
  22922 |     34
  55762 |     68
  35316 |     72
  40790 |     78
    112 |    105
  15602 |    106
  40941 |    111
 211228 |    150
  40127 |    158
(17 rows)
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 2 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:237]: I like ternary operators and prefer your suggestion. Thanks

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 7]
```diff
@@ -0,0 +1,332 @@
...
+            if (!entityIdTypeList.isEmpty()) {
+                batchUpdate(entityIdTypeList);
+            }
+
+            entityIdTypeList = getEntityIdTypes(entityIdCap.get(), timestampCap.get(), flywayMigrationProperties
+                    .getEntityMismatchReadPageSize());
+        }
+
+        log.info("Entity mismatch correction completed in {} s. {} total entities, {} mismatches encountered",
+                stopwatch.elapsed(TimeUnit.SECONDS), entityTransactionCount
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:120]: Don't need to hardcode to seconds, can just log.info("{}", stopwatch) and it will automatically use the biggest duration unit.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java (hunk 5 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java:138]: Left over, will remove.
Originally, these two are added to make it so the max entities in the table isn't actually a valid entity.
I can actually take it out because by this migration any entities above the max valid entityId would have been delete in v1_31_1

Also originally I was going to do the delete after this migration.

Will remove thanks

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 8]
```diff
@@ -0,0 +1,332 @@
...
+    }
+
+    /**
+     * Confirm no type mismatches exist on accounts, contracts, files, topics and tokens entities
+     *
+     * @throws SQLException
+     */
+    private void verifyNoEntityMismatchesExist() throws MigrationSQLException {
+        log.info("Verifying no further entity mismatches exist for accounts, contracts, files, topics and tokens ...");
+        Long accountMismatchCount = getMismatchCount(TransactionTypeEnum.CRYPTOCREATEACCOUNT
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:292]: Each of these is a full table scan since it doesn't use indexes. You can just do a single query with a group by. You can then use having to remove rows equal to zero and have a single throw statement.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 9]
```diff
@@ -0,0 +1,332 @@
...
+        log.info("Entity type mismatch encountered: {}", transactionType);
+        return entityIdType;
+    }
+
+    /**
+     * Confirm no type mismatches exist on accounts, contracts, files, topics and tokens entities
+     *
+     * @throws SQLException
+     */
+    private void verifyNoEntityMismatchesExist() throws MigrationSQLException {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:290]: Why do we need to confirm no entity mismatch unless the database migration has a bug? If it there is a bug in the migration do we really want to block/fail the deployment? We haven't done this in any previous migration

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
Some initial feedback, still working through it. Please also ensure the SonarCloud scan shows no bugs and no new code smells.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 10]
```diff
@@ -0,0 +1,332 @@
...
+        log.trace("batchUpdate {} entities ", entityIdTypes.size());
+        return jdbcTemplate.batchUpdate(
+                ENTITIES_TYPE_UPDATE_SQL,
+                entityIdTypes,
+                flywayMigrationProperties.getEntityMismatchWriteBatchSize(),
+                new ParameterizedPreparedStatementSetter<>() {
+                    @Override
+                    public void setValues(PreparedStatement ps, EntityIdType entityIdType) throws SQLException {
+                        long id = entityIdType.entityId;
+                        ps.setLong(1, entityIdType.correctedEntityTypeId);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:211]:
```suggestion
                        ps.setInt(1, entityIdType.correctedEntityTypeId);
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 11]
```diff
@@ -0,0 +1,332 @@
...
+    }
+
+    @Data
+    // Custom Subset of on Entities object with corresponding consensusTimestamp of create transaction
+    private class EntityIdType {
+        private final long consensusTimestamp;
+        private final long correctedEntityTypeId;
+        private final long entityId;
+        private final long initialEntityTypeId;
+        private final long transactionType;
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:330]:
```suggestion
        private final int correctedEntityTypeId;
        private final long entityId;
        private final int initialEntityTypeId;
        private final int transactionType;
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EntityTypeEnum.java [hunk 12]
```diff
@@ -34,4 +34,14 @@
     TOKEN(5);
 
     private final int id;
+
+    public static EntityTypeEnum fromId(int id) {
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EntityTypeEnum.java:38]: Initially it was, seems in my refactors I no longer needed it. Will remove

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 13]
```diff
@@ -0,0 +1,332 @@
...
+import com.hedera.mirror.importer.domain.TransactionTypeEnum;
+import com.hedera.mirror.importer.exception.MigrationSQLException;
+import com.hedera.mirror.importer.repository.EntityRepository;
+import com.hedera.mirror.importer.repository.TransactionRepository;
+import com.hedera.mirror.importer.util.Utility;
+
+@Log4j2
+@Named
+public class V1_31_1__Entity_Type_Mismatch extends BaseJavaMigration {
+    private final EntityRepository entityRepository;
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:55]: Left over, removed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 14]
```diff
@@ -0,0 +1,332 @@
...
+    private final DataSource dataSource;
+    private final FlywayMigrationProperties flywayMigrationProperties;
+    private JdbcTemplate jdbcTemplate;
+
+    private final String TRANSACTION_MAX_ENTITY_ID_SQL = "select max(entity_id) from transaction where entity_id is " +
+            "not null";
+    private final String CREATED_ENTITIES_TRANSACTION_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
+            "t.consensus_ns from t_entities e join transaction t on (e.id = t.entity_id and t.result = 22 and " +
+            "t.type in (8,11,17,24,29)) where e.id < ? and t.consensus_ns < ? order by id desc, consensus_ns desc " +
+            "limit ?";
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:66]: nit: order by consensus_ns desc is redundant since there won't be duplicate entity IDs in those successful create transactions

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 15]
```diff
@@ -0,0 +1,332 @@
...
+                new ParameterizedPreparedStatementSetter<>() {
+                    @Override
+                    public void setValues(PreparedStatement ps, EntityIdType entityIdType) throws SQLException {
+                        long id = entityIdType.entityId;
+                        ps.setLong(1, entityIdType.correctedEntityTypeId);
+                        ps.setLong(2, id);
+
+                        // update filter counters
+                        entityIdCap.set(id);
+                        timestampCap.set(entityIdType.consensusTimestamp);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:216]: these are already updated in `getTypeMismatchedEntity` and it's also possible updating them here would cause some rows to be reprocessed.

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 9 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:290]: In migrations where info is deleted/updated I think if there's a way to verify the final state is as expected we should utilize it.
If it's not we certainly should fail and prioritize accuracy, no?

File: hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql (hunk 6 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql:9]: Yep, good catch. Should be 
```suggestion
delete from t_entities where id > (select max(entity_id) from transaction where entity_id is not null and result = 22);
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 16]
```diff
@@ -0,0 +1,332 @@
...
+        return entityIdTypes;
+    }
+
+    /**
+     * Batch update entities with correct fk_entity_type_id
+     *
+     * @param entityIdTypes List of mismatched entities
+     * @return
+     */
+    @Transactional
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:200]: Removed

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 17]
```diff
@@ -0,0 +1,332 @@
...
+        }
+
+        log.info("Entity mismatch correction completed in {} s. {} total entities, {} mismatches encountered",
+                stopwatch.elapsed(TimeUnit.SECONDS), entityTransactionCount
+                        .get(), entityTransactionMismatchCount.get());
+
+        verifyNoEntityMismatchesExist();
+
+        // drop temp table
+        jdbcTemplate.execute(DROP_TEMP_ENTITIES_SQL);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:126]: Will removed, had toyed with the idea of leaving temp table around for a while, then deciding on dropping.
Given migration logic and verification I can remove temp table need.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 11 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:330]: Updating, only the timestamp needs to be long

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 14 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java:66]: the order by is to ensure that the search is done in desc order to support the batching of search

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: I got that part, I meant only order by id desc is needed for the reason I provided in the initial comment.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java [hunk 18]
```diff
@@ -0,0 +1,302 @@
...
+
+        // migration
+        migration.migrate(new FlywayContext());
+
+        assertEquals(5, entityRepository.count());
+        assertEquals(5, transactionRepository.count());
+    }
+
+    @Test
+    void verifyEntityTypeMigrationInValidEntities() throws Exception {
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java]: Renamed

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java]: Renamed

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java [hunk 19]
```diff
@@ -365,11 +366,13 @@ protected void assertEntities(EntityId... entityIds) {
...
+        IterableAssert<Entities> entitiesIterableAssert = assertThat(entityRepository.findAll())
+                .hasSize(entityIds.length)
+                .allMatch(entity -> entity.getId() > 0)
+                .allMatch(entity -> entity.getEntityTypeId() != null);
 
-        // verify entities
-        for (EntityId entityId : entityIds) {
-            assertThat(entityRepository.findById(entityId.getId())).isPresent();
-        }
+        entitiesIterableAssert
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java]: Continued chaining. Intellisense error was misleading but since I didn't need the return chaining works fine.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 20]
```diff
@@ -0,0 +1,332 @@
...
+
+    private final String TRANSACTION_MAX_ENTITY_ID_SQL = "select max(entity_id) from transaction where entity_id is " +
+            "not null";
+    private final String CREATED_ENTITIES_TRANSACTION_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
+            "t.consensus_ns from t_entities e join transaction t on (e.id = t.entity_id and t.result = 22 and " +
+            "t.type in (8,11,17,24,29)) where e.id < ? and t.consensus_ns < ? order by id desc, consensus_ns desc " +
+            "limit ?";
+    private final String ENTITIES_TYPE_UPDATE_SQL = "update t_entities set fk_entity_type_id = ? where id = ?";
+    private final String ENTITY_MISMATCH_COUNT_SQL = "select count(*) from t_entities e join transaction t" +
+            " on (e.id = t.entity_id and t.result = 22 and t.type = ? and e.fk_entity_type_id <> ?)";
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Moved out into where.
Also created a separate where string for easier reading.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 21]
```diff
@@ -0,0 +1,332 @@
...
+        this.entityRepository = entityRepository;
+        this.transactionRepository = transactionRepository;
+        this.dataSource = dataSource;
+        this.flywayMigrationProperties = flywayMigrationProperties;
+    }
+
+    @Override
+    public void migrate(Context context) throws Exception {
+        Stopwatch stopwatch = Stopwatch.createStarted();
+        jdbcTemplate = new JdbcTemplate(dataSource);
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Injected `JdbcOperations`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java [hunk 22]
```diff
@@ -0,0 +1,332 @@
...
+        return maxEntityId;
+    }
+
+    /**
+     * Gets the numbers of entity type mismatches found for a specific type of entity
+     *
+     * @param args
+     * @return
+     */
+    private Long getMismatchCount(@Nullable Object... args) {
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Removed

File: hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql (hunk 6 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__remove_invalid_entities.sql]: Updated

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 7 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Updated

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 8 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Adopted single query. With group by letting me log  clearly each entity type that has mismatches whiles till having a single throw for if it's at all above 0

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 10 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Updated

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 14 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Sure, I guess that inherently works because entity id are created in asc id value over time.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 15 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Left over, single update occurs in `getTypeMismatchedEntity()` now

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 1 above)
Comment (ijungmann) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Much better, thanks

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java (hunk 14 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_Mismatch.java]: Updated

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java (hunk 5 above)
Comment (ijungmann) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_1__Entity_Type_MismatchTest.java]: Cool, makes sense, thanks for the details.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java [hunk 23]
```diff
@@ -0,0 +1,323 @@
...
+    private static final String ENTITY_TYPE_MISMATCH_WHERE_CLAUSE = "t.result = 22 and ((t.type = 11 and " +
+            "e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and " +
+            "e.fk_entity_type_id <> 3) or (t.type = 24 and e.fk_entity_type_id <> 4) or (t.type = 29 and " +
+            "e.fk_entity_type_id <> 5))";
+    private static final String ENTITY_TYPE_MISMATCH_COUNT_SQL = "select e.fk_entity_type_id, t.type, count(*) from " +
+            "t_entities e join transaction t on e.id = t.entity_id where " + ENTITY_TYPE_MISMATCH_WHERE_CLAUSE +
+            " group by e.fk_entity_type_id, t.type having count(*) > 0";
+    private static final String ENTITY_TYPE_MISMATCH_SEARCH_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
+            "t.consensus_ns from t_entities e join transaction t on e.id = t.entity_id  where e.id < ? and " +
+            "t.consensus_ns < ? and t.result = 22 and t.type in (8,11,17,24,29) order by id desc " +
```
Comment (ijungmann) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:68]: Is there a reason to do the granular type mismatch checks (`(t.type = 8 and e.fk_entity_type_id <> 2)`, etc) in the count SQL but not here?

**Review by ijungmann — CHANGES_REQUESTED** [review]
Couple minor things, otherwise looks good.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 23 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:68]: Yeah, had wanted to share that logic, but if you do that and combine with paging logic on the search the result is that you don't know when you've hit the end.
It's difficult to reliably differentiate between not finding a a mismatch in the last batch search vs there's no more rows left to actually search.
I didn't want to get down to relying on static id or time stamp numbers to determine this as it could be wrong. 
So decided to leave it as is.
Upside is we're ensured to consider every single entity that was said to have been created.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java [hunk 24]
```diff
@@ -0,0 +1,323 @@
...
+                    public TypeMismatchedEntity mapRow(ResultSet rs, int rowNum) throws SQLException {
+                        return getTypeMismatchedEntity(rs);
+                    }
+                });
+
+        if (typeMismatchedEntities.isEmpty()) {
+            // no more rows to consider, return null
+            log.debug("Retrieved {} entities with mismatch type from t_entities and transaction join",
+                    typeMismatchedEntities.size());
+            return new TypeMismatchSearchResult();
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:198]: Happy to remove the @NoArgs on the class and be explicit here w the following
```suggestion
            return new TypeMismatchSearchResult(null, false);
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 23 above)
Comment (ijungmann) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:68]: That makes sense, I'm okay with it then

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 24 above)
[the remark this answers is not in the document]
Comment (ijungmann) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:198]: I'd prefer that.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java [hunk 25]
```diff
@@ -0,0 +1,323 @@
...
+public class V1_31_2__Entity_Type_Mismatch extends BaseJavaMigration {
+    private final FlywayMigrationProperties flywayMigrationProperties;
+    private final JdbcTemplate jdbcTemplate;
+
+    private static final String TRANSACTION_MAX_ENTITY_ID_SQL = "select max(entity_id) from transaction where " +
+            "entity_id is " +
+            "not null";
+    // where clause used by count that captures correct entityType to transactionType mapping
+    private static final String ENTITY_TYPE_MISMATCH_WHERE_CLAUSE = "t.result = 22 and ((t.type = 11 and " +
+            "e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and " +
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:60]: Why are we limiting to these certain types here and in the search SQL? It should be all transaction types that are associated with one of the entity types. For example, a CONSENSUSUPDATETOPIC can certainly return an INVALID_TOPIC_ID.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java [hunk 26]
```diff
@@ -0,0 +1,323 @@
...
+@Named
+public class V1_31_2__Entity_Type_Mismatch extends BaseJavaMigration {
+    private final FlywayMigrationProperties flywayMigrationProperties;
+    private final JdbcTemplate jdbcTemplate;
+
+    private static final String TRANSACTION_MAX_ENTITY_ID_SQL = "select max(entity_id) from transaction where " +
+            "entity_id is " +
+            "not null";
+    // where clause used by count that captures correct entityType to transactionType mapping
+    private static final String ENTITY_TYPE_MISMATCH_WHERE_CLAUSE = "t.result = 22 and ((t.type = 11 and " +
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:59]: If we later add new transaction types but someone runs this migration after that point, it would miss those types. Perhaps we should auto-generate this SQL from the enums? Also, it would be less brittle and hard to understand.

That is, add an optional `EntityTypeEnum` field to `TransactionTypeEnum` that groups transactions types per which entity they are associated with. Then generate the SQL using that info.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java [hunk 27]
```diff
@@ -0,0 +1,323 @@
...
+            "e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and " +
+            "e.fk_entity_type_id <> 3) or (t.type = 24 and e.fk_entity_type_id <> 4) or (t.type = 29 and " +
+            "e.fk_entity_type_id <> 5))";
+    private static final String ENTITY_TYPE_MISMATCH_COUNT_SQL = "select e.fk_entity_type_id, t.type, count(*) from " +
+            "t_entities e join transaction t on e.id = t.entity_id where " + ENTITY_TYPE_MISMATCH_WHERE_CLAUSE +
+            " group by e.fk_entity_type_id, t.type having count(*) > 0";
+    private static final String ENTITY_TYPE_MISMATCH_SEARCH_SQL = "select  e.id, e.fk_entity_type_id, t.type, " +
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:66]: We should use a DB cursor instead of using this complicated keyset pagination approach with stateful Atomics. The updating can be batched but the querying should not be. 

Besides being harder to understand and making the class stateful, this query will be slower since it's joining an un-indexed field. Keyset pagination only makes sense when using index fields. I ran this query in mainnet and a single page took a few minutes.

This would also allow you to reuse the sql that compares the entity type with the transaction type. It would also make the verification query completely unnecessary as it's the same SQL.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
With the change requested to use DB Cursor, this whole Java Migration could really just be simplified to a CTE with an update. This is way easier to understand, maintain and is a lot more efficient to execute.

pseudo-sql:
```sql
with mismatch as (
  select e.fk_entity_type_id, e.id from 
  t_entities e join transaction t on e.id = t.entity_id where 
  t.result = 22 and ((t.type = 11 and 
  e.fk_entity_type_id <> 1) or (t.type = 8 and e.fk_entity_type_id <> 2) or (t.type = 17 and 
  e.fk_entity_type_id <> 3) or (t.type = 24 and e.fk_entity_type_id <> 4) or (t.type = 29 and 
  e.fk_entity_type_id <> 5))
)
update t_entities set fk_entity_type_id = mismatch.fk_entity_type_id where id = mismatch.id
```

The test that verifies this scenario can still be used with such a sql.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 25 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:60]: True, but the additional transactions types aren't necessary to determine if an entity type is mismatched. 
Every entity noted by a successful transaction create type should have a mapping in the t_entities table.
That's all you need to determine and correct the t_entities table.
Updated and deletes etc will all follow a create transaction, so it's sufficient to look at that.

Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:60]: Post offline discussion the tricky part here is the backfill problem. With missing historic data we can't rely on only create transactions as they may not be present.
I see the need for all transactions, which can make the list exhaustive and sql long but will look into that

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 26 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:59]: Good point. Such a mapping is useful.
Especially given the exhaustive transactions type discussed.
Will look into this.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 27 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java:66]: Agreed, will look into this.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 24 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java]: Made the change but then blew this whole class away in the end.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java [hunk 28]
```diff
@@ -0,0 +1,323 @@
...
+        return new TypeMismatchSearchResult(typeMismatchedEntities, true);
+    }
+
+    /**
+     * Batch update entities with correct fk_entity_type_id
+     *
+     * @param typeMismatchedEntities List of mismatched entities
+     * @return
+     */
+    public int[][] batchUpdate(List<TypeMismatchedEntity> typeMismatchedEntities) {
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java]: N/A, class removed.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Entity_Type_MismatchTest.java [hunk 29]
```diff
@@ -0,0 +1,298 @@
...
+import com.hedera.mirror.importer.domain.Entities;
+import com.hedera.mirror.importer.domain.EntityId;
+import com.hedera.mirror.importer.domain.EntityTypeEnum;
+import com.hedera.mirror.importer.domain.Transaction;
+import com.hedera.mirror.importer.domain.TransactionTypeEnum;
+import com.hedera.mirror.importer.repository.EntityRepository;
+import com.hedera.mirror.importer.repository.TransactionRepository;
+
+@Log4j2
+@TestPropertySource(properties = "spring.flyway.target=1.31.1")
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Entity_Type_MismatchTest.java]: Is this still applicable. Should be okay now with the modification to 
```
@TestPropertySource(properties = "spring.flyway.target=1.31.0")
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 25 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java]: Went for an exclusive set. in CTE update I ignore system, unknown and freeze transaction - basically those that don't relate to an entity.
This way future entities added can be picked up.

Also update the transaction_types table with the corresponding entity_type

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 26 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java]: Mapping now in db as noted

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java (hunk 27 above)
Comment (Nana-EC) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_31_2__Entity_Type_Mismatch.java]: Cursor was a good idea.
With CTE update no longer needed as this class is gone

**Review by steven-sheehy — COMMENTED** [review]
LGTM. Just need to change the migration number

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Entity_Type_MismatchTest.java [hunk 30]
```diff
@@ -0,0 +1,275 @@
...
+class V_1_31_2__Entity_Type_MismatchTest extends IntegrationTest {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Entity_Type_MismatchTest.java:54]: This class name no longer matches the sql name

**Review by steven-sheehy — APPROVED** [review]
LGTM. Please also update the PR description with the changes before merging.

**Review by ijungmann — APPROVED** [review]

**Review by xin-hedera — APPROVED** [review]
LGTM
