### PR TITLE
Suppress recoverable error for inactive evm addresses

### LINKED ISSUE #8290: Suppress recoverable errors for inactive addresses
### Description

Previously, consensus nodes were required to always send us `shard.realm.num` entity IDs in the `TransactionRecord`. With the EVM equivalence work, contract calls are now allowed against inactive EVM addresses which will result in no changes to state. Since these inactive addresses have never been created on consensus nodes, there's no `shard.realm.num` ID to convert to and consensus nodes put `shard.realm.address` in the `TransactionRecord`. Mirror node attempts to map this back to its numeric form and fails and logs a recoverable error which causes an alert.

### Steps to reproduce

https://hashscan.io/testnet/transaction/1714759950.957066003
https://hashscan.io/testnet/account/0x7e8a489e17fc9eaec4a4b0ade5acf7f31eb5b961?pt=1

### Additional context

`Recoverable Error Logs for testnet-na/testnet/mirror-importer-544d7857c7-f9kdk have reached 2 error messages/s in a 1m period`

```
2024-05-10T22:12:00.241Z ERROR pool-12-thread-2 c.h.m.i.util.Utility Recoverable error. Entity not found for EVM address 7e8a489e17fc9eaec4a4b0ade5acf7f31eb5b961 
2024-05-10T22:12:00.241Z ERROR pool-12-thread-2 c.h.m.i.util.Utility Recoverable error. Invalid contract id for contract result at 1714759950957066003 
```

```
receipt {
  status: SUCCESS
  contractID {
    evm_address: "~\212H\236\027\374\236\256\304\244\260\255\345\254\367\363\036\265\271a"
  }
  exchangeRate {
    currentRate {
      hbarEquiv: 30000
      centEquiv: 340516
      expirationTime {
        seconds: 1714762800
      }
    }
    nextRate {
      hbarEquiv: 30000
      centEquiv: 338602
      expirationTime {
        seconds: 1714766400
      }
    }
  }
}
transactionHash: "\355q\025l\310\032\305\r\257\263\347\271\206\300\026\367\235\2359\325\2226 \362\216\263\000}E]\r\035&\225\301v:\376O-(\033NAo\233\370\a"
consensusTimestamp {
  seconds: 1714759950
  nanos: 957066003
}
transactionID {
  transactionValidStart {
    seconds: 1714759942
    nanos: 398861689
  }
  accountID {
    accountNum: 3038782
  }
}
transactionFee: 948003430
contractCallResult {
  contractID {
    evm_address: "~\212H\236\027\374\236\256\304\244\260\255\345\254\367\363\036\265\271a"
  }
  bloom: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  gasUsed: 12000000
  gas: 15000000
  functionParameters: ".\230&\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\nIGNHMKYBAT\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  sender_id {
    accountNum: 3432148
  }
  signer_nonce {
    value: 109
  }
}
transferList {
  accountAmounts {
    accountID {
      accountNum: 3
    }
    amount: 1719755
  }
  accountAmounts {
    accountID {
      accountNum: 98
    }
    amount: 941655308
  }
  accountAmounts {
    accountID {
      accountNum: 800
    }
    amount: 4628367
  }
  accountAmounts {
    accountID {
      accountNum: 3038782
    }
    amount: -48003430
  }
  accountAmounts {
    accountID {
      accountNum: 3432148
    }
    amount: -900000000
  }
}
ethereum_hash: "\206\370\033/\230\032\360z\201\2206\330\212\263\212F\252\037\204;v\f0i= \2558m\"7\241"
```

### Hedera network

testnet

### Version

v0.103.0

### Operating system

None

### PR DESCRIPTION
**Pull request by edwin-greene**
**Description**:
Suppresses recoverable errors when unable to lookup an entity id for an inactive evm address.

**Related issue(s)**:

Fixes #8290

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 1]
```diff
@@ -149,6 +151,13 @@ private boolean isContractCreateOrCall(TransactionBody transactionBody) {
         return transactionBody.hasContractCall() || transactionBody.hasContractCreateInstance();
     }
 
+    private boolean shouldThrowRecoverableError(TransactionRecord transactionRecord) {
+        var receipt = transactionRecord.getReceipt();
+        return !(receipt.getStatus().equals(ResponseCodeEnum.SUCCESS)
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:156]: Use recordItem.isSuccessful()

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 2]
```diff
@@ -88,13 +89,14 @@ public void process(@NonNull RecordItem recordItem, Transaction transaction) {
...
-
+        var throwRecoverableError = shouldThrowRecoverableError(transactionRecord);
         // in pre-compile case transaction is not a contract type and entityId will be of a different type
         var contractId = (contractCallOrCreate
                         ? Optional.ofNullable(transaction.getEntityId())
-                        : entityIdService.lookup(functionResult.getContractID()))
+                        : entityIdService.lookup(functionResult.getContractID(), throwRecoverableError))
                 .orElse(EntityId.EMPTY);
-        var isRecoverableError = EntityId.isEmpty(contractId)
+        var isRecoverableError = throwRecoverableError
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:98]: While probably they're both guaranteed to be set the same, just in case we should separate recoverable error logic. That is, don't call shouldThrowRecoverableError() once and pass it to both but check them separately with the proper field.

```suggestion
        var isRecoverableError = !(recordItem.isSuccessful() && functionResult.getContractID().hasEvmAddress())
```

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 3]
```diff
@@ -149,6 +151,13 @@ private boolean isContractCreateOrCall(TransactionBody transactionBody) {
         return transactionBody.hasContractCall() || transactionBody.hasContractCreateInstance();
     }
 
+    private boolean shouldThrowRecoverableError(TransactionRecord transactionRecord) {
+        var receipt = transactionRecord.getReceipt();
+        return !(receipt.getStatus().equals(ResponseCodeEnum.SUCCESS)
+                        && receipt.getContractID().hasEvmAddress())
+                && !transactionRecord.getContractCallResult().getContractID().hasEvmAddress();
```
[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java]: Thanks I have updated this.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java (hunk 2 above)
Comment (edwin-greene) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:98]: I tried a few things here and my changes broke the unit tests, will continue to look at this.

Comment (edwin-greene) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java]: Thanks I have now fixed this, please re-review.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 4]
```diff
@@ -88,15 +89,17 @@ public void process(@NonNull RecordItem recordItem, Transaction transaction) {
 
         // contractResult
         var transactionHandler = transactionHandlerFactory.get(TransactionType.of(transaction.getType()));
-
+        var throwRecoverableError = shouldThrowRecoverableError(functionResult, recordItem, transactionRecord);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:92]: When I said separate I meant to do a similar change for the receipt contractId.
```suggestion
        var throwRecoverableError = !(recordItem.isSuccessful() && transactionRecord.getReceipt().getContractID().hasEvmAddress());
```

Comment (edwin-greene) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java]: Got it, this has now been updated.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 5]
```diff
@@ -88,15 +88,18 @@ public void process(@NonNull RecordItem recordItem, Transaction transaction) {
...
         var contractId = (contractCallOrCreate
                         ? Optional.ofNullable(transaction.getEntityId())
-                        : entityIdService.lookup(functionResult.getContractID()))
+                        : entityIdService.lookup(functionResult.getContractID(), throwRecoverableError))
                 .orElse(EntityId.EMPTY);
-        var isRecoverableError = EntityId.isEmpty(contractId)
-                && !contractCallOrCreate
-                && !ContractID.getDefaultInstance().equals(functionResult.getContractID());
+        var isRecoverableError =
+                !(recordItem.isSuccessful() && functionResult.getContractID().hasEvmAddress())
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java:99]: I might've misled you before. Believe `functionResult.getContractID()` should already log above if it had a recoverable error. This check should run for the one in receipt.

Also, we want to ensure we don't log twice like we're doing now on main so we can skip if previously logged. Something like this (please verify):

```suggestion
                !throwRecoverableError &&
                !(recordItem.isSuccessful() && transactionRecord.getReceipt().getContractID().hasEvmAddress())
```

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java [hunk 6]
```diff
@@ -88,15 +88,18 @@ public void process(@NonNull RecordItem recordItem, Transaction transaction) {
 
         // contractResult
         var transactionHandler = transactionHandlerFactory.get(TransactionType.of(transaction.getType()));
-
+        var throwRecoverableError = !(recordItem.isSuccessful()
+                && (transactionRecord.getReceipt().getContractID().hasEvmAddress()));
```
[the remark this answers is not in the document]
Comment (edwin-greene) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java]: Thanks I have updated this.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java (hunk 5 above)
Comment (edwin-greene) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java]: Thanks. I ran through the recreate scenario and updated this section. 

The first boolean, `throwRecoverableError` wouldn't indicate that an error was thrown, only that it could be thrown. I've changed the name and added a comment.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplTest.java [hunk 7]
```diff
@@ -101,7 +110,9 @@ private static Stream<Arguments> provideEntities() {
                 Arguments.of(withDefaultContractId, EntityId.EMPTY, false),
                 Arguments.of(contractCreate, EntityId.EMPTY, false),
                 Arguments.of(contractCreate, null, false),
-                Arguments.of(contractCreate, EntityId.of(0, 0, 5), false));
+                Arguments.of(contractCreate, EntityId.of(0, 0, 5), false),
+                Arguments.of(withInactiveEvm, null, false),
+                Arguments.of(withInactiveEvm, EntityId.EMPTY, false));
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplTest.java:115]: Can we capture the logs and verify no recoverable errors for these?

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by jascks — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
