### PR TITLE
Address book fix

### LINKED ISSUE #58: Rework address book file update
When a transaction to update the address book is detected by mirror node, the address book file is updated.
Need to test this scenario with an actual address book update transaction.

In the event that an address book update transaction itself cannot be tested, a test with another file to verify contents are updated would be a good first confidence test.

1. Create a file on the file system containing some data
2. Create the same file on the network via a transaction
3. Issue an update transaction for the same file with new contents
4. Check that the 0.0.102 file contains the new contents.

### LINKED ISSUE #695: Address book parsing fails when file update spans transactions
**Detailed Description**
Testing a new address book update (0.0.102) in staging and it failed:
```
textPayload,insertId,resource.type,resource.labels.project_id,resource.labels.instance_id,resource.labels.zone,timestamp,"labels.""compute.googleapis.com/resource_name""",logName,receiveTimestamp
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1189) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhmx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhmw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.",4nbmt13dmz9axyhmv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:28,144 ERROR [scheduling-2] c.h.m.i.a.NetworkAddressBook Failed to parse NodeAddressBook from /var/lib/hedera-mirror-importer/staging1.f102.bin",4nbmt13dmz9axyhmu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.Thread.run(Thread.java:834) [?:?],4nbmt13dmz9axyhmt,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?],4nbmt13dmz9axyhms,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?],4nbmt13dmz9axyhmr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?],4nbmt13dmz9axyhmq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?],4nbmt13dmz9axyhmp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?],4nbmt13dmz9axyhmo,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhmn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhmm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?],4nbmt13dmz9axyhml,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?],4nbmt13dmz9axyhmk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?],4nbmt13dmz9axyhmj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.record.RecordFileDownloader.download(RecordFileDownloader.java:49) [classes!/:0.9.0],4nbmt13dmz9axyhmi,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.downloadNextBatch(Downloader.java:95) [classes!/:0.9.0],4nbmt13dmz9axyhmh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.downloadSigFiles(Downloader.java:121) [classes!/:0.9.0],4nbmt13dmz9axyhmg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.addressbook.NetworkAddressBook.load(NetworkAddressBook.java:98) [classes!/:0.9.0],4nbmt13dmz9axyhmf,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.parseFrom(NodeAddressBook.java:237) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhme,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhmd,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhmc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhmb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhma,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhlz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:811) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhly,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:816) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhlx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:13) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhlw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:63) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhlv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:886) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhlu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1189) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhlt,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhls,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.",4nbmt13dmz9axyhlr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:28,141 ERROR [scheduling-2] c.h.m.i.a.NetworkAddressBook Failed to parse NodeAddressBook from /var/lib/hedera-mirror-importer/staging1.f102.bin",4nbmt13dmz9axyhlq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:28,132 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:28,106 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 2 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlo,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:28,079 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 385 transfer lists, 0 files, 2 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhln,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:28,054 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 394 transfer lists, 0 files, 0 contracts, 0 claims, 6 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:28,026 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 1 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhll,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:28 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:28,000 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 0 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:28Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,969 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,943 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 1 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhli,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,918 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 0 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,894 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,868 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 1 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlf,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,841 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhle,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,814 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 385 transfer lists, 0 files, 2 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhld,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,787 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 2 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,760 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 2 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhlb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,731 INFO  [scheduling-3] c.h.m.i.p.r.RecordFileParser Loading version 2 record file: /var/lib/hedera-mirror-importer/recordstreams/valid/2020-04-17T21_29_15.018302Z.rcd",4nbmt13dmz9axyhla,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,726 INFO  [scheduling-3] c.h.m.i.p.r.RecordFileParser Finished parsing 6168 transactions from record file /var/lib/hedera-mirror-importer/recordstreams/valid/2020-04-17T21_29_10.018111Z.rcd in 1.786 s",4nbmt13dmz9axyhkz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,712 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 68 transactions, 265 transfer lists, 0 files, 0 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhky,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.Thread.run(Thread.java:834) [?:?],4nbmt13dmz9axyhkx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?],4nbmt13dmz9axyhkw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?],4nbmt13dmz9axyhkv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?],4nbmt13dmz9axyhku,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?],4nbmt13dmz9axyhkt,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?],4nbmt13dmz9axyhks,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhkr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhkq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?],4nbmt13dmz9axyhkp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?],4nbmt13dmz9axyhko,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?],4nbmt13dmz9axyhkn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.record.RecordFileDownloader.download(RecordFileDownloader.java:49) [classes!/:0.9.0],4nbmt13dmz9axyhkm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.downloadNextBatch(Downloader.java:97) [classes!/:0.9.0],4nbmt13dmz9axyhkl,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.verifySigsAndDownloadDataFiles(Downloader.java:278) [classes!/:0.9.0],4nbmt13dmz9axyhkk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.NodeSignatureVerifier.<init>(NodeSignatureVerifier.java:50) [classes!/:0.9.0],4nbmt13dmz9axyhkj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.addressbook.NetworkAddressBook.load(NetworkAddressBook.java:98) [classes!/:0.9.0],4nbmt13dmz9axyhki,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.parseFrom(NodeAddressBook.java:237) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhkh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhkg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhkf,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhke,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhkd,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhkc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:811) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhkb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:816) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhka,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:13) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhjz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:63) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhjy,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:886) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhjx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1189) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhjw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhjv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.",4nbmt13dmz9axyhju,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,644 ERROR [scheduling-6] c.h.m.i.a.NetworkAddressBook Failed to parse NodeAddressBook from /var/lib/hedera-mirror-importer/staging1.f102.bin",4nbmt13dmz9axyhjt,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.Thread.run(Thread.java:834) [?:?],4nbmt13dmz9axyhjs,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?],4nbmt13dmz9axyhjr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?],4nbmt13dmz9axyhjq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?],4nbmt13dmz9axyhjp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?],4nbmt13dmz9axyhjo,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?],4nbmt13dmz9axyhjn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhjm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhjl,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?],4nbmt13dmz9axyhjk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?],4nbmt13dmz9axyhjj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?],4nbmt13dmz9axyhji,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.record.RecordFileDownloader.download(RecordFileDownloader.java:49) [classes!/:0.9.0],4nbmt13dmz9axyhjh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.downloadNextBatch(Downloader.java:95) [classes!/:0.9.0],4nbmt13dmz9axyhjg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.downloadSigFiles(Downloader.java:121) [classes!/:0.9.0],4nbmt13dmz9axyhjf,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.addressbook.NetworkAddressBook.load(NetworkAddressBook.java:98) [classes!/:0.9.0],4nbmt13dmz9axyhje,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.parseFrom(NodeAddressBook.java:237) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhjd,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhjc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhjb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhja,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhiz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhiy,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:811) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhix,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:816) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhiw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:13) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhiv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:63) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhiu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:886) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhit,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1189) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhis,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhir,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.",4nbmt13dmz9axyhiq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,642 ERROR [scheduling-6] c.h.m.i.a.NetworkAddressBook Failed to parse NodeAddressBook from /var/lib/hedera-mirror-importer/staging1.f102.bin",4nbmt13dmz9axyhip,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,612 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 393 transfer lists, 0 files, 0 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhio,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,584 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 0 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhin,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,561 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 385 transfer lists, 0 files, 3 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhim,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,532 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 0 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhil,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,506 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 393 transfer lists, 0 files, 0 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhik,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,481 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 1 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhij,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,456 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 385 transfer lists, 0 files, 2 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhii,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,424 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhih,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,398 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 0 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhig,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,369 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 393 transfer lists, 0 files, 1 contracts, 0 claims, 6 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhif,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,343 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 4 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhie,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,316 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 385 transfer lists, 0 files, 0 contracts, 0 claims, 15 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhid,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,291 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 393 transfer lists, 0 files, 0 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhic,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,266 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 0 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhib,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,240 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 0 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhia,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,213 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 384 transfer lists, 0 files, 2 contracts, 0 claims, 14 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhhz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:32:05.607285083Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,188 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhhy,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,160 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhhx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.Thread.run(Thread.java:834) [?:?],4nbmt13dmz9axyhhw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?],4nbmt13dmz9axyhhv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?],4nbmt13dmz9axyhhu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?],4nbmt13dmz9axyhht,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?],4nbmt13dmz9axyhhs,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?],4nbmt13dmz9axyhhr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhhq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhhp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?],4nbmt13dmz9axyhho,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?],4nbmt13dmz9axyhhn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?],4nbmt13dmz9axyhhm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.record.RecordFileDownloader.download(RecordFileDownloader.java:49) [classes!/:0.9.0],4nbmt13dmz9axyhhl,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.downloadNextBatch(Downloader.java:97) [classes!/:0.9.0],4nbmt13dmz9axyhhk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.verifySigsAndDownloadDataFiles(Downloader.java:278) [classes!/:0.9.0],4nbmt13dmz9axyhhj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.NodeSignatureVerifier.<init>(NodeSignatureVerifier.java:50) [classes!/:0.9.0],4nbmt13dmz9axyhhi,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.addressbook.NetworkAddressBook.load(NetworkAddressBook.java:98) [classes!/:0.9.0],4nbmt13dmz9axyhhh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.parseFrom(NodeAddressBook.java:237) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhhg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhhf,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhhe,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhhd,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhhc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhhb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:811) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhha,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:816) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhgz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:13) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhgy,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:63) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhgx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:886) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhgw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1189) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhgv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhgu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.",4nbmt13dmz9axyhgt,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,145 ERROR [scheduling-6] c.h.m.i.a.NetworkAddressBook Failed to parse NodeAddressBook from /var/lib/hedera-mirror-importer/staging1.f102.bin",4nbmt13dmz9axyhgs,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.Thread.run(Thread.java:834) [?:?],4nbmt13dmz9axyhgr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?],4nbmt13dmz9axyhgq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?],4nbmt13dmz9axyhgp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?],4nbmt13dmz9axyhgo,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?],4nbmt13dmz9axyhgn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?],4nbmt13dmz9axyhgm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhgl,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE],4nbmt13dmz9axyhgk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?],4nbmt13dmz9axyhgj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?],4nbmt13dmz9axyhgi,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?],4nbmt13dmz9axyhgh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.record.RecordFileDownloader.download(RecordFileDownloader.java:49) [classes!/:0.9.0],4nbmt13dmz9axyhgg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.downloadNextBatch(Downloader.java:95) [classes!/:0.9.0],4nbmt13dmz9axyhgf,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.downloader.Downloader.downloadSigFiles(Downloader.java:121) [classes!/:0.9.0],4nbmt13dmz9axyhge,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hedera.mirror.importer.addressbook.NetworkAddressBook.load(NetworkAddressBook.java:98) [classes!/:0.9.0],4nbmt13dmz9axyhgd,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.parseFrom(NodeAddressBook.java:237) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhgc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhgb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhga,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhfz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhfy,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhfx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:811) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhfw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook$1.parsePartialFrom(NodeAddressBook.java:816) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhfv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:13) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhfu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.hederahashgraph.api.proto.java.NodeAddressBook.<init>(NodeAddressBook.java:63) ~[hedera-protobuf-java-api-0.4.0.jar!/:?],4nbmt13dmz9axyhft,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:886) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhfs,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1189) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhfr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: #011at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84) ~[protobuf-java-3.10.0.jar!/:?],4nbmt13dmz9axyhfq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.",4nbmt13dmz9axyhfp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,142 ERROR [scheduling-6] c.h.m.i.a.NetworkAddressBook Failed to parse NodeAddressBook from /var/lib/hedera-mirror-importer/staging1.f102.bin",4nbmt13dmz9axyhfo,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,133 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 0 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,108 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,082 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfl,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,056 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,031 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 2 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:27 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:27,004 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfi,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:27Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,978 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 384 transfer lists, 1 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,943 INFO  [scheduling-3] c.h.m.i.a.NetworkAddressBook New address book successfully saved to /var/lib/hedera-mirror-importer/staging1.f102.bin",4nbmt13dmz9axyhfg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,929 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 398 transfer lists, 0 files, 0 contracts, 0 claims, 2 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhff,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,904 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 383 transfer lists, 0 files, 2 contracts, 0 claims, 15 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfe,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,873 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 385 transfer lists, 0 files, 1 contracts, 0 claims, 14 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfd,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,842 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,812 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 0 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,787 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhfa,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,760 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 0 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhez,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,734 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 385 transfer lists, 0 files, 1 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhey,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,707 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhex,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,682 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 3 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhew,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,656 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 1 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhev,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,629 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 2 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyheu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,603 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhet,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,577 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 0 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhes,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,552 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 0 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyher,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,522 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 0 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyheq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,495 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 2 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhep,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,467 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 0 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyheo,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,441 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 1 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhen,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,412 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhem,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,385 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhel,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,360 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 0 contracts, 0 claims, 14 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhek,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,330 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 393 transfer lists, 0 files, 0 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhej,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,303 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 4 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhei,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,275 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyheh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,243 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyheg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,213 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 383 transfer lists, 0 files, 0 contracts, 0 claims, 17 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhef,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,183 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 393 transfer lists, 0 files, 0 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhee,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,157 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 1 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhed,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,128 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 0 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhec,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,099 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 2 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyheb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,073 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 0 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhea,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,049 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:26 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:26,024 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 3 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdy,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:26Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,995 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 384 transfer lists, 0 files, 2 contracts, 0 claims, 14 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,969 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,944 INFO  [scheduling-3] c.h.m.i.p.r.RecordFileParser Loading version 2 record file: /var/lib/hedera-mirror-importer/recordstreams/valid/2020-04-17T21_29_10.018111Z.rcd",4nbmt13dmz9axyhdv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,939 INFO  [scheduling-3] c.h.m.i.p.r.RecordFileParser Finished parsing 6401 transactions from record file /var/lib/hedera-mirror-importer/recordstreams/valid/2020-04-17T21_29_05.016510Z.rcd in 3.138 s",4nbmt13dmz9axyhdu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,925 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 1 transactions, 3 transfer lists, 0 files, 0 contracts, 0 claims, 1 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdt,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,839 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhds,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,811 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 0 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,786 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 0 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,760 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 385 transfer lists, 0 files, 2 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,733 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 0 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdo,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,708 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 1 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,681 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 1 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,653 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 2 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdl,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,622 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 1 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,592 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 1 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,566 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 2 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdi,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,541 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 0 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdh,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,515 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 1 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,490 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 0 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdf,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,466 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 2 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhde,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,439 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 0 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdd,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,412 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 2 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,386 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhdb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,360 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 0 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhda,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,335 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 0 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,309 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcy,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,266 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 1 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,218 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,155 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 2 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,129 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 2 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,101 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhct,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,073 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 0 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcs,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,048 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 2 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:25 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:25,022 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 0 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:25Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:24 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:24,998 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 1 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:24Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:24 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:24,971 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhco,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:24Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:24 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:24,945 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 0 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:24Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:24 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:24,917 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:24Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:24 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:24,816 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 1 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcl,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:24Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:24 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:24,645 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 0 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhck,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:24Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:24 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:24,326 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 386 transfer lists, 0 files, 1 contracts, 0 claims, 13 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhcj,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:24Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,758 WARN  [scheduling-6] c.h.m.i.d.NodeSignatureVerifier Verified signature file 2020-04-19T04_51_15.002234001Z.rcd_sig reached consensus but with some errors: {MISSING=[0.0.11, 0.0.13, 0.0.14, 0.0.15, 0.0.6, 0.0.7, 0.0.9], VERIFIED=[0.0.12]}",4nbmt13dmz9axyhci,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,756 INFO  [scheduling-6] c.h.m.i.d.r.RecordFileDownloader Downloaded 6 signatures in 114.8 ms (52/s)",4nbmt13dmz9axyhch,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,756 INFO  [pool-7-thread-2] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.3 in 112.6 ms",4nbmt13dmz9axyhcg,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,748 INFO  [pool-7-thread-6] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.12 in 103.5 ms",4nbmt13dmz9axyhcf,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,746 INFO  [pool-7-thread-4] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.5 in 103.8 ms",4nbmt13dmz9axyhce,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,745 INFO  [pool-7-thread-5] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.10 in 100.3 ms",4nbmt13dmz9axyhcd,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,738 INFO  [pool-7-thread-10] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.8 in 95.36 ms",4nbmt13dmz9axyhcc,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,737 INFO  [pool-7-thread-12] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.4 in 95.08 ms",4nbmt13dmz9axyhcb,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,730 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhca,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,642 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 3 contracts, 0 claims, 6 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbz,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,601 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhby,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,545 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 389 transfer lists, 0 files, 1 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbx,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,507 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 390 transfer lists, 0 files, 0 contracts, 0 claims, 10 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbw,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,431 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 388 transfer lists, 0 files, 1 contracts, 0 claims, 11 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbv,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,367 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 1 contracts, 0 claims, 7 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbu,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,341 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 0 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbt,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,316 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 387 transfer lists, 0 files, 1 contracts, 0 claims, 12 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbs,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,291 WARN  [scheduling-6] c.h.m.i.d.r.RecordFileDownloader Signature verification failed for 2020-04-19T04_51_15.002234001Z.rcd_sig: {MISSING=[0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.6, 0.0.7, 0.0.8, 0.0.9], VERIFIED=[0.0.3, 0.0.4, 0.0.5]}",4nbmt13dmz9axyhbr,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,290 INFO  [scheduling-6] c.h.m.i.d.r.RecordFileDownloader Downloaded 3 signatures in 147.9 ms (20/s)",4nbmt13dmz9axyhbq,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,289 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 392 transfer lists, 0 files, 0 contracts, 0 claims, 8 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbp,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,289 INFO  [pool-7-thread-5] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.5 in 147.4 ms",4nbmt13dmz9axyhbo,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,263 INFO  [pool-7-thread-8] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.4 in 120.8 ms",4nbmt13dmz9axyhbn,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,258 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 384 transfer lists, 0 files, 2 contracts, 0 claims, 14 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbm,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,233 INFO  [pool-7-thread-6] c.h.m.i.d.r.RecordFileDownloader Downloaded 1 signatures for node 0.0.3 in 89.95 ms",4nbmt13dmz9axyhbl,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
"Apr 19 04:51:23 mirrornode-staging1-parser-1 java[31059]: 2020-04-19 04:51:23,232 INFO  [scheduling-3] c.h.m.i.p.r.PostgresWritingRecordParsedItemHandler Inserted 100 transactions, 391 transfer lists, 0 files, 0 contracts, 0 claims, 9 topic messages, 0 non-fee transfers",4nbmt13dmz9axyhbk,gce_instance,staging1,9185304416728857784,us-central1-a,2020-04-19T04:51:23Z,mirrornode-staging1-parser-1,projects/staging1/logs/syslog,2020-04-19T05:31:59.583719141Z
```

**Actual Behavior**
 Update address book with a file that spans multiple transactions

**Expected Behavior**
- Downloader does not fail validating signatures temporarily while address book update is incomplete
- Mirror node does not halt indefinitely if the transactions span record files

**Environment:**
- Java: OpenJDK 11
- OS: Ubuntu 18.04
- Version: 0.9.0

**Additional Context**

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
Fix address book updates to:
- Not write to in memory objects as they are stateful and we may lose data if restarted before it's complete
- Use an addressbook.bin.tmp to store address books that don't fit in a single file update and don't parse
- Overwrite addressbook.bin if file update parses
- Overwrite addressbook.bin if contents of tmp file plus file append contents parse
- Otherwise append to addressbook.bin.tmp if file append and it exists
- Delete tmp whenever addressbook.bin written

**Which issue(s) this PR fixes**:
Fixes #58
Fixes #695 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/NetworkAddressBook.java [hunk 1]
```diff
@@ -72,45 +72,58 @@ private void init() {
...
-        saveToDisk();
+        saveToDisk(newContents, StandardOpenOption.TRUNCATE_EXISTING);
     }
 
     public void append(byte[] extraContents) throws IOException {
-        byte[] newAddressBook = Arrays.copyOf(addressBookBytes, addressBookBytes.length + extraContents.length);
-        System.arraycopy(extraContents, 0, newAddressBook, addressBookBytes.length, extraContents.length);
-        addressBookBytes = newAddressBook;
-        saveToDisk();
+        saveToDisk(extraContents, StandardOpenOption.APPEND);
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/NetworkAddressBook.java:79]: I don't think this method has test coverage.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/NetworkAddressBook.java [hunk 2]
```diff
@@ -72,45 +72,58 @@ private void init() {
...
-                    .getNodeAddressList()) {
-                NodeAddress nodeAddress = NodeAddress.builder()
-                        .id(nodeAddressProto.getMemo().toStringUtf8())
-                        .ip(nodeAddressProto.getIpAddress().toStringUtf8())
-                        .port(nodeAddressProto.getPortno())
-                        .publicKey(nodeAddressProto.getRSAPubKey())
-                        .build();
-                builder.add(nodeAddress);
-            }
+            return parse(path);
```
Comment (apeksharma) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/NetworkAddressBook.java:122]: Since NetworkAddressBook "owns" underlying file, it doesn't need a disk IO every time Downloader needs list of nodes.
We can store `Collection<NodeAddress>` in local variable, initializing it in `init()` and updating it in `saveToDisk` in `if (!nodeAddresses.isEmpty()) {` condition

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/NetworkAddressBook.java:122]: We will defer this item to resolving it on master

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/NetworkAddressBook.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/NetworkAddressBook.java:79]: There is integration test coverage in RecordItemParserFileTest. Will add NetworkAddressBook unit tests when porting to master.
