### PR TITLE
Fix rosetta empty peer ip

### LINKED ISSUE #2502: Rosetta API missing node IPs
### Description

Rosetta API `/network/status` returns peer IPs as empty string. Updating Rosetta was missed during the addition of `address_book_service_endpoint`.

### Steps to reproduce

`curl -sL -d '{"network_identifier": {"blockchain":"Hedera","network":"integration","sub_network_identifier":{"network":"shard 0 realm 0"}}}' "http://localhost:5700/network/status"`

```json
{
   "current_block_identifier":{
      "index":1198868,
      "hash":"0xc30186dc7e80574d154bab7d055943b867b7bf8de349ff6d6bbcd460ace4ce6fd26e0ac2684b5915f6b001472520e56d"
   },
   "current_block_timestamp":1630705896524,
   "genesis_block_identifier":{
      "index":0,
      "hash":"0x658f113697fcefc37ceae862b03484f5b157e1e7b2e9e4eadce89df5e5452d3ed337611dc53b7c93d88e44d3d1c2af74"
   },
   "peers":[
      {
         "peer_id":"0.0.3",
         "metadata":{
            "ip":"",
            "port":0
         }
      },
      {
         "peer_id":"0.0.4",
         "metadata":{
            "ip":"",
            "port":0
         }
      },
      {
         "peer_id":"0.0.5",
         "metadata":{
            "ip":"",
            "port":0
         }
      },
      {
         "peer_id":"0.0.6",
         "metadata":{
            "ip":"",
            "port":0
         }
      },
      {
         "peer_id":"0.0.7",
         "metadata":{
            "ip":"",
            "port":0
         }
      },
      {
         "peer_id":"0.0.8",
         "metadata":{
            "ip":"",
            "port":0
         }
      }
   ]
}
```

### Additional context

_No response_

### Hedera network

other

### Version

v0.39.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the empty peer ip in rosetta `/network/status` query response.

- query address book related tables for the current node info with service endpoints

**Related issue(s)**:

Fixes #2502 

**Notes for reviewer**:

This is the response for testnet:

```json
{
    "current_block_identifier": {
        "index": 11900315,
        "hash": "0x4585bb295f0cebbee3ec6639b0c309a7068682ebfa49b7b594175f648235a055b13edb6a12ef55e327c88588c39d6981"
    },
    "current_block_timestamp": 1631722618809,
    "genesis_block_identifier": {
        "index": 0,
        "hash": "0x4a7eed88145253eca01a6b5995865b68b041923772d0e504d2ae5fbbf559b68b397adfce5c52f4fa8acec860e6fbc395"
    },
    "peers": [
        {
            "peer_id": "0",
            "metadata": {
                "account_id": "0.0.3",
                "endpoints": [
                    "138.91.142.219:50211",
                    "34.94.106.61:50211",
                    "50.18.132.211:50211"
                ]
            }
        },
        {
            "peer_id": "1",
            "metadata": {
                "account_id": "0.0.4",
                "endpoints": [
                    "3.212.6.13:50211",
                    "35.237.119.55:50211",
                    "52.168.76.241:50211"
                ]
            }
        },
        {
            "peer_id": "2",
            "metadata": {
                "account_id": "0.0.5",
                "endpoints": [
                    "35.245.27.193:50211",
                    "40.79.83.124:50211",
                    "52.20.18.86:50211"
                ]
            }
        },
        {
            "peer_id": "3",
            "metadata": {
                "account_id": "0.0.6",
                "endpoints": [
                    "34.83.112.116:50211",
                    "52.183.45.65:50211",
                    "54.70.192.33:50211"
                ]
            }
        },
        {
            "peer_id": "4",
            "metadata": {
                "account_id": "0.0.7",
                "endpoints": [
                    "13.64.181.136:50211",
                    "34.94.160.4:50211",
                    "54.176.199.109:50211"
                ]
            }
        },
        {
            "peer_id": "5",
            "metadata": {
                "account_id": "0.0.8",
                "endpoints": [
                    "13.78.238.32:50211",
                    "34.106.102.218:50211",
                    "35.155.49.147:50211"
                ]
            }
        },
        {
            "peer_id": "6",
            "metadata": {
                "account_id": "0.0.9",
                "endpoints": [
                    "34.133.197.230:50211",
                    "52.14.252.207:50211",
                    "52.165.17.231:50211"
                ]
            }
        }
    ]
}
```
**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rosetta/app/persistence/address_book_entry.go [hunk 1]
```diff
@@ -0,0 +1,87 @@
+/*-
```
Comment (xin-hedera) [inline hedera-mirror-rosetta/app/persistence/address_book_entry.go:1]: moved the source file to `hedera-mirror-rosetta/app/persistence/address_book_entry.go`

we should gradually change the structure to have a flat package / directory structure

File: hedera-mirror-rosetta/app/persistence/address_book_entry.go [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+                                    string_agg(
+                                      ip_address_v4 || ':' || port::text, ',' order by ip_address_v4, port
+                                    ) endpoints
+                                  from address_book_entry abe
+                                  left join address_book_service_endpoint abse on
+                                    abse.node_id = abe.node_id and
+                                    abse.consensus_timestamp =
+                                      (select max(consensus_timestamp) from address_book_service_endpoint)
+                                  where abe.consensus_timestamp =
+                                    (select max(consensus_timestamp) from address_book_entry)
```
Comment (steven-sheehy) [inline hedera-mirror-rosetta/app/persistence/address_book_entry.go:45]: We should filter for file_id = 0.0.101 as that is the client address book that traditionally carries the IPs. 0.0.102 historically doesn't have IPs but is now supposed to be considered the "complete address book" with all fields populated. But in practice that hasn't occurred yet. If you get the max you can get 102 which probably won't have IPs.

File: hedera-mirror-rosetta/app/persistence/address_book_entry.go [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+	log "github.com/sirupsen/logrus"
+	"gorm.io/gorm"
+)
+
+const (
+	latestNodeServiceEndpoints = `select
+                                    abe.node_id,
+                                    node_account_id, 
+                                    string_agg(
+                                      ip_address_v4 || ':' || port::text, ',' order by ip_address_v4, port
```
Comment (steven-sheehy) [inline hedera-mirror-rosetta/app/persistence/address_book_entry.go:37]: Is there some rule that metadata has to have string values? Or can we simply return a string list in the JSON? It seems like it's pretty open. If so, I'd prefer `"endpoints": ["10.0.0.1:50211", 10.0.0.2:50211"]`.

File: hedera-mirror-rosetta/app/persistence/address_book_entry.go [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+                                    ) endpoints
+                                  from address_book_entry abe
+                                  left join address_book_service_endpoint abse on
+                                    abse.node_id = abe.node_id and
+                                    abse.consensus_timestamp =
+                                      (select max(consensus_timestamp) from address_book_service_endpoint)
```
Comment (steven-sheehy) [inline hedera-mirror-rosetta/app/persistence/address_book_entry.go:43]: We shouldn't have two max selects from different tables as they can return data from different address books. Since you need to filter by file id, need to get the max 101 address_book first, then join that consensus timestamp with address_book_entry and endpoints.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-rosetta/app/persistence/address_book_entry.go (hunk 3 above)
Comment (xin-hedera) [reply hedera-mirror-rosetta/app/persistence/address_book_entry.go:37]: as long as the value struct can be JSON stringified. sure I'll change it to an array of strings

File: hedera-mirror-rosetta/app/persistence/address_book_entry.go (hunk 2 above)
Comment (xin-hedera) [reply hedera-mirror-rosetta/app/persistence/address_book_entry.go]: changed it to query address book 101 first, if no 101, resort to 102 as that's the case for partial mirror node which hasn't received address book updates yet

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
LGTM
