### PR TITLE
Round down fee in tinybars

### LINKED ISSUE #9942: Mirror and Consensus Nodes use different rounding strategies when converting gas fees from cents to tinybars
### Description

Mirror and Consensus Nodes use different rounding strategies when converting gas fees from cents to tinybars.
In particular, CN does rounding down while MN does `Math.round`, so if the value is **30.6** for example, MN will report **31** and the actual rate used by CN will be **30**.

### Steps to reproduce

Here some evidence of the situation.

```text
--------------- MAINNET

❯ curl --silent https://mainnet-public.mirrornode.hedera.com/api/v1/network/fees | jq
{
  "fees": [
    {
      "gas": 31,
      "transaction_type": "ContractCall"
    },
    {
      "gas": 31,
      "transaction_type": "ContractCreate"
    },
    {
      "gas": 31,
      "transaction_type": "EthereumTransaction"
    }
  ],
  "timestamp": "1731539031.252243998"
}

1731539031.252243998 = Wed Nov 13 2024 23:03:51 GMT+0000

https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.995584-1733889926-055379664

Sender pays 0.16800000ℏ
Gas consumed: 560,000
560,000 * 30 = 16800000 tinybars = 0.16800000ℏ

--------------- TESTNET

❯ curl --silent https://testnet.mirrornode.hedera.com/api/v1/network/fees | jq
{
  "fees": [
    {
      "gas": 31,
      "transaction_type": "ContractCall"
    },
    {
      "gas": 31,
      "transaction_type": "ContractCreate"
    },
    {
      "gas": 31,
      "transaction_type": "EthereumTransaction"
    }
  ],
  "timestamp": "1733335386.501909996"
}

1733335386.501909996 = 	Wed Dec 04 2024 18:03:06 GMT+0000

https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.4441206-1733890133-741513632

Sender pays 0.02769420ℏ
Gas consumed 92,314
92,314 * 30 = 2769420 tinybars = 0.02769420ℏ

--------------- PREVIEWNET

❯ curl --silent https://previewnet.mirrornode.hedera.com/api/v1/network/fees | jq
{
  "fees": [
    {
      "gas": 71,
      "transaction_type": "ContractCall"
    },
    {
      "gas": 71,
      "transaction_type": "ContractCreate"
    },
    {
      "gas": 71,
      "transaction_type": "EthereumTransaction"
    }
  ],
  "timestamp": "1733860615.738043910"
}

1733860615.738043910 = Tue Dec 10 2024 19:56:55 GMT+0000
	
https://previewnet.mirrornode.hedera.com/api/v1/transactions/0.0.902-1733807887-715139894

Sender pays 0.06024776ℏ
Gas consumed 84,856
92,314 * 71 = 6024776 tinybars = 0.06024776ℏ
```

### Additional context

_No response_

### Hedera network

mainnet, testnet, previewnet

### Version

v0.119.0

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the inconsistent fee issue

- Round down when converting gas price to fee in tinybars

**Related issue(s)**:

Fixes #9942 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/utils.js [hunk 1]
```diff
@@ -1622,22 +1622,18 @@ const conflictingPathParam = (req, paramName, possibleConflicts = []) => {
...
- * @returns {number|null} `null` if the gasPrice cannot be converted. The minimum `number` returned is 1
+ * @param {number} gasPrice - gas price
+ * @param {number} hbars - equivalent hbars from exchange rate
+ * @param {number} cents - equivalent cents from exchange rate
+ * @returns {BigInt|null} `null` if the gasPrice cannot be converted. The minimum value returned is 1n
  */
-const convertGasPriceToTinyBars = (gasPrice, hbarsPerTinyCent, centsPerHbar) => {
-  if ([gasPrice, hbarsPerTinyCent, centsPerHbar].some((n) => !_.isNumber(n))) {
+const convertGasPriceToTinyBars = (gasPrice, hbars, cents) => {
+  if ([gasPrice, hbars, cents].some((n) => !_.isNumber(n))) {
```
Comment (edwin-greene) [inline hedera-mirror-rest/utils.js:1631]: Can we add a check for divide by zero, for the `cents` value

Comment (xin-hedera) [reply hedera-mirror-rest/utils.js:1631]: sure

**Review by edwin-greene — APPROVED** [review]
Looks good to me

**Review by steven-sheehy — APPROVED** [review]
