### PR TITLE
Fix system precompile tests for modularized

### LINKED ISSUE #10088: Fix `ContractCallSystemPrecompileTest` test suite
Fix failing tests for `ContractCallSystemPrecompileTest` using the modularized EVM

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:
This PR fixes all failing tests in `ContractCallSystemPrecompileTest`.

Mono logic expects calls with value against exhange rate and prng to fail with CONTRACT_REVERT_EXECUTED.

In modularized code this was changed from CONTRACT_REVERT_EXECUTED to INVALID_CONTRACT_ID in this [PR](https://github.com/hashgraph/hedera-services/pull/14843/files#diff-96aa7ce2c35096ea838d8b25fc11a5bce2863e9641f26af78690e80e9f93fe7a)

Fixes #10088

**Notes for reviewer**:
3361 tests completed, 55 failed, 6 skipped

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java [hunk 1]
```diff
@@ -52,8 +53,11 @@ void exchangeRatePrecompileTinybarsToTinycentsTestEthCall() throws Exception {
     @Test
     void exchangeRatePrecompileTinycentsToTinybarsTestEthCallAndEstimateWithValueRevertExecution() {
         final var contract = testWeb3jService.deploy(ExchangeRatePrecompile::deploy);
+        testWeb3jService.setSender(getAddressFromEntity(treasuryEntity));
```
Comment (kselveliev) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java:56]: This is needed because if we do not set sender and the call is with value we have the following logic in TransactionExecutionService -> 
 ```
if (params.getSender().canonicalAddress().isZero() && params.getValue() == 0L) {
            // Set a default account to keep the sender parameter optional.
            return TREASURY_ACCOUNT_ID;
 }
```
And we are going to get into PAYER_ACCOUNT_NOT_FOUND

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java [hunk 2]
```diff
@@ -63,8 +67,11 @@ void exchangeRatePrecompileTinycentsToTinybarsTestEthCallAndEstimateWithValueRev
     @Test
     void exchangeRatePrecompileTinybarsToTinycentsTestEthCallAndEstimateWithValueRevertExecution() {
         final var contract = testWeb3jService.deploy(ExchangeRatePrecompile::deploy);
+        testWeb3jService.setSender(getAddressFromEntity(treasuryEntity));
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java:70]: We have a declared constant that can be used directly - `TREASURY_ADDRESS`.

Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java]: Ahh yes didn't see that, addressed

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
