### PR TITLE
Long overflow on CryptoAddClaim processing (#263)

### LINKED ISSUE #263: Long overflow on CryptoAddClaim processing
**Detailed Description**
CryptoAddClaim TransactionRecords received by the mirror-node contain incorrect consensus timestamp and overflow a java long on conversion to the mirror-node's timestamp format.

The incoming (protobuf) consensus seconds appears to actually be milliseconds and the nanos value is empty. This results in a long overflow on conversion to mirror-node's nanos_timestamp type.

**Expected Behavior**
Handle this exceptional case without storing the overflowed value in the database (use safe math functions and cleanly handle the error when there is overflow).

**Environment:**
- mirror-node: v0.1.2
- services-hedera: OA-rc6

**Additional Context**
testnet data around 1568376750 unix timestamp (Friday, September 13, 2019 12:12:30 PM GMT), type CryptoAddClaim.

### PR DESCRIPTION
**Pull request by apeksharma**
**Detailed description**:
Use safe math to detect long and throw exception when long overflow happens

**Which issue(s) this PR fixes**:
Fixes #263 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by apeksharma** [comment]
Added to the mentioned doc and added unit test.

**Comment by mike-burrage-hedera** [comment]
@apeksharma Did you forget to commit and push?

File: src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java [hunk 1]
```diff
@@ -285,10 +285,23 @@ public static void storeRecord(Transaction transaction, TransactionRecord txReco
...
-		final long validStartNs = Utility.convertInstantToNanos(Instant.ofEpochSecond(vs.getSeconds(), vs.getNanos()));
-		final var c = txRecord.getConsensusTimestamp();
-		final long consensusNs = Utility.convertInstantToNanos(Instant.ofEpochSecond(c.getSeconds(), c.getNanos()));
+        final var vs = transactionID.getTransactionValidStart();
+        final var c = txRecord.getConsensusTimestamp();
+        long validStartNs;
+        long consensusNs;
+
+        try {
+            validStartNs = Utility.convertInstantToNanos(Instant.ofEpochSecond(vs.getSeconds(), vs.getNanos()));
```
Comment (Nana-EC) [inline src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java]: I feel like you could overload Utility.convertInstantToNanos() to just take vs. Inside the method you can call Instant.ofEpochSecond().

**Comment by mike-burrage-hedera** [comment]
@apeksharma I see you added an integration test. Where are the unit tests of that Utility function?

File: src/main/java/com/hedera/utilities/Utility.java [hunk 2]
```diff
@@ -590,26 +590,26 @@ public static boolean greaterThanSuperMajorityNum(long n, long N) {
...
-	 * @param seconds
-	 * @param nanos
-	 * @return
-	 */
-    public static Long timeStampInNanos(long seconds, int nanos) {
-	  return seconds * SCALAR + nanos;
+    /**
+     * Converts time in (second, nanos) to time in only nanos.
+     */
+    public static Long convertToNanos(long second, long nanos) {
```
Comment (apeksharma) [inline src/main/java/com/hedera/utilities/Utility.java]: @Nana-EC  if i interpreted your suggestion right (there were probably some missing words), you were suggesting directly taking (sec, nanos) and convert to Instant in the overloaded fn? If so, let me mark it as resolved.

**Comment by apeksharma** [comment]
> @apeksharma I see you added an integration test. Where are the unit tests of that Utility function?
> Unit tests invoking and verifying the
> 
> Unit tests invoking only that utility function. Null, exception thrown, valid values.

Looks like there are none for existing functionality like valid values and null. Will add them too when adding one for exception.

File: src/main/java/com/hedera/utilities/Utility.java [hunk 3]
```diff
@@ -590,51 +590,37 @@ public static boolean greaterThanSuperMajorityNum(long n, long N) {
 		return n > N * 2 / 3.0;
 	}
 
-	/**
-	 * Convert an Instant to a Long type timestampInNanos
-	 * @param instant
-	 * @return
-	 */
-	public static Long convertInstantToNanos(Instant instant) {
-		if (instant == null) {
```
Comment (apeksharma) [inline src/main/java/com/hedera/utilities/Utility.java]: Removed this check because it's useless, if 'instant' is really null, auto-unboxing of returned null Long to long will result in NPE anyway.
timeStampToNanos() fns below is same.

File: src/main/java/com/hedera/utilities/Utility.java [hunk 4]
```diff
@@ -590,51 +590,37 @@ public static boolean greaterThanSuperMajorityNum(long n, long N) {
...
     }
 
 	/**
 	 * Convert Timestamp to a Long type timeStampInNanos
-	 * @param TimeStamp
-	 * @return
 	 */
     public static Long timeStampInNanos(Timestamp timestamp) {
-	  return timestamp.getSeconds() * SCALAR + timestamp.getNanos();
+        try {
```
Comment (apeksharma) [inline src/main/java/com/hedera/utilities/Utility.java]: added overflow check to timestamp too here.
