### PR TITLE
Fix incorrect column default in EntityMetadataRegistry 

### LINKED ISSUE #4265: Importer fails to insert a token due to incorrect default value of token type
### Description

Importer failed to insert a token from a `TokenCreate` transaction because the sql generated somehow set `CONTRACT` as `token.type` default value

```
Aug 10 16:51:45 mirrornode-stable-testnet-failover-parser-1 java[13479]: 2022-08-10T10:51:45.281-0600 ERROR scheduling-2 c.h.m.i.p.r.RecordFileParser Error parsing file 2022-08-10T16_42_40.372679003Z.rcd after 33.19 ms com.hedera.mirror.importer.exception.ParserException: Error copying 1 items to table token_temp
        at com.hedera.mirror.importer.parser.batch.BatchInserter.persist(BatchInserter.java:112)
        at com.hedera.mirror.importer.parser.batch.CompositeBatchPersister.persist(CompositeBatchPersister.java:62)
        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.executeBatches(SqlEntityListener.java:291)
        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.onEnd(SqlEntityListener.java:209)
        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.onEnd(SqlEntityListener.java:88)
        at com.hedera.mirror.importer.parser.record.RecordFileParser.doParse(RecordFileParser.java:142)
        at com.hedera.mirror.importer.parser.record.RecordFileParser.doParse(RecordFileParser.java:52)
        at com.hedera.mirror.importer.parser.AbstractStreamFileParser.parse(AbstractStreamFileParser.java:79)
        at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:117)
        at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:52)
        at com.hedera.mirror.importer.parser.record.RecordFileParser$$FastClassBySpringCGLIB$$8b9310db.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:97)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:133)
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:160)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.hedera.mirror.importer.parser.record.RecordFileParser$$EnhancerBySpringCGLIB$$d334e546.parse(<generated>)
        at com.hedera.mirror.importer.config.MessagingConfiguration.lambda$integrationFlow$1(MessagingConfiguration.java:107)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.integration.handler.LambdaMessageProcessor.processMessage(LambdaMessageProcessor.java:105)
        at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:105)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
        at org.springframework.integration.endpoint.PollingConsumer.handleMessage(PollingConsumer.java:158)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:475)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:461)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:413)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:348)
        at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
        at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
        at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$5(AbstractPollingEndpoint.java:341)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.hedera.mirror.importer.exception.ParserException: Error copying 1 items to table token
        at com.hedera.mirror.importer.parser.batch.BatchUpserter.persistItems(BatchUpserter.java:111)
        at com.hedera.mirror.importer.parser.batch.BatchInserter.persist(BatchInserter.java:108)
        ... 54 more
Caused by: org.postgresql.util.PSQLException: ERROR: invalid input value for enum token_type: "CONTRACT"
  Position: 1881
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at com.hedera.mirror.importer.parser.batch.BatchUpserter.insertToFinalTable(BatchUpserter.java:117)
        at com.hedera.mirror.importer.parser.batch.BatchUpserter.insertItems(BatchUpserter.java:160)
        at com.hedera.mirror.importer.parser.batch.BatchUpserter.persistItems(BatchUpserter.java:103)
        ... 55 more
```

The generated sql to insert token:

```sql
with existing as (
  select e.created_timestamp as e_created_timestamp,e.decimals as e_decimals,e.fee_schedule_key as e_fee_schedule_key,e.freeze_default as e_freeze_default,e.freeze_key as e_freeze_key,e.initial_supply as e_initial_supply,e.kyc_key as e_kyc_key,e.max_supply as e_max_supply,e.modified_timestamp as e_modified_timestamp,e.name as e_name,e.pause_key as e_pause_key,e.pause_status as e_pause_status,e.supply_key as e_supply_key,e.supply_type as e_supply_type,e.symbol as e_symbol,e.token_id as e_token_id,e.total_supply as e_total_supply,e.treasury_account_id as e_treasury_account_id,e.type as e_type,e.wipe_key as e_wipe_key, t.*
  from token_temp t
  left join token e on e.token_id = t.token_id
)
insert into token (created_timestamp,decimals,fee_schedule_key,freeze_default,freeze_key,initial_supply,kyc_key,max_supply,modified_timestamp,name,pause_key,pause_status,supply_key,supply_type,symbol,token_id,total_supply,treasury_account_id,type,wipe_key)
select coalesce(created_timestamp, e_created_timestamp, null),coalesce(decimals, e_decimals, null),coalesce(fee_schedule_key, e_fee_schedule_key, null),coalesce(freeze_default, e_freeze_default, false),coalesce(freeze_key, e_freeze_key, null),coalesce(initial_supply, e_initial_supply, null),coalesce(kyc_key, e_kyc_key, null),coalesce(max_supply, e_max_supply, '9223372036854775807'),coalesce(modified_timestamp, e_modified_timestamp, null),coalesce(name, e_name, null),coalesce(pause_key, e_pause_key, null),coalesce(pause_status, e_pause_status, 'NOT_APPLICABLE'),coalesce(supply_key, e_supply_key, null),coalesce(supply_type, e_supply_type, 'INFINITE'),coalesce(symbol, e_symbol, null),coalesce(token_id, e_token_id, null),case when total_supply >= 0 then total_supply else e_total_supply + coalesce(total_supply, 0) end,coalesce(treasury_account_id, e_treasury_account_id, null),coalesce(type, e_type, 'CONTRACT'),coalesce(wipe_key, e_wipe_key, null)
from existing
where coalesce(created_timestamp, e_created_timestamp) is not null
on conflict (token_id)
do update set fee_schedule_key = excluded.fee_schedule_key,freeze_key = excluded.freeze_key,kyc_key = excluded.kyc_key,modified_timestamp = excluded.modified_timestamp,name = excluded.name,pause_key = excluded.pause_key,pause_status = excluded.pause_status,supply_key = excluded.supply_key,symbol = excluded.symbol,total_supply = excluded.total_supply,treasury_account_id = excluded.treasury_account_id,wipe_key = excluded.wipe_key
```

### Steps to reproduce

need to figure it out

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.61.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the incorrect column default in EntityMetadataRegistry which causes the importer unable to processing transactions when transactions happen in some specific orders.

**Related issue(s)**:

Fixes #4265

**Notes for reviewer**:

The bug is triggered if since the start of the importer, during a record file parsing (in a database transaction), `Contract` metadata is loaded first, any other domain class metadata loaded in the same db transaction, for which if there is a `type` column, its default is set to `'CONTRACT'`. This is because the entity class `InformationSchemaColumns` has `columnName` as its `Id` column, EntityManager cache is in play so querying any other `type` column will return the cached entity object.
 
**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/EntityMetadataRegistryTest.java [hunk 1]
```diff
@@ -83,6 +88,31 @@ void lookup() {
...
     }
 
+    @Test
+    @Transactional
+    void lookupSameColumnNameFromMultipleDomainClasses() {
+        // The test case reproduces the issue in the ticket https://github.com/hashgraph/hedera-mirror-node/issues/4265
+        // With the entity manager cache, if we look up two domain classes metadata in the same session, for columns with
+        // the same name, the defaults of the first domain class will override those of the second. For example,
+        // without the fix, entity.type's default will be "'FUNGIBLE_COMMON'"
+        // given, when
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/EntityMetadataRegistryTest.java:98]: nit: In the future, prefer to add comments to javadocs on method.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good
