### PR TITLE
Fix error on calls with value with not existing sender alias

### LINKED ISSUE #9301: `Internal Server Error` on POST `api/v1/contracts/call` with non-existent `from`
### Description

If we try to execute a contract call (or estimate gas) with a value within the body and a non-existent `from,` an internal server error is thrown.

### Steps to reproduce

Execute a POST request to `/api/v1/contracts/call` with a body like this:
```
{
    "from": "0x6b175474e89094c44da98b954eedeac495271d0f", // non-existent from
    "to": "0xffc7d3ff264c838ad75167e64d043794bf1bd57c", // existent to
    "data": "0xddf363d7", // random selector
    "value": 1,
    "gasPrice": 710000000000,
    "estimate": false,
    "block": "latest"
}
```

### Additional context

Trace log from the mirror-node-web3
```
2024-09-09T06:52:32.284Z ERROR tomcat-handler-861 c.h.m.w.c.GenericControllerAdvice Generic error:  java.lang.NullPointerException: Cannot invoke "org.hyperledger.besu.evm.account.MutableAccount.decrementBalance(org.hyperledger.besu.datatypes.Wei)" because "senderAccount" is null
	at org.hyperledger.besu.evm.processor.MessageCallProcessor.transferValue(MessageCallProcessor.java:128)
	at org.hyperledger.besu.evm.processor.MessageCallProcessor.start(MessageCallProcessor.java:72)
	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmMessageCallProcessor.start(HederaEvmMessageCallProcessor.java:79)
	at com.hedera.mirror.web3.evm.contracts.execution.AbstractEvmMessageCallProcessor.start(AbstractEvmMessageCallProcessor.java:65)
	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:196)
	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.process(HederaEvmTxProcessor.java:209)
	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.execute(HederaEvmTxProcessor.java:154)
	at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessorImpl.execute(MirrorEvmTxProcessorImpl.java:105)
	at com.hedera.mirror.web3.service.ContractCallService.doProcessCall(ContractCallService.java:109)
	at com.hedera.mirror.web3.service.ContractCallService.callContract(ContractCallService.java:102)
	at com.hedera.mirror.web3.service.ContractExecutionService.lambda$processCall$0(ContractExecutionService.java:67)
	at com.hedera.mirror.web3.common.ContractCallContext.lambda$run$0(ContractCallContext.java:83)
	at java.base/java.lang.ScopedValue$Carrier$CallableAdapter.call(Unknown Source)
	at java.base/jdk.internal.vm.ScopedValueContainer.callWithoutScope(Unknown Source)
	at java.base/jdk.internal.vm.ScopedValueContainer.call(Unknown Source)
	at java.base/java.lang.ScopedValue$Carrier.get(Unknown Source)
	at java.base/java.lang.ScopedValue.getWhere(Unknown Source)
	at com.hedera.mirror.web3.common.ContractCallContext.run(ContractCallContext.java:83)
	at com.hedera.mirror.web3.service.ContractExecutionService.processCall(ContractExecutionService.java:54)
	at com.hedera.mirror.web3.controller.ContractController.call(ContractController.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at com.hedera.mirror.web3.config.MetricsFilter.doFilterInternal(MetricsFilter.java:68)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at com.hedera.mirror.web3.config.LoggingFilter.doFilterInternal(LoggingFilter.java:57)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at java.base/java.lang.VirtualThread.run(Unknown Source)

2024-09-09T06:52:32.286Z  WARN tomcat-handler-861 c.h.m.w.c.LoggingFilter 172.18.0.1 POST /api/v1/contracts/call in 31 ms: 500 Cannot invoke "org.hyperledger.besu.evm.account.MutableAccount.decrementBalance(org.hyperledger.besu.datatypes.Wei)" because "senderAccount" is null - {"from":"0x6b175474e89094c44da98b954eedeac495271d0f","to":"0xffc7d3ff264c838ad75167e64d043794bf1bd57c","data":"0xddf363d7","value":1,"gasPrice":710000000000,"estimate":false,"block":"latest"} 
```

### Hedera network

other

### Version

latest

### Operating system

None

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:
This PR aims to fix null error when a contract call is made with value and evm address as a sender. Where the evm address is not existing.

Couple of scenarios:

Currently when an empty from is passed. 
We are creating an Account.getDummySenderAccount(). that does not have alias

If the from is a not existing long zero address
We are creating an Account.getDummySenderAccount(long zero address) from it without alias.

**In the cases where evm address alias was passed as a from parameter. We were still creating a dummy account without alias. And subsequent account retrievals by alias were returning null causing the error since we did not create the account with that alias.**

**This pr adds a check.
Check if the from is an evm canonical address. Create the dummy account with that alias.
Otherwise create the dummy account as before without alias.**

This PR modifies:
`MirrorEvmTxProcessorImpl` - add a check to see is the from address is not existing and also a canonical evm address and it it is creates the dummy account with that alias.

`Account`.java - created new methods that creates dummy account with and alias

`MirrorEvmTxProcessorTest` - adds a test case for the error scenario.

`ContractCallServiceTest` - adds a test case for the error scenario.

**Related issue(s)**:

Fixes #9301

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by steven-sheehy — APPROVED** [review]
LGTM

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorTest.java [hunk 1]
```diff
@@ -214,6 +228,32 @@ void assertSuccessExecution(boolean isEstimate) {
                 .returns(receiver.canonicalAddress(), r -> r.getRecipient().orElseThrow());
     }
 
+    @ParameterizedTest
+    @MethodSource("provideIsEstimateParameters")
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorTest.java:232]: The parameters are just booleans - we can simplify this to use a `@ValueSource(booleans = {true, false})` directly.

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java [hunk 2]
```diff
@@ -39,12 +39,9 @@
...
  * <p>
- * Differences with the original:
- * 1. Removed fields like memo, key, isReceiverSigRequired, isSmartContract
- * 2. Added field accountAddress for convenience
- * 3. Changed collection types to SortedMap and SortedSet
- * 4. Added constructors and set methods for creating new instances and achieve immutability
- * 6. Added factory method that returns empty instance
+ * Differences with the original: 1. Removed fields like memo, key, isReceiverSigRequired, isSmartContract 2. Added
+ * field accountAddress for convenience 3. Changed collection types to SortedMap and SortedSet 4. Added constructors and
+ * set methods for creating new instances and achieve immutability 6. Added factory method that returns empty instance
```
Comment (bilyana-gospodinova) [inline hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java:44]: The 5th bullet point is missing. Perhaps use the PR to rename it.

**Review by bilyana-gospodinova — DISMISSED** [review]
LGTM

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorTest.java (hunk 1 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorTest.java]: Comment addressed

File: hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java (hunk 2 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java]: Comment addressed

**Review by steven-sheehy — APPROVED** [review]
