### PR TITLE
Fixing repeatable partitions to use a case-insensitive map

### LINKED ISSUE #4984: Repeatable java migration should accept case insensitive property names
### Description

Repeatable java migrations support a generic property map, however, the implementation reads the properties from the map using a case sensitive key. it's a problem when properties are set by env variables since the convention is env vars are named in all upper case.

### Steps to reproduce

Run a repeatable java migration with custom properties specified by env variables.

### Additional context

_No response_

### Hedera network

other

### Version

v0.71.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by mgoelswirlds**
**Description**:

This PR allows repeatable java migrations to support case insensitive keys for its  generic property map.

This PR modifies:
* Change property map to TreeMap to allow case insensitivity.

**Related issue(s)**:

Fixes #4984

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java [hunk 1]
```diff
@@ -33,8 +34,12 @@ abstract class RepeatableMigration extends MirrorBaseJavaMigration {
     protected final MigrationProperties migrationProperties;
 
     protected RepeatableMigration(Map<String, MigrationProperties> migrationPropertiesMap) {
+        Map<String, MigrationProperties> treeMap = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
+        for (Map.Entry<String, MigrationProperties> kvEntry : migrationPropertiesMap.entrySet()) {
+            treeMap.put(kvEntry.getKey(), kvEntry.getValue());
+        }
         String propertiesKey = StringUtils.uncapitalize(getClass().getSimpleName());
-        migrationProperties = migrationPropertiesMap.getOrDefault(propertiesKey, DEFAULT_MIGRATION_PROPERTIES);
+        migrationProperties = treeMap.getOrDefault(propertiesKey, DEFAULT_MIGRATION_PROPERTIES);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java:42]: should revert the above changes, instead, change `MirrorProperties.migration` to the case insensitive map.

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java (hunk 1 above)
Comment (mgoelswirlds) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java:42]: So do we want to do it for all migration and not just repeatable?

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java:42]: `MirrorProperties.migration` is only used by repeatable migrations

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java:42]: Should we consider having both case insensitive?

Comment (mgoelswirlds) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java:42]: So TreeMap doesn't work as is for MirrorProperties.migration, since spring is overwriting it, with its own TreeMap without the CASE_INSENSITIVE comparator. So I am working on using another type of map there. I think it might become redundant if we do it in both places right? though I am not sure why RepeatableMigration wouldn't suffice.

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/RepeatableMigration.java:42]: I don't think it's redundant, they are both `Map<String, *>` at different levels.

One is at `hedera.mirror.importer.migration`, the other is at `hedera.mirror.importer.migration.someMigration.params`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java [hunk 2]
```diff
@@ -54,7 +53,7 @@ public class MirrorProperties {
     private boolean leaderElection = false;
 
     @NotNull
-    private Map<String, MigrationProperties> migration = Collections.emptyMap();
+    private CaseInsensitiveMap<String, MigrationProperties> migration = new CaseInsensitiveMap<>();
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java:56]: this and the other place can be just
```suggestion
    private Map<String, MigrationProperties> migration = new CaseInsensitiveMap<>();
```

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BlockNumberMigrationTest.java [hunk 3]
```diff
@@ -59,7 +59,7 @@ void setup() {
 
     @Test
     void checksum() {
-        assertThat(blockNumberMigration.getChecksum()).isEqualTo(4);
+        assertThat(blockNumberMigration.getChecksum()).isEqualTo(5);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BlockNumberMigrationTest.java:62]: shouldn't test it here since the purposes of `checksum` test is to verify that we bump up the checksum for the `BlockNumberMigration` in the main `application.yaml` whenever we change the migration

instead, you should add this to the test `application.yaml`:

```yaml
hedera:
  mirror:
    importer:
      migration:
        DUMMYMIGRATION:
          checksum: 2 
```

and have a new integration test class in which you have an inner class `class DummyMigration extends RepeatableMigrationextends RepeatableMigration`, then have a `checksum` test to verify the checksum is correct

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/RepeatableMigrationTest.java [hunk 4]
```diff
@@ -58,6 +59,21 @@ void checksum() {
                 .returns(null, TestMigration::getVersion);
     }
 
+    @Test
+    void caseInsensitivity() {
+        var migrationProperties = new MigrationProperties();
+        migrationProperties.setChecksum(4);
+        CaseInsensitiveMap<String, MigrationProperties> migrationMap = new CaseInsensitiveMap<>();
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/RepeatableMigrationTest.java:66]: need also test `MigrationProperties.params` can do case insensitive lookup

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good to me.
