### PR TITLE
Fix monitor validation issues

### LINKED ISSUE #2642: Parallelize monitor node validation
### Problem

The monitor logic that revalidates nodes periodically can be slow, especially as the list of nodes grows.  This can delay the time it takes to adjust to unhealthy nodes, as the monitor only updates the list of valid nodes after every node has gone through the validation process.

### Solution

* Parallelize the validation process so that we can validated many nodes at once.
* As soon as a single node is validated it should be used for transaction publishing immediately and not wait for other nodes to complete

### Alternatives

_No response_

### LINKED ISSUE #2914: Monitor subscription halts during node validation
### Description

The mirror node APIs periodically return HTTP code 502 and fail to return a response. The monitor dashboard shows these errors and would trigger an alert indicating mainnet-public is down. This would seem to only occur when one of the two clusters was down for maintenance.

Investigation revealed that the java monitor that provides cluster health checking was showing API subscription rates drop to zero for a few minutes exactly every 2 hours. This coincided with logs indicating the node revalidation routine was running. Disabling the node validation made the errors go away.

### Steps to reproduce

1. Bring one of the two mainnet-public clusters down for maintenance.
2. Wait a few hours

### Additional context

Screen Shot 2021-11-29 at 16 48 38

### Hedera network

mainnet

### Version

v0.43.2

### Operating system

_No response_

### LINKED ISSUE #3157: Monitor takes too long to validate a down node
### Description

When a main node is down and access to the proxy is cut off (like 0.0.24 on mainnet now), the SDK's behavior used by the monitor can cause a single node's validation to take up to 45 minutes. This should really only take 10 seconds or less.

### Steps to reproduce

1. Disable access to a main node via its proxy
2. Start the monitor with validation enabled

### Additional context

```console
2022-01-13T19:02:45.373-0600 INFO resolver-2 c.h.m.m.p.TransactionPublisher Validating nodes
2022-01-13T19:03:05.581-0600 INFO main c.h.m.m.MonitorApplication Started MonitorApplication in 69.495 seconds (JVM running for 80.106)
2022-01-13T19:06:03.432-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 250 ms after failure during attempt #1: UNAVAILABLE
2022-01-13T19:08:14.489-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 500 ms after failure during attempt #2: UNAVAILABLE
2022-01-13T19:10:25.567-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 1000 ms after failure during attempt #3: UNAVAILABLE
2022-01-13T19:12:36.633-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 2000 ms after failure during attempt #4: UNAVAILABLE
2022-01-13T19:12:38.634-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #5 for 1642122758634 ms
2022-01-13T19:14:47.709-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 4000 ms after failure during attempt #5: UNAVAILABLE
2022-01-13T19:14:49.709-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #6 for 1642122891709 ms
2022-01-13T19:16:58.778-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #6: UNAVAILABLE
2022-01-13T19:17:00.779-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #7 for 1642123026779 ms
2022-01-13T19:19:09.849-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #7: UNAVAILABLE
2022-01-13T19:19:11.849-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #8 for 1642123157849 ms
2022-01-13T19:21:20.921-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #8: UNAVAILABLE
2022-01-13T19:21:22.922-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #9 for 1642123288922 ms
2022-01-13T19:23:31.993-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #9: UNAVAILABLE
2022-01-13T19:23:33.994-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #10 for 1642123419994 ms
2022-01-13T19:25:43.074-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #10: UNAVAILABLE
2022-01-13T19:25:45.075-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #11 for 1642123551075 ms
2022-01-13T19:27:54.147-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #11: UNAVAILABLE
2022-01-13T19:27:56.147-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #12 for 1642123682147 ms
2022-01-13T19:30:05.209-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #12: UNAVAILABLE
2022-01-13T19:30:07.210-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #13 for 1642123813210 ms
2022-01-13T19:32:16.280-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #13: UNAVAILABLE
2022-01-13T19:32:18.281-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #14 for 1642123944281 ms
2022-01-13T19:34:27.353-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #14: UNAVAILABLE
2022-01-13T19:34:29.353-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #15 for 1642124075353 ms
2022-01-13T19:36:38.425-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #15: UNAVAILABLE
2022-01-13T19:36:40.426-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #16 for 1642124206425 ms
2022-01-13T19:38:49.497-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #16: UNAVAILABLE
2022-01-13T19:38:51.498-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #17 for 1642124337497 ms
2022-01-13T19:41:00.569-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #17: UNAVAILABLE
2022-01-13T19:41:02.570-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #18 for 1642124468569 ms
2022-01-13T19:43:15.742-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #18: UNAVAILABLE
2022-01-13T19:43:17.742-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #19 for 1642124603742 ms
2022-01-13T19:45:26.809-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #19: UNAVAILABLE
2022-01-13T19:45:28.809-0600 WARN resolver-2 c.h.h.s.TransferTransaction Using unhealthy node 0.0.24. Delaying attempt #20 for 1642124734809 ms
2022-01-13T19:47:37.882-0600 WARN resolver-2 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 8000 ms after failure during attempt #20: UNAVAILABLE
2022-01-13T19:47:39.892-0600 WARN resolver-2 c.h.m.m.p.TransactionPublisher Unable to validate node NodeProperties(accountId=0.0.24, host=34.89.103.38, port=50211):  com.hedera.hashgraph.sdk.MaxAttemptsExceededException: exceeded maximum attempts for request with last exception being\\n	at com.hedera.hashgraph.sdk.Executable.isAttemptGreaterThanMax(Executable.java:190)\\n	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:209)\\n	at com.hedera.hashgraph.sdk.Transaction.execute(Transaction.java:34)\\n	at com.hedera.mirror.monitor.publish.TransactionPublisher.validateNode(TransactionPublisher.java:225)\\n	at com.hedera.mirror.monitor.publish.TransactionPublisher.validateNodes(TransactionPublisher.java:191)\\n	at com.hedera.mirror.monitor.publish.TransactionPublisher.getClients(TransactionPublisher.java:156)\\n	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)\\n	at reactor.core.publisher.FluxReplay.connect(FluxReplay.java:1120)\\n	at reactor.core.publisher.FluxAutoConnectFuseable.subscribe(FluxAutoConnectFuseable.java:63)\\nat reactor.core.publisher.Mono.subscribe(Mono.java:4400)\\n	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)\\n	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)\\n	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)\\n	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)\\n	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)\\n	at io.micrometer.core.instrument.internal.TimedCallable.call(TimedCallable.java:46)\\n	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)\\n	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\\n	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\\n	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\\n	at java.base/java.lang.Thread.run(Unknown Source)\\nCaused by: io.grpc.StatusRuntimeException: UNAVAILABLE\\n	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)\\n	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)\\n	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:123)\\n	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:224)\\n	... 19 more\\nCaused by: java.net.ConnectException: Connection timed out (Connection timed out)\\n	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)\\n	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)\\n	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)\\n	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)\\n	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)\\n	at java.base/java.net.Socket.connect(Unknown Source)\\n	at java.base/java.net.Socket.connect(Unknown Source)\\n	at java.base/java.net.Socket.<init>(Unknown Source)\\n	at java.base/java.net.Socket.<init>(Unknown Source)\\n	at java.base/javax.net.DefaultSocketFactory.createSocket(Unknown Source)\\n	at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:558)\\n	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)\\n	... 3 more
```

### Hedera network

mainnet

### Version

v0.47.0

### Operating system

macOS

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:
* Add `hedera.mirror.monitor.nodeValidation.maxThreads=25` property
* Add `hedera.mirror.monitor.nodeValidation.requestTimeout=10s` property
* Add new mainnet nodes
* Bump `hedera-sdk-java` to 2.6.0 for monitor
* Change monitor to validate nodes in parallel
* Disable `hedera.mirror.test.acceptance.retrieveAddressBook` since it doesn't currently work with service endpoints
* Fix `EntityRecordItemListenerPerformanceCryptoTest` sporadically timing out
* Fix node validation blocking subscribe and re-enable it
* Fix node validation taking too long
* Workaround SDK bug with a modified `ManagedNode` class https://github.com/hashgraph/hedera-sdk-java/issues/855

**Related issue(s)**:

Fixes #2642
Fixes #2914
Fixes #3157

**Notes for reviewer**:
Acceptance tests had failures when used with SDK 2.6.0 so it's not updated

Log of the changes running against mainnet showing that total time to validate 22 nodes (including 3 down nodes) was around 6 seconds.

```console
2022-01-18T23:08:26.346-0600 INFO main c.h.m.m.s.g.GrpcClientSDK Connecting 1 clients to mainnet-public.mirrornode.hedera.com:443
2022-01-18T23:08:26.683-0600 INFO main c.h.m.m.s.r.RestSubscriber Connecting to mirror node https://mainnet-public.mirrornode.hedera.com:443/api/v1
2022-01-18T23:08:26.917-0600 INFO single-1 c.h.m.m.c.MonitorConfiguration Starting publisher flow
2022-01-18T23:08:26.962-0600 INFO parallel-45 c.h.m.m.c.MonitorConfiguration Starting subscribe flow
2022-01-18T23:08:26.976-0600 INFO parallel-45 c.h.m.m.s.g.GrpcClientSDK Starting 'hcs' scenario to client 0
2022-01-18T23:08:27.083-0600 INFO resolver-1 c.h.m.m.p.TransactionPublisher Starting node validation
2022-01-18T23:08:27.191-0600 INFO validator-51 c.h.m.m.p.TransactionPublisher Validating node 0.0.4
2022-01-18T23:08:27.191-0600 INFO validator-63 c.h.m.m.p.TransactionPublisher Validating node 0.0.9
2022-01-18T23:08:27.191-0600 INFO validator-66 c.h.m.m.p.TransactionPublisher Validating node 0.0.11
2022-01-18T23:08:27.191-0600 INFO validator-47 c.h.m.m.p.TransactionPublisher Validating node 0.0.3
2022-01-18T23:08:27.191-0600 INFO validator-56 c.h.m.m.p.TransactionPublisher Validating node 0.0.19
2022-01-18T23:08:27.191-0600 INFO validator-59 c.h.m.m.p.TransactionPublisher Validating node 0.0.21
2022-01-18T23:08:27.191-0600 INFO validator-57 c.h.m.m.p.TransactionPublisher Validating node 0.0.24
2022-01-18T23:08:27.192-0600 INFO validator-61 c.h.m.m.p.TransactionPublisher Validating node 0.0.12
2022-01-18T23:08:27.192-0600 INFO validator-46 c.h.m.m.p.TransactionPublisher Validating node 0.0.13
2022-01-18T23:08:27.192-0600 INFO validator-52 c.h.m.m.p.TransactionPublisher Validating node 0.0.18
2022-01-18T23:08:27.191-0600 INFO validator-50 c.h.m.m.p.TransactionPublisher Validating node 0.0.7
2022-01-18T23:08:27.192-0600 INFO validator-64 c.h.m.m.p.TransactionPublisher Validating node 0.0.20
2022-01-18T23:08:27.192-0600 INFO validator-65 c.h.m.m.p.TransactionPublisher Validating node 0.0.8
2022-01-18T23:08:27.191-0600 INFO validator-67 c.h.m.m.p.TransactionPublisher Validating node 0.0.17
2022-01-18T23:08:27.192-0600 INFO validator-49 c.h.m.m.p.TransactionPublisher Validating node 0.0.14
2022-01-18T23:08:27.192-0600 INFO validator-48 c.h.m.m.p.TransactionPublisher Validating node 0.0.16
2022-01-18T23:08:27.192-0600 INFO validator-58 c.h.m.m.p.TransactionPublisher Validating node 0.0.6
2022-01-18T23:08:27.192-0600 INFO validator-55 c.h.m.m.p.TransactionPublisher Validating node 0.0.22
2022-01-18T23:08:27.192-0600 INFO validator-62 c.h.m.m.p.TransactionPublisher Validating node 0.0.23
2022-01-18T23:08:27.192-0600 INFO validator-60 c.h.m.m.p.TransactionPublisher Validating node 0.0.15
2022-01-18T23:08:27.192-0600 INFO validator-54 c.h.m.m.p.TransactionPublisher Validating node 0.0.10
2022-01-18T23:08:27.192-0600 INFO validator-53 c.h.m.m.p.TransactionPublisher Validating node 0.0.5
2022-01-18T23:08:27.373-0600 WARN validator-57 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 250 ms after failure during attempt #1: UNAVAILABLE
2022-01-18T23:08:27.373-0600 WARN hedera-sdk-3 c.h.h.s.TopicMessageSubmitTransaction Retrying node 0.0.24 in 250 ms after failure during attempt #1: UNAVAILABLE
2022-01-18T23:08:27.603-0600 WARN validator-56 c.h.h.s.TransferTransaction Retrying node 0.0.19 in 250 ms after failure during attempt #1: UNAVAILABLE: HTTP status code 503
2022-01-18T23:08:27.614-0600 WARN validator-48 c.h.h.s.TransferTransaction Retrying node 0.0.16 in 250 ms after failure during attempt #1: UNAVAILABLE: HTTP status code 503
2022-01-18T23:08:27.874-0600 WARN validator-57 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 500 ms after failure during attempt #2: UNAVAILABLE
2022-01-18T23:08:27.994-0600 INFO main c.h.m.m.MonitorApplication Started MonitorApplication in 3.748 seconds (JVM running for 4.518)
2022-01-18T23:08:28.003-0600 INFO scheduling-1 c.h.m.m.p.PublishMetrics Scenario pinger published 0 transactions in 1s at 0.0/s. Errors: {ConnectException=1}
2022-01-18T23:08:28.215-0600 WARN validator-56 c.h.h.s.TransferTransaction Retrying node 0.0.19 in 500 ms after failure during attempt #2: UNAVAILABLE: HTTP status code 503
2022-01-18T23:08:28.241-0600 WARN validator-48 c.h.h.s.TransferTransaction Retrying node 0.0.16 in 500 ms after failure during attempt #2: UNAVAILABLE: HTTP status code 503
2022-01-18T23:08:28.881-0600 WARN validator-57 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 1000 ms after failure during attempt #3: UNAVAILABLE
2022-01-18T23:08:29.330-0600 WARN validator-56 c.h.h.s.TransferTransaction Retrying node 0.0.19 in 1000 ms after failure during attempt #3: UNAVAILABLE: HTTP status code 503
2022-01-18T23:08:29.368-0600 WARN validator-48 c.h.h.s.TransferTransaction Retrying node 0.0.16 in 1000 ms after failure during attempt #3: UNAVAILABLE: HTTP status code 503
2022-01-18T23:08:30.887-0600 WARN validator-57 c.h.h.s.TransferTransaction Retrying node 0.0.24 in 2000 ms after failure during attempt #4: UNAVAILABLE
2022-01-18T23:08:31.444-0600 WARN validator-56 c.h.h.s.TransferTransaction Retrying node 0.0.19 in 2000 ms after failure during attempt #4: UNAVAILABLE: HTTP status code 503
2022-01-18T23:08:31.463-0600 INFO validator-67 c.h.m.m.p.TransactionPublisher Validated node 0.0.17 successfully
2022-01-18T23:08:31.470-0600 INFO validator-62 c.h.m.m.p.TransactionPublisher Validated node 0.0.23 successfully
2022-01-18T23:08:31.491-0600 WARN validator-48 c.h.h.s.TransferTransaction Retrying node 0.0.16 in 2000 ms after failure during attempt #4: UNAVAILABLE: HTTP status code 503
2022-01-18T23:08:31.531-0600 INFO validator-51 c.h.m.m.p.TransactionPublisher Validated node 0.0.4 successfully
2022-01-18T23:08:31.535-0600 INFO validator-53 c.h.m.m.p.TransactionPublisher Validated node 0.0.5 successfully
2022-01-18T23:08:31.737-0600 INFO validator-49 c.h.m.m.p.TransactionPublisher Validated node 0.0.14 successfully
2022-01-18T23:08:31.817-0600 INFO validator-64 c.h.m.m.p.TransactionPublisher Validated node 0.0.20 successfully
2022-01-18T23:08:31.880-0600 INFO validator-55 c.h.m.m.p.TransactionPublisher Validated node 0.0.22 successfully
2022-01-18T23:08:32.019-0600 INFO validator-59 c.h.m.m.p.TransactionPublisher Validated node 0.0.21 successfully
2022-01-18T23:08:32.039-0600 INFO validator-61 c.h.m.m.p.TransactionPublisher Validated node 0.0.12 successfully
2022-01-18T23:08:32.159-0600 INFO validator-52 c.h.m.m.p.TransactionPublisher Validated node 0.0.18 successfully
2022-01-18T23:08:32.216-0600 INFO validator-47 c.h.m.m.p.TransactionPublisher Validated node 0.0.3 successfully
2022-01-18T23:08:32.304-0600 INFO validator-50 c.h.m.m.p.TransactionPublisher Validated node 0.0.7 successfully
2022-01-18T23:08:32.320-0600 INFO validator-65 c.h.m.m.p.TransactionPublisher Validated node 0.0.8 successfully
2022-01-18T23:08:32.356-0600 INFO validator-60 c.h.m.m.p.TransactionPublisher Validated node 0.0.15 successfully
2022-01-18T23:08:32.474-0600 INFO validator-66 c.h.m.m.p.TransactionPublisher Validated node 0.0.11 successfully
2022-01-18T23:08:32.641-0600 INFO validator-63 c.h.m.m.p.TransactionPublisher Validated node 0.0.9 successfully
2022-01-18T23:08:32.682-0600 INFO validator-54 c.h.m.m.p.TransactionPublisher Validated node 0.0.10 successfully
2022-01-18T23:08:32.714-0600 INFO validator-58 c.h.m.m.p.TransactionPublisher Validated node 0.0.6 successfully
2022-01-18T23:08:32.736-0600 INFO validator-46 c.h.m.m.p.TransactionPublisher Validated node 0.0.13 successfully
2022-01-18T23:08:32.892-0600 WARN validator-57 c.h.m.m.p.TransactionPublisher Unable to validate node NodeProperties(accountId=0.0.24, accountIds=[0.0.24], host=34.89.103.38, port=50211):  com.hedera.hashgraph.sdk.MaxAttemptsExceededException: 
2022-01-18T23:08:33.446-0600 WARN validator-56 c.h.m.m.p.TransactionPublisher Unable to validate node NodeProperties(accountId=0.0.19, accountIds=[0.0.19], host=34.89.87.138, port=50211):  com.hedera.hashgraph.sdk.MaxAttemptsExceededException: 
2022-01-18T23:08:33.497-0600 WARN validator-48 c.h.m.m.p.TransactionPublisher Unable to validate node NodeProperties(accountId=0.0.16, accountIds=[0.0.16], host=34.91.181.183, port=50211):  com.hedera.hashgraph.sdk.MaxAttemptsExceededException: 
2022-01-18T23:08:33.498-0600 INFO validator-48 c.h.m.m.p.TransactionPublisher 19 of 22 nodes are functional
2022-01-18T23:08:34.788-0600 INFO parallel-71 c.h.m.m.s.g.GrpcClientSDK Starting 'hcs' scenario to client 0
```

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java [hunk 1]
```diff
@@ -0,0 +1,342 @@
...
+
+        if (channel != null) {
+            return channel;
+        }
+
+        ManagedChannelBuilder<?> channelBuilder;
+
+        if (address.isInProcess()) {
+            channelBuilder = InProcessChannelBuilder.forName(Objects.requireNonNull(address.getName()));
+        } else if (address.isTransportSecurity() || address.getPort() == 443) {
```
Comment (steven-sheehy) [inline hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:233]: This block is the only change to this file to workaround the SDK TLS bug.

**Review by ijungmann — APPROVED** [review]
LGTM

File: hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java [hunk 2]
```diff
@@ -0,0 +1,342 @@
...
+     * Used when a node has received a bad gRPC status
+     */
+    synchronized void increaseDelay() {
+        this.attempts++;
+        this.backoffUntil = System.currentTimeMillis() + this.currentBackoff.toMillis();
+        this.currentBackoff = Duration.ofMillis(Math.min(this.currentBackoff.toMillis() * 2, this.maxBackoff.toMillis()));
+    }
+
+    /**
+     * Used when a node has not received a bad gRPC status.
```
Comment (Nana-EC) [inline hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:189]: nit: Try wording in the affirmative instead of double negative
```suggestion
     * Used when a node has received a good gRPC status after receiving multiple bad gRPC status.
```
Can then remove the '(receiving several bad gRPC status)' since the context is provided earlier

File: hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java [hunk 3]
```diff
@@ -0,0 +1,342 @@
...
+        }
+
+        ManagedChannelBuilder<?> channelBuilder;
+
+        if (address.isInProcess()) {
+            channelBuilder = InProcessChannelBuilder.forName(Objects.requireNonNull(address.getName()));
+        } else if (address.isTransportSecurity() || address.getPort() == 443) {
+            channelBuilder = Grpc.newChannelBuilder(address.toString(), getChannelCredentials());
+
+            if (address.getPort() != 443) {
```
Comment (Nana-EC) [inline hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:236]: Make '443' a `private static` variable

File: hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java (hunk 1 above)
Comment (steven-sheehy) [reply hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:233]: The code smells are all due to this SDK file. We should be able to remove this file after 2.7.0 of the SDK is released assuming my upstream [PR](https://github.com/hashgraph/hedera-sdk-java/pull/856) is merged.

**Review by xin-hedera — APPROVED** [review]
LGTM

File: hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java [hunk 4]
```diff
@@ -0,0 +1,342 @@
...
+        if (channel != null) {
+            channel.shutdown();
+            channel.awaitTermination(timeout.getSeconds(), TimeUnit.SECONDS);
+            channel = null;
+        }
+    }
+
+    /**
+     * Compares one node to another. The order is determined by health. If both nodes are healthy then their {@link ManagedNode#useCount}
+     * and {@link ManagedNode#lastUsed} values are used to determine order. The node which is used less will be
```
Comment (Nana-EC) [inline hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:301]: Q: Shouldn't it be the node used more should be considered more healthy since it's considered more reliable.
Less used doesn't really inform reliability.

**Review by Nana-EC — CHANGES_REQUESTED** [review]
1st pass

File: hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/HederaNetwork.java [hunk 5]
```diff
@@ -73,7 +73,10 @@ private static MirrorNodeProperties mirrorNode(String environment) {
                 new NodeProperties("0.0.21", "34.76.140.109"),
                 new NodeProperties("0.0.22", "34.64.141.166"),
                 new NodeProperties("0.0.23", "35.232.244.145"),
-                new NodeProperties("0.0.24", "34.89.103.38")
+                new NodeProperties("0.0.24", "34.89.103.38"),
```
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/HederaNetwork.java:76]: I think it's probably better if we move towards using the SDK hardcoded values in the future. We didn't before since they were always out of date but they've been maintaining them better and will soon dynamically pull the address book so we can consider switching.

File: hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java (hunk 2 above)
Comment (steven-sheehy) [reply hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:189]: As discussed offline, this is a copied SDK file so trying to minimize changes to just fix the bug.

Comment (Nana-EC) [reply hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:189]: Seems to be SDK copied file so not worth the effort resolving this here.

File: hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java (hunk 3 above)
Comment (Nana-EC) [reply hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:236]: Seems to be SDK copied file so not worth the effort resolving this here.

File: hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java (hunk 4 above)
Comment (Nana-EC) [reply hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java:301]: Seems to be SDK copied file so not worth the effort resolving this here.

**Review by Nana-EC — APPROVED** [review]
LG
