### PR TITLE
Fix incorrect fungible token total supply

### LINKED ISSUE #5642: Incorrect fungible token total supply
### Description

mirrornode shows incorrect total supply for fungible token ([0.0.786931](https://mainnet-public.mirrornode.hedera.com/api/v1/tokens/0.0.786931)) on mainnet.

Initial investigation shows mirrornode importer incorrectly handled the token transfers in a token dissociate transaction (consensus timestamp 1669227339081494447) and override the token total supply to 9229

### Steps to reproduce

1. create a fungible token with non-zero initial supply
2. associate an account and transfer certain amount `X` (different than the total supply) token to the account
3. dissociate the account from the token
4. mirrornode REST API will show token's total supply is `X`

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.76.0

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes incorrect fungible token total supply

- Don't update fungible token total supply if the transfers in the token dissociate tx is not for a deleted token
- Add a repeatable java migration to fix incorrect fungible token total supply 

**Related issue(s)**:

Fixes #5642 

**Notes for reviewer**:

The migration took ~8 seconds to complete in mainnet-staging-na

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixFungibleTokenTotalSupplyMigration.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+              select token_id, sum(balance) amount
+              from token_balance
+              where consensus_timestamp = (select timestamp from snapshot_timestamp)
+              group by token_id
+            ), initial as (
+              select tb.*
+              from token_balance_sum tb
+              join token tk on tk.token_id = tb.token_id
+              where tk.type = 'FUNGIBLE_COMMON'
+            ), change as (
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/FixFungibleTokenTotalSupplyMigration.java:52]: had to split to two CTEs to make citus happy

**Review by steven-sheehy — APPROVED** [review]
LGTM
