### PR TITLE
Internal error when retrieving contract result by ethereum transaction hash

### LINKED ISSUE #3952: Internal error when retrieving contract result by ethereum transaction hash
### Description

When querying `/api/v1/contracts/results/{ethereum-tx-hash}` with an ethereum transaction that has been submitted multiple times to the network (e.g. it failed and the user wanted to retry), the REST API returns `Internal error` instead of a successful response. This occurs because of an internal check for multiple results for what is supposed to be a unique key (see logs below).

### Steps to reproduce

Invoke contract results by ethereum hash with an ethereum transaction that you've submitted multiple times to the network.

https://previewnet.mirrornode.hedera.com/api/v1/contracts/results/0xb8e8b5f4a0e5821fd12fe7b0dbc14036ead8bfe30a04ef34274e6affa9ed4a69

### Additional context

```bash
9|6559  | 2022-06-15T14:45:42.218Z ERROR 694775b4 75.12.148.71 GET /api/v1/contracts/results/0xb8e8b5f4a0e5821fd12fe7b0dbc14036ead8bfe30a04ef34274e6affa9ed4a69 in 4 ms: 500 Internal error Error: Transaction invariance breached
9|6559  |     at getContractResultsByTransactionIdOrHash (/opt/restapi/controllers/contractController.js:1025:13)
9|6559  |     at runMicrotasks (<anonymous>)
9|6559  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
9|6559  |     at async wrappedMiddleware (/opt/restapi/node_modules/@awaitjs/express/index.js:64:9)
```

### Hedera network

previewnet

### Version

v0.58.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by ar-conmit**
Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #3952 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/controllers/contractController.js [hunk 1]
```diff
@@ -1019,12 +1019,6 @@ class ContractController extends BaseController {
 
     if (transactions.length === 0) {
       throw new NotFoundError('No correlating transaction');
-    } else if (transactions.length > 1) {
-      logger.error(
-        'Transaction invariance breached: there should be at most one transaction with none-duplicate-transaction ' +
-          'result for a specific (payer + valid start timestamp + nonce) combination'
-      );
-      throw new Error('Transaction invariance breached');
```
Comment (steven-sheehy) [inline hedera-mirror-rest/controllers/contractController.js:1027]: We shouldn't remove this check since there are other scenarios like lookup by transaction ID that can fail. We only want to change the lookup by ethereum hash flow.

Instead, we should modify the ethereum transaction join to filter out transactions with status of WRONG_NONCE, order by consensus timestamp and limit by 1. That way this invariance can never be reached with ethereum hash flow since we're moving the check to the query.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/controllers/contractController.js (hunk 1 above)
Comment (ar-conmit) [reply hedera-mirror-rest/controllers/contractController.js:1027]: What if there are transactions with WRONG_NONCE only and we filter them out, so we should return no transaction found for the given ethereum hash?

File: hedera-mirror-rest/__tests__/specs/contracts-result-details-17-transaction-hash-match-multiple-tx.spec.json [hunk 2]
```diff
@@ -33,14 +33,16 @@
         "payerAccountId": "8001",
         "transaction_hash": "519a008fabde4d",
         "type": 50,
-        "valid_start_timestamp": 167654000123400
+        "valid_start_timestamp": 167654000123400,
+        "result": 22
```
Comment (Nana-EC) [inline hedera-mirror-rest/__tests__/specs/contracts-result-details-17-transaction-hash-match-multiple-tx.spec.json:37]: To confirm that the 1st transaction is always taken you'd want to add a duplicate with a success result since that would not be filtered out

**Review by Nana-EC — CHANGES_REQUESTED** [review]
LG.
2 nits for improvement and a test improvement.

File: hedera-mirror-rest/service/transactionService.js [hunk 3]
```diff
@@ -145,11 +146,22 @@ class TransactionService extends BaseService {
       ),
       [ethHash],
       'getTransactionDetailsFromEthHash',
-      excludeTransactionResults
```
Comment (steven-sheehy) [inline hedera-mirror-rest/service/transactionService.js:148]: Please add some unit tests to transactionService.test.js for `getTransactionDetailsFromEthHash`.

**Review by Nana-EC — APPROVED** [review]
LGTM
