### PR TITLE
Fix postgresql deadlock in integration tests

### LINKED ISSUE #1164: Postgresql deadlock in importer integration test
**Detailed Description**
Postgresql deadlock on rows in table `t_application_status` happens sporadically during importer integration tests. There is a race condition in the cleanup.sql script and `MirrorDateRangePropertiesProcessor`, both update `t_application_status` but in different order so deadlock happens.

**Actual Behavior**
1. ./mvnw package -pl hedera-mirror-importer

```
[ERROR] com.hedera.mirror.importer.reader.balance.BalanceFileReaderImplV1Test.readInvalidWhenFileDoesNotExist  Time elapsed: 1.245 s  <<< ERROR!
org.springframework.jdbc.datasource.init.ScriptStatementFailedException:
Failed to execute SQL script statement #12 of class path resource [db/scripts/cleanup.sql]: UPDATE t_application_status SET status_value = NULL; nested exception is org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 53 waits for ShareLock on transaction 609; blocked by process 52.
Process 52 waits for ShareLock on transaction 608; blocked by process 53.
  Hint: See server log for query details.
  Where: while updating tuple (0,3) in relation "t_application_status"
Caused by: org.postgresql.util.PSQLException:
ERROR: deadlock detected
  Detail: Process 53 waits for ShareLock on transaction 609; blocked by process 52.
Process 52 waits for ShareLock on transaction 608; blocked by process 53.
  Hint: See server log for query details.
  Where: while updating tuple (0,3) in relation "t_application_status"
```
**Expected Behavior**
Postgresql deadlock should not happen and integration tests run successfully

**Environment:**
- Java: [e.g. OpenJDK 11.0.4]
- Node: [e.g. v12.9.1-x86]
- OS: [e.g. Ubuntu 18.04]
- Version: [e.g. 1.0.1]

**Additional Context**

### PR DESCRIPTION
**Pull request by xin-hedera**
**Detailed description**:
In cleanup.sql, lock `t_application_status` table in `ACCESS EXCLUSIVE` mode to prevent the updates in the script and `MirrorDateRangePropertiesProcessor` interleaving then running into deadlock.

**Which issue(s) this PR fixes**:
Fixes #1164 

**Special notes for your reviewer**:

**Outdated**: The BEFORE_TEST_METHOD sql script seems unnecessary. The other option is explicitly acquire a table lock in cleanup.sql so the updates to `t_application_status` are serialized.

Changed to add explicit lock in cleanup.sql.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

**Review by Nana-EC — APPROVED** [review]
LGTM

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_28_1__Address_BookTest.java [hunk 1]
```diff
@@ -48,7 +48,6 @@
 import com.hedera.mirror.importer.repository.FileDataRepository;
 
 @TestPropertySource(properties = "spring.flyway.target=1.28.0")
-@Sql(executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:db/scripts/cleanup_V1.28.1.sql")
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_28_1__Address_BookTest.java:51]: This test fails in my local env but not in CircleCI runs. What happened is if the Sql annotations here do not match exactly those in `IntegrationTest`, springboot test will list all 3 sql scripts and cleanup.sql will run in AFTER_TEST_METHOD phase and errors out since it tries to truncate tables after V1.28.1

**Review by ijungmann — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]

**Review by steven-sheehy — COMMENTED** [review]
There's also `AddressBookServiceImplTest` that has `@Sql`. It should probably be changed to extend `IntegrationTest`.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_28_1__Address_BookTest.java (hunk 1 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_28_1__Address_BookTest.java:51]: There is an open ticket regarding this confusing behavior:

https://bugs.openjdk.java.net/browse/JDK-8188040

for annotations which are both `repeatable` and `inherited`

File: hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql [hunk 2]
```diff
@@ -9,8 +9,8 @@ TRUNCATE TABLE t_entities RESTART IDENTITY CASCADE;
 TRUNCATE TABLE transaction RESTART IDENTITY CASCADE;
 TRUNCATE TABLE topic_message RESTART IDENTITY CASCADE;
 TRUNCATE TABLE non_fee_transfer;
-UPDATE t_application_status
-SET status_value = NULL;
+LOCK TABLE t_application_status IN ACCESS EXCLUSIVE MODE;
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql:12]: ends up also explicitly acquire the highest level table lock on `t_application_status` since `AddressBookServiceImplTest` assumes empty `address_book` and `address_book_entry` tables. It's better and easier to maintain a single all-in-one cleanup script instead of creating test class specific cleanup scripts.

**Comment by xin-hedera** [comment]
> There's also `AddressBookServiceImplTest` that has `@Sql`. It should probably be changed to extend `IntegrationTest`.

When trying to update `AddressBookServiceImplTest`, hit the weird behavior of `@Sql` which is both `@Inherited` and `@Repeatable`. Solved it by:

- Add explicit table level strong lock on `t_application_status`
- Make `AddressBookServiceImplTest` extend `IntegrationTest` and override to run cleanup.sql in `BEFORE_TEST_METHOD` phase to satisfy the assumption of the tests

**Review by steven-sheehy — APPROVED** [review]
LGTM
