### PR TITLE
Fix BalanceFileParserTest failure

### LINKED ISSUE #800: Multiple PostgreSQL containers running concurrently during tests
**Detailed Description**
Added a new `BalanceFileParserTest` and it works when ran in isolation or via CircleCI, but not when ran via Maven locally. While debugging, I noticed there are multiple postgresql containers being started during the importer tests and my test is inserting into one DB while verifying from the other. This is due to tests that cause a new ApplicationContext to start (`RecordParserDisabledTest`, `PubSubIntegrationTest`) are also causing a new PostgreSQL container to start. Disabling those two tests lets the tests pass.

**Actual Behavior**
1. Enable `BalanceFileParserTest`
2. `./mvnw clean package`

**Expected Behavior**
Only one PostgreSQL container to run at a time

**Environment:**
- Java: OpenJDK 11
- OS: MacOS
- Version: 0.12.x

**Additional Context**

### PR DESCRIPTION
**Pull request by xin-hedera**
**Detailed description**:
Remove `DatabaseUtilities`, refactor balance parser so that during tests with multiple test contexts, the correct `DataSource` is injected and `BalanceFileParserTest` write to and read from the same database.

**Which issue(s) this PR fixes**:
Fixes #800 

**Special notes for your reviewer**:
When running test, `BalanceFileParserTests` will fail. The root cause is

* during test, multiple Spring text contexts will be created since some `SpringBootTest` test classes have different configurations
* For `BalanceFileParserTest`, the repositories in the test cases are from one context while `DatabaseUtilities.dataSource` used by the code being tested is from a different context, which means, data is written to one database while it's read and verified with another database 

Performance: for the new sample account balance csv file with 373713 account balance lines, the time cost is almost identical, 4.21s before v.s. 4.19s after.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+                    .filter(Predicate.not(String::isEmpty))
+                    .map(line -> {
+                        try {
+                            return AccountBalanceItem.of(line, consensusTimestamp);
+                        } catch(IllegalArgumentException ex) {
+                            log.error(ex);
+                            return null;
+                        }
+                    })
+                    .filter(Objects::nonNull);
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java:71]: difference from previous implementation:

neither an empty line nor a malformed account balance line is considered as a failure. The file is verified, so we should try out best to process as much valid info as we can.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+        // The file should contain:
+        //  - single header row Timestamp:YYYY-MM-DDTHH:MM:SS.NNNNNNNNZ
+        //  - shardNum,realmNum,accountNum,balance
+        // followed by rows of data.
+        // The logic here is a slight bit more lenient. Look at up to MAX_HEADER_ROWS rows ending at any row containing
+        // "shard" and requiring that one of the rows had "Timestamp: some value"
+        String line = null;
+        try {
+            long consensusTimestamp = -1;
+            for (int i = 0; i < MAX_HEADER_ROWS; i++) {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java:87]: the logic of header parsing if preserved here: reading MAX_HEADER_ROWS for a a timestamp header and a column header.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/BalanceFileParserTest.java [hunk 3]
```diff
@@ -168,9 +166,9 @@ void assertAccountBalances(BalanceFile... balanceFiles) {
     }
 
     @lombok.Value
-    private class BalanceFile {
-        private final long consensusTimestamp;
-        private final long count;
-        private final String filename;
+    private static class BalanceFile {
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/BalanceFileParserTest.java:169]: followed IntelliJ idea suggestion, looks like it's unnecessary

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReader.java [hunk 4]
```diff
@@ -20,15 +20,19 @@
...
+import com.hedera.mirror.importer.exception.InvalidDatasetException;
+import com.hedera.mirror.importer.parser.domain.AccountBalanceItem;
 
-    @Override
-    public String toString() {
-        return lineNumber + ":" + value;
-    }
+public interface BalanceFileReader {
+    /**
+     * Reads a account balance file, parses the header to get the consensus timestamp, and returns a stream of
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReader.java:31]: nit: an
i.e Reads '**an**' account balance ...

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+import java.util.stream.Collectors;
+import lombok.RequiredArgsConstructor;
+import lombok.Value;
+
+import com.hedera.mirror.importer.domain.EntityId;
+import com.hedera.mirror.importer.domain.EntityTypeEnum;
+
+@Value
+@RequiredArgsConstructor
+public class AccountBalanceItem {
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java:35]: q: Why create `AccountBalanceItem` instead of utilizing the `AccountBalance` domain entity?
They're almost the same except AccountBalance has realm and num broken out and here you are using the newer and preferred EntityId.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java [hunk 6]
```diff
@@ -21,194 +21,182 @@
...
+        log.info("Starting processing account balances file {}", balanceFile.getPath());
+        final String fileName = balanceFile.getName();
+        long timestampFromFileName = Utility.getTimestampFromFilename(balanceFile.getName());
+        int validItemCount = 0;
+        int insertedItemCount = 0;
+        boolean complete = false;
+        Stopwatch stopwatch = Stopwatch.createStarted();
+
+        try (Connection connection = dataSource.getConnection();
+             PreparedStatement insertSetStatement = connection.prepareStatement(INSERT_SET_STATEMENT);
```
Comment (Nana-EC) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java:100]: Should we consider using Repositories here instead of staying with PreparedStatements?
It should simplify the file logic.

Also if we utilize the AccountBalance entity object it'd be even smoother.

It's fine if the change would cause greater complexity and require significant refactoring but if it's centralized to mostly this file we should consider if it's in scope for this PR

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java (hunk 5 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java:35]: two reasons:

1. it parses a line from the csv file
2. it's a business layer domain object, not supposed to use an entity object here

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java (hunk 6 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java:100]: performance is worse with Repositories. with batch turned on for CrudRepository, it takes 2~3 times to insert the rows from a sample csv file with ~24000 balance lines

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReader.java (hunk 4 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReader.java:31]: will update!

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+    private final int fileBufferSize;
+
+    public BalanceFileReaderImplV2(BalanceParserProperties balanceParserProperties) {
+        this.fileBufferSize = balanceParserProperties.getFileBufferSize();
+    }
+
+    @Override
+    public Stream<AccountBalanceItem> read(File file) {
+        try {
+            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(file)), fileBufferSize);
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java:57]: will add logic to close the reader when the stream is closed. using try resource here will cause the reader closing before the stream is consumed, and the consumer will get an exception.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+        //  - single header row Timestamp:YYYY-MM-DDTHH:MM:SS.NNNNNNNNZ
+        //  - shardNum,realmNum,accountNum,balance
+        // followed by rows of data.
+        // The logic here is a slight bit more lenient. Look at up to MAX_HEADER_ROWS rows ending at any row containing
+        // "shard" and requiring that one of the rows had "Timestamp: some value"
+        String line = null;
+        try {
+            long consensusTimestamp = -1;
+            for (int i = 0; i < MAX_HEADER_ROWS; i++) {
+                line = Optional.of(reader.readLine()).get().trim();
```
[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java:88]: blank lines (empty string) should not cause optional.of to throw NPE. the only case here is readLine return null, i.e., EOF has reached. so we should catch that NPE since EOF has reached, and no timestamp header + column header combination is found.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java:57]: True, the try with resources should be for the Stream object since it's AutoCloseable and wraps the other readers.

[the remark this answers is not in the document]
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceFileReaderImplV2.java:57]: yup. I forgot to put the read() call into the try with resource block in `loadAccountBalances`. As discussed, I'll also add stream.onClose to close the reader in `BalanceFileReaderImplV2.read`

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java (hunk 5 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java:35]: will move the parsing logic into `AccountBalance` as it's easier to test than having the same logic in `BalanceFileReader`

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java:35]: oh, there is a subtle difference between the two. `AccountBalance` does not have shard while `AccountBalanceItem` does.

It's not good to add shard into `AccountBalance`. Also because of the difference, `BalanceFileReader.read` should return a stream of `AccountBalanceItem` objects. Since we need a different class, it's natural to have the account balance line parsing implemented in the class itself. So this makes more sense now.

Comment (steven-sheehy) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java:35]: We don't need shard to be added to account balance. It's assumed that all entities in the system are for the same shard. You can just check if shard in csv doesn't equal mirrorProperties.getShard() then throw an error. Then can drop shard

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java (hunk 6 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalancesFileLoader.java:100]: IMO, the reader should just worry about reading the csv file in its designated format and let the loader to decide which lines to drop / persist.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java (hunk 5 above)
Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/domain/AccountBalanceItem.java:35]: IMO, the reader should just worry about reading the csv file in its designated format and let the loader to decide which lines to drop / persist.

**Comment by xin-hedera** [comment]
> Have you done any performance testing with the before and after refactoring to see if there's any regression?

sure, I'll run the perf tests and compare the numbers.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/BalanceFileParserPerformanceTest.java [hunk 9]
```diff
@@ -0,0 +1,57 @@
...
+    void before() {
+        streamType = parserProperties.getStreamType();
+        parserProperties.getMirrorProperties().setDataPath(dataPath);
+        parserProperties.init();
+    }
+
+    @Timeout(15)
+    @Test
+    void parseAndIngestMultipleBalanceCsvFiles() {
+        parse("*.csv");
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/BalanceFileParserPerformanceTest.java:45]: The warmup file should be processed in the before method so it doesn't count towards the timeout.
