### PR TITLE
Convert ethereum transaction value from weibar to tinybar

### LINKED ISSUE #3808: ethereum transaction handler doesn't convert value from weibar to tinybar
### Description

In importer `EthereumTransactionHandler`, the value in ethereum transaction is in unit of weibar, we need to convert it to tinybar with the rate of 1 tinybar = 10_000_000_000L weibars

we should also
 - change the db schema so `value` is of type `bigint` since after the conversion, the value can fit into a 8-byte long
 - migrate existing data
 - update rest api logic to use the `bigint` `value` directly

### Steps to reproduce

refer to the description

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.56.3

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

- Fix EthereumTransactionHandler not converting value from weibar to tinybar
- Migrate existing ethereum transaction value from weibar to tinybar
- Remove weibar to tinybar conversion in rest api

**Related issue(s)**:

Fixes #3808

**Notes for reviewer**:

For a ethereum transaction, a value larger than long max will not fail precheck but fail at consensus so such a transaction will get into record stream. As a result, we can't change the db data type for `value` from `bytea` to `bigint`.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConvertEthereumTransactionValueMigration.java [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+    public MigrationVersion getVersion() {
+        return MigrationVersion.fromVersion("1.60.0");
+    }
+
+    @Override
+    protected void doMigrate() {
+        var converter = WeiBarTinyBarConverter.INSTANCE;
+        long count = 0L;
+        var lastConsensusTimestamp = -1L;
+        var paramSource = new MapSqlParameterSource().addValue("limit", BATCH_SIZE);
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConvertEthereumTransactionValueMigration.java:69]: Why have this as parameter if it's just hardcoded as a constant? Might as well move to the SQL.

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConvertEthereumTransactionValueMigration.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+        var stopwatch = Stopwatch.createStarted();
+
+        while (true) {
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConvertEthereumTransactionValueMigration.java:72]: I think it would be cleaner and more robust to use a cursor to iterate over the rows. Then you don't need a batch size or consensus timestamp parameters to update each iteration. See this code in `AccountEvmAddressMigration` for an example:

```java
        jdbcOperations.query(query, rs -> {
            long id = rs.getLong(1);
            byte[] alias = rs.getBytes(2);
            byte[] evmAddress = Utility.aliasToEvmAddress(alias);

            if (evmAddress != null) {
                jdbcOperations.update(update, Map.of("evmAddress", evmAddress, "id", id));
            }
        });
```

**Comment by xin-hedera** [comment]
> Maybe we should also check where `length(value) > 0`?

will add

**Review by steven-sheehy — DISMISSED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
LGTM

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConvertEthereumTransactionValueMigration.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
+
+import com.hedera.mirror.common.converter.WeiBarTinyBarConverter;
+
+@Log4j2
+@Named
+@RequiredArgsConstructor(onConstructor_ = {@Lazy})
+public class ConvertEthereumTransactionValueMigration extends MirrorBaseJavaMigration {
+
+    private static final String SELECT_NON_NULL_VALUE_SQL = "select consensus_timestamp, value " +
```
Comment (matheus-dallrosa) [inline hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConvertEthereumTransactionValueMigration.java:40]: I think we can use Java 15 text blocks, what do you think?

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConvertEthereumTransactionValueMigration.java:40]: will update

Comment (xin-hedera) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ConvertEthereumTransactionValueMigration.java:40]: reverted
